### ISSUE TITLE
INFO: VCS comparison mentioning jj

### ISSUE THREAD

**Issue by xxxserxxx** [martinvonz/jj#1006]
Hi Martin -- I didn't find another way to contact you, but I thought you might be interested in this:

https://blog.waleedkhan.name/git-ui-features

Some of the points may not be feature objectives that you are interested in; Waleed does mention that jj has issues with large repos, although I haven't experienced that myself.  

I'm closing this immediately since it's not actionable.

**Comment by arxanas** [comment]
The best way might be to join the Discord chat at https://discord.gg/dkmfj3aGQN

I had Martin look over the table already, so he's aware :). On the topic of scaling to large repositories, I had started https://github.com/martinvonz/jj/pull/362 towards that end; feel free to pick it up if the lack of large repository support is a problem for you.

**Comment by xxxserxxx** [comment]
Aha. I didn't realize.  

No project I work on is anywhere near large enough to have issues. jj is nice enough to tempt me away from Mercurial, especially with the git back-end which ensures future compatability regardless of what happens with jj. The Rust implementation is nice -- while I don't care for the language myself, I approve of the compiled nature; many of the issues I encounter with Mercurial these days have been related to the choice of Python.

In any case, cheers @arxanas, and thanks for the heads-up.
