### ISSUE TITLE
gh cli doesn't work on jj repos (unless they're "colocated")

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#1008]
## Description

I can't seem to get [gh cli](https://cli.github.com/) to detect the associated git repo from a jj repo (unless it's "colocated" using regular `git clone` and `jj repo init`).

## Steps to Reproduce the Problem

1. Run `jj git clone https://github.com/martinvonz/jj.git` as described in [the tutorial](https://github.com/martinvonz/jj/blob/main/docs/tutorial.md)
2. With git cli installed, cd into the jj dir and run `gh repo view` or some other basic gh command
3. Try instead to cd into .jj/repo/store/git and run the same `gh repo view`

## Expected Behavior
There should be _some_ way to convince gh cli to detect the associated GitHub repo and list info about the martinvonz/jj repo.

## Actual Behavior
Can't get anything but error messages ("not a git repository" from 2, "No default remote repo set" from 3).

Note: previously [discussed in Discord](https://discord.com/channels/968932220549103686/969829516539228222/1060409320040308797). Reporting here to capture some details I've found so far.

We'd also talked about gh cli apparently not supporting a `GIT_DIR` env var or similar. I found that's tracked in https://github.com/cli/cli/issues/2228, but it'd basically do the same as if you cd into the given target directory before running commands so it'd presumably give me the same errors.

**Comment by dbarnett** [comment]
I'd expected https://yadm.io/ would have the same issue, but apparently it doesn't. I'm having trouble making sense of why...

For yadm:
```console
~/.local/share/yadm/repo.git$ ls
branches        config       FETCH_HEAD  hooks  info  objects    refs
COMMIT_EDITMSG  description  HEAD        index  logs  ORIG_HEAD
~/.local/share/yadm/repo.git$ gh repo view
dbarnett/dotfiles
No description provided

This repository does not have a README

View this repository on GitHub: https://github.com/dbarnett/dotfiles
```

But for jj:
```console
~/projects/jj/.jj/repo/store/git$ ls
config  description  FETCH_HEAD  HEAD  hooks  info  objects  refs
~/projects/jj/.jj/repo/store/git$ gh repo view
X No default remote repository has been set for this directory.

please run `gh repo set-default` to select a default remote repository.
~/projects/jj/.jj/repo/store/git$ gh repo set-default
must be run from inside a git repository
```

**Comment by martinvonz** [comment]
I can think of two possible difference:

1. The yadm repo has a `.git` in the path but the jj repo doesn't (it has `git`)
2. The jj repo is bare (`.jj/repo/store/git/config` contains `bare = true`) but I think the yadm repo isn't because I see that it has an `index` file.

I suspect it's (2) that's the important difference. I've never used `gh`. I wonder if it's reasonable to ask them to support it in a bare repo. A bare repo is a repo without a working copy. For example, do most subcommands seem to need to know what HEAD points to? Do they seem to check if the working copy is dirty? Bare repos can still have a HEAD (a current checkout), but I don't remember what happens if you e.g. run `git status` in them.

**Comment by dbarnett** [comment]
For 1, I tried renaming jj's dir to something with ".git" and it seemed to make no difference. Probably just being a bare repo is the distinction.

> do most subcommands seem to need to know what HEAD points to?

No, I think some might but a good number of them don't. Might complicate their code to try to manage that case-by-case, but I could at least ask.

**Comment by dbarnett** [comment]
Dug into the repro case and filed an issue. In general gh cli actually does seem to work on bare repos, but the `gh repo set-default` command chokes. I reported that upstream (see backlink above).

And... I found that it's pretty trivial to work around by manually editing the git config and adding `gh-resolved = base` under my preferred GH remote! After that, gh cli seems to work okay if I cd into .jj/repo/store/git/ before running it OR run it like `GIT_DIR=.jj/repo/store/git gh ...`.

**Comment by martinvonz** [comment]
> run it like `GIT_DIR=.jj/repo/store/git gh ...`

I think I remember that we looked at their docs and it didn't mention `GIT_DIR`, but that's good that they support it after all.

**Comment by dbarnett** [comment]
Small update: If you have gh 2.22.0 or later the `gh-resolved = base` workaround is no longer needed, and I found a pretty decent workaround on my system for twiddling the `GIT_DIR` values: using [ondir](https://github.com/alecthomas/ondir) and ondirrc config from https://github.com/dbarnett/dotfiles/commit/1b0cdd6.

Not sure where to stash that recipe but it'd be nice to somehow surface it to new users so it's discoverable for anyone trying to run gh cli in a non-colocated repo (unless/until some more general solution could get gh cli to automatically detect the appropriate `$GIT_DIR` path from anywhere in the local repo).

**Comment by martinvonz** [comment]
Somewhere in https://github.com/martinvonz/jj/blob/main/docs/github.md is the best place I can think of.

**Comment by necauqua** [comment]
This ondir thing seems like a far less popular version of direnv, I'd suggest using direnv (or at least mention both of them) in the docs.

Also on a system with direnv installed the workaround is as easy as doing
```bash
echo 'export GIT_DIR=$PWD/.jj/repo/store/git' >> .envrc
direnv allow
```

**Comment by dbarnett** [comment]
Not necessarily opposed, but to understand differences: direnv says it checks for env/envrc files in current and parent directories. Can it also handle if you cd _through_ a given directory into its children, like `cd ~/projects/jj/src/commands/`?

**Comment by necauqua** [comment]
"and parent directories" gives it away :)
For the `$PWD` part I specifically googled and found out that it's relative to where the .envrc file is so it's correct too.

**Comment by dbarnett** [comment]
Yes, that seems to work (and apparently expands `$PWD` so it doesn't break if `$PWD` changes later, no `eval` needed?).

I did run into a direnv limitation direnv/direnv#556 preventing me from having my own local direnv hooks w/o dirtying up the repo, though. For now I'm continuing to use ondir (since I can configure that from outside the file tree). Still interested to figure out how to solve that repo vs. local limitation and get a recipe for it documented; direnv does seem like a nicer tool otherwise.
