### ISSUE TITLE
`jj -R` is confusing (ignored?) when using the `init` command

### ISSUE THREAD

**Issue by colemickens** [martinvonz/jj#101]
## Steps to Reproduce the Problem

I was trying to be all cute and execute some git/jj commands in different dirs without cd-ing around and did this:

(this would have been the build from my PR https://github.com/martinvonz/jj/pull/100)

```
cole@porty ~/jj
❯ git -C nixpkgs status
On branch cmpkgs
Your branch is up to date with 'origin/cmpkgs'.

nothing to commit, working tree clean


cole@porty ~/jj
❯ jj -R nixpkgs-jj init --git-repo=nixpkgs
Working copy now at: 0916907ca7ee
Initialized repo in "/home/cole/jj/."
```

## Expected Behavior

`Initialized repo in "/home/cole/jj/nixpkgs-jj"`

or something akin to:
```
> jj -R foo-jj-src init --git-repo=bar foo-jj
init: error: `destination-dir and -R` are not allowed
```

or, to match git's lack of `-C` for init:
```
init: error: -R is unsupported for init
```

## Actual Behavior

`Initialized repo in "/home/cole/jj/."`

## Specifications

- Platform: nix

**Comment by martinvonz** [comment]
@epage, do you have any suggestion for how to tell Clap that certain a global flag should not be allowed in combination with certain subcommands? Is there are built-in way of specifying that or do I have to add a check for the global flag in each subcommand that doesn't allow it? If there's no built-in support for it in Clap, do you think it's a common-enough feature that I should file a feature request for it?

**Comment by epage** [comment]
What you are looking for is a combination of https://github.com/clap-rs/clap/issues/2375 and https://github.com/clap-rs/clap/issues/1204.  Unless someone comes up with an acceptable design, we'll most likely leave solving parts of this to https://github.com/clap-rs/clap/discussions/3476.

For manually implementing the check in each subcommand, you can [Command::error](https://docs.rs/clap/latest/clap/struct.App.html#method.error) to get an error that looks like a clap error.  It doesn't look like we support adding your own [context](https://docs.rs/clap/latest/clap/error/enum.ContextKind.html) to errors but that is something we can open up though we only have a [hard-coded support for rendering context](https://docs.rs/clap/latest/src/clap/error/mod.rs.html#637), so it would have to match an existing recognized pattern.

**Comment by epage** [comment]
> Or are you saying that it could (hypothetically) be implemented in a similar way if the subcommand (e.g. "init") could be configured to conflict with the global flag (e.g. "--repository")?

Yes, that is what I was thinking
