### ISSUE TITLE
`jj init --git-repo=../dir` results in empty checkout

### ISSUE THREAD

**Issue by colemickens** [martinvonz/jj#102]
## Steps to Reproduce the Problem

this would have been the build from my PR https://github.com/martinvonz/jj/pull/100

```console
cole@porty ~/jj
❯ exa -al
drwxr-xr-x - cole  2 Mar 02:11 nixpkgs


cole@porty ~/jj
❯ git -C nixpkgs status
On branch cmpkgs
Your branch is up to date with 'origin/cmpkgs'.

nothing to commit, working tree clean


cole@porty ~/jj
❯ mkdir nixpkgs-jj


cole@porty ~/jj
❯ cd nixpkgs-jj


cole@porty ~/jj/nixpkgs-jj
❯ jj init --git-repo=../nixpkgs
Working copy now at: 4f1d5ded0540
Initialized repo in "/home/cole/jj/nixpkgs-jj/."


cole@porty ~/jj/nixpkgs-jj
❯ jj status
Parent commit: 000000000000
Working copy : 4f1d5ded0540
The working copy is clean


cole@porty ~/jj/nixpkgs-jj
❯ ls -al
total 2
drwxr-xr-x 3 cole cole 3 Mar  2 02:38 .
drwxr-xr-x 4 cole cole 4 Mar  2 02:38 ..
drwxr-xr-x 4 cole cole 4 Mar  2 02:38 .jj


cole@porty ~/jj/nixpkgs-jj
❯ jj checkout 4f1d5ded0540
Already on that commit


cole@porty ~/jj/nixpkgs-jj
❯ ls -al
total 2
drwxr-xr-x 3 cole cole 3 Mar  2 02:38 .
drwxr-xr-x 4 cole cole 4 Mar  2 02:38 ..
drwxr-xr-x 4 cole cole 4 Mar  2 02:38 .jj


cole@porty ~/jj/nixpkgs-jj
❯ ls -al ../nixpkgs
total 97
drwxr-xr-x  9 cole cole   18 Mar  2 02:11 .
drwxr-xr-x  4 cole cole    4 Mar  2 02:38 ..
drwxr-xr-x 11 cole cole   22 Mar  2 02:11 doc
drwxr-xr-x  8 cole cole   13 Mar  2 02:29 .git
drwxr-xr-x  4 cole cole   10 Mar  2 02:11 .github
drwxr-xr-x  4 cole cole   30 Mar  2 02:11 lib
drwxr-xr-x  3 cole cole    5 Mar  2 02:11 maintainers
drwxr-xr-x  7 cole cole   13 Mar  2 02:11 nixos
# etc
```

## Expected Behavior

To have a checkout after initing from a git repo in another directory.

## Actual Behavior

I'm not sure, but I don't seem to have a checkout or an obvious way to manifest one.

**Comment by colemickens** [comment]
huh, after I did a `jj checkout cmpkgs` (my default nixpkgs branch name), it worked for a bit and then I had a checkout.

In retrospect, the `jj log` output is weird, it's really ancient commits. It seems like whatever it imported by default it picked an odd branch or commit to start from? Is there a command that shows what branch jj is on? I don't see it but I might just be missing it?

**Comment by martinvonz** [comment]
I think it doesn't check out any commit at all, so it remains checked out on the root commit (the virtual commit with hash 0000000... that's the root of all other commits).

There's a TODO about fixing this here: https://github.com/martinvonz/jj/blob/2a6ab8b6fceab91f35cae697c0c9f1f4de727594/src/commands.rs#L1733-L1734. I don't think my idea there is correct, though; we probably want to use the Git repo's HEAD commit instead. We keep track of the HEAD commit these days (pretty sure that came after that TODO), so it should be an easy fix.
