### ISSUE TITLE
FR: `jj tree` (a `jj log` like command) to display a small number of commits as a tree

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1036]
My most frequent use for `jj log` (by far) is to display "draft" commits (i.e., commits that are not merged with origin yet), these commits are always (at least in my workflow) a tree (not a DAG) and while `jj log` works in displaying them as a DAG, I personally find something like the following tree representation to be much more readable --

```
o c0a26f76426e 543967befc73 martinvonz@google.com 2021-10-13 11:08:01.000 -07:00
|...o ca796b49f06f b4323a1a35b6 martinvonz@google.com 2021-10-13 20:38:39.000 -07:00
|   | docs: describe how to set up commmand-line completion
|   |---o cfd9255b94d3 c48b95a17bdf martinvonz@google.com 2021-10-13 16:17:40.000 -07:00
|   |     index: start indexing file-level conflicts
|   |...o 2e4dc019d943 e8c23f0ee5e2 martinvonz@google.com 2021-10-20 14:21:01.000 -07:00
|         git: don't update public heads for now
>---@ 77b94b593d68 bb3b69138188 martinvonz@google.com 2021-10-13 12:29:47.000 -07:00
      git: move logic for adding remote to git module
```

(Example from #242)

Although orthogonal, implementing #242 for this would probably be much easier too.

I don't expect this to be accepted and am logging this mostly for bookkeeping (and because I miss Fig tree) but it would be interesting to see if this makes sense to / interests anyone else.

**Comment by martinvonz** [comment]
> I don't expect this to be accepted

I wouldn't mind having such a command.

What would you do for merge commits? I think git-branchless's `git sl` shows them by showing non-first parents as a line that leads nowhere and then another line that enters the graph where the parent commit is. I've forgotten where @arxanas shared a screenshot of how that looks...

**Comment by avamsi** [comment]
With Sapling's much nicer rendering and #242 about to be closed, I don't think there's much to be done here, closing (as a duplicate).
