### ISSUE TITLE
FR: have `jj log` wrap text based on terminal width

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1043]
Current behavior --

```
o 3728442fe4f3 martinvonz@google.com 1 day ago main* 31ad0cd2ed36
| formatter: reset color around newlines
o a48caf2e5753 avamsi07@gmail.com 15 hours ago push-4fe214e50ae1 HEAD@git 1
5a08e021ff9
| let branches and remote_branches revset functions take needles as argumen
ts
@ f5bdc08c86aa avamsi07@gmail.com 15 hours ago c3d77fa6a56f
  (no description set)
```

Desired behavior (note the graph is not "broken" in this example) --

```
o 3728442fe4f3 martinvonz@google.com 1 day ago main* 31ad0cd2ed36
| formatter: reset color around newlines
o a48caf2e5753 avamsi07@gmail.com 15 hours ago push-4fe214e50ae1 HEAD@git
| 15a08e021ff9
| let branches and remote_branches revset functions take needles as
| arguments
@ f5bdc08c86aa avamsi07@gmail.com 15 hours ago c3d77fa6a56f
  (no description set)
```

I picked a straightforward example but this makes even more sense for deeply nested commits (and more relevant if/when log templates are documented and people go for more compact representations in a single line e.t.c.)

All that said, this may not be desired by everyone, so maybe this could be a default-false flag to `jj log`.

**Comment by martinvonz** [comment]
For reference, Mercurial does this (as you probably know). It has `termwidth` and `graphwidth` keywords and `fill()` function for doing it in a template.

**Comment by avamsi** [comment]
Woot, thanks @yuja!
