### ISSUE TITLE
`jj undo` doesn't do anything after `jj duplicate` in a test

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1050]
In https://github.com/martinvonz/jj/pull/999, I changed the `duplicate` command and used `jj undo` in a test.

Unexpectedly, `jj undo` didn't do anything. The test in questin is `test_duplicate_many`, you can see it inside the `debug` commit. 

**Update:** This bug now has a fix. In case the links stop working, for future reference, `jj undo` simply didn't do anything after a `jj duplicate`:

```rust
    let stdout = test_env.jj_cmd_success(&repo_path, &["duplicate", "a"]);
    insta::assert_snapshot!(stdout, @r###"
    Created: f5cefcbb65a4 a
    "###);
    insta::assert_snapshot!(test_env.jj_cmd_success(&repo_path, &["undo"]), @r###"
    Nothing changed.
    "###);
```

## Older description

**Update:** See next comment for a better way to see this bug.

A link that may stop working at some point:

https://github.com/martinvonz/jj/blob/b30df8e10cbd1a7a4fbc3bb4df96d85480ad3a19/tests/test_duplicate_command.rs#L199-L299

Is this somehow expected? Is this a bug I introduced? I'm quite confused.

**Comment by ilyagr** [comment]
Actually, the bug shows up in my earlier PR. For a simpler reproduction, see the new "TMP Debug commit" of https://github.com/martinvonz/jj/pull/1049.

**Comment by martinvonz** [comment]
I think the fix is to replace https://github.com/martinvonz/jj/blob/60d1537731ebc255a5233cab19a6b530d3177565/lib/src/repo.rs#L612-L614 by
```rust
    pub fn has_changes(&self) -> bool {
        self.abandoned_commits.is_empty()
            && self.rewritten_commits.is_empty()
            && self.view() != &self.base_repo.view
    }
```

**Comment by ilyagr** [comment]
Thank you very much, I will try it! Am I right to guess that you meant an `||` of not empty or not equal, or is it correct as written?
