### ISSUE TITLE
Minor maybe bug with `graph.format=curved`

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1058]
If you run `jj log -r R --config-toml 'ui.graph.format="curved"'` in this repo, you get a very slightly misleading graph:

[jj.minor-graph-bug.tar.gz](https://github.com/martinvonz/jj/files/10432071/jj.minor-graph-bug.tar.gz)

![image](https://user-images.githubusercontent.com/4123047/212828456-8d0a7cac-dc74-4387-9176-3b2b48a4e002.png)

`f88b`'s parent is `5bb5`. So, I think it should use `├`  where it has  `╭`.

**Comment by ilyagr** [comment]
We decided this is probably intended behavior, to distinguish `f88b` having one parent (as is the case here) from the case of it having three parent.

**Comment by ilyagr** [comment]
We were discussing it on Discord. The conclusions were:

- It could be rendered similarly at the cost of using one extra column. It seem's Sapling's dag library doesn't do that to save space.

- According to @MFoster, his original prototype did do that and it didn't seem to help readability much

**Comment by MForster** [comment]
For the record, here is a comparison of [sapling's curved style](https://github.com/martinvonz/jj/pull/1048/files#diff-1ca0bda506fe1e2ffd7e9bc08dd53dca9fcd80a923e97c4d97c946703aa2a56fR217)
```
        o  node 3
        │ o    node 2
        ╭─┼─╮  with
        │ │ │  many
        │ ~ ~  lines
        │      of
        │      text
        o  node 1
```

with [my curved style](https://github.com/martinvonz/jj/pull/1048/files#diff-a97eeb0ef7cc0f5332817fe118d7d910566d6cb857380b2b9853de17248d174fR198)

```
        ⬤ node 3
        │ ⬤─┬─┬─╮ node 2
        │ │ ┊ ⯆ ┊ with
        │ ⯆ ┊   ┊ many
        ├───╯   ┊ lines
        ├───────╯ of
        │         text
        ⬤ node 1
```

Sapling's layout also seemed to have merged the two anonymous/missing edges, but it's clearly visible how this style uses an additional column.
