### ISSUE TITLE
FR: let git.(fetch|push) config options be lists?

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1091]
I'm trying to unify 2 scenarios --

1. I fetch and push from `origin` (personal repositories e.t.c.).
2. I fetch from `origin` and push to `fork` (work, some minor contributions e.t.c.).

I know I can configure these per repository and the solution I'm proposing will probably be more confusing than helpful, but if we could have git.push support lists, I could just configure it to `[fork, origin]` (meaning if `fork` exists, push to `fork`, otherwise push to `origin`) and it'll just work for both the scenarios.

There's also a 3rd scenario in which I fetch from `upstream` and push to `origin` (Github default remote names) -- I usually rename remotes to match `#2` above but with this FR, I could just set git.fetch to `[upstream, origin]` and git.push to `[fork, origin]` in the global config to cover all 3 scenarios pretty seamlessly.

**Comment by samueltardieu** [comment]
I am not sure this is worth the complexity (including the added documentation complexity). Setting the remotes to use is a one-time operation if they differ from the ones set globally.

**Comment by avamsi** [comment]
Yeah, I'm leaning towards "not worth the complexity" too, just wanted to see if people think otherwise. Closing.
