### ISSUE TITLE
Nix flake includes .jj and target/ in src

### ISSUE THREAD

**Issue by Ralith** [martinvonz/jj#1095]
As a result, `nix build` has an extremely slow "copying" stage. This should be mitigated by filtering those paths out of the src, but the flake currently uses a strange `src = self;` construction that I'm not sure how to transform.

**Comment by MForster** [comment]
Could be this: https://github.com/NixOS/nix/issues/3121

**Comment by Ralith** [comment]
Hmm, maybe. This would be a problem for a traditional derivation too, but for those there's the solutions discussed in https://discourse.nixos.org/t/filtering-source-trees-with-nix-and-nixpkgs/19148. I assumed those could be usefully applied to the flake `src` attribute, but maybe not...
