### ISSUE TITLE
`nix profile install` fails

### ISSUE THREAD

**Issue by Ralith** [martinvonz/jj#1096]
This should use the flake.nix to build and install jj in the user environment, but it fails with `error: opening directory '/nix/store/m5frwjzn35zfpi1gv0ynhmj8rmjrs55s-crate-cargo2nix-0.9.0': No such file or directory`.

**Comment by MForster** [comment]
Works for me. Do you have more detailed repro instructions?

**Comment by MForster** [comment]
And, FWIW, I do not have `cargo2nix` in my nix store either.

**Comment by Ralith** [comment]
Literally `nix profile install 'github:martinvonz/jj'`. as specified by the README. IIRC similar behavior when running in a checkout with no arguments as well, but that takes a long time to reproduce due to #1095.

**Comment by MForster** [comment]
I just tried 

```
nix \
  --extra-experimental-features nix-command \
  --extra-experimental-features flakes \
  profile install 'github:martinvonz/jj'
```

on
- my desktop with Ubuntu (home-manager configured via flake) and nix 2.11.1
- my server on nixos-unstable (configured via flake) with nix 2.12.0
- a pristine server instance on nixos-22.05 (configured without flakes), nix 2.8.1
- a pristine server instance on nixos-22.11 (configured without flakes), nix 2.11.1

None of them failed. A direct `nix run` succeeds as well. None of the nix stores contains `cargo2nix`.

Is it possible that you have a corrupted store? (I think it's unlikely that this is the reason, considering that I was able to build `jj` without `cargo2nix`.)

What Nix version are you using? Is this on NixOS? Any interesting nix configuration?

Can you see which process produces the error message? I assume not Nix itself? (Why would it try to access a store path that doesn't exist, if it should know exactly the state of the store.)

**Comment by Ralith** [comment]
```
> nix --version
nix (Nix) 2.11.1
> nixos-version
22.11.1442.2dea8991d89 (Raccoon)
> nix-store --verify
reading the Nix store...
checking path existence...
```
```nix
  nix = {
    package = pkgs.nixUnstable;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
   };
```

> Can you see which process produces the error message? I assume not Nix itself?

It shows up in the terminal when I run the command. Do you know a reasonable way to trace it with any finer granularity?

> Why would it try to access a store path that doesn't exist, if it should know exactly the state of the store?

I agree it is very strange.

**Comment by Ralith** [comment]
Removing (an old version of) `cargo2nix` from my user profile suppressed the error. That has some worrying implications, but they're not jj's problem.
