### ISSUE TITLE
FR: underline current commit in addition to annotating with @

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1103]
Any objections to doing this by default?

**Comment by samueltardieu** [comment]
In addition to the bold font and bright colors?

**Comment by avamsi** [comment]
I'm one of those people who turn off bold text on terminal, so I didn't even realize jj bolds the current copy, TBH. And the colors are distinctive enough on certain terminals but sadly, not on all the terminals I use.

Definitely not by default, then -- maybe as a config option? I don't know if it's already possible (either through the config or through the template).

**Comment by yuja** [comment]
You can set `colors.working_copy.underlined = true`.
See https://github.com/martinvonz/jj/blob/main/src/config/colors.toml for the default color table.

**Comment by avamsi** [comment]
Ah, awesome. Thank you both!

**Comment by martinvonz** [comment]
We could change the default style to use underline instead of bold and bright, or maybe instead of one of them. Another option is to set the background color. In my personal hg config, I have red background set for the working copy's parent.

**Comment by avamsi** [comment]
> We could change the default style to use underline instead of bold and bright, or maybe instead of one of them.

Yeah, I definitely wouldn't mind that 😅, but I suppose someone who actually uses one of them should comment.

> In my personal hg config, I have red background set for the working copy's parent.

Ooh, I would also like to do something like that -- how do I identify the parent?  Maybe there's value in setting up some sort of place where folks can share their jj config / adjacent scripts e.t.c. (a Discord channel?)

**Comment by martinvonz** [comment]
> Yeah, I definitely wouldn't mind that 😅, but I suppose it should be up to someone who actually uses at least one of them.

I tried with just underlining and I found it harder to see than bold+bright, so I think we should either just leave it as is, or use a different background color (but we'd have to pick one that we don't use for anything else).

> Ooh, I would also like to do something like that -- how do I identify the parent?

You mean with hg? We have `{ifcontains(rev, revset("."), "desc.here")}"` in the template and then configured `color.desc.here=red_background`. jj doesn't have a way of identifying the parent(s) of the working copy in the template.

> Maybe there's some value in setting up some sort of place where folks can share their jj config / adjacent scripts e.t.c. (a Discord channel?)

It seem fine to share in the #chat Discord channel.

**Comment by avamsi** [comment]
> You mean with hg?

I completely missed the hg bit 🤦🏻‍♂️, I thought it's possible in jj somehow 😅 (I mostly use the amend workflow, so parent of the current commit is the "actual" commit for me most of the time).
