### ISSUE TITLE
Support git-like remote and local branch UX

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#1136]
## Description

`jj` treats remote branches very differently compared to Git. Unfortunately, `jj` is primarily used as a client to remote Git repositories which the user may or may not have control over. Certain idiomatic Git patterns don't fit this model well, leading to a bad UX:

- Adding a remote with a large number of branches that developers aren't necessarily expected to interact with regularly, e.g. https://github.com/gitster/git has a large number of historical topic branches. This is a somewhat GIt-specific problem since Git repos tend to have more branches than Mercurial repos have bookmarks.
  - branch import causes local branches to be created, and they may be exported back to Git unexpectedly
  - the output of `jj branch list` becomes very large and largely irrelevant

- Adding multiple remotes with different branching structures. In Git, remotes can be used to "bookmark" URLs without necessarily fetching the entire contents of the remote/creating local branches for each remote branch.
  - when branches share the same name across remotes (particularly read-only remotes), the "conflicted" branch state becomes less meaningful

## Proposal

Add a config option that gives a more Git-like user experience to remote branches.  An initial list of features could be:

- Don't create local branches automatically on imports
- Hide remote-only branches in `jj branch list`
- When deleting a remote branch with `jj git push --branch=no-local-target`, require an explicit `--delete` flag

**Comment by martinvonz** [comment]
SGTM :)

**Comment by samueltardieu** [comment]
This should be configurable by remote repository in addition to a default setting.

Wouldn't it be useful to also have an option for `jj git clone` and `jj git remote add` to overwrite the configured default behaviour? It would add this remote-specific option to the local configuration file.

**Comment by martinvonz** [comment]
> This should be configurable by remote repository in addition to a default setting.

Makes sense.

> Wouldn't it be useful to also have an option for `jj git clone` and `jj git remote add` to overwrite the configured default behaviour? It would add this remote-specific option to the local configuration file.

That also makes sense to me. We'd need support for writing configuration files first.

**Comment by ilyagr** [comment]
> Hide remote-only branches in jj branch list

I think this is a good idea, we have some discussion of it in https://github.com/martinvonz/jj/pull/1762#discussion_r1248438240.

I think an important detail is that if `jj branch list` does not print these branches by default, it should instead print a message along the lines of:

> Skipped 55 inactive branches; show them with `--include-inactive`.

**Comment by ppwwyyxx** [comment]
Thanks @yuja for adding this. I think it's better to also hide these branches in `jj log` by default?

**Comment by yuja** [comment]
> I think it's better to also hide these branches in `jj log` by default?

I prefer to see remote branches in log, but we should have some way to hide them. Maybe we can add `local_branches` template keyword for that purpose.
