### ISSUE TITLE
`jj rebase` should accept multiple revisions for `-r` (`-s`, and `-b` are done)

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1158]
It already accepts multiple `-d` arguments.

If multiple `-r` arguments are specified, the parent-child relationship between the multiple commits being rebased should be preserved.

It seems to make little sense to preserve such relationships for `-s` and `-b`.

~There's also the related https://github.com/martinvonz/jj/issues/571 about specifying a revset with multiple commits in a single `-d` or `-r` argument. This seems especially important for `-r`.~ 

**Update:** #571 is now fixed. While the `--allow-large-revsets` option exists, `-r`, `-s`, and `-b` should use it the same way `-d` does.

**Comment by avamsi** [comment]
Does this PR include revsets? I.e., if this were to be implemented, would passing multiple -r arguments and passing a single revset (made up of the same revisions) be equivalent?

Either way, my `torebase` revset alias (consisting of local revisions that are not descendants of `origin/main`) and the `torebase` command alias that prints those revisions would very much appreciate this FR!

**Comment by ilyagr** [comment]
I'll work on `-s` and `-b`.

**Comment by ilyagr** [comment]
Thank you so much for working on this! I haven't been able to look at the details yet, but it sounds very nice.

**Comment by ilyagr** [comment]
I also tried it out, it's wonderful so far :)
