### ISSUE TITLE
FR: support template aliases similar to command and revset aliases

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1190]
This'll be useful for custom log aliases, shell completion functions etc.

**Comment by yuja** [comment]
And options like `ui.relative-timestamps` could be translated to alias rule.
```rust
if relative_timestamp {
    ("format_timestamp(x)", "x.ago()")
} else {
    ("format_timestamp(x)", "x")
}
```

**Comment by yuja** [comment]
Implementation note:

We'll probably need to extract AST-level structure to make alias expansion testable.
Mercurial has Sexp-like tree of tuples for that place. Our revset engine has `RevsetExpression`, which is more close to execution code than AST, but still implements Debug/PartialEq.
