### ISSUE TITLE
Custom pager for diffs?

### ISSUE THREAD

**Issue by max-sixty** [martinvonz/jj#1194]
## Description

Following on from https://github.com/martinvonz/jj/issues/33, would it be possible to support custom pagers? 

I really like `delta` (personally I find it much better than both `jj diff` and `jj diff --git`, though possible I'm just used to it). In git I have this as a setting.

Thanks!

**Comment by martinvonz** [comment]
Does adding `ui.pager = "delta"` to your `~/.jjconfig.toml` do what you want? It seemed to work when I tried it just now.  Looking at https://dandavison.github.io/delta/configuration.html, I suspect `delta` will read other configs from your `~/.gitconfig`, so just leave those there.

**Comment by martinvonz** [comment]
Oh, you'll probably also want to add `diff.format="git"` to your `~/.jjconfig.toml`.

**Comment by max-sixty** [comment]
This works, thanks!

Lmk if there's a place I should have found this prior...

**Comment by martinvonz** [comment]
The [config documentation](https://github.com/martinvonz/jj/blob/main/docs/config.md) mentions the pager config but not `diff.format`. I'm working on a patch for that.

**Comment by martinvonz** [comment]
For the record, that's in PR #1205.

**Comment by dbarnett** [comment]
Seems to work fine, but feels a little weird to have it configured as the pager for *all* commands, not just diff. Would it be overkill to have a mechanism to customize the pager independently for diff vs log vs other commands?

**Comment by dbarnett** [comment]
It also sadly doesn't seem to play nicely with delta's merge conflict support https://dandavison.github.io/delta/merge-conflicts.html. That probably couldn't be supported generically as a "custom pager for diffs" FR though (right @martinvonz ?). I could file an FR to discuss tighter integration if that's an idea worth exploring.

**Comment by martinvonz** [comment]
Do you mean if we could support diff3-style conflict markers? We have #823 for that.

Regarding filing an FR, would that be against delta or jj?

**Comment by dbarnett** [comment]
I see, git style markers might be the piece I was missing.

I'd imagined an FR for jj, assuming that a workaround exists but involves some awkward config on the jj side, in which case the FR would be to make it easy to configure for delta's case and/or capture some notes about the suggested config options to set it up to use delta.
