### ISSUE TITLE
Tab-complete branch names for `jj branch` subcommands 

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#1217]
Tab-completing branch names would be useful for all `branch` subcommands today execpt `list`.

e.g. I run into this on a regular basis:

```sh
$ jj branch delete # wait what that branch again?
$ jj branch list
$ jj branch delete <furiously typed branch name and/or copied>
```

or

```sh
$ jj branch set <typo-ed branch name>
# Ugh
$ jj undo
$ jj branch set <correct branch name>
```

It seems that Clap completion doesn't have support for this yet https://github.com/clap-rs/clap/issues/1232.

**Comment by senekor** [comment]
Here are my custom additions to the auto-generated completions (fish shell):

```fish
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from delete" -f -a "(jj branch list | cut --delimiter ':' --fields 1)"
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from forget" -f -a "(jj branch list | cut --delimiter ':' --fields 1)"
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from rename" -f -a "(jj branch list | cut --delimiter ':' --fields 1)"
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from set" -f -a "(jj branch list | cut --delimiter ':' --fields 1)"
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from track" -f -a "(jj branch list --all-remotes | cut --delimiter ':' --fields 1 | grep '\w@\w')"
complete -c jj -n "__fish_seen_subcommand_from branch; and __fish_seen_subcommand_from untrack" -f -a '(
for line in (jj branch list -a | cut --delimiter ":" --fields 1)
    if echo $line | grep --quiet "^\S"
        set --function __local_branch $line
        continue
    end
    if [ $line = "  @git" ]
        continue
    end
    echo "$__local_branch$(string trim $line)"
end
set --erase __local_branch
)'
```

As mentioned in [this comment](https://github.com/martinvonz/jj/issues/2550#issuecomment-2039523836), adding that to the output of `jj util completion`.

I would be happy to make that contribution, unless maintainers consider this an undue maintenance burden. In my opinion, if it does turn out to be a burden, it can just be deleted again. I don't think shell completions come with any expection of stability.

**Comment by martinvonz** [comment]
That seems fine to me.

Since #3651, `jj branch list | cut --delimiter ':' --fields 1` can be replaced by `jj branch list -T 'name ++ "\n"'`. Maybe the `untrack` script can also be simplified somehow.

**Comment by senekor** [comment]
Great! I didn't think of using templates, great idea. I'll see how simple I can make it and open a PR.

**Comment by julienvincent** [comment]
Here is a slightly modified version of @senekor script that uses cross-platform `cut` arguments, the new `bookmark` subcommand and sets up the autocompletion for all current variations of the branch subcommand:

```fish
set -l list_bookmarks "(jj bookmark list -T 'name ++ \"\n\"')"
set -l subcommands bookmark b branch

complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from delete" -f -a $list_bookmarks
complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from forget" -f -a $list_bookmarks
complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from rename" -f -a $list_bookmarks
complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from set" -f -a $list_bookmarks
complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from track" -f -a "(jj bookmark list --all-remotes -T 'name ++ \"\n\"' | grep '\w@\w')"
complete -c jj -n "__fish_seen_subcommand_from $subcommands; and __fish_seen_subcommand_from untrack" -f -a '(
for line in (jj bookmark list -a | cut -d ":" -f 1)
    if echo $line | grep --quiet "^\S"
        set --function __local_bookmark $line
        continue
    end
    if [ $line = "  @git" ]
        continue
    end
    echo "$__local_bookmark$(string trim $line)"
end
set --erase __local_bookmark
)'
```

**Comment by istudyatuni** [comment]
Clap now has support for dynamic completions under `unstable-dynamic` cargo feature

**Comment by senekor** [comment]
Wow, I just played a little with the [example](https://github.com/clap-rs/clap/blob/master/clap_complete/examples/dynamic.rs) and it totally works. The example doesn't have a _custom_ completer, that one is documented [here](https://docs.rs/clap_complete/latest/clap_complete/engine/struct.ArgValueCompleter.html) and it works too.

So, now it's just about finding time to implement it in jj :wink:
