### ISSUE TITLE
Operation log image seems to be missing some context

### ISSUE THREAD

**Issue by JeffreyFalgout** [martinvonz/jj#1221]
https://github.com/martinvonz/jj/blob/main/demos/operation_log.png

Just before that example starts undoing actions, it says `# The repo now looks like this`, shows the state of the repo, and says `# And the operation log looks like this`, but doesn't actually show what the operation log looks like

**Comment by martinvonz** [comment]
Thanks for letting us know. I'm soon going to update the demos to incorporate recent changes. I'll make sure to fix this at the same time.
