### ISSUE TITLE
On a merge commit, `jj restore file` should restore from the merge of "@-"

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1228]
Currently, if you do not specify any `--from`, `jj restore file` complains that "@-" is not a single revision.

**Comment by martinvonz** [comment]
Good point! It looks like `jj restore` is the only command that uses the "@-" revset in its implementation, here:

https://github.com/martinvonz/jj/blob/8eda80fc539fdf9d9caf9a49d3bbee04f9877e51/src/commands/mod.rs#L2570-L2575

The simplest fix would be to handle the first case specially. However, we should also figure out if we would like an explicit `jj restore --from @- file` to behave the same way. I've previously felt that it's a little weird that `jj diff -r X` cannot be emulated with `jj diff --from X- --to X` for merge commits. So I think we should consider whether we want some commands that currently expect a single revision to also accept multiple revisions when are then merged. I think `jj restore` and `jj diff` are the only two existing candidates. The risk is obviously that users unintentionally specify multiple revisions when they meant one. For example, maybe they have a conflicted branch and they then get confusing behavior from `jj diff --from my-branch`.

**Comment by ilyagr** [comment]
In principle, `jj restore` could take many `--from` arguments and use `--allow-large-revsets`, just like `jj rebase`. That would also be quite simple to implement, but might be overkill.
