### ISSUE TITLE
Materialized conflicts in a deleted file have no context lines

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#1244]
## Description

When `jj` materializes a conflict in a file that was deleted, no context lines are shown, e.g. the file is materialized like:

```
>>>>>>>
<<<<<<<
%%%%%%%
+    enum config_scope parsing_scope;
>>>>>>>
```

instead of seeing the change in its original context, like:

```
struct config_stack {
    struct config_source *head;
+    enum config_scope parsing_scope;
};
```

I typically encounter this when I rebase a change onto a renamed file. e.g. prior to https://github.com/martinvonz/jj/pull/1061 getting merged, I had WIP changes on `commands.rs`. That PR renames `commands.rs` -> `commands/mod.rs` (and more), so when I rebased my WIP changes onto that PR, I see a context-less conflict on `commands.rs`.

Since the lines have no context, it takes me a while to figure out where I should move my changes to. I end up resorting to `jj obslog` to find the lines in some previous version and then manually applying the changes to the right place.

Besides rename detection, a possible fix is to show context lines from the undeleted side. This would require special-casing in the event of a deleted file, since we otherwise always show the left side as the base.

**Comment by martinvonz** [comment]
I'm pretty sure we're hitting this block:
https://github.com/martinvonz/jj/blob/b44148871a0db33fb442259bdf7ce1048d35fa7b/lib/src/files.rs#L257-L259

Also note that TODO above the function:
https://github.com/martinvonz/jj/blob/b44148871a0db33fb442259bdf7ce1048d35fa7b/lib/src/files.rs#L210-L213

Should be an easy fix.

**Comment by martinvonz** [comment]
In case anyone wants to reproduce this, you can simply create a file with some lines in a base commit, then delete it one child, modify it in a sibling, and then merge the two commits.
