### ISSUE TITLE
diff-editor does not seem to work with additional arguments

### ISSUE THREAD

**Issue by isinyaaa** [martinvonz/jj#1272]
## Description

I'm trying to use a custom `diff-editor` but the way docs describe it doesn't seem to actually work.

## Steps to Reproduce the Problem

1.  Set `ui.diff-editor = ["nvim", -d", "$left", "$right"]` 
1.  Use `jj split`

I also tried to use `ui.diff-editor = "nvim -d"` with no success, as it errors out with

```raw
Error: Failed to edit diff: Error executing 'nvim -d' with args ["/var/folders/5c/s_mq3zbx0tj9vpxpg8pzjg7w0000gn/T/jj-diff-edit-c5TCi7/left", "/var/folders/5c/s_mq3zbx0tj9vpxpg8pzjg7w0000gn/T/jj-diff-edit-c5TCi7/right"]: No such file or directory (os error 2)
```

## Expected Behavior

This should use NeoVim as the `diff-editor`.

## Actual Behavior

I instead get:

```raw
Using default editor 'meld'; you can change this by setting ui.diff-editor
Error: Failed to edit diff: Error executing 'meld' with args ["/var/folders/5c/s_mq3zbx0tj9vpxpg8pzjg7w0000gn/T/jj-diff-edit-cDEpkw/left", "/var/folders/5c/s_mq3zbx0tj9vpxpg8pzjg7w0000gn/T/jj-diff-edit-cDEpkw/right"]: No such file or directory (os error 2)
```

## Specifications

- Platform: MacOS Ventura 13.2.1 (M1)
- Version: 0.6.1

**Comment by samueltardieu** [comment]
> `ui.diff-editor = ["nvim", -d", "$left", "right"] `

Do you mean `"$right"` instead of `"right"`? Can you check with `jj config list` that it appears configured as expected?

**Comment by isinyaaa** [comment]
I just noticed I'm using an older release of `jj`, I'll try updating it via brew or install from cargo then update the issue if it still happens.

**Comment by isinyaaa** [comment]
> > `ui.diff-editor = ["nvim", -d", "$left", "right"] `
> 
> Do you mean `"$right"` instead of `"right"`? Can you check with `jj config list` that it appears configured as expected?

Yes, sorry.

**Comment by isinyaaa** [comment]
Sorry for the noise, this works on the latest release just fine.
