### ISSUE TITLE
pager does not seem to work with pipes

### ISSUE THREAD

**Issue by isinyaaa** [martinvonz/jj#1273]
## Description

I've been using `diff-so-fancy` with `git` for quite a while now, so I think some other people might want to use it as well, though I'm pondering on just using the defaults on `jj`.

## Steps to Reproduce the Problem

1. Set `ui.diff.format = "git"` and `ui.pager = "diff-so-fancy | less -RFX"`
1. Use `jj diff`

## Expected Behavior

Output should be piped/paged through `less -RFX`.

## Actual Behavior

Output is not paged at all.

## Specifications

- Platform: MacOS Ventura 13.2.1 (M1) 
- Version: 0.7.0 (installed directly from `cargo`)

**Comment by isinyaaa** [comment]
> Unlike git/hg, the command is executed directly. You'll probably need to pass the command through /bin/sh (something like `ui.pager = ["sh", "-c", "diff-so-fancy | less -RFX"]`.)

Works, perfectly, thanks :) I wonder if this should be in the docs, though.

**Comment by yuja** [comment]
Agreed, it would be nice if the doc had a pipe example.

**Comment by martinvonz** [comment]
With you PR #1274 merged (thanks!), I'll close this.
