### ISSUE TITLE
Support multiple working copies

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#13]

**Comment by martinvonz** [comment]
I'm debating what the UX should be when a commit that's checked out in one working copy gets rewritten.

First some background: We currently keep track of the current checkout in the repo "view", which is part of the "operation" object in the operation log. This is considered the source of truth for which commit is checked out the working copy. That record gets updated within a transaction, before the working copy itself gets updated. The working copy has its own record of what's currently checked out. That's supposed to follow the record in the view object. For example, if a transaction committed and then the power was cut, we'll end up with a mismatch. In such cases, next time `jj` is run, we should detect that the working copy commit isn't the intended commit, and automatically update to the new commit. That's not implemented yet, but it should be done regardless of support for multiple working copies.

For support for multiple working copies, I plan to extend the view object to keep track of the current checkout in each working copy. The question is what should happen if you run a command in one working copy that impacts the checkout in another working copy. For example, you might rebase a whole tree of commits, including the current working copy's checkout and another working copy's checkout. I see a few options:

1. Update the other working copies' checked-out commits and also update the working copy files. This will of course only work if the other working copy is on a file system that's available (e.g. not on a USB stick or a network file system). It also requires the central repo to keep track of where every working copy is.
2. Update the other working copies' checked-out commits, but don't update their working copy files. The working copy would then be stale and it would be update later when the user runs a command in that working copy. There's a small risk that the old working copy's checkout would be GC'd at this point.
3. Don't update the other working copies' checked-out commits but leave them visible. This would mean that you'd end up with two visible commits with the same change ID, which by definition means that you'll have divergence. The user would then have to manually update and hide the old commit, or run some command that we don't yet have.
4. Don't update the other working copies' checked-out commits and hide them. This would mean that your working copy would not appear in `jj log` but `jj log -r @` would still show it. The change would not be considered divergent. The user can recover by updating to the new commit. We would probably want to make `jj status` highlight the fact that the working copy's commit is not currently visible.

**Comment by arxanas** [comment]
It might be worth delineating two specific workflows that the user can pick from at a given time: live or on-demand sync. Similar to auto-fetch/auto-push systems for Git, or whatever Fossil does with auto-syncing. In particular, the same live sync workflow would extend to the use-case of syncing across multiple devices.

I think it would be hard to pick a single workflow that aligns with user expectations for multiple checkouts.

**Comment by martinvonz** [comment]
Interesting idea. I'll have to go read about what Fossil does.

For reference, Git does 3 or 4 (they're the same there since it has no concept of change ID and it only moves the current branch pointer on rebase [1]). Git still has the main repo keep track of each worktree's location. IIRC, it does that mostly to prevent GC of commits checked out in other worktree. I don't know if the reflog for each worktree's HEAD is stored in the main repo or in worktree (it's easy to check, of course, I just haven't yet).

[1] By the way, @arxanas, since `git move` can move multiple branches, I suppose that means you may want to check that the branches you're about to move are not checked out in other working copies (I haven't checked if you already do, but it seems like something that's easy to overlook).

**Comment by martinvonz** [comment]
I just pushed some commits refactoring `ReadonlyRepo` so it no longer has `working_copy()` and `working_copy_path()`. The coupling was already very weak, but now it's gone completely. It wasn't a necessary change, as we could instead have made `ReadonlyRepo::working_copy()` simply depend on which working copy it was loaded from, but it is cleaner to separate it completely. It was always a bit ugly how the `WorkingCopy` had to be kept in a `Mutex` only because `ReadonlyRepo` is `Sync`. Now that `ReadonlyRepo` doesn't have a `WorkingCopy`, we don't need the `Mutex` and we can benefit from Rust's ownership rules.

I've added a "workspace" concept and a `Workspace` type, representing a working copy and a `.jj/` directory. `.jj/working_copy/` will keep the working copy state ("index"/"dirstate" in Git-/Mercurial-speak) for the workspace. All other directories in `.jj/` (i.e. `.jj/store/`, `.jj/op_store/`, `.jj/op_heads/`, `.jj/index/`) will be shared between all workspaces backed by the same repo. Perhaps we should move them into `.jj/repo/` or something to clarify that.

I still haven't decided which of the solutions for updating "other" workspaces I like best.

**Comment by martinvonz** [comment]
I've put the this work on hold for a while but I hope to come back to it now. One idea I remember having earlier was to record the operation ID of the last successful update in `.jj/working_copy/`. I don't remember the details, but thinking a bit more about it now, it seems to make sense.

By having the operation ID there, we can detect if the working copy is stale. It may be stale because a process had crashed before it finished updating the working copy, or maybe it was a workspace that was stored on a disconnected USB stick. It could also be that it was stale because we went with solution 2 above and a process had rebased the commit in another workspace connected to the same repo.

The working copy's associated operation ID can also help us address [a hack](https://github.com/martinvonz/jj/blob/4e20548e3290325ce107692cda7b65fcaff131f8/src/commands.rs#L466-L467) related to concurrent updates of the working copy. If we have recorded the operation ID there, then we simply reload at that operation instead of the current operation.

If we store the operation ID in the `.jj/working_copy/`, then the commit ID that's recorded there won't be needed anymore since it can be found in the operation. We may still want to store it so we don't need to look up the operation when updating the working copy, but it would be just a cache of the checkout recorded in the operation.

**Comment by martinvonz** [comment]
You can now create additional workspaces with `jj workspace add <path to new workspace>`, list workspaces with `jj workspace list`, and forget workspaces with `jj workspace forget`. Each workspace's checked-out commit shows up in the default log template (they're recorded in the repo view, so that's easy and cheap to do). You can also refer to them using e.g. `jj diff --from workspace1@ --to workspace2@` to show a diff from workspace1's checkout to workspace2's checkout. Plain `@` is now a short form to refer to the current workspace's checkout.

I went with solution 2 [above](https://github.com/martinvonz/jj/issues/13#issuecomment-967764814), meaning that all checkouts are rebased along with commits they point to, but the working copy is not updated. If you run a command in the workspace after its checkout has been updated from another workspace, then it'll get automatically updated. Perhaps we should change that to just print a warning, in case the user was running a build or tests, or maybe it's just confusing.

I consider this done now and we can open new bugs for any improvements to it.
