### ISSUE TITLE
Rust panics during conflict resolution

### ISSUE THREAD

**Issue by xxxserxxx** [martinvonz/jj#1304]
I rebased a branch, and fixed a trivial conflict. I then continued working. When I went to push, I discovered that the conflict, some 10 commits prior, was preventing the push. So I started a series of 'jj resolve', 'jj edit' and similar to try to resolve the conflict, which only appeared to propegate and get worse, pushed into conflicts on every commit between the original and the end. As I worked backwards through history to resolve the conflict, I ended up at a point where I'm unable to do anything with the repo, because jj keeps crashing with an 'index out of bounds' error:

```
$ jj log
Error: The working copy is stale (not updated since operation aabfb13f4075).
Hint: Run `jj workspace update-stale` to update it.
$ jj workspace update-stale
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', lib/src/conflicts.rs:215:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any jj command either gives me the "stale" message, or the panic.

Since I'm at least 3 commits from the head of the branch, and jj crashes, is there any way I can get to the head to recover my work?

jj 0.7.0   
Linux nivrim 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux

**Comment by yuja** [comment]
Can you try `update-stale` with jj at 975350f73b28? Appears that the recent change introduced off-by-one error.

**Comment by martinvonz** [comment]
For next time, it's better to resolve conflicts in the first commit they appear and only resolve any remaining conflicts in descendants afterwards. We should probably print a hint about that somewhere, maybe in `jj resolve` and maybe in `jj status`.

**Comment by xxxserxxx** [comment]
I installed jj with cargo; I'm not a Rust developer -- how do I install a specific commit with cargo? Or do I need to clone the repo and install it from there?

I did try to resolve the conflict when it happened, but it wasn't clear to me what I needed to do. I manually fixed the single conflict, but when I ran the command suggested by the status command, it didn't do what I expected.

There are a lot of things contributing to my struggle with this: I'm coming from mercurial; I use git only when forced to; I'm entirely new to jj; and I was fixing bugs in someone else's project. The conflict was a result of trying to merge in bug fixes from someone else's fork of the same project, and I was working on top of that.  While I don't think this is an edge case situation, it probably was not the best first situation to start using jj.

**Comment by xxxserxxx** [comment]
Ok, different question: how do I resolve the conflicts? Every time I fix it in one revision, it just pushes the conflict marker to other commits, often to children which had no conflicts. At this point, I just want to get the repo clean, and I'm considering two options:

- Starting over and re-adding every of the 15 changes, one at a time, on a fresh repo
- Squashing all of the 15 commits, discarding the history, and hoping it doesn't push the conflict flag farther into history

**Comment by martinvonz** [comment]
To clarify, let's say your repo looks like this:
```
$ jj log # not actual output below
o S conflict
|
o R conflict
|
o Q conflict
|
o P
|
```

You would then start by doing `jj checkout Q`. That would get you conflict markers in the working copy. Resolve those, run tests, etc., and then do `jj squash` to move the conflict resolution into Q. That would propagate up to R and S. If those commits touched the same lines (or very nearby lines), you'd get new conflicts there to resolve. You'd then repeat the process with `jj checkout R`, resolve the conflict, `jj squash`.

I hope that helps.

**Comment by xxxserxxx** [comment]
Thank you, that does.
