### ISSUE TITLE
FR: A way to commit a stale workspace

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1310]
If the workspace is stale, currently `jj workspace update-stale` will try to annihilate it and replace it to something from the repo.

We could have a second command, e.g. `jj workspace commit-stale`, that commits the current workspace to the repository. It could work similarly to `jj new` and take a revision argument. Instead of creating an empty commit, it would create a commit with the current state of the workspace and resolve the "stale" condition.

This would be useful if the user is worried that they made some important changes to the workspace while it was in the stale state.

Logically, it would make sense to have the new commit always be a direct child of the root commit, but that seems like it's asking for trouble in practice.

This is related to https://github.com/martinvonz/jj/pull/1309

**Comment by yuja** [comment]
IIRC, the plan is to somehow make `update-stale` not lose the working copy changes.
https://github.com/martinvonz/jj/pull/515#issuecomment-1249931581

**Comment by martinvonz** [comment]
Yes, and I think it's probably not too hard to implement that now that we have the `update-stale` command and we keep the operation id up to date when we update the working copy.
