### ISSUE TITLE
`format_short_commit_id`/`format_short_change_id` seem to have no effect

### ISSUE THREAD

**Issue by necauqua** [martinvonz/jj#1329]
## Steps to Reproduce the Problem

1. Checkout some git repo, `jj log -r :@` works as expected
2. Change the config like:
```toml
[template-aliases]
'format_short_id(id)' = 'id.shortest(7)'
```
It works as expected

3. But if you set the config to:
```toml
[template-aliases]
'format_short_commit_id(id)' = 'id.shortest(7)'
'format_short_change_id(id)' = 'id.prefix()'
```
The id format of both IDs is just the default, and if you do those changes separately it doesn't work either. Even the 'uppercase change IDs' one copied straight from the example in config docs.

## Expected Behavior
It works

## Actual Behavior
It does not

## Specifications

- Platform: NixOS unstable
- Version: 0.7.0

**Comment by martinvonz** [comment]
The ability to style the two kinds of IDs differently came in #1299, which was after the release of 0.7.0. I don't use NixOS myself, but see [our installation instructions](https://github.com/martinvonz/jj#nix-os) for how to use the flake to get an unreleased version (i.e. later than 0.7.0).

**Comment by martinvonz** [comment]
Also note that `id.prefix()` in your example should be `id.shortest().prefix()`

**Comment by necauqua** [comment]
Ooh so that's just an unreleased feature, got it, sorry to trouble
Just found out about jj and learning stuff, I like it a lot :)

**Comment by martinvonz** [comment]
> Ooh so that's just an unreleased feature, got it, sorry to trouble Just found out about jj and learning stuff, I like it a lot :)

No problem! I'm glad you like it.

Oh, also see our hot-off-the-press documentation of templates in https://github.com/martinvonz/jj/blob/main/docs/templates.md :) Most (all?) of it still applies even if you're on the released version.

**Comment by dbarnett** [comment]
Related: #1153

Although in this case IIUC it's not "wrong" to define unused template aliases. Maybe could have some kind of linting to highlight aliases you're not currently using but I'm not sure how to make that discoverable for cases like this without getting annoying for other cases. 🤔
