### ISSUE TITLE
jj does not work with sr.ht

### ISSUE THREAD

**Issue by necauqua** [martinvonz/jj#1334]
## Steps to Reproduce the Problem

Try to clone something from sr.ht, for example `jj git clone git@git.sr.ht:~necauqua/nixos-config`, assuming you've registered and added your SSH key there.
Alternatively, clone it with git, init jj and then try to push.
Alternatively alternatively, create a new repo, add a remote pointing to not-yet-existent sr.ht repo and then try to push (this is something that sr.ht supports - I think it's transparent to git so should be no difference there anyway)

## Expected Behavior
It should clone it and push to it, just `git clone`/`git push` work fine ofc.

## Actual Behavior
It fails with this error:
```
Error: Fetch failed: failed to start SSH session: Unable to exchange encryption keys; class=Ssh (23)
```

## Specifications

- Platform: NixOS unstable
- Version: d4b13d7

~hey look an actual issue this time~ it's a duplicate, although I searched for that.. oh well 🤷

**Comment by PhilipMetzger** [comment]
This was previously reported in #389. I don't think anything happened though, although `git2` was upgraded from `0.15` to `0.16.1`.

**Comment by martinvonz** [comment]
Yes, this seems very likely to be the same issue. I probably won't have time to look into what's going on here. Hopefully someone else can figure it out.
