### ISSUE TITLE
RFE: Bare jj repositories

### ISSUE THREAD

**Issue by xelxebar** [martinvonz/jj#1372]
## Description

Tangentially related to #1249. 

With git, I have a workflow where all my git repositories are organized as a collection bare repos sitting together (in a git repo!) and then external worktrees scattered about my filesystem. This is just a minimal way of managing all my git repos, and it would be nice to do something similar with jujutsu.

## Workaround

Piggy-backing off how `jj workspace add` works, we can move the `.jj/repo` wherever and replace it with a file containing the absolute path to that location.

It's also important to note that the *only* bytes in the `.jj/repo` "link" can be part of the path. In particular, a trailing newline causes the repo to not be found.

**Comment by martinvonz** [comment]
What's the advantage of bare repos? If it's about saving the space used by the working copy, would it work to instead check out the root commit or to include no paths in the checkout (`jj sparse --clear`)?

**Comment by xelxebar** [comment]
Ah, interesting. Those are options I was unaware of and would certainly cover the primary need. 
Here are the reasons other reasons I use bare git repos:
* Batch clone a bunch of repos without thrashing the filesystem (as much?),
* Avoid flubs from accidentally trying to do worktree-requiring ops on the bare copy, and
* Just cosmetic, but allow cloning in an obvious way from the local copy, *e.g* `git clone /path/to/repo.git`

**Comment by martinvonz** [comment]
> Ah, interesting. Those are options I was unaware of and would certainly cover the primary need.

Great!

> * Batch clone a bunch of repos without thrashing the filesystem (as much?),

It should be equivalent if we add an option to start with an empty set of paths in the working copy and/or to check out the root commit. 

> * Avoid flubs from accidentally trying to do worktree-requiring ops on the bare copy, and

Makes sense. The empty set of paths would solve that too.

> * Just cosmetic, but allow cloning in an obvious way from the local copy, _e.g_ `git clone /path/to/repo.git`

I think it makes sense to still allow that.

**Comment by xelxebar** [comment]
> It should be equivalent if we add an option to start with an empty set of paths in the working copy and/or to check out the root commit.

Sounds like a straightforward approach. Cheers!

**Comment by martinvonz** [comment]
If we add support for creating a clone with a sparse working copy, we should keep in mind that we have several ways of creating working copies:  `jj git clone`, `jj init`, and `jj workspace add`. It may make sense to reuse some code and some (but not all) argument definitions for those cases, maybe including functionality for giving the workspace a name (instead of the default of "default").

**Comment by xelxebar** [comment]
Note, we would probably want to also make `init --git-repo=<path>` also support bare backing repos. Currently, it hard-expects `path/.git` to exist.

**Comment by martinvonz** [comment]
Yes, that's #1249 (which you linked to above), I think. Happy to review a PR for that :) I imagine it's not very hard to implement. It's just not been a priority for me.

**Comment by xelxebar** [comment]
Haha. That memory sector must have gotten reclaimed. Roger. I'll add that PR to the list of possible ways I can procrastinate on other tasks in my life :D

**Comment by martinvonz** [comment]
I don't think we've had many requests for this and we have an alternative solution (checking out the root commit) that seems to work well, so I'll close this.
