### ISSUE TITLE
Jj git fetch not connecting to ssh-agent

### ISSUE THREAD

**Issue by xelxebar** [martinvonz/jj#1374]
### Overview

For some reason, ssh operations don't seem to be connecting to the `ssh-agent` for me. This is means that my `~/.ssh/config` doesn't get read, so port and key settings never get read:

```
$ jj git fetch
Error: Unexpected git error when fetching: failed to connect to git.wilsonb.com: Connection refused; class=Os (2)
```

#### Level 1

I am fairly sure my `ssh-agent` is running and `SSH_AUTH_SOCK` is setup correctly:

```
$ ssh-add -L
...
<my key>
...
```

#### Level 2

But, just to be sure, I directly checked whether `jj` is actually trying to connect to `ssh-agent`

```
$ strace -fo ~/jj.strace jj git fetch
...
$ grep -F "$SSH_AUTH_SOCK" ~/jj.strace || echo nope
nope
```

#### Level 3

But since `SSH_AUTH_SOCK` was added in 4a1576c, I started to doubt my sanity, so I ran `ssh-agent -d`, which stays in the foreground and noisily shows when anyone connects. Running something like `ssh example.com` does cause it to generate connection logs; however, in the same shell as that working `ssh` command, running `jj git fetch` errors out, and `ssh-agent` stays completely silent.

Am I missing something obvious?

### Version info

I am running the latest flake on `HEAD`:

```
$ nix shell github:martinvonz/jj#jujutsu
$ command -v jj
/nix/store/8i7lzldsqwl35zl04p8x7vlll03zjch4-jujutsu-unstable-86318bf/bin/jj
```

**Comment by joyously** [comment]
> `grep -F "$SSH_AUTH_SOCK" ~/jj.fetch || echo nope`

I had to read about shell operators, but didn't get a clear answer on how the shell parses `||` ; as meaning "OR" or meaning pipe to nothing and then pipe to the `echo`. (I need a better reference manual, but don't know what shell you are using.)

**Comment by xelxebar** [comment]
Ah, that's just showing that `grep` failed to find anything. The relevant documentation for `||` is POSIX shell [OR Lists](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_03_08). The key in this case is to know that `grep` exits with `1` when it finds zero matches.

**Comment by martinvonz** [comment]
What's the remote's URL? Does `git clone` from the same URL work? How about `jj git clone`?

**Comment by xelxebar** [comment]
It's my personal server: `git@git.wilsonb.com:dyalog-play.git`, and `git clone` succeeds, but `jj git clone` fails.
The error message itself can probably be ignored. I'm running `sshd` on funky random port, so `connect` is getting `ECONNREFUSED` since it's not ussing `ssh-agent` and probably trying to directly connect over 22.

**Comment by martinvonz** [comment]
I suspect this is a libgit2 thing. I found https://stackoverflow.com/questions/41101414/unable-to-make-julia-package-manager-work-behind-proxy and https://discourse.julialang.org/t/using-pkg-behind-a-firewall/6295 about a similar issue. Do you have `$HTTP_PROXY` and/or `$HTTPS_PROXY` set? Maybe you need to move those to config in that case.

**Comment by xelxebar** [comment]
```
$ env | grep -Fi proxy || echo nope
nope
```

**Comment by martinvonz** [comment]
I don't have any other ideas, I'm afraid. I still suspect it's a libgit2 bug/limitation, or possibly a bug in how we use libgit2.

**Comment by xelxebar** [comment]
Roger. I'll try to spin up a Rust dev env and see what I can find.

**Comment by yuja** [comment]
> I'm running `sshd` on funky random port, 

Where did you set the destination port number? jj might not read ~/.ssh/config because it doesn't use the openssh's ssh command.

**Comment by xelxebar** [comment]
Hah. You're completely right. Embedding the port number in the fetch URL did the trick: `ssh://git@git.wilsonb.com:24570/~/dyalog-play.git`.

I was thinking that `ssh-agent` passed connection establishment off to openssh somehow, but it turns out that `ssh-agent` keeps its responsibilities small and only provides auth tokens. Here's a good overview explanation: https://unix.stackexchange.com/questions/338853/how-to-use-ssh-agent-for-offering-host-specific-keys-from-ssh-config-file-and#answer-590262

It's pretty annoying that `sshlib2` pushing `ssh_config` parsing off to its users. Anyway, since that's on our radar already and this issue is unrelated, I'm closing.

**Comment by xxxserxxx** [comment]
What if it's not the port? I tried again with Sourcehut, but it seems to still be broken.

- #1334
- #389
- #928

Is there any chance of replacing libgit2? It seems to be having a remarkable number of issues.

**Comment by xelxebar** [comment]
@xxxserxxx It's hard to say without knowing specifics of your case.

1. Is `ssh-agent` running?
2. Do you have `SSH_AUTH_SOCK` set correctly?
3. Have you added your key(s) with `ssh-add`?
4. What settings, if any, are you setting in `~/.ssh/config` that apply to SourceHut?

> Is there any chance of replacing libgit2? It seems to be having a remarkable number of issues.

AFAICT, the issues are all centered around libssh2 (not libgit2) electing to not parse `ssh_config` files.

**Comment by martinvonz** [comment]
@xxxserxxx, see the update from @yuja in https://github.com/martinvonz/jj/issues/389#issuecomment-1473098558.

**Comment by xxxserxxx** [comment]
@martinvonz, #389 doesn't fix it for me:

```bash
$ ###### Remove the existing keys
$ ssh-keygen -R git.sr.ht -f .ssh/known_hosts
# Host git.sr.ht found: line 40
# Host git.sr.ht found: line 61
.ssh/known_hosts updated.
Original contents retained as .ssh/known_hosts.old
$ 
$ ###### And then, from the the instructions, re-add the keys (keys trimmed for brevity)
$ cat >> .ssh/known_hosts
git.sr.ht ssh-rsa AAAAB3...W+UvKB3SOz
git.sr.ht ecdsa-sha2-nistp256 AAAAE2VjZHN...WTkmglpYhFp4Iy4=
git.sr.ht ssh-ed25519 AAAAC3NzaC1lZ...DSAvW0t2Tkj60
$ 
$ ###### Cloning with jj fails
$ jj git clone git@git.sr.ht:~ser/gonic
Fetching into new repo in "/home/ser/gonic"
Error: Fetch failed: failed to start SSH session: Unable to exchange encryption keys; class=Ssh (23)
$ 
$ ###### But cloning with git succeeds
$ git clone git@git.sr.ht:~ser/gonic
Cloning into 'gonic'...
X11 forwarding request failed on channel 0
remote: Enumerating objects: 8702, done.
remote: Counting objects: 100% (8702/8702), done.
remote: Compressing objects: 100% (2653/2653), done.
remote: Total 8702 (delta 5643), reused 8702 (delta 5643), pack-reused 0
Receiving objects: 100% (8702/8702), 42.80 MiB | 1.67 MiB/s, done.
Resolving deltas: 100% (5643/5643), done.
```

To answer @xelxebar's questions, yes, ssh-agent is running -- and verified with the correct key, since the previous git clone worked. But test it anyway trimming the keys for brevity:

```bash
$ ssh-add -L
ssh-rsa AAAAB3N...XzHVWc= ser@glamdring
ssh-rsa AAAAB3Nz...7sedW+EKEHDcFYpNpk= /home/ser/.ssh/id_rsa
ssh-ed25519 AAAAC3NzaC...1v2HFDG+dDv1w9VihOIv7J57w ser@glamdring
ssh-dss AAAAB3Nz...OHE+cpyB3IqbwA== /home/ser/.ssh/id_dsa
$ 
$ ###### I have nothing in my .ssh/config for Sourcehut
$ grep sr.ht ~/.ssh/config
$ 
```

So: I completely moved `.ssh` out of the way, copied only the required in, and ran a totally new agent; git cloned the repo successfully, jj git fails.

```bash
$ mv .ssh ssh_
$ mkdir .ssh
$ cat > .ssh/known_hosts
git.sr.ht ssh-rsa AAAAB...PYW+UvKB3SOz
git.sr.ht ecdsa-sha2-nistp256 AAAAE...TkmglpYhFp4Iy4=
git.sr.ht ssh-ed25519 AAAAC3...SAvW0t2Tkj60
$ 
$ ###### Set up ssh-agent again
$ eval $(ssh-agent)
Agent pid 2971163
$ ssh-add -L
The agent has no identities.
$ ssh-add .ssh_/id_rsa
Enter passphrase for .ssh_/id_rsa:
Identity added: .ssh_/id_rsa (.ssh_/id_rsa)
$ ssh-add -L
ssh-rsa AAAAB3Nz...W+EKEHDcFYpNpk= .ssh_/id_rsa
$ 
$ ###### Test git success
$ git clone git@git.sr.ht:~ser/gonic
Cloning into 'gonic'...
remote: Enumerating objects: 8702, done.
remote: Counting objects: 100% (8702/8702), done.
remote: Compressing objects: 100% (2653/2653), done.
remote: Total 8702 (delta 5643), reused 8702 (delta 5643), pack-reused 0
Receiving objects: 100% (8702/8702), 42.80 MiB | 1.56 MiB/s, done.
Resolving deltas: 100% (5643/5643), done.
$ 
$ rm -rf gonic
$ jj -v git clone git@git.sr.ht:~ser/gonic
2023-03-17T17:21:00.505079Z DEBUG jujutsu::cli_util: verbose logging enabled
Fetching into new repo in "/home/ser/gonic"
2023-03-17T17:21:00.531264Z DEBUG fetch{remote_name="origin" branch_name_globs=None git_settings=GitSettings { auto_local_branch: true }}: jujutsu_lib::git: remote.download
Error: Fetch failed: failed to start SSH session: Unable to exchange encryption keys; class=Ssh (23)
$
```

I was able to clone from Sourcehut earlier by building with `--no-default-features`; it was recommended in another ticket because it disabled bundled `libssh2` (or something like that). However, with or without that it no longer talks to Sourcehut.  Github and Gitlab work; just not Sourcehut:

```bash
$ jj git clone git@github.com:xxxserxxx/stmp.git stmp
Fetching into new repo in "/home/ser/stmp"
Working copy now at: 26128964732d (no description set)
Added 12 files, modified 0 files, removed 0 files
$ 
$ jj git clone git@gitlab.com:serussell/logxi.git
Fetching into new repo in "/home/ser/logxi"
Working copy now at: 29639e852b47 (no description set)
Added 29 files, modified 0 files, removed 0 files
$ 
$ jj git clone git@git.sr.ht:~ser/stmp
Fetching into new repo in "/home/ser/stmp"
Error: Fetch failed: failed to start SSH session: Unable to exchange encryption keys; class=Ssh (23)
$
```

**Comment by yuja** [comment]
> ```shell
> $ cat >> .ssh/known_hosts
> git.sr.ht ssh-rsa AAAAB3...W+UvKB3SOz
> git.sr.ht ecdsa-sha2-nistp256 AAAAE2VjZHN...WTkmglpYhFp4Iy4=
> git.sr.ht ssh-ed25519 AAAAC3NzaC1lZ...DSAvW0t2Tkj60
> ```

If you mean you've added the `ssh-rsa` line, remove it (or at least move it after the other lines.)

**Comment by yuja** [comment]
> Error: Fetch failed: Failed to retrieve list of SSH authentication methods: Failed getting response; class=Ssh (23); code=Auth (-16)

I got this error if I deleted my private keys from the agent (`ssh-add -D`), but I have no idea if that's the error you saw.

`jj -v` (or `RUST_LOG=trace jj`) might show some more information, but tracing options are far more restricted compared to `ssh -v`. You can also use wireshark to inspect the initial key exchange part.

**Comment by xelxebar** [comment]
FWIW, I can successfully reproduce.

After playing around a bit, the issue only appears when I have lots of keys in `ssh-agent`. In fact, it only happens when my sourcehut keys is low in the list of keys added to `ssh-agent`. The last successful cutoff seems to be 6th place. I am guessing that `libssh2` simply ends up trying all keys in the agent, in order, and that Sourcehut has a hard limit of 5 on the number of failed auth attempts before forecfully killing the connection.

@xxxserxxx What happens if you use an ssh-agent with *only* your Sourcehut key?

The "correct" fix in this case is to register each of your keys with `ssh-agent` to be host-specific, *cf* the `-h` flag from ssh-add(1).

**Comment by yuja** [comment]
Maybe you can try other type of private key? My key is `ssh-ed25519`, which appears to work for `jj` to connect to git.sr.ht.

> how would I use ssh -v with jj?

I don't know libgit2 internals, but maybe it doesn't support shelling out ssh transport. What we can do with `ssh -vvv...` is, to trace how `git`/`hg` can establish ssh connection, and guess workaround for libgit2/libssh2.

**Comment by xelxebar** [comment]
@xxxserxxx I recommend doing some sanity checking yourself: E.g.
- Are you sure you sure `git` is actually connecting to `ssh-agent`? E.g. put `ssh-agent` in a known broken state (i.e. with no keys) and make sure `git clone` fails.
- Is `ssh-agent` actually getting a request from jj? I.e. run `ssh-agent` in the foreground with debug logs enabled. Compare logs between when you run `jj git clone` and `git clone`;
- Exactly what settings are needed for `git clone` to work? E.g. Drop into a lightweight Alpine Linux container (or whatever) and set up the bare minimum needed to connect with git.

The above are just examples. The key is to doggedly check your assumptions, which will help you nail down exactly what is falling over. Heck, there is a whole zoo of more low-level options for debugging as well, *e.g.* `strace`/`ltrace`, `rust-gdb`,  *etc.*

**Comment by xxxserxxx** [comment]
So, to try the "really-truly" isolated approach, I tried in an Alpine container. I'm trimming liberally for brevity, but the punchline is that jj segfaults when trying to do a clone.

I'm running a container that's sharing the key via a mount; the minimum to get git working was pretty minimal:

```
$ mkdir container-ssh
$ cp .ssh/id_rsa .ssh/id_rsa.pub container-ssh
$ podman run -it --rm -v $PWD/container-ssh:/root/.ssh /bin/sh
# cd ~
# apk add git openssh
...
# eval $(ssh-agent)
# ssh-add .ssh/id_rsa
...
# git clone git@git.sr.ht:~/stmp
... (Success)
# rm -rf stmp
```

To get jj running was a bit more work; rustup was required because the Alpine package's rustc is 1.60, and the jujutsu build requires 1.64. Compressing a fair bit of trail and error, it needed 5 more packages. FWIW, not only does the ssh clone from sr.ht segfault, but https clone from github does as well.

```
# apk add rustup build-base pkgconfig openssl openssl-dev
...
# rustup-init -y
...
# cargo install --git https://github.com/martinvonz/jj.git --bin jj jujutsu
...
   Compiling jujutsu v0.7.0 (/root/.cargo/git/checkouts/jj-1467e3dd78fc324a/2a87e1f)
    Finished release [optimized] target(s) in 4m 41s
  Installing /root/.cargo/bin/jj
   Installed package `jujutsu v0.7.0 (https://github.com/martinvonz/jj.git#2a87e1f9)` (executable `jj`)
# jj version
0.7.0
# jj git clone git@git.sr.ht:~ser/stmp
Segmentation fault
# jj git clone https://github.com/xxxserxxx/stmp
Segmentation fault
```

I installed `strace` but the failure point means nothing to me:

```
# strace jj git clone https://github.com/xxxserxxx/stmp
...
stat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=13488, ...}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f34ef756b06}, NULL, 8) = 0
rt_sigreturn({mask=[]})                 = 140725235409168
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by xelxebar** [comment]
@xxxserxxx As @yuja points out, it looks like you're using an RSA key. The only salient difference I can see between your setup and mine at this point is that I'm using `ed-25519`.

**Comment by xxxserxxx** [comment]
@xelxebar I think you're right. At least, that's my pet theory: it's the private key itself. If it's true, though, then that indicates a bug in libssl2, right? Or, possibly, libssl2 is technically correct and openssl is wrong (I'm guessing everything else in my toolchain, and on Github, Gitlab, and Sourcehut, uses openssh and openssl).

I'll try a different key; changing it on sr.ht won't be too much of a PITA. However, if this *is* a bug in libssl2 I'm going to have to drop it; I don't program in Rust and feel unqualified to file a coherent ticket. While I keep mentioning libssl2, it's only because of other references made in various tickets about issues with it.

**Comment by yuja** [comment]
> If it's true, though, then that indicates a bug in libssl2, right?

Correction: libssh2

I suspect it's a bug of libgit2 (and/or missing feature of libssh2.)
As I explained in #389, libgit2 (which uses libssh2 under the hood) has some problem in host key exchange. I guess libgit2 would have a similar shortcoming in authentication process.
