### ISSUE TITLE
unclear tutorial regarding closing external editor

### ISSUE THREAD

**Issue by joyously** [martinvonz/jj#1386]
I did `jj help` and it says to read the `tutorial.md`. It wasn't that helpful to me since it assumes that you know Git. 
One thing that is confusing is the following three references to closing an external program. The gist is to modify the line, then close it. Could you make it more clear whether a save needs to happen before closing the program?

https://github.com/martinvonz/jj/blob/e64ca31bfda16d41a4c7d9cd683b3c11d7e5ae80/docs/tutorial.md?plain=1#L43

https://github.com/martinvonz/jj/blob/e64ca31bfda16d41a4c7d9cd683b3c11d7e5ae80/docs/tutorial.md?plain=1#L377

https://github.com/martinvonz/jj/blob/e64ca31bfda16d41a4c7d9cd683b3c11d7e5ae80/docs/tutorial.md?plain=1#L404

Is there somewhere that lists all the commands? When I did `jj help`, it had some, but not all of the commands I've read about in discussions. (One missing is `commit` or is that just an alias? `jj help commit` gave me a little info.)

**Comment by martinvonz** [comment]
> It wasn't that helpful to me since it assumes that you know Git.

Yes, I agree that we need a tutorial for users who come from other VCSs than Git and for users who have no VCS experience at all.

> Could you make it more clear whether a save needs to happen before closing the program?

Done in #1389.

> Is there somewhere that lists all the commands? When I did `jj help`, it had some, but not all of the commands I've read about in discussions. (One missing is `commit` or is that just an alias? `jj help commit` gave me a little info.)

`jj help` lists practically all commands. I've sent #1388 to unhide `commit` and a few more.
