### ISSUE TITLE
Resolving conflicts in remote branches

### ISSUE THREAD

**Issue by xelxebar** [martinvonz/jj#1390]
## Description

This is undoubtedly a PEBKAC issue, but somehow I got my repository into a state where the remote branch is conflicting:

```
$ jj status
...
These remote branches have conflicts:
  master@origin
  Use `jj branch list` to see details. Use `jj git fetch` to resolve.
...

$ jj git fetch
Nothing changed.
```

so `jj git fetch` doesn't resolve this coflict, and moreover `jj log` isn't showing conflicts like I expected:

```
$ jj log
@  xwutvklrrtmn x@wilsonb.com 2023-03-17 03:13:15.000 +09:00 a5874c04b36b
│  (no description set)
o  rzpquunpvyyt x@wilsonb.com 2023-03-17 02:36:07.000 +09:00 master* 1bba389459ca
│  p2.1: Use source test data
o  opzuwxsypkwq x@wilsonb.com 2023-03-16 21:57:32.000 +09:00 master@origin? df4d55a8aba5
│  p2.1: Test readFASTA edge cases
~
```

Instead, the branch names have decorations with which I am unfamiliar. So what is going on here? What is conflicting with what?

**Comment by martinvonz** [comment]
Sorry, I know this bug is really annoying. I think #922 is our canonical bug for it. I think the workaround is to `jj git remote remove origin; jj git import; jj git remote add origin <URL>`  but let me know if that doesn't work.

**Comment by xelxebar** [comment]
That did the trick! Much appreciated, and than you for the pointer to the ongoing discussion.
