### ISSUE TITLE
jj is unable to communicate with Sourcehut using RSA keys

### ISSUE THREAD

**Issue by xxxserxxx** [martinvonz/jj#1419]
This is a "clean" ticket to summarize several other tickets related to jj's SSL library's issues communicating with Sourcehut using RSA keys.

- Ticket #389 discusses issues when the Sourcehut server key is RSA
- This [ticket in libgit2](https://github.com/libgit2/libgit2/issues/6454) was referenced as possibly being a source 
- #928, which I filed, is I believe a duplicate of #389.
- And, finally, #1374 which detail a laborious journey in realizing that RSA keys do not work when the **client** key is RSA, regardless of the server key

I've verified this as best I can by creating new RSA keys, uploading them to sr.ht, and using them to connect (successfully with git, unsuccessfully with jj); and then creating ed25519 keys, uploading those, and using them to connect (successfully with both git and jj). In summary, I've observed:

- jj works with Github and Gitlab with client RSA keys
- jj works with Sourcehut with client ed25519 keys
- jj does not work with Sourcehut with server RSA keys
- jj does not work with Sourcehut with client RSA keys
- git works with Github, Gitlab, and Sourcehut with client RSA and ed25519 keys

I have emailed @ddevault about the issue, and referenced the tickets. I'm able to provide more information, but am unfamiliar with the software underpinning either side; and I believe this is easily reproducible.

**Comment by martinvonz** [comment]
I just approved #1476, which upgrades to a later libgit2 version. That libgit2 version supposedly has a "better SSH host key algorithm negotiation". You may want to try again with a new version of jj built from head.

**Comment by necauqua** [comment]
Fetching/pushing from/to sr.ht works for me now :tada:

**Comment by xxxserxxx** [comment]
Is it sufficient to re-install jj with `cargo install --git https://github.com/martinvonz/jj.git --bin jj jujutsu`, or does `libgit2` in the host OS need upgrading?

**Comment by martinvonz** [comment]
> Is it sufficient to re-install jj with `cargo install --git https://github.com/martinvonz/jj.git --bin jj jujutsu`, or does `libgit2` in the host OS need upgrading?

It's sufficient to run that command. libgit2 should always be statically linked into the `jj` binary IIRC.

**Comment by necauqua** [comment]
Yes, only system dependencies (judging purely by the nix flake) are openssl, dbus and sqlite

**Comment by inv2004** [comment]
```
jj --version
jj 0.8.0-8149ec6df6490ac596f92fdf584d2d666e8c0b6b

jj git clone ... git@git.sr.ht:...
Error: invalid or unknown remote ssh hostkey; class=Ssh (23); code=Certificate (-17)

git clone ... git@git.sr.ht:...
Ok
```

**Comment by martinvonz** [comment]
We've made some improvements in this area recently (e.g. #2016). Can you try [installing from source](https://github.com/martinvonz/jj/blob/main/docs/install-and-setup.md) and see if that helps?

**Comment by xxxserxxx** [comment]
Sorry for the long delayed reply, but as no-one else has yet responded, this appears to be fixed for me. I can both pull and push to sr.ht.
