### ISSUE TITLE
Documentation: Add a Jujutsu Book

### ISSUE THREAD

**Issue by PhilipMetzger** [martinvonz/jj#1430]
Git has the [Git Book][git] and Subversion has the [red Book][red], so it would be appropriate for Jujutsu to have it's own user guide in a book. 

The start of this would be adding a [MDBook][md] with an introduction but longterm it would be similar to the [Git Book][git].

[git]: https://git-scm.com/book/en/v2
[red]: https://svnbook.red-bean.com/index.en.html
[md]: https://rust-lang.github.io/mdBook/index.html

**Comment by martinvonz** [comment]
Sounds good.

By the way, as we get ready to test jj on users at Google, we'll need better documentation, so that will probably result in some documentation PRs (but not a whole book).

**Comment by ilyagr** [comment]
https://github.com/martinvonz/jj/issues/1294 is a related (but different) issue about compiling the docs into the binary. Given a nice website/book, #1294 would be less important, though I think still useful.

**Comment by ilyagr** [comment]
I made a first attempt to turn the existing docs into a website. From my perspective, the main goal is to have separate pages for prerelease docs and stable version docs, and to have everything be generated automatically from the `jj` repo.

Here's what it looks like now: https://ilyagr.github.io/jj/

It's created by MDBook a terrible shell script that will probably become a PR once I clean it up a bit: https://github.com/martinvonz/jj/compare/main...ilyagr:jj:mdbook-back

**Comment by necauqua** [comment]
This is probably far-fetched, but it would be super cool if the examples in codeblocks actually run, so the command output is always up-to-date or is at least tested and fails CI :)
