### ISSUE TITLE
.envrc blows up with "nix: command not found"

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#1433]
## Description

If I install direnv and cd into a jj working dir then its .envrc file triggers all kinds of errors like `nix: command not found`, seemingly because it's set up with the assumption I'm using NixOS and I'm not?

Some of this might be intentional but completely undocumented...

## Steps to Reproduce the Problem

1. Install direnv (https://direnv.net/)
2. Clone jj repo and cd into its directory
3. Run `direnv allow .` like it prompts you to

## Expected Behavior

I'm cd'd into the jj dir without errors.

## Actual Behavior

It spits out some cryptic errors at me:
```
direnv: loading ~/projects/jj/.envrc
direnv: using flake
environment:1270: nix: command not found
```

## Specifications

- Platform: Debian Linux (crostini on Chrome OS)

**Comment by dbarnett** [comment]
FWIW I ran into this because I wanted to hook up a _different_ direnv command (see #1008). I'm trying to figure out if there's a way to silently block this one (to not get warnings every time I cd) _AND_ have my own local untracked .envrc, or what.

Or is nix a thing I can install on Debian and the suggested fix just for everyone who wants to hack on jj to install nix? If so, I'd like some hints in the docs about why and how.

**Comment by necauqua** [comment]
You can install Nix, yes, and I recomend you to :)

Nix ensures a consistent dev env so you work with exact version of rust for example etc

**Comment by dbarnett** [comment]
But still this needs documentation. I'd rather not have to learn that it's recommended to install nix via an error when I try to cd into the jj directory. Making it required-ish also feels burdensome to new contributors. Could it be behind an `if has nix` guard (with a gentle nag to install nix if you insist)?

And FWIW I found my use case for local envrc hooks alongside the repo ones is tracked at https://github.com/direnv/direnv/issues/556 and just isn't supported right now, once there's a .envrc file checked into the repo.

**Comment by necauqua** [comment]
Surely it needs to be documented, I was just answering the question ~~I didn't read the last part~~

**Comment by dbarnett** [comment]
Even after installing nix (I think?) I'm now getting a different warning:
```
direnv: using flake
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```
I have zero idea where to use that `--extra-experimental-features` since I think it's a flag to pass to nix, and I'm not even calling nix directly? Somewhere in .envrc or flake.nix files? Or somewhere else entirely in some other nixrc file on my system?

**Comment by necauqua** [comment]
> Or somewhere else entirely in some other nixrc file on my system?

Yep, and yes it definitely should be documented for non-nix-users
`echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf`

I do think we should recommend contributors to use nix and not make `.envrc` conditional though

**Comment by dbarnett** [comment]
K, the bad news: I have no idea what I'm doing nor exactly why, and none of this gets me any closer to a neat solution to the local direnv hook I'd wanted.

The good news: I seem to have gotten past all the errors to now just a really long unexplained hang when I try to cd 🙃 (after adding two `extra-experimental-features` options I don't understand into a ~/.config/nix/nix.conf file):
```
direnv: loading ~/projects/jj/.envrc
direnv: using flake
copying '/home/dbarnett/projects/jj'direnv: ([/home/dbarnett/.local/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
copying '/home/dbarnett/projects/jj'
```
My computer overall got really really slow, so I'm just going to leave it alone for a while, give it some time to do whatever it's doing and hope that it's actually valuable. Does seem to be eating a looooot of disk space as it goes, though, and still not giving me much feedback about what it's doing and why.

**Comment by dbarnett** [comment]
Nope, now it's disk space errors:
```
...
copying '/home/dbarnett/projects/jj'direnv: ([/home/dbarnett/.local/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
error: writing to file: No space left on device
(use '--show-trace' to show detailed location information)
```
At this point I'm going to take a step back and try to find my way back to an error-free state while I wait for someone to tell me if there's something fixable here. That might mean completely uninstalling direnv for now. I do think even if this nix stuff is valuable, it seems to have quite some overhead and it should be way more opt-in and documented.

**Comment by necauqua** [comment]
The hang should not be _that_ long and its only the first time - it's downloading the specific rust version and whatever, as I've said, next times it's instant.
Not sure about why the computer got slow, it shouldn't compile anything..

Oof there's something weird going on with your system or the nix install, the nix store does take up some space but in case of a fresh install it should basically be (as I've said :smile:) just the specific version of rust and whatever.

For the opt-in part - this issue only applies if you have direnv and no nix (doesn't work for some reason and/or someone is not willing to install/use it), in that case you can remove the `use flake` part from .envrc, and yeah it's a burden to remember to not commit that part

Ultimately it's not for me to decide anyway

**Comment by martinvonz** [comment]
Is there a way to tell direnv that `use flake` should be ignored if nix is not installed? It seems like a warning should be enough. I don't use direnv or nix, so take that with a grain of salt.

**Comment by necauqua** [comment]
Well `.envrc` is just a bash script so we can do something like
```bash
if type -q nix; then
    use flake
fi
```

**Comment by dbarnett** [comment]
direnv has an even simpler built-in for that, `if has nix`. Sent a PR to add that.
