### ISSUE TITLE
Move .envrc to .envrc.recommended?

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#1436]
## Description

Committing a .envrc file directly to the repo root has two downsides: It's awkward to extend with it with your own local hooks, and it's awkward to decline using it without direnv constantly nagging you to activate it. Would it be possible to rename it to .envrc.recommended and let people symlink/source it locally as desired (until direnv supports prompting for that automatically: direnv/direnv#556)? That would've helped me tremendously in #1008 and #1433.

**Comment by Ralith** [comment]
Even when nix is available, the .envrc can be a major impediment if there's some issue with the environment. I agree that arranging it to be opt-in would be an improvement.
