### ISSUE TITLE
Branches at the root commit lead to confusing errors; `jj abandon` can create such a branch

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1529]
To do it, simply add a branch to a child of the root commit and then `jj abandon` the branch.

Branches at the root commit cause confusing errors on `git export` and `git push`.

Since #1479, `jj branch` is not allowed to create such branches. If we decide to resolve this by supporting such branches better, that restriction should be lifted.

**Comment by martinvonz** [comment]
Can we make the error less confusing? I don't see anything inherently bad about having a branch on the root commit.

**Comment by ilyagr** [comment]
That would work too. It'd be a bit of work, since we'd have to figure out how to export such branches (we could ignore them or we could try to put the git repo in the state `git checkout --orphan` puts it in) and figure out when the user needs to be informed that their branch is not representable in git (for example, it cannot be pushed).

**Comment by martinvonz** [comment]
We already skip conflicted branches on exported. Maybe we can treat these branches similarly (but ideally producing a different warning message for the user).
