### ISSUE TITLE
FR: Warn when revision is used without `-r` for `diff` and `split`

### ISSUE THREAD

**Issue by tp-woven** [martinvonz/jj#1538]
Since `diff` and `split` default to `-r @`, it is easy to forget to add `-r` when using them for another revision. When this happens, `jj` treats the argument as a file name that usually doesn't match anything and proceeds to report and empty diff.

Instead, `jj` should show a warning when the pattern doesn't match any actual files, similar to [log](https://github.com/martinvonz/jj/pull/768). Potentially, we could also (or instead) check whether the argument actually matches a revision first.

Related Discord discussion: https://discord.com/channels/968932220549103686/968932220549103689/1098397923819135036

**Comment by tp-woven** [comment]
Thanks, I'll close this as a duplicate of #505 then.

**Comment by ilyagr** [comment]
OK, I'll change the name of that bug then to make it more general.
