### ISSUE TITLE
`jj config edit --user` fails if no existing config

### ISSUE THREAD

**Issue by arxanas** [martinvonz/jj#1571]
## Steps to Reproduce the Problem

1. Create Git-colocated repo.
2. Ensure no user config exists (i.e. not `~/.jjconfig.toml` and not `~/.config/jj/config.toml`).
3. Run `jj config edit --user`.

## Expected Behavior

`jj config edit --user` opens an editor to create one of the possible config files.

## Actual Behavior

Error:

```sh
$ jj config edit --user
Error: No repo config path found to edit
```

## Specifications

- Platform:
- Version:

**Comment by dbarnett** [comment]
Oops, my bad. Still haven't had time to look into it, but sounds pretty low urgency / trivial to work around at least.

I definitely remember making accommodations to create if missing on one of the other configs too, repo I think?
