### ISSUE TITLE
FR: Allow users to see and address git repo refs as `@git` branches

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1666]
This will present the refs tracking the local git repo branches similarly to remote-tracking branches. This would affect:

- [x] Revision parser
- [x] `jj log` via the `branches()` function in the templater
- [x] `jj branch list` output
- [ ] We should figure out what to do with the jj refs tracking the local git repo's remote-tracking branches. E.g., we could refer to them as `@remote@git`. I was previously hoping to remove them entirely, but I now think they are necessary (see comment below).

(might add more to the list above once I think of it)

The `@git` branch should only be shown if it differs from the local branch. The user should see this rarely. Especially in a colocated repository, if `@git` ref does not match the local branch, something weird is going on. For example, the local branch might be conflicted or missing.

I'm not necessarily proposing changing the way `git_refs` are stored in the view option. From the perspective of `git_refs`, we would only display the *local* git branches; this is similar how we currently display tags and have the revision parser understand tags.

### `jj branch forget` should not remove the git remote ref.

This would be easily observed by users, and should be documented.

In spite of the potential confusion, I think this is the best option we have. Otherwise, we'd have two choices I can think of:

- Delete the git branch and git remote-tracking branch on `jj branch forget`. This would be
  the only case jj does something like that outside `jj git export`. We'd also have to decide
  how `jj op restore` can work when restoring past such an operation.

  Also, it's important to note that, currently (with git remote refs preserved), `jj branch forget && jj git export` has exactly this effect without having to do anything exceptional.

- Not touch them as normal. This would mean that the local branch to be immediately recreated on the next `jj git import` if *either* the local branch or a remote-tracking branch for it exists in the git repo.

    The user would have a hard time getting rid of the branch. If they delete it on the git side, it would be recreated by the next `jj git export`.

### `jj undo` will treat it differently, at least in colocated repositories

See #922 and the discussion in #1541

### (might add more to this list once I think of it)

**Update:** I previously mentined a bug report by @arxanas here, but it's not relevant. See https://github.com/martinvonz/jj/pull/1714 for that.

**Comment by ilyagr** [comment]
Update: actually, this plan will not resolve @arxanas's issue. For that to be address, we'd probably need to address accessing remote-tracking branches in the local git repo, which is a step beyond this issue.

**Comment by ilyagr** [comment]
I added the question of what to do with refs tracking the local git repo's remote-tracking branches. E.g., we could refer to them as `@remote@git`. 

I was previously hoping to remove them entirely, but I now think they are necessary in colocated repos. We need them for the same reason as the refs tracking the local git branches: we to differentiate between A) the situation when `jj git fetch` happened and the remote-tracking branches on the jj are more up to date and B) the situation when `git fetch` happened and the remote-tracking branches on the git side are more up to date.

**Comment by yuja** [comment]
> * [ ]  We should figure out what to do with the jj refs tracking the local git repo's remote-tracking branches. E.g., we could refer to them as `@remote@git`.

I think this one is settled, so closing the issue.

We couldn't remove `git_refs`, but users no longer need to care about that.
https://github.com/martinvonz/jj/blob/390b3208da4bf95526fc491b2db06a127c5a3caa/docs/design/tracking-branches.md#importexport-data-flow
