### ISSUE TITLE
Add rebase mode for rebasing whole "current commit tree", and make it the default

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#168]
## Description

Let's say you commit graph looks like this:

```
o abc999 main
| upstream change
| @ abc444
| | working copy
| | o abc333
| |/  new feature
| o abc222
|/   refactor
o abc111
~
```

`jj rebase` currently default `-r @`, meaning that only the working copy will be rebased. So if you run `jj rebase -d main`, then only that commit will be rebased. You can rebase `abc222` and all descendants by running `jj rebase -d main -s abc222` instead. However, you have to manually find the commit ID (or use a revset). It would be nice to be able to say something like `jj rebase -d main -b @` and have that find all commits on the current side branch that need to be rebased. The `-b` is what Mercurial uses for that, but we should see if there's a better name.

We should make this new option the default.

Note that there are trickier cases where the "side branch" has merges from multiple points of upstream:

```
o abc999 main
| upstream change 2
| @ abc555
| | working copy
| o abc444
|/| merge from main
o | abc888
| | upstream change 1
| o abc333
| | new feature
| o abc222
|/   refactor
o abc111
~
```

In the above case, `jj rebase -d main` should rebase `abc222`, `abc333`, `abc444`, `abc555`. The merge commit will then become a single-parent commit.

(The rebased merge commit is also likely to be empty, because it was likely to be empty before the rebase. It should then probably be dropped, but's a separate feature request from this one.)

## Specifications

- Platform: All
- Version: 0.3.3

**Comment by arxanas** [comment]
git-branchless also calls this `-b`/`--base` like Mercurial. I've been trying to start using the technology "commit stack" for this situation (as per the definition at https://github.com/arxanas/git-branchless/wiki/Concepts#commit-stacks). For example, `git sync` rebases all "commit stacks" onto the main branch.

**Comment by martinvonz** [comment]
Thanks, that may be a good term to copy. (I think you meant "terminology" rather than "technology".)

Seems like a good name for `-b/--base` would be `-s/--stack` then? I suppose the problem is that `-s` is already taken by `--source`. Hmm. Maybe there's a better name for `--source`. I do think that's not particularly clear (I've also just copied the name from Mercurial).

**Comment by arxanas** [comment]
Yep, I've (we've) kind of backed ourselves into a corner there 😅 . I was thinking about a `--root` option to indicate what is currently `--source`. The short version `-r` oftentimes means "recursive", which is... not entirely wrong, I guess? Although it might conflict with a term meaning "the root of the entire graph". The other alternatives which come to mind conflict in various ways (`--start`, `--subtree`, `--begin`, ...).

I should note that I haven't really tested to see how intuitive users find the terminology "commit stack" yet, especially considering that the "stack" might be a tree or sub-DAG. It might not be the best term.

One mnemonic I suggested was that `-b` kind of means "branch": https://github.com/arxanas/git-branchless/wiki/Command:-git-move#moving-branches

**Comment by martinvonz** [comment]
> Yet another alternative name for `--source` I considered was `--descendants`, but its short form would conflict with `-d` for destination. Do we now change *that* to `--onto/-o`? :) It would definitely confuse me a bit in the beginning if `-d` started meaning `-s` in hg-speak. But I try to be open to even big changes like that this early in the project.

> One mnemonic I suggested was that `-b` kind of means "branch":

Yes, I think that matches how we sometimes call it a "topological branch" at Google, to distinguish it from a `refs/heads/` branch (or from a "named branch" or "bookmark", rather, since we use Mercurial internally).

> https://github.com/arxanas/git-branchless/wiki/Command:-git-move#moving-branches

Interestingly (though not surprisingly), you described `--source` as being about descendants. I take that as an indication that it's a decent name for it (but, again, there's the issue with `-d` currently being taken).

**Comment by martinvonz** [comment]
I'm going with `-b/--branch` for now. Thinking about how real branches look, I think that word is a good match. jj's and git's current "branches" are more like sticks or leaves (depending on whether you consider ancestors included or not). I don't think I'm going to rename `jj branch` to `jj stick/leaf`, though :)
