### ISSUE TITLE
No 'util' command in Homebrew jj; the documentation is ahead of Homebrew/release version

### ISSUE THREAD

**Issue by GaryBoone** [martinvonz/jj#1711]
For a Homebrew install on Mac Ventura using `$ brew info jj`, the documentation for zsh completions [here](https://github.com/martinvonz/jj#zsh) says to add these lines:

    autoload -U compinit
    compinit
    source <(jj util completion --zsh)

However, there isn't a `util` command in the Homebrew version:

    $ jj util completion
    error: The subcommand 'util' wasn't recognized

    Usage: jj [OPTIONS] <COMMAND>

    For more information try '--help'

The command is present in head. The directions worked correctly when building from source. So this is just a case of the Homebrew version being behind the documentation. Posted in part in case other users are confused before a new Homebrew version is released.

**Comment by martinvonz** [comment]
Sorry, the command was called `jj debug completion` in 0.70. It's mentioned in [the heading above](https://github.com/martinvonz/jj#command-line-completion), but we should probably repeat it for each shell.
