### ISSUE TITLE
Cannot list specific config with parentheses in key

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#1723]
## Description

It doesn't seem possible to list a config value with a parentheses in the key:

```shell
$ jj config list 'template-aliases.format_short_change_id(id)'
Config error: Char
For help, see https://github.com/martinvonz/jj/blob/main/docs/config.md.
```

## Steps to Reproduce the Problem

1. `jj config set --repo 'x.y(z)' value`
1. `jj config list 'x.y(z)'`

## Expected Behavior

```
$ jj config list 'x.y(z)'
x.y(z)="value"
```

## Actual Behavior

```
$ jj config list 'x.y(z)'
Config error: Char
For help, see https://github.com/martinvonz/jj/blob/main/docs/config.md.
```

## Specifications

- Platform: Linux
- Version: 0.7.0-02bb3aecf37203886251233b843c70ddee628df6

**Comment by kevincliao** [comment]
This error is coming from the external config library when trying to read the config https://github.com/martinvonz/jj/blob/5d02a577137bf987748df41da40207eb0bd61c59/src/config.rs#L149
When doing `config.get("x.y(z)")` it returns a PathParse error with nom::error::ErrorKind::Char.

**Comment by kevincliao** [comment]
`jj config set` operation is fine - maybe because it's using a different library (toml_edit). I wonder why jj is using different libraries for reading and writing though.

**Comment by martinvonz** [comment]
> `jj config set` operation is fine - maybe because it's using a different library (toml_edit). I wonder why jj is using different libraries for reading and writing though.

The `config` crate does more than just parsing TOML. It also helps with merging configs from different sources.

**Comment by Dr-Emann** [comment]
It looks like the config crate doesn't consider identifiers containing `(`/`)`:
https://github.com/mehcode/config-rs/blob/f57eadd6ddf6916098303f9ae8f6168fe315909d/src/path/parser.rs#L15-L25

**Comment by Dr-Emann** [comment]
Their readme says:

> Access nested fields using a formatted path — Uses a subset of JSONPath; currently supports the child ( `redis.port` ) and subscript operators ( `databases[0].name` )

If they're trying to match JSONPath, they might not want to accept `x.y(z)`, the way to do that in JSONPath would be `x["y(z)"]` (Using the ability to [index by a quoted member name](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-01.html#section-3.5.4)). However, `config` currently only implements indexing by an integer.

**Comment by martinvonz** [comment]
Maybe we want to do our own parsing of dot-separated keys. However, it seems that `config` doesn't provide an API for getting a value given an already parsed path.
