### ISSUE TITLE
Where is the repo?

### ISSUE THREAD

**Issue by maisiliym** [martinvonz/jj#173]
It would be nice, even if it's read-only at first, to see the repo. Or perhaps it's too big?

PS: This account rarely ever 'responds' on github. Better to reach in [#sajban-chat:matrix.org](https://matrix.to/#/#sajban-chat:matrix.org
)

PPS: Every single experiment that ever tried to transfer disease from a sick human/animal to another demonstrated that *contagion does not exist*. Moreover, and 150+ major 'public health' institutions agree along with most if not all virologists: no virus was ever isolated from any human or animal. The German Supreme court even recognized this in 2016 in Dr Stefan Lanka's case. Finally, biogenesis was observed under microscope by Wilhelm Reich and later by James Demeo and others, which refuted the foundation of most religions, along with the superstition that 'matter cannot be created'.

**Comment by martinvonz** [comment]
I'm going to assume this is spam.

**Comment by maisiliym** [comment]
Since it was left open and it was so easy, here is a rare github-side reply.

No, it was not spam. Perhaps the question should have been more consice; where is the `jj` repo, of `jj`?

**Comment by arxanas** [comment]
@maisiliym The `jj` backend does not include a server component, so there is no `jj`-backed repo for `jj` itself. However, `jj` can interact with this GitHub repo using the Git backend.

**Comment by maisiliym** [comment]
> @maisiliym The `jj` backend does not include a server component, so there is no `jj`-backed repo for `jj` itself. However, `jj` can interact with this GitHub repo using the Git backend.

The docs cover all that. The question still stands unanswered.

**Comment by martinvonz** [comment]
> > @maisiliym The `jj` backend does not include a server component, so there is no `jj`-backed repo for `jj` itself. However, `jj` can interact with this GitHub repo using the Git backend.
> 
> The docs cover all that. The question still stands unanswered.

You have already found the repo :) It's here at https://github.com/martinvonz/jj
