### ISSUE TITLE
Not correctly ignoring a `node_modules` subdirectory

### ISSUE THREAD

**Issue by chriskrycho** [martinvonz/jj#1785]
## Description

In one project I work with, Jujutsu is adding `.gitignored` files to the working copy. Git itself is ignoring them correctly, and `untrack` does not help since Jujutsu (helpfully and cheerfully!) informs me that they will just end up added right back since they are not ignore:

```
Error: 'node_modules/minipass-sized/.gitignore' and 6 other files are not ignored.
Hint: Files that are not ignored will be added back by the next command.
Make sure they're ignored, then try again.
```

…but they *are* ignored; the `.gitignore` file has `node_modules` in it and `git status` does not see these files.

## Steps to Reproduce the Problem

I have not yet managed to make a minimal reproduction of this, though I have tried!

1. Clone https://github.com/chriskrycho/v5.chriskrycho.com. You can do this however you like, including `git clone`, `gh repo clone`, or `jj git clone`.

1. `cd` into the newly cloned repo and run `yarn`. You will need Node and Yarn 3 on your system. (I use [Volta](https://volta.sh) to manage Node tools, if you don't have Node and Yarn already.)

1. Run `jj status`. You should now see:

    ```
		Parent commit: 6cd7a8cee51f latest update from Gathering Storm
		Working copy : 8cee62c1d97e (no description set)
		Working copy changes:
		A node_modules/minipass-sized/.gitignore
		A node_modules/minipass-sized/LICENSE
		A node_modules/minipass-sized/README.md
		A node_modules/minipass-sized/index.js
		A node_modules/minipass-sized/package-lock.json
		A node_modules/minipass-sized/package.json
		A node_modules/minipass-sized/test/basic.js
    ```

    (Note the commit hash; this repo’s dependencies do not change *often*, but they do from time to time, and I have no idea if it is specific to the current revision.)

1. Compare this to the output from `git status`:

		```
		On branch main
		Your branch is up to date with 'origin/main'.

		nothing to commit, working tree clean
		```

## Expected Behavior

`jj status` should report the same thing as `git status`. More specifically, it should respect the fact that `.gitignore` includes `node_modules`, and so *no* item within `node_modules` should be added automatically.

## Actual Behavior

`jj status` is, for reasons extremely unclear to me, not respecting `.gitignore` in this one very specific case! Notably, though, just installing `minipass-sized` in a no-other-dependencies Node package created to see if it is sufficient for a minimal reproduction does *not* reproduce this.

## Specifications

- Platform: macOS Ventura 13.4.1, Apple M1 Max
- Version: 0.7.0

**Comment by martinvonz** [comment]
Thanks for the report. We have [our own `.gitignore` code](https://github.com/martinvonz/jj/blob/main/lib/src/gitignore.rs). I don't have access to a computer right now, and I'd prefer not to install Yarn and Node anyway if I don't have to. What does `node_modules/minipass-sized/.gitignore` contain? I wonder if there are any negative patterns there that we interpret differently from git. If there's also a `node_modules/.gitignore`, could you share the contents of that too?

Also, if you move those files aside, then run `jj status` again, then moved the files back, do they still show up as added?

**Comment by chriskrycho** [comment]
Re: installing Yarn and Node—that is *fair*. 😂

The contents of `minipass-sized`'s `.gitignore` do appear to be the issue; when I rename that file, this problem goes away. The contents of `node_modules/minipass-sized/.gitignore`:

```
# ignore most things, include some others
/*
/.*

!bin/
!lib/
!docs/
!package.json
!package-lock.json
!README.md
!CONTRIBUTING.md
!LICENSE
!CHANGELOG.md
!example/
!scripts/
!tap-snapshots/
!test/
!.travis.yml
!.gitignore
!.gitattributes
!coverage-map.js
!index.js
```

Intuitively, I would expect any `.gitignore` implementation to never bother traversing something excluded at the top level in the first place, which would presumably avoid this issue. 🤔 I imagine there's a reason `jj`’s doesn't, even if that is just “whoops, we missed it”—but I’m curious if there’s a reason not to use [@burntsushi’s `ignore` crate](https://crates.io/crates/ignore) rather than a custom implementation?

**Comment by martinvonz** [comment]
> Re: installing Yarn and Node—that is *fair*. 😂
> 
> The contents of `minipass-sized`'s `.gitignore` do appear to be the issue; when I rename that file, this problem goes away. The contents of `node_modules/minipass-sized/.gitignore`:
> 
> ```
> # ignore most things, include some others
> /*
> /.*
> 
> !bin/
> !lib/
> !docs/
> !package.json
> !package-lock.json
> !README.md
> !CONTRIBUTING.md
> !LICENSE
> !CHANGELOG.md
> !example/
> !scripts/
> !tap-snapshots/
> !test/
> !.travis.yml
> !.gitignore
> !.gitattributes
> !coverage-map.js
> !index.js
> ```
> 
> Intuitively, I would expect any `.gitignore` implementation to never bother traversing something excluded at the top level in the first place, which would presumably avoid this issue. 🤔 I imagine there's a reason `jj`’s doesn't, even if that is just “whoops, we missed it”—

We generally do ignore the whole directory, but only for performance reasons (scanning all of `target/` in a Rust project can be really slow); I don't think I considered this case you ran into when I wrote the code some years ago. We should only visit the directory [if there are already some tracked files in the directory](https://github.com/martinvonz/jj/blob/597a74d51b2b909cb3c2fd14d2b3df338a359c05/lib/src/working_copy.rs#L525). We clearly need to be more careful when we do visit such directories in other to handle your case. It seems better to instead visit only the files that are already tracked, so maybe we can rewrite it to work that way.

> but I’m curious if there’s a reason not to use [@burntsushi’s `ignore` crate](https://crates.io/crates/ignore) rather than a custom implementation?

Thanks for the suggestion. I'll try to remember to look into switching to that.

**Comment by arxanas** [comment]
> We clearly need to be more careful when we do visit such directories in other to handle your case. It seems better to instead visit only the files that are already tracked, so maybe we can rewrite it to work that way.

I happened to touch that logic in https://github.com/martinvonz/jj/pull/1740 so you could try it and see if it was coincidentally fixed.

**Comment by chriskrycho** [comment]
I just checked whether #1740 happens to fix it and it does not.

I also spent a little while looking at how the current `.gitignore` system works, particularly reading through `lib/src/working_copy.rs`, and it looks like switching to `ignore` will mostly involve switching to `GitignoreBuilder` and always supplying a root path for it, rather than *only* supplying lines to the `GitIgnoreFile` representation. Much of the rest of the existing infrastructure should work with only minimal modification.

**Comment by martinvonz** [comment]
Thanks for looking into it. Sounds good to switch to the `ignore` crate. I don't think it will help fix this bug, though.

**Comment by chooglen** [comment]
> We should only visit the directory [if there are already some tracked files in the directory](https://github.com/martinvonz/jj/blob/597a74d51b2b909cb3c2fd14d2b3df338a359c05/lib/src/working_copy.rs#L525). We clearly need to be more careful when we do visit such directories in other to handle your case. It seems better to instead visit only the files that are already tracked, so maybe we can rewrite it to work that way.

Yes, visiting only the tracked files seems like the right step. From https://git-scm.com/docs/gitignore:

```
An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included 
again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".
```

IOW a `.gitignore` under an ignored directory has no effect, so we should just ignore it.
But note that it's important distinguish between `node_modules/` and `node_modules/*`. The latter does not ignore a directory, and the same rule doesn't apply https://lore.kernel.org/git/d748b4bb-6be2-4936-04d0-f0edcf228dfb@gmail.com.
