### ISSUE TITLE
`jj log` tag colors overloaded, confusing

### ISSUE THREAD

**Issue by GaryBoone** [martinvonz/jj#1843]
Repro:
1. I made a branch off main, b1 and made a bunch of commits. 
2. `jj log` now shows three tags: "main", "b1", and "HEAD@git".
3. I can `jj co` to "main" and "b1", but not "HEAD@git". 

Expected:
I should be able to `jj co HEAD@git`, given that it looks like a tag like the others.

Comment from @aseipp:
It's telling you that particular commit is currently the HEAD in the underlying, colocated git repository. Frankly I think just coloring it differently than a branch name would help a lot. Because it doesn't really work the same way; the @ syntax is typically used to disambiguate which remote you're referring to, i.e. main is a branch, or main@upstream for the main branch on the upstream remote. So there's two ways it's confusing! It re-uses syntax that means something else, and it's colored like a thing that it isn't.

**Comment by necauqua** [comment]
Reiterating my point from discord here to be slightly more permanent:

I would argue that `HEAD@git` should resolve to the commit that it points to in the revset language, making `jj co` and the others just work - this would be my intuition as well here, I was surprised it doesn't work like that already.

Since we're doubling down on reusing the remote syntax, which to me does make sense (the `git` being a pseudo-remote that refers to the colocated git repo), we could also support it in revsets.

**Comment by thoughtpolice** [comment]
5c82100ef0dd1c7c39ea6df7398f693c53bd461e will now highlight the `HEAD@git` ref in a different color to *hopefully* help indicate that it's not a typical branch object. But it looks like the consensus is the `HEAD@git` syntax should still work as a revset value, too.

**Comment by joyously** [comment]
For those 7% that are red-green color blind, how does this look?

**Comment by thoughtpolice** [comment]
> For those 7% that are red-green color blind, how does this look?

That's actually something I was thinking about more generally: I don't know what colorblind terminal users will see, but I wasn't sure how to approach it. I think most terminal UXs are pretty bad about this, but there's no reason we can't do (much) better.

IIRC, one thing Phabricator did that I think a lot of colorblind users liked was both color config, but there was also a "Higher contrast" mode you could enable that was a single toggle with good defaults. I wonder if we could have something like that, too.

**Comment by necauqua** [comment]
> For those 7% that are red-green color blind, how does this look?

I mean it's not like colors reveal any new information that would otherwise be unaccessible to those who can't see them, so in this particular instance it's a non-issue.

And if your vision is not completely grayscale you can always configure all the colors to your liking, here jj does a good job.

**Comment by ilyagr** [comment]
> And if your vision is not completely grayscale you can always configure all the colors to your liking

I don't know how many color-blind people are using this, but most terminals allow you to configure the standard 16-color palette jj uses however you like (see e.g. https://terminal.sexy/ for a bunch of themes). That's one nice aspect of using 16 colors as opposed to 256 or more.

> maybe also having a single toggle to up the contrast would be great.

The way jj functions, this would have to be adjusted in the terminal settings.

----------

Also, our tests mostly don't show colors, so we have at least some way to see if essential information is only communicated through color.
