### ISSUE TITLE
FR: Allow using external diff engines

### ISSUE THREAD

**Issue by ocharles** [martinvonz/jj#1886]
**Is your feature request related to a problem? Please describe.**
Coming from Git, I usually use https://github.com/wilfred/difftastic as my diff engine. I miss it when I use `jj diff`!

**Describe the solution you'd like**
I would be happy with a config option that lets me specify an external diff engine (which I would configure to be `difft`).

**Describe alternatives you've considered**
I'm not sure I can think of any alternatives.

**Additional context**
When using Git, I do occasionally want to turn Difftastic _off_, which I can do with `--no-ext-diff`. I would probably want a similar CLI flag for the rare times where I want a simpler diff. Alternatively, maybe `--git` would be fine here.

**Comment by martinvonz** [comment]
Makes sense. The few different diff formats we currently support are defined [here](https://github.com/martinvonz/jj/blob/4da8483228160fcc090b7e601891af54ccac1a39/src/diff_util.rs#L60C10-L65). We could add an `External(String)` variant where the string identifies the tool to use. The tool could probably be configured similar to [diff editors](https://github.com/martinvonz/jj/blob/main/docs/config.md#editing-diffs). Patches would be very much appreciated, if you can find time for it.

**Comment by yuja** [comment]
Related: #1285

**Comment by necauqua** [comment]
I use delta, and for me having an alias like
`'d' = ['diff', '--git', '--config-toml=ui.pager=["delta","--line-numbers","--navigate"]']`
(stolen from someone from discord) was enough

This is just a hack which may work for you if difftastic can read git diffs from stdin, haven't heard about it though (although now I looked into it and it's amazing)

**Comment by martinvonz** [comment]
Difftastic needs the full input files because it does language-specific parsing (and diffing?). I have actually considered using difftastic to do our diffs. It would be really nice to do language-specific merging too.

**Comment by poucet** [comment]
Wow, @necauqua thanks for mentioning delta. That's an amazing difftool.
