### ISSUE TITLE
`jj split` always includes new files

### ISSUE THREAD

**Issue by chriskrycho** [martinvonz/jj#1916]
## Description

When adding a new file, I cannot get `jj split` to *not* include a newly-added file, regardless of whether it is included in the "diff".

## Steps to Reproduce the Problem

1. `echo "a" > a.txt`
1. `jj commit -m "add a"`
1. `echo "b" >> a.txt && echo "b" > b.txt`
1. `jj split`
1. Only include `a.txt` in the first commit (and include all of it).

## Expected Behavior

`b.txt` should not be present in the first commit, so this should now show the commit message editor for the first commit.

## Actual Behavior

`b.txt` *is* present in the first commit, so the result is "Nothing changed".

[![asciicast](https://asciinema.org/a/pkbjWsfABQgrwOavgnFpJsgfx.svg?theme=none&rows=30)](https://asciinema.org/a/pkbjWsfABQgrwOavgnFpJsgfx?theme=none&rows=30)

## Specifications

- Platform: macOS 13.4.1 (c)
- Version: 0.8.0

**Comment by martinvonz** [comment]
I think this is https://github.com/arxanas/git-branchless/issues/995.

**Comment by chriskrycho** [comment]
Ah, I see. Because of the way the flow works, you have to be able to *delete* the file. (Kaleidoscope also struggled with this, but Meld seems to handle it fine.) Feels adjacent to #1905. Closing as *not* a `jj` issue *exactly*, but hopefully the existence of the issue here will help other folks.

**Comment by ilyagr** [comment]
Workaround by @martinvonz from https://discord.com/channels/968932220549103686/969829516539228222/1135299839706529852:

> You can work around it by passing the paths you want in the first commit to the command
