### ISSUE TITLE
docs/config.md specifies difftool 

### ISSUE THREAD

**Issue by enckse** [martinvonz/jj#1939]
## Description

 
Looking at the `docs/config.md` the section about using `--config-toml` calls out override "ui.difftool" which is otherwise unreferenced by the rest of jj it seems.

I wasn't sure if the "ui.difftool" was used by a library and just isn't defined by `jj` or if it was supposed to be "ui.diff-editor". If the former, likely it should be specified what the setting impacts and if the latter - it should likely be renamed to whatever the intended value was supposed to be.

Specific line in question:
```
jj --config-toml='ui.color="always"' --config-toml='ui.difftool="kdiff3"' split
```

**Comment by arxanas** [comment]
Thanks, this should be `ui.diff-editor` everywhere, @enckse want to open a PR? 😀
