### ISSUE TITLE
FR: add fsmonitor docs

### ISSUE THREAD

**Issue by arxanas** [martinvonz/jj#1940]
There should probably be a document under https://github.com/martinvonz/jj/tree/main/docs explaining how to install, configure, and troubleshoot a filesystem monitor. See https://github.com/martinvonz/jj/issues/1841#issuecomment-1657464287, https://github.com/martinvonz/jj/issues/1841#issuecomment-1657562017, https://github.com/martinvonz/jj/issues/1841#issuecomment-1657590471 for some relevant items.

**Comment by martinvonz** [comment]
It's now enabled by default, and we have docs describing the other setup, so I think we can close this. We might need to remind packagers to enable the feature. I don't know how good they generally are at noticing what default features change in Rust projects.
