### ISSUE TITLE
FR: Display output from remotes

### ISSUE THREAD

**Issue by spiffytech** [martinvonz/jj#1967]
**Is your feature request related to a problem? Please describe.**
`jj git push` doesn't display output from remotes. This results in a misleading error if the remote has hooks which reject the push: `Error: Remote rejected the update of some refs (do you have permission to push to ["refs/heads/main"]?)`

It also makes it appear as if `jj` has hung if the remote is slow (e.g., Dokku building a container).

**Describe the solution you'd like**
`jj git push` would display the text returned by the remote, streaming as it comes in.

**Describe alternatives you've considered**
Use `git push` directly until this is implemented.

**Additional context**
[Discord discussion](https://discord.com/channels/968932220549103686/969829516539228222/1136659637274423377)

**Comment by martinvonz** [comment]
This is probably not very hard to implement, if someone is interested in attempting it. We'd presumably want to add a callback to https://github.com/martinvonz/jj/blob/edc34f06162be142e629ff332ce86e52359a679d/lib/src/git.rs#L840C1-L848. I'm not sure how to deal with interleaved messages and progress updates.

**Comment by arxanas** [comment]
For what it's worth, git-branchless renders output from subprocesses in gray, and the lines always appear above the progress indicator. Forwarded output is always line-buffered. Assuming that the progress indicator line is updated by using `\r` then you might get this behavior for free by simply writing a line of text with a newline (in a manner synchronized with progress indicator output) and then the next progress indicator line will appear on the next line as normal. (Actually, I'm not sure if, after printing `\r`, you still have to clear the rest of the line to ensure that there aren't stray characters left from a previous progress indicator.)
