### ISSUE TITLE
BUG: jj checkout and HEAD@git out of sync

### ISSUE THREAD

**Issue by shavitmichael** [martinvonz/jj#2011]
jj can enter a state where its currently checked out commit get's out of sync with the git HEAD in a colocated repository. This looks similar to #1495 but doesn't seem to involve unborn branches (AFAICT).

My jj log looks like:
```
❯ jj log
@  zmvmkzxk mshavit@google.com 2023-08-09 00:30:18.000 +08:00 393d6c13
│  (empty) (no description set)
◉  xxttkkus mshavit@google.com 2023-08-04 02:11:47.000 +08:00 HEAD@git c09cbd8e
│  iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
◉  xqmpkklm mshavit@google.com 2023-08-04 02:11:46.000 +08:00 2279e212
│  iommu/arm-smmu-v3: Free pasid domains on iommu release
```
and git status
```
❯ git checkout HEAD~1
Previous HEAD position was c09cbd8ed86ef iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
HEAD is now at 2279e21297f5c iommu/arm-smmu-v3: Free pasid domains on iommu release
```

This looks ok at a glance, but updating the currently checked out commit in either jj or git is broken

Checking out a commit in git should be reflected in jj with an updated HEAD@git label, and a new checked-out commit `@`. Neither of those get updated however.
```
❯ git checkout HEAD~1
Previous HEAD position was c09cbd8ed86ef iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
HEAD is now at 2279e21297f5c iommu/arm-smmu-v3: Free pasid domains on iommu release
❯ jj log
@  npytpmkq mshavit@google.com 2023-08-09 00:40:15.000 +08:00 10f210ed
│  (no description set)
◉  xxttkkus mshavit@google.com 2023-08-04 02:11:47.000 +08:00 HEAD@git c09cbd8e
│  iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
◉  xqmpkklm mshavit@google.com 2023-08-04 02:11:46.000 +08:00 2279e212
│  iommu/arm-smmu-v3: Free pasid domains on iommu release
```

Similarly, updating the checked out commit in jj should be reflected on the git side; but git is instead still checked out at the previous commit and thus sees changes in jj's checked out commit as diffs.
```
// Undo previous git checkout for a cleaner experiment
❯ git checkout c09cbd8ed86ef
Previous HEAD position was 2279e21297f5c iommu/arm-smmu-v3: Free pasid domains on iommu release
HEAD is now at c09cbd8ed86ef iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
❯  jj co xqmpkklm
❯ jj log
@  wvnrupnq mshavit@google.com 2023-08-09 00:42:05.000 +08:00 18804d9c
│  (empty) (no description set)
│ ◉  xxttkkus mshavit@google.com 2023-08-04 02:11:47.000 +08:00 HEAD@git c09cbd8e
├─╯  iommu/arm-smmu-v3: Cleanup arm_smmu_domain_finalise
◉  xqmpkklm mshavit@google.com 2023-08-04 02:11:46.000 +08:00 2279e212
│  iommu/arm-smmu-v3: Free pasid domains on iommu release
❯ git status
HEAD detached at c09cbd8ed86ef
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c
```

I haven't yet figured out how I got into this state, let alone reproduction steps. Let me know if you have any suggestions on how I could investigate further.

**Comment by martinvonz** [comment]
Thanks for the report.

Maybe you can get some hints from running `jj op log`. You should see some operations saying "import git refs". You can also try `jj debug operation <operation id>` for various operations there and see where the `git_head` and `wc_commit_ids` point. Let us know what you find.

**Comment by ilyagr** [comment]
Also, what version of `jj` are you using? Is it 0.8? Newer unreleased version? `jj version` should tell you the exact commit.

**Comment by shavitmichael** [comment]
> Also, what version of `jj` are you using? Is it 0.8? Newer unreleased version? `jj version` should tell you the exact commit.

Running on `jj 0.8.0-b6c65c12aca94c0574b629424931ea7f772babed`

> Maybe you can get some hints from running `jj op log`. You should see some operations saying "import git refs". You can also try `jj debug operation <operation id>` for various operations there and see where the `git_head` and `wc_commit_ids` point. Let us know what you find.

**1. Git->jj direction**

Ok, trying out the `git checkout HEAD~1` test, and the first possibly unexpected observation is that `jj log` does not result in an "import git refs" operation:
```
@  553776c13193 mshavit@google.com 15 seconds ago, lasted 1 second
│  snapshot working copy
│  args: jj log
```
The same operation on a fresh checkout of the repo (also collocated) has a different behavior
```
@  3c0a985116c0 mshavit@google.com 7 seconds ago, lasted 2 seconds                                          │ git branch <new-branch-name> 149ba7d0c399
│  import git refs                                                                                                           │
│  args: jj log  
```
Perhaps expected then, the git_head isn't updated, and the wc points to an (empty) wc child of the stale git_head
```
    git_head: RefTarget {
        conflict: Conflict {
            removes: [],
            adds: [
                Some(
                    CommitId(
                        "c09cbd8ed86ef376fba5ee842a9d1925eaff6644",
                    ),
                ),
            ],
        },
    },
    wc_commit_ids: {
        WorkspaceId(
            "default",
        ): CommitId(
            "bf24c5c944fe0b3a20f60c12009fcfe1d2832718",
        ),
    },
```

Explicitly calling `jj git import` correctly updates the git_head in jj to reflect the one in git, but  wc_commit_ids isn't updated.

**2. jj->Git**

Running `jj co @--` doesn't update the git_head:
```
❯ jj op log

@  07ae677156ae mshavit@google.com 8 seconds ago, lasted 1 second
│  check out commit 2279e21297f5c8540810288a2d3023c2b7ff5b94
│  args: jj co @--

❯ jj debug operation @

    git_head: RefTarget {
        conflict: Conflict {
            removes: [],
            adds: [
                Some(
                    CommitId(
                        "c09cbd8ed86ef376fba5ee842a9d1925eaff6644",
                    ),
                ),
            ],
        },
    },
````
In this direction, jj git export has no effect.
```
❯ jj git export
Nothing changed.
```

Meanwhile, the same operation on the fresh checkout does update the git_head.
```
@  c639e2dba547 mshavit@google.com 21 seconds ago, lasted 1 second
│  check out commit d92b86f672a42d9d74a24a63a1e59793c4116830
│  args: jj co @--

    git_head: RefTarget {
        conflict: Conflict {
            removes: [],
            adds: [
                Some(
                    CommitId(
                        "d92b86f672a42d9d74a24a63a1e59793c4116830",
                    ),
                ),
            ],
        },
    },
```

**Comment by yuja** [comment]
> I did early on also create a non-collocated jj workspace backed by the same repo; could that have confused the collocated one?

The check for "colocated" repo is implemented as follows. I'm not pretty sure, but if Git's worktree is involved, weird thing might occur.
https://github.com/martinvonz/jj/blob/b6c65c12aca94c0574b629424931ea7f772babed/src/cli_util.rs#L695-L700
(note: `workspace_root()` is canonicalized)

**Comment by shavitmichael** [comment]
(Can confirm that forcing ` working_copy_shared_with_git = true` resolved all the issues from the original comment.)

**Comment by shavitmichael** [comment]
That was quick; tried out your fix and it worked :). Thanks Yuya!
