### ISSUE TITLE
BUG: "no match for id" panic when initializing repo with a bad object

### ISSUE THREAD

**Issue by jvns** [martinvonz/jj#2022]
## Description

When I run `jj init` in a github repo, I get this panic:

```
$ jj init --git-repo=.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ObjectNotFound { object_type: "commit", hash: "a430c04e28fbc783f99abbc701aaef35dd103803", source: Error { code: -3, klass: 9, message: "object not found - no match for id (a430c04e28fbc783f99abbc701aaef35dd103803)" } }', lib/src/git.rs:199:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## Steps to Reproduce the Problem

I think this is happening because my repo has a bad object in it for some reason:

```
$ git show a430c04e28fbc783f99abbc701aaef35dd103803
fatal: bad object a430c04e28fbc783f99abbc701aaef35dd103803
```

I don't know how to create a git repo with a "bad object" but I expect that `jj init` might fail on another such repo.

## Expected Behavior

I've been using this git repo with no problems for years (I had no idea it had a bad object in it) and it would be nice to be able to use `jj` on it, though I don't know what the implications of that are -- maybe it's too dangerous.

An error message instead of a panic would definitely be an improvement.

## Specifications

- Platform: Mac OS
- Version: `jj 0.8.0-e7e49527efdfddf3eb29ce21e79b056c71c873d6`

**Comment by arxanas** [comment]
The error message could certainly be improved. Is your repo a shallow or partial clone? In those cases, there may be objects referenced by the repository that have not actually been downloaded yet.

**Comment by jvns** [comment]
Ah yeah -- it looks like my repo is a shallow clone.

**Comment by arxanas** [comment]
I opened https://github.com/martinvonz/jj/pull/2024 for the error message. However, we rely on libgit2 for all Git-backend-related stuff, and they only recently added shallow clone support in https://github.com/libgit2/libgit2/releases/tag/v1.7.0. The Rust `git2` crate doesn't have them yet, and, after that, we would have to make sure that jj supported shallow clones properly, so it would probably take a while to get support.

**Comment by martinvonz** [comment]
We may even decide not to support shallow clones. I think [partial clones](https://git-scm.com/docs/partial-clone) is a much better design and should cover the same uses (and more).
