### ISSUE TITLE
Not waiting for editor

### ISSUE THREAD

**Issue by reagle** [martinvonz/jj#2029]
## Description

Hi, I'm new to this and am trying to describe my first init. I've configured Sublime Text for wait, but `jj described` open a file and immediately returns "Nothing changed".

```
user.name = "Joseph Reagle"
user.email = "joseph.aaaa@reagle.org"
editor = ["subl", "-w"]
```

**Comment by ilyagr** [comment]
I think it should be `ui.editor`. I'm guessing it's using whatever is in the `$EDITOR` environment variable for the editor.

**Comment by martinvonz** [comment]
> I think it should be `ui.editor`.

Good catch.

> I'm guessing it's using whatever is in the `$EDITOR` environment variable for the editor.

Incidentally, I just changed the default from `pico` to `Notepad` on Windows in #2028. @reagle, the error message should have included a mention of `pico`. Did it not or did you just not notice it?

**Comment by reagle** [comment]
I changed the toml key, but sublime still opens without wait.

```
❯ env | g -E "editor|visual"
EDITOR=/opt/homebrew/bin/micro
VISUAL=/opt/homebrew/bin/subl
❯ cat .jjconfig.toml
user.name = "Joseph Reagle"
user.email = "joseph.2011@reagle.org"
ui.editor = ["subl", "-w"]
```

**Comment by martinvonz** [comment]
@reagle, does `subl -w .jjconfig.toml` wait? (You can of course try with any other file. That's just a file I know you have.)

**Comment by reagle** [comment]
Yes, `subl -w foo` otherwise works. I just tried `git ci` in the terminal and note it has the same problem -- I never use git on the command line though, I use the GitSavvy plugin in Sublime Text.

**Comment by ilyagr** [comment]
I'm not sure what's going on, but another thing you can try is adding the full path:

    ui.editor = ["/opt/homebrew/bin/subl", "-w"]

**Comment by reagle** [comment]
I fixed the jj issue by moving `.jjconfig.toml` to `~/` from the project folder. If I wanted a repo specific config, it looks like I should've used `.jj/repo/config.toml`. And had I use `jj config set --user user.name foo` it looks like it would've put it in my home folder in the first place. Thanks for the help.
