### ISSUE TITLE
windows: Failed to spawn pager (...): program not found

### ISSUE THREAD

**Issue by akavel** [martinvonz/jj#2040]
## Description

During my first attempts at using `jj` on Windows, I'm welcomed with an error message that jj failed to spawn pager. I'm not sure to what extent that would make it annoying for me to work with jj further, or how to resolve this. I'd love if this error either would not need to show up, or at least some workaround/solution was mentioned in the Readme in a section about installing/using on Windows. I don't seem to be able to find guidance in the docs about config.toml, nor in the FAQ.

## Steps to Reproduce the Problem

1. Install jj for Windows by downloading and unpacking from the release URL: https://github.com/martinvonz/jj/releases/download/v0.8.0/jj-v0.8.0-x86_64-pc-windows-msvc.zip, then putting it in PATH.
1. Configure `user.name` and `user.email` in jj's config.toml.
1. `jj init --git tmpj`
1. `cd tmpj`
1. `jj`

## Expected Behavior

No error messages related to pager.

## Actual Behavior

An error message related to pager is displayed. I don't know how to resolve this on Windows - is there any compatible version of "less" for Windows that I should install into my PATH? Or what?

```
C:\prog\tmpj>jj

Hint: Use `jj -h` for a list of available commands.
Set the config `ui.default-command = "log"` to disable this message.
Failed to spawn pager 'LESSCHARSET=utf-8 less -FRX': program not found
@  wzmysutluulr czapkofan@gmail.com 2023-08-11 13:20:33.000 +02:00 d919aea51ed2
│  (empty) (no description set)
◉  zzzzzzzzzzzz 1970-01-01 00:00:00.000 +00:00 000000000000
   (empty) (no description set)
```

## Specifications

- Platform: Windows 10
- Version: 0.8.0

**Comment by 0xdeafbeef** [comment]
Windows has `more`

**Comment by martinvonz** [comment]
Ah, `more` is installed by default? We should probably default to that on Windows then.

Once #2035 has been merged, you will also be able to easily turn off paging.

Finally, we could decide to run an in-process [streampager](https://github.com/markbt/streampager) by default, so we don't rely on an external binary.

**Comment by akavel** [comment]
Ah, totally forgot about `more`. That said:

- it's fairly crappy on Windows (compared to `less`), notably it doesn't allow scrolling back, only forward;
- it seems like it kinda doesn't work anyway - maybe it's a `cmd.exe` builtin? see the transcript below (notably I got *something* with `cmd /c more`, but the unicode gets garbled then):

```
C:\prog\upj>set pager=more

C:\prog\upj>jj
Hint: Use `jj -h` for a list of available commands.
Set the config `ui.default-command = "log"` to disable this message.
Failed to spawn pager 'more': program not found
@  puqnzypusqsx (no email configured) 2023-08-11 13:11:29.000 +02:00 425c42a1b0ab
│  (empty) (no description set)
◉  rtlkxvplozyy git@ghislain-rodrigues.fr 2021-04-27 09:22:47.000 +02:00 master 840f23c21d3e
│  keys: Implement unix-word-rubout (Ctrl-W)
~

C:\prog\upj>set pager=more.exe

C:\prog\upj>jj
Hint: Use `jj -h` for a list of available commands.
Set the config `ui.default-command = "log"` to disable this message.
Failed to spawn pager 'more.exe': program not found
@  puqnzypusqsx (no email configured) 2023-08-11 13:11:29.000 +02:00 425c42a1b0ab
│  (empty) (no description set)
◉  rtlkxvplozyy git@ghislain-rodrigues.fr 2021-04-27 09:22:47.000 +02:00 master 840f23c21d3e
│  keys: Implement unix-word-rubout (Ctrl-W)
~

C:\prog\upj>echo foo | more.exe
'more.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\prog\upj>set pager=cmd /c more

C:\prog\upj>jj
Hint: Use `jj -h` for a list of available commands.
Set the config `ui.default-command = "log"` to disable this message.
@  puqnzypusqsx (no email configured) 2023-08-11 13:11:29.000 +02:00 425c42a1b0ab
Ôöé  (empty) (no description set)
Ôùë  rtlkxvplozyy git@ghislain-rodrigues.fr 2021-04-27 09:22:47.000 +02:00 master 840f23c21d3e
Ôöé  keys: Implement unix-word-rubout (Ctrl-W)
~
```

**Comment by martinvonz** [comment]
> * it's fairly crappy on Windows (compared to `less`), notably it doesn't allow scrolling back, only forward;

I'm starting to lean strongly towards defaulting to streampager. We'd probably do that on all platforms in that case, for consistency, and because it solves some issues with people's different configurations of `less`.

> * haven't tested with actual multi-page data, not sure how to achieve it

`jj log -r 'all()'`, for example. See https://github.com/martinvonz/jj/blob/main/docs/revsets.md for what else you can do with revset.

**Comment by thoughtpolice** [comment]
Martin created #2040 to turn off paging by default in `v0.9.0`, but as of #3024 there's now a built-in pager based on `minus`, and it's enabled by default on Windows, shipping in `v0.15.0` in a few weeks. It isn't yet as good as `less -FRX`, but at least it's not busted OOTB, and unlike the existing solution with no pager, you don't have to use `--reversed` to get immediately usable log output.

I think this can be marked as closed; feel free to reopen or open a new bug if you have something else you find, though!

**Comment by Zoybean** [comment]
Just thought I'd note that in order to get Windows' `more` working as the pager, I had to call it with the extension, `more.com`
