### ISSUE TITLE
`jj config set --user` complains if not in jj repo

### ISSUE THREAD

**Issue by emilykfox** [martinvonz/jj#2054]
## Description

When I try to set my user name with `jj config` outside of a jj repo, I get an error. (I also cannot find in the docs the right location to manually write user's config toml file, but I succeeded on another computer, so maybe I'm just missing something.)

## Steps to Reproduce the Problem

1. `cd` to somewhere outside of a jj repo.
2. Run `jj config set --user user.name "NAME"`.

## Expected Behavior

I successfully set my username.

## Actual Behavior

My terminal reports `Error: There is no jj repo in "."`. Based on the warnings I get while cloning a git repo, my user name was not set. I can successfully set my --user level user name when in a jj repo.

## Specifications

- Platform: MacOS Version 14.0 Beta (23A5312d) running fish, version 3.6.1
- Version: jj 0.8.0-28633bb754348bd183654f9e65f9ccb68ad25e1c

**Comment by martinvonz** [comment]
Ah, right, I've run into that myself. Sorry I haven't fixed it yet, especially before I suggested we update the documentation to use the command. Looks like @qfel is going to look into it. Thanks!

**Comment by emilykfox** [comment]
Looks good. Thank you!
