### ISSUE TITLE
FR: Templating function to change timestamps to UTC timezone

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2080]
As suggested by @prestonvanloon [on Discord](https://discord.com/channels/968932220549103686/969829516539228222/1139656538961739776) and, it would be nice to be able to show timezones in UTC. @yuja suggested a method `.utc()` for the templating [`Timestamp` type](https://github.com/martinvonz/jj/blob/main/docs/templates.md#timestamp-type) that changes a timestamp's zone to UTC.

@prestonvanloon, I'll try to assign the bug to you or you can assign it to yourself. This doesn't come with any pressure or time-commitment, and feel free to unassign yourself whenever you feel like it.

**Comment by prestonvanloon** [comment]
thanks @ilyagr. Please assign to me :)
