### ISSUE TITLE
Make Git backend support empty name/email, let UI use separate placeholders

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2094]
This originally came up [here](https://github.com/martinvonz/jj/pull/2091#discussion_r1296093775). Copying my comment from there:

Actually, it's probably better to move those strings into the UI layer as just rendering artifacts. I'm thinking we should go back to using empty strings in [the model](https://github.com/martinvonz/jj/blob/2d81cf91560ce891d3150e90227442d6dbdf449e/lib/src/backend.rs#L140-L141) and then deal with Git not accepting empty strings in the Git backend, perhaps by setting some other placeholder there. Since that placeholder only shows up when using git (and other Git-adjacent tools) to interact with the repo, I think it's less important that it's user-friendly. Using e.g. "JJ_EMPTY_STRING_PLACEHOLDER" or something seems good enough to me. What do you think?

**Comment by ilyagr** [comment]
I'm not sure whether this is important, but should the backend then be able to inform the CLI that "yeah, I stored this commit, but tell the user I would rather not push it in this state"?

**Comment by martinvonz** [comment]
> I'm not sure whether this is important, but should the backend then be able to inform the CLI that "yeah, I stored this commit, but tell the user I would rather not push it in this state"?

I was thinking that the backend would convert the placeholder(s) to empty strings when reading the commit object, so the CLI would see an empty name and email. The CLI would then reject pushing that. Does that clarify?

**Comment by ilyagr** [comment]
I think so, that would make sense.

Now I'm confused by the title of the issue. Did you mean "move the strings **out of** the Git backend"? That would make more sense to me considering the rest of what you said.

**Comment by martinvonz** [comment]
> Now I'm confused by the title of the issue.

That's very understandable :) I think I meant that we should move the logic for putting placeholders in the git commit into the git backend. I'll think of a better title and update it.

**Comment by ilyagr** [comment]
Yeah, this plan sounds great to me then.

**Comment by emilykfox** [comment]
I'm interested in working on this, but I may suddenly become busy with the upcoming semester.

**Comment by martinvonz** [comment]
No problem if that happens. It's been the way it is for years; I don't consider it urgent to fix.
