### ISSUE TITLE
FR: alias `@_` to `@-`

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#2099]
```toml
[revset-aliases]
    '@_' = '@-'
```

I've been fat fingering `@_` (by holding `<shift>` too long) and found this alias to be very practical, thoughts?

**Comment by martinvonz** [comment]
I *have* had that problem, but I still agree that it's easy enough to add that alias for those of us who make the typo.

**Comment by avamsi** [comment]
Makes sense, closing for now.
