### ISSUE TITLE
Add better support for git-like (ref-based) branches

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#21]
We'll want to have better support for git-like branches *at least* for interop with git. I've been thinking a lot about branching recently and I plan to add native support for git-like branches to jj. By "native support", I mean that they can be used regardless of backend.

**Comment by martinvonz** [comment]
By the way, we may *also* want some kind of "persistent" branches (stored in the commit metadata) like hg's branches or topics.

**Comment by martinvonz** [comment]
I think this is now done. `jj git clone/fetch` will now give you native branches for each git branch. You can list branches with `jj branches` and update them with `jj branch`. You can update to a branch with `jj co <name>` or `jj co <name@remote>`.

**Comment by martinvonz** [comment]
I should say that the branches don't currently get automatically updated. For now their largest benefit is that they let us hide `git_refs()` and similar from the CLI.

I'm not sure how I want the "current" branch to be handled, if there should even be such a thing. I want the branches to be updated when a commit they point to get rewritten, however. I also plan to make it so that when a branch gets updated to point to a new commit, all descendants will be automatically rebased (and any branches pointing to them will get updated).

I also plan to make `jj git push` use the new information about local and remote branches to implement something like git's `push --force-with-lease`. That means that if you pull from a git remote, update the branch locally, and then push it back to the remote, you won't need a `--force` flag as long as the branch has not moved on the remote in the meantime (and if it has, you'll need to fetch and resolve the conflict locally).

**Comment by amiryal** [comment]
@martinvonz, hi!

Is this “new” information about local and remote branches already being used in the latest implementation of `jj git push`? I.e. does it already make sure not to unintentionally discard remote git commits?

**Comment by martinvonz** [comment]
> @martinvonz, hi!
> 
> Is this “new” information about local and remote branches already being used in the latest implementation of `jj git push`? I.e. does it already make sure not to unintentionally discard remote git commits?

Hi. Yes, the branches inform how we push to Git. If you have moved a branch straight forward compared to where it was on the remote, we will not do a force push. If you have moved the branch sideways or backwards, however, we will do a force push. We should do a force-with-lease push, but support for that was added quite recently to libgit2 and we just haven't gotten around to it (and it will force me to upgrade all of Google to use the new libgit2 version, which makes me not want to personally add the feature :) ).
