### ISSUE TITLE
`jj git fetch` taking a long time, then reporting "remote rejected authentication" even though `git fetch` works fine.

### ISSUE THREAD

**Issue by Resonious** [martinvonz/jj#2105]
## Description

This is kind of weird, but I recently switched my window manager from GNOME to Sway. Since the switch, I can't use `jj git fetch` anymore. It worked fine before. Regular `git fetch` works fine. `jj git fetch` hangs for awhile then says the remote rejected auth.

Since regular `git` commands work, I can just use those with little issue, so this is no big deal, but I'm curious as to what happened here.

## Steps to Reproduce the Problem

1. `jj git fetch`

(`jj git push` also exhibits the same behavior)

## Expected Behavior

It fetches updates from the remote.

## Actual Behavior

```
Error: remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
Hint: Jujutsu uses libssh2, which doesn't respect ~/.ssh/config. Does `ssh -F /dev/null` to the host work?
```
(and yes, `ssh -F /dev/null git@github.com` does work. I don't have a `~/.ssh/config`.)

If I try with `--verbose`, it spams this message constantly:

```
INFO cmd_git_fetch{args=GitFetchArgs { branch: [], remotes: [] }}:fetch{remote_name="origin" branch_name_globs=None git_settings=GitSettings { auto_local_branch: true }}: jj_lib::git: using ssh_key_from_agent username="git"
```

Since it mentioned agent, I realized I didn't have ssh-agent running. So I tried again after running `eval $(ssh-agent)`, but same result.

## Specifications

- Platform: Arch Linux
- Version: Kernel 6.4.10-arch1-1, updated 2023-08-16

**Comment by martinvonz** [comment]
This sounds a lot like #2008, which is fixed but not released. Try [installing the latest version from source](https://github.com/martinvonz/jj#build-using-cargo) and see if that helps.

>  So I tried again after running eval $(ssh-agent), but same result.

I think you'll need to also run `ssh-add` to add your keys to the agent. `ssh-add -l` should tell you which keys it knows about.

**Comment by Resonious** [comment]
Oh, great, thanks! `ssh-add` fixed it for me. I forgot that was necessary - haven't used `ssh-agent` in awhile.

**Comment by martinvonz** [comment]
FYI, once you've upgraded to a newer version of jj, you shouldn't need to use `ssh-agent` (assuming your keys are not password protected). I just wanted to clarify that because I didn't say it before.
