### ISSUE TITLE
FR: empty string placeholders for names and emails in templates.toml

### ISSUE THREAD

**Issue by emilykfox** [martinvonz/jj#2112]
See https://github.com/martinvonz/jj/pull/2108#discussion_r1298865005. We might want to pass empty names and emails as is to the user's template file. We can change `cli/src/config/templates.toml` a bit to keep the current behavior as the default.

**Comment by avamsi** [comment]
Sorry, didn't see this (thanks, Yuya!), yeah, I think I agree with Yuya's comment on #2154 that we should resolve this before #2154 (Emily or anyone else planning to pick this up, feel free to fold in #2154 if you'd like).

**Comment by yuja** [comment]
I'll take a look tomorrow.
