### ISSUE TITLE
Can we use `owning_ref` to avoid some `unsafe` blocks?

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2127]
In a review of `unsafe` code at Google, the suggestion to use `owning_ref` (https://docs.rs/owning_ref/latest/owning_ref/) came up. We should look into that.

**Comment by arxanas** [comment]
`owning_ref` seems unsound and unmaintained: https://github.com/Kimundi/owning-ref-rs/issues/77. There might be a maintained solution, or it might simply be possible (without having looked at the code) to shuttle around the value and its reference separately in an unergonomic way.

**Comment by yuja** [comment]
Mercurial recently switched to `self_cell`, and I think any of these can be used to remove `unsafe` from recursive tree iterators.
https://github.com/Voultapher/self_cell#related-projects
