### ISSUE TITLE
FR: jj log `-from` flag

### ISSUE THREAD

**Issue by cflewis** [martinvonz/jj#2177]
**Is your feature request related to a problem? Please describe.**

Follow up to https://github.com/martinvonz/jj/issues/229#issuecomment-1664532410, where without the implementation of removing empty commits from rebase, `jj log` gets really messy.

**Describe the solution you'd like**

`jj log` could take a `-from` flag which from a certain tag, rather than all the commits it knows. The obvious use cases being `jj log -from main` and `jj log -from HEAD@git`.

**Comment by cflewis** [comment]
Worth noting I figured out how to do this with shell scripting so I'm not out on a limb:

```
$ jj log --color=always | sed '/main/q'
@  zqywvzzo cflewis@google.com 2023-08-28 19:28:08.000 +00:00 9b173c98
│  (empty) (no description set)
◉  nkuoktpr cflewis@google.com 2023-08-28 19:28:08.000 +00:00 HEAD@git 3b31827a
│  [recipe_wrapper] Allow BCID tests to use real tool
◉  vzkpxvmp cflewis@google.com 2023-08-25 21:58:20.000 +00:00 main master 794119f5
```

**Comment by ilyagr** [comment]
Have you tried `jj log -r main::` or `jj log -r 'main..'` or `jj log -r 'main..@'`? The last two have the disadvantage of not showing the "root" of the log (the commits on the main branch), if that bothers you, you can also try `jj log -r 'main..|(main..)-'`.

I have a `[revset-alias]` configured to show `'siddot(from, to)'= '(from..to)|(from..to)-'`. It needs a better name, and I'm wondering if we can come up with something similar that could be provided out of the box.

**Comment by cflewis** [comment]
Ah, `jj log -r main::` does exactly what I want!

1. What does the `::` mean? Is that common `jj` syntax?
2. Perhaps the help text could mention this.

**Comment by ilyagr** [comment]
> What does the `::` mean? Is that common `jj` syntax?

Indeed! See the link I gave.

> Perhaps the help text on `jj log` could mention this?

I think it would be good to mention the revset docs from `jj log` help.

**Comment by cflewis** [comment]
Awesome, thank you for your help. This was great and has really improved my `jj` experience.

I'll close this out, feel free to reopen if you want it to track any help doc changes!
