### ISSUE TITLE
FR:  Print a hint of how to resolve conflicted branches or conflicted change ids

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2192]
When a user has a conflicted branch, they usually run into a message like the following:

```
Error: Revset "deneb-produce-blockv3" resolved to more than one revision
Hint: The revset "deneb-produce-blockv3" resolved to these revisions:
179b3c05123f practical review :)
c79ed56ed347 config/params: Require placeholderFields to be sorted and distinct (#12834)
```

When a user has a conflicted change id, they run into a very similar message.

It would be nice if we did one or both of the following:

1. `jj` informed the user when such conflicts are created (this could also apply to file conflicts)
2. `jj` could automatically determine that it's in one of these situations when resolving a revset.

In either case, `jj` could then the appropriate advice (`jj branch set` for conflicted branches, `jj abandon` for conflicted change ids).

Related Discord discussions: [1](https://discord.com/channels/968932220549103686/969829516539228222/1144282894500634665), [2](https://discord.com/channels/968932220549103686/969829516539228222/1146980406042828810).

**Comment by james-prysm** [comment]
having some of these tips would be great!

**Comment by wmrmrx** [comment]
Hi, could this issue be assigned to @isinyaaa and me (@wmrmrx)? We'll try looking at it!

**Comment by martinvonz** [comment]
I could only assign it to you, @wmrmrx, probably because @isinyaaa hasn't said anything on this issue yet. @isinyaaa, can you add a comment so we can see if GitHub lets me assign it to you too after that?

**Comment by isinyaaa** [comment]
Here you go :) Thanks!

**Comment by martinvonz** [comment]
It worked :)

**Comment by wmrmrx** [comment]
Hi, checking if the revset is a branch would be the way to go here? 
https://github.com/martinvonz/jj/blob/e3c85d6ecc20ee4240cdf3ed80107ce7dc268abe/cli/src/cli_util.rs#L1018C4-L1018C4
```rust
if revset_is_branch {
    hint = ... // hint to use jj branch set/jj abandon
} else {
    hint = normal_hint
}
```

**Comment by martinvonz** [comment]
Yes, that sounds right to me. You can inspect the `revset_expression` to see if it mentions any conflicted branches. It's probably good enough to check only if the expression is exactly `RevsetExpression::CommitRef(RevsetCommitRef::Symbol(name))`, where `name` is a conflicted branch.

**Comment by PhilipMetzger** [comment]
I'm going to close this issue as it has been adressed by #2244
