### ISSUE TITLE
FR: preserve current Git branch in co-located repo when possible

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2210]
This report stems from the discussion starting with https://github.com/martinvonz/jj/pull/2183#issuecomment-1706861202.

In a co-located repo, `jj` generally puts the git repo in a "detached HEAD" state since `jj` does not have a concept of the current branch. In general, I don't propose we change that.

However, after a `git switch branch`, we could make more effort to preserve `branch` as a current branch when possible.

`jj` already makes some effort here. For example `touch qq && jj log` keeps Git's current branch at `branch`. This is good.

However, `jj describe -m qq` currently switches to a detached HEAD state, even though it doesn't modify the `@-` commit where `branch` is at. This is undesired.

`jj new @-` also currently switches to a detached HEAD state. Arguably, it shouldn't for the same reason: if the user just did `git switch branch`, they probably mainly care about whether the `@-` commit (where `branch` is at) changed.

For reference, the situation `git switch branch` brings us to (after the subsequent automatic `jj git import`) is:

```
@ (empty) (no description set)
|
o branch
|
...
```

**Comment by necauqua** [comment]
As a bonus it will get rid of annoying warnings in tools :upside_down_face: 
![image](https://github.com/martinvonz/jj/assets/33968278/2817e360-566c-4581-861a-1cecbbb721ce)

**Comment by isinyaaa** [comment]
Hi, there, could this be assigned to me and @wmrmx?

**Comment by wmrmrx** [comment]
Commenting so I can be assigned @wmrmrx
