### ISSUE TITLE
FR: a way to reverse the order of commits in `jj split` 

### ISSUE THREAD

**Issue by thoughtpolice** [martinvonz/jj#2286]
`jj split -r x [PATHS...]` currently splits the given revision `x` in two by:

- Putting all specified `PATH`(s) within `x` into a "first" commit,
- Creating a new "second" commit with the first commit as parent; this commit contains all other modified paths within `x` that were not specified.

However, there are cases where I want the *reverse* of this: all specified `PATH`(s) go into the *second* commit, and everything else goes into the first commit.

Imagine my current `@` has many many files being modified:

```
A foo
A bar
A baz
...
```

Let's say 100 files are modified/added. I might want only a single file to go into the second commit, while all other 99 modified files go into the first one. To do this today, I would have to specify 99 file paths with `jj split`.

**Comment by thoughtpolice** [comment]
Note that this could also be generally true of most verbs that take a `[PATHS...]` argument, such as `jj move`.

**Comment by martinvonz** [comment]
It might be sufficient if we had something like [Mercurial's "file sets"](https://www.mercurial-scm.org/doc/hg.1.html#specifying-file-sets).

**Comment by ilyagr** [comment]
This is also related to https://github.com/martinvonz/jj/issues/1155.

**Comment by yuja** [comment]
30984dae4a92fbee0dc0b0cbcbaefab2a93a2aa3
