### ISSUE TITLE
"Wrong" config file location in docs

### ISSUE THREAD

**Issue by talpr** [martinvonz/jj#233]
I've really miss `fig` so when I heard about `jj` I just had to check it out 😄 

So while going through the docs (README.md, tutorial.md) I noticed they reference `~/.config/jj/config.toml`, but trying to set stuff there didn't actually do anything. AFAICT from the v0.4.0 release notes, this location is not the correct location for macOS (which I am currently on) or Windows, so it makes the documentation a bit confusing. Should there be a note there to clarify that, or maybe a suggestion to set `$JJ_CONFIG`? (Also, would it be useful to have some command to show the location of the config file?)

**Comment by martinvonz** [comment]
Hmm, you're right. It seems only https://github.com/martinvonz/jj#initial-configuration has the right location (i.e. `~/Library/Application Support/jj/config.toml` on macOS).

It's very likely that I'll back out https://github.com/martinvonz/jj/commit/095fb9fef4b1f25377576c4d9d56a3876106c949 to fix it.

>  (Also, would it be useful to have some command to show the location of the config file?)

Yes, good point. Maybe we should add some debug command for that, or maybe part of a real `jj config` command.

**Comment by martinvonz** [comment]
> I've really miss fig so when I heard about jj I just had to check it out 😄

Good to hear :) I'm on the Fig team. Thanks for filing bugs reports. Please keep them coming so we know what to prioritize!

**Comment by martinvonz** [comment]
If we restore support for reading from another place (which I think we should), should that be `~/.jjconfig` as it was before? Or maybe `~/.jj.toml`? Probably not `~/.jj/config.toml` because `.jj/` directories is what makes `jj` think it's a repo.

Also, should  configs set in that file override those in `~/Library/Application Support/jj/config.toml` etc.? Or the other way around? Or should it be an error to have both as it was before?

**Comment by talpr** [comment]
`~/.jjconfig` or `~/.config/jj/config.toml` both sound good to me. `~/.jj.toml` feels a bit strange (not having the word "config" anywhere), but it's not that big of a deal.

As for conflicts, I'm not sure, but my intuition is that it would be better to give an error message rather than potentially misbehaving quietly. Also, I assume `$JJ_CONFIG` would still "win" if it's set?

**Comment by martinvonz** [comment]
> As for conflicts, I'm not sure, but my intuition is that it would be better to give an error message rather than potentially misbehaving quietly.

Yes, I think that's best. Even if we allow both, the "misbehaving" would only be that you might have forgotten that you had one of the files. That can be partially alleviated with a command to list the config options and where they come from, so maybe it's not so bad. We'll (eventually) do the same overlaying of configs read from some system directory, as well as config in the `.jj/` directory. Still, I can't think of reason a user would want to use both `~/Library/Application Support/jj/config.toml` and `~/.jjconfig.toml`, so let's forbid having both to start with at least.

> Also, I assume `$JJ_CONFIG` would still "win" if it's set?

Yes.

**Comment by martinvonz** [comment]
Closing manually because I apparently duplicated the "#" in "Closes ##233" in the commit message so GitHub didn't recognize it.
