### ISSUE TITLE
FR: automatically add `.jj/.gitignore` with *

### ISSUE THREAD

**Issue by ppwwyyxx** [martinvonz/jj#2385]
**Is your feature request related to a problem? Please describe.**
I'm using jj colocated in a git repo. After initializing jj, `git status` reports untracked files in `.jj`.

**Describe the solution you'd like**
`jj init` can put a `.gitignore` file under `.jj/`, with content
```
*
```

**Describe alternatives you've considered**
User can manually ignore this themselves, but why not let jj do it.

**Comment by arxanas** [comment]
I had thought that jj would add itself to your excludes file; do you see it in `.git/info/exclude`?

https://github.com/martinvonz/jj/blob/0582893144e91ad04aa24e703a943e33549165f8/cli/src/commands/mod.rs#L1218

Although putting the `.gitignore` directly in the `.jj` directory seems like a possibly better solution regardless, since it won't touch user settings files and it'll be more obvious what's ignoring it.

**Comment by ppwwyyxx** [comment]
My `.git/info` directory does not have `exclude`. Not sure why.

**Comment by yuja** [comment]
I don't know if this is the case, but iirc, jj fails to update info/exclude if the git repo is a worktree. Anyway, adding `.jj/.gitignore` should be much easier than detecting the info/exclude file location.

**Comment by ppwwyyxx** [comment]
I used `jj init --git-repo=.`.

Just tried on a fresh repo and got this:
```
$ jj init --git-repo=.
Failed to add `.jj/` to /tmp/t/kinetics-dataset/.git/info/exclude because it doesn't exist
Initialized repo in "."
$ ls .git
config  HEAD  index  logs/  objects/  packed-refs  refs/
```

Note that this wasn't the message I got initially as my repo did have `.git/info`. But it does look like the exclude logic isn't very robust

**Comment by martinvonz** [comment]
Interesting, I think I've seen that once before. Do you know how you created that repo? Both `git init` and `git clone` create the file. Maybe your repo was created by libgit2 or something else. Either way, I assume it's a valid state that we should just handle by creating `info/exclude`.

**Comment by ppwwyyxx** [comment]
Interesting. After more careful look, it turns out that `info/exclude` is usually created because it is in git's default template (https://git-scm.com/docs/git-init#_template_directory). For users with their custom git template, this file will be missing.
