### ISSUE TITLE
Short commit template should show whether a commit is hidden or divergent

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2411]
Currently, the short commit template (the one-line summary shown in `jj status` and after many commands that mutate commits) shows less information than `jj log`. Adding these two pieces of information would fix this, wrapping up the changes started in #1845 and (more relevantly) in #1928:

1. [x] Show which commits are hidden (done)
2. [x] Show which commits are divergent

Currently, if we simply add these pieces of information to the template in the same way as in the `jj log` template, this causes (at least) two problems:

- `jj abandon` lists all the commits it abandoned as `(hidden)`.
- IIRC, `jj duplicate` lists all the commits it duplicated as divergent (red `??`). (I actually need to double-check whether this was the problem).

This is because, in both cases, the commits are passed to the template at the wrong point of the process (too late for `jj abandon` and too early for `jj duplicate`).

I meant to work on this on and off, but I'm not working on it now.

See also @yuja's suggestion in https://github.com/martinvonz/jj/pull/1928#issuecomment-1659719883 and the surrounding discussion.

**Comment by yuja** [comment]
> * `jj abandon` lists all the commits it abandoned as `(hidden)`.
> * IIRC, `jj duplicate` lists all the commits it duplicated as divergent (red `??`). (I actually need to double-check whether this was the problem).

The abandon problem should have been fixed. And duplicated commits will have new change ids, so they won't become divergent.

**Comment by ilyagr** [comment]
That's great news about abandon. I guess I'll try it once more and update the bug.

**Comment by ilyagr** [comment]
I briefly looked at this. Indeed, `abandon` is fixed! :tada: So, adding `hidden` shouldn't be a problem, it just needs a test.

You are right that `duplicate` is not a problem for divergent change ids, but at least `restore` and `diffedit` are problematic. See https://github.com/ilyagr/jj/commit/short-commit-abandon.

**Comment by ilyagr** [comment]
I'm not sure when I'll get a moment to deal with `restore` and `diffedit`, so I leave this bug open for others if anyone is interested.
