### ISSUE TITLE
Command alias doesn't work in repo-level config

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2414]
## Description

I'm filing this on @ppwwyyxx's behalf. Copying from https://github.com/martinvonz/jj/pull/982#issuecomment-1774202104:

> This is what I got:
> 
> ```
> ❯ 14:18 cd $(mktemp -d) ; jj init --git
> Initialized repo in "."
> ❯ 14:18 echo 'aliases.foo = ["diff"]' > .jj/repo/config.toml
> ❯ 14:18 jj config list aliases.foo
> ❯ 14:18 jj config --no-pager list aliases.foo
> aliases.foo=["diff"]
> ❯ 14:18 jj foo
> error: unrecognized subcommand 'foo'
> 
> Usage: jj [OPTIONS] [COMMAND]
> 
> For more information, try '--help'.
> ```

## Specifications

- Platform: unknown
- Version: 0.10.0-8dbe12da2a6d771d3409b19b76bf0f8781e6b218

**Comment by martinvonz** [comment]
I have no idea what the problem could be here. @ppwwyyxx, can you think of anything unusual in your setup? What else do you have in your config? Is `jj` a shell alias? What shell do you use?

**Comment by yuja** [comment]
There's a TODO about this. The repository path isn't determined until the command arguments gets parsed.
https://github.com/martinvonz/jj/blob/171896aefa4c65be37e3b325fe5441b3d0885da3/cli/src/cli_util.rs#L2783-L2802

Possible workarounds:
* show warning (as the comment says)
* load temporary repo config from cwd and use it only for command alias expansion
* parse command arguments without aliases as much as possible, and use `-R` to load temporary repo config

In any case, it's better to show warning if the repository path was different from the one we use for alias expansion.
