### ISSUE TITLE
docs: Useful Revsets section looks like runon sentences

### ISSUE THREAD

**Issue by joyously** [martinvonz/jj#2426]
https://github.com/martinvonz/jj/blob/5e407982b19793a7e240b2010e837e3b148a973f/docs/github.md?plain=1#L194

When I look at the [GitHub page](https://github.com/martinvonz/jj/blob/main/docs/github.md#useful-revsets), the Revsets are hard to read.

![Working with GitHub - Jujutsu docs-24](https://github.com/martinvonz/jj/assets/7957680/db310b2f-a4fe-4524-8bf4-f0374626a0cf)

**Comment by ilyagr** [comment]
Thanks! It's meant to be a list, but the Markdown isn't formatted correctly.

**Comment by martinvonz** [comment]
Yes, thanks for reporting it. I'll work on a fix.
