### ISSUE TITLE
`jj commit -i` commit message editor has inaccurate file listing

### ISSUE THREAD

**Issue by solson** [martinvonz/jj#2439]
## Description

When I use `jj commit -i` and select changes from a subset of files, the commit message editor will say that the commit contains changes from all files. Note that `jj split` does not have this bug.

## Steps to Reproduce the Problem

1. `echo 1 > foo; echo 2 > bar`
1. `jj commit -i`
1. Select changes from `foo` only.
1. Observe the commit message editor (`.jjdescription` file).

## Expected Behavior

```
JJ: This commit contains the following changes:
JJ:     A foo
```

## Actual Behavior

```
JJ: This commit contains the following changes:
JJ:     A bar
JJ:     A foo
```

## Specifications

- Platform: Linux
- Version: 0.10.0

**Comment by arxanas** [comment]
Relevant lines of code (which notably happen before `tx.select_diff`) in that function:

https://github.com/martinvonz/jj/blob/f656d9668b29b81b3df0359e82f467882d5fb8b0/cli/src/commands/mod.rs#L2168-L2169
