### ISSUE TITLE
FR: when `jj log <file>` is empty, suggest e.g.`-r ::@`

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2475]
When `jj log X` is empty, we already print a hint about using `-r X` instead. However, if `X` was actually a path, then it's probably quite likely that the user instead meant `jj log -r ::@ X` or maybe `jj log -r 'all()' X` instead. Maybe we should hint about both possibilities, or maybe we can decide between the two hints by checking if `X` resolves to a non-empty revset. Maybe we should also check if `jj log -r 'all()' X` is non-empty. Checking two additional revsets can be a bit costly. I don't think that's a problem in interactive use because the user most likely expected a non-empty output. We can think about how to make it possible to skip the hints in non-interactive use later.

Originally suggested by @BatmanAoD in https://github.com/martinvonz/jj/discussions/2474#discussioncomment-7429127.

**Comment by yuja** [comment]
Should be fixed by b79984884d91f89f5e2d0bd25a94fcd9c169e5d3.
