### ISSUE TITLE
FR: `jj workspace add` could support multiple `--revision`s

### ISSUE THREAD

**Issue by solson** [martinvonz/jj#2496]
Following on from #2364, which added `jj workspace add --revision <rev>`, it would be nice if it also supported multiple revisions, by creating a new working copy with multiple parents (just like `jj new r1 r2`).

Example usecase: create a fresh working copy to run tests on the combination of some sibling commits.

I think it would feel smoothest with `jj workspace add -r rev1 -r rev2`, but other syntaxes like `jj workspace add -r 'rev1|rev2'` could work.

**Comment by thoughtpolice** [comment]
Good idea. I can take a look at this sometime soon, I think.
