### ISSUE TITLE
FR: `show` should also list references for a given commit by default

### ISSUE THREAD

**Issue by thoughtpolice** [martinvonz/jj#2509]
Consider the following as of [37d6e71](https://github.com/martinvonz/jj/commit/37d6e71f7620d41248781c5067828c5afd254633):

```
austin@GANON:~/src/jj$ jj show nnt
Commit ID: 37d6e71f7620d41248781c5067828c5afd254633
Change ID: nntxpvokupwyvyltzpwrylyxvrxozvtl
Author: Austin Seipp <aseipp@pobox.com> ([8 hours ago])
Committer: Austin Seipp <aseipp@pobox.com> ([5 hours ago])

    github: fix codespell `skip` syntax for directories

    Summary: Codespell actually matches local files at the root of the repo with the
    `./` prefix, so without it the `skip` field won't match. Fix this for `./target`
    and `./.jj` directories.

    Signed-off-by: Austin Seipp <aseipp@pobox.com>
    Change-Id: Ibeafd7e400ff3bca9187d62241296060
```

This is `main` as of now, but there's no indication of that in the UX. Actually, this is true of any commit; just try `jj show HEAD@git` and it doesn't tell you that you're looking at `HEAD@git`, either.

In contrast, `git show` tells you what refs point at the commit following the commit hash:

```
austin@GANON:~/src/jj$ git show
commit d8a845dd2a7e6b0d8577c888fb94daa291c8dca3 (HEAD)
Author: Austin Seipp <aseipp@pobox.com>
Date:   Thu Nov 2 20:26:39 2023 -0500
```

This is probably part of the template I'm guessing, but I think this should be in the default template.

**Comment by martinvonz** [comment]
I don't think one even needs to write (Rust) code for that; this seems to be this TODO: https://github.com/martinvonz/jj/blob/b7c480a5757fc2a0b8f2e10182a93b237e7ce379/cli/src/config/templates.toml#L78-L90
