### ISSUE TITLE
`jj ci -i` and `jj split`: permission changes

### ISSUE THREAD

**Issue by crackcomm** [martinvonz/jj#2548]
## Description
When I selected a single file (`.gitignore`) in `jj split` and/or `jj ci -i`, the commit contained unrelated and invalid changes to file permissions (100755 → 100644). These files have 0755 permissions on my filesystem.

## Steps to Reproduce the Problem

1. Make sure you have a modified file with the executable bit set.
2. Use the `jj` command to perform a split operation or create a commit interactively (`jj split` or `jj ci -i`).
3. Select a single file, such as `.gitignore`, for inclusion in the operation.
4. Complete the operation and commit the changes.

## Expected Behavior
The selected file, such as `.gitignore`, should be included in the commit without any additional file changes.

## Actual Behavior
The commit includes unrelated and invalid changes to the file permissions, altering them from 100755 to 100644.

## Specifications

- Platform: Ubuntu 20.04
- `jj` Version: 2ac9865ce75451974aa127c30e7d6e659df2ee99, 0a81f54f0903d3f91f502841d89fa9a5f2bca8b0

## Additional information

After selecting a single file (`.gitignore`) in `jj split`:

![image](https://github.com/martinvonz/jj/assets/206368/39bd257e-409b-4720-9561-d712991ed14f)

Files were already in the tree and not empty with 0755 permissions both in repo and on my fs.

**Comment by martinvonz** [comment]
This seems to fix it in my very limited testing:
```
diff --git a/cli/src/merge_tools/builtin.rs b/cli/src/merge_tools/builtin.rs
index 200ec2a736...28ed354a77 100644
--- a/cli/src/merge_tools/builtin.rs
+++ b/cli/src/merge_tools/builtin.rs
@@ -350,7 +350,7 @@
         files.push(scm_record::File {
             old_path: None,
             path: Cow::Owned(changed_path.to_fs_path(Path::new(""))),
-            file_mode: None,
+            file_mode: Some(right_file_mode),
             sections,
         });
     }
```

**Comment by crackcomm** [comment]
It partially does.

I changed permissions of one file (`chmod 0644 tools/rbe/config/BUILD`) and this time this file was included:

```
JJ: Enter commit description for the first part (parent).

JJ: This commit contains the following changes:
JJ:     M .gitignore
JJ:     M tools/rbe/config/BUILD

JJ: Lines starting with "JJ: " (like this one) will be removed.
```

**Comment by crackcomm** [comment]
> This seems to fix it in my very limited testing:

I think it's a proper fix and the issue mentioned in the above comment is a separate issue.

**Comment by crackcomm** [comment]
I tried writing a test for this issue and to my surprise the test passed even w/o the above patch and when I use `jj ci -i` it works properly only with the patch applied. `jj ci file` also works w/o the patch.

It seems like the issue is in `scm_record` library.

**Comment by martinvonz** [comment]
I think the problem is with the integration with `scm-record` we have in `cli/src/merge_tools/builtin.rs`. When you use `jj ci file` it completely bypasses the diff editor, and even our tests of `jj split` bypass the `scm-record` integration because they use a custom diff editor (`fake-diff-editor`). Sorry that I didn't think of that before. Feel free to take my patch above and create a PR from it.
