### ISSUE TITLE
Checking out branch with `-` in its name fails with error.

### ISSUE THREAD

**Issue by tp-woven** [martinvonz/jj#255]
## Description

Trying to check-out a branch containing `-`s in its name fails. Neither quoting nor adding parentheses helps:

```
❯ jj branch foo-bar
❯ jj co foo-bar
Error: Failed to parse revset:  --> 1:5
  |
1 | foo-bar
  |     ^---
  |
  = Incomplete parse
❯ jj co "foo-bar"
Error: Failed to parse revset:  --> 1:5
  |
1 | foo-bar
  |     ^---
  |
  = Incomplete parse
❯ jj co "(foo-bar)"
Error: Failed to parse revset:  --> 1:6
  |
1 | (foo-bar)
  |      ^---
  |
  = expected parents_op, children_op, dag_range_op, range_op, union_op, intersection_op, or difference_op
```

## Specifications

- Platform: MacOS
- Version: jujutsu 0.4.0

**Comment by martinvonz** [comment]
That's actually working as intended right now. See #46 for discussion. The unfortunate workaround is to quote the branch name. To convince your shell not to parse the quotes, you'll need another layer of quotes, so something like `jj co '"foo-bar"'` will work.

**Comment by tp-woven** [comment]
Oh, sorry, I was looking at the quoting paragraph in revsets.md, saw the first two sentences, and then somehow missed the extra quotes in the last one... Thanks for the reference, though, that discussion is really interesting.

**Comment by martinvonz** [comment]
FYI, I've sent #256 to allow `-` (and `+`) in symbol names
