### ISSUE TITLE
`jj diff --stat` and `jj diff -s` do not print a final newline

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2568]
## Actual Behavior

`jj` didn't print a newline at the end:

```shell
$ jj diff --stat && echo aa
.gitignore     |   1 +
pdm.lock       | 730 +++++++++++++++++++++++++++++++++++++++++++++++++++++
pyproject.toml |  27 ++-
3 files changed, 756 insertions(+), 2 deletions(-)aa
```

This also affects `jj diff --summary`, and possibly other commands as well. I didn't investigate much at this point.

Fortunately, most shells work around such problems, so many users will not notice.

## Expected Behavior

```shell
$ jj diff --stat && echo aa
.gitignore     |   1 +
pdm.lock       | 730 +++++++++++++++++++++++++++++++++++++++++++++++++++++
pyproject.toml |  27 ++-
3 files changed, 756 insertions(+), 2 deletions(-)
aa
```

- Platform: Debian testing
- Version: jj 0.11.0-9533177422e788c1bc8ada48f22b91dd0d72ce0d

**Comment by martinvonz** [comment]
That doesn't reproduce for me. Does it happen for you with `--no-pager`?

**Comment by ilyagr** [comment]
Great question, I do have a weird pager set up (either streampager or moar), and that would make sense. I'll check for sure later.

**Comment by ilyagr** [comment]
This is https://github.com/walles/moar/issues/165.

I'm wondering whether we should put advice about trying `--no-pager` either in the issue template or in `contributing.md`.
