### ISSUE TITLE
FR: Add a "--tool" flag to resolve

### ISSUE THREAD

**Issue by matts1** [martinvonz/jj#2575]
**Is your feature request related to a problem? Please describe.**
According to the docs,
* The `ui.merge-editor` key specifies the tool used for three-way merge tools by `jj resolve`
* You can run `jj diff --tool=<tool>` to specify which tool to use to diff

It makes sense to also add this flag for conflict resolution.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by martinvonz** [comment]
The way we do alias expansion means that you might not even need a shell script for it; you can define an alias like this:

```
[aliases]
meld = ['--config-toml', 'ui.merge-editor="TOOL"']
```

And then use it with `jj meld resolve`. Strange but true.

**Comment by ilyagr** [comment]
You can go even fancier:

```toml
[aliases]
meld = ['--config-toml', 'ui.merge-editor="meld"',
        '--config-toml', 'ui.diff-editor="meld-3"', 
        '--config-toml', 'ui.diff.tool="meld"',
       ]
```

Here's the script I was thinking of, called `jj.tool`:

```sh
#!/bin/sh
TOOL="$1"
shift
jj --config-toml "[ui]
diff-editor = \"$TOOL\"
merge-editor = \"$TOOL\"
diff.tool = \"$TOOL\"" "$@";
```

It might be more readable if it had several `--config-toml`-s, like the alias example.

**Comment by essiene** [comment]
I'd like to take a stab at this is no one else is working on it.

**Comment by martinvonz** [comment]
> I'd like to take a stab at this is no one else is working on it.

Thanks! I've assigned this and #1457 to you.

**Comment by essiene** [comment]
Is the `--tool` flag limited to only diff related external tools? 

I don't know enough yet, but I'm wondering if we want to be able to easily "opt-in" a command to take a `--tool` flag, which can be any external command.

I will propose an approach to see if it makes sense, but I want to know what seems like a good direction in general.

**Comment by martinvonz** [comment]
I think the merge tools generally take multiple arguments so just pointing to a binary is not enough. See https://martinvonz.github.io/jj/v0.13.0/config/#setting-up-a-custom-merge-tool for how they're configured. I think we'll want `--tool` to take a name pointing into that config section (i.e. `kdiff3`, `meld` or `kdiff3` in the example on that page).
