### ISSUE TITLE
scm-record integration: interactive split

### ISSUE THREAD

**Issue by crackcomm** [martinvonz/jj#2591]
## Description

This issue was created to track the minor bug discovered in #2548.

When using `jj split` or `jj ci -i` and selecting a single file (e.g., .gitignore), the resulting commit includes unrelated and invalid changes to file permissions (e.g., 100755 → 100644). The problem seems to be related to the integration with `scm-record`.

## Steps to Reproduce the Problem

1. Ensure you have a modified file with the executable bit set.
2. Use the jj command to perform a split operation or create a commit interactively (`jj split` or `jj ci -i`).
3. Select a single file (e.g., .gitignore) for inclusion in the operation.
4. Complete the operation and commit the changes.

## Expected Behavior

The selected file (e.g., `.gitignore`) should be included in the commit without any additional and incorrect changes to file permissions.

**Comment by ilyagr** [comment]
I did not follow all the context, but I'm curious: how does this relate to #2572 ? Is it harder to fix?

**Comment by crackcomm** [comment]
#2572 fixed invalid change of chmod (change wasn't on the disk) it fixed #2548 but another bug was [discovered](https://github.com/martinvonz/jj/issues/2548#issuecomment-1806868455).
