### ISSUE TITLE
`jj` unexpectedly simplifies ancestry when rewriting a commit that is both a direct child and an indirect descendant of another commit

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2600]
## Description

I have always assumed that we do not allow a commit to be a direct child and an indirect descendant of another commit at the same time. See, for example:
 https://github.com/martinvonz/jj/blob/5186066cf5064564466e58096b79fba6b0c0ecfd/cli/tests/test_rebase_command.rs#L264-L269 

from https://github.com/martinvonz/jj/pull/538. `jj abandon` has similar functionality, see #2601.

However, it is actually possible to create such commits. Even simple commands like `jj describe` misbehave in such situations.

I originally discovered this in https://github.com/ilyagr/jj/commit/rebase-bug (see the test), but that bug seemed less relevant after I realized `describe` is also affected.

Is this a recent change? What is the desired behavior here?

## Steps to Reproduce the Problem

Start with this tree:

```
◉  MPVRWZ ilyagr@ 2023-11-19 15:21 -08 089239         
│  (empty) r                   
@  ZMKTYM ilyagr@ 2023-11-19 15:21 -08 default@ b94c44 
│  (empty) base   
```

1. Execute `jj new mpv zmk -m test`. (Aside: `jj rebase -r another_commit -d mpv -d zmk` produces a similar result.).

We get:

```
@    YOUOPL ilyagr@ 2023-11-19 15:22 -08 default@ 1c5b5a
├─╮  (empty) test              
│ ◉  MPVRWZ ilyagr@ 2023-11-19 15:21 -08 089239        
├─╯  (empty) r    
◉  ZMKTYM ilyagr@ 2023-11-19 15:21 -08 HEAD@git b94c44 
│  (empty) base  
``` 

2. Execute `jj describe -r mpv -m newname` (Aside: `jj edit mpv; touch qq; jj status` produces a similar result)

## Actual Behavior

```
@  YOUOPL ilyagr@ 2023-11-19 15:23 -08 default@ 5ecf8e  
│  (empty) test                
◉  MPVRWZ ilyagr@ 2023-11-19 15:23 -08 HEAD@git 976459 
│  (empty) newname
◉  ZMKTYM ilyagr@ 2023-11-19 15:21 -08 b94c44          
│  (empty) base           
```

## Expected Behavior

Either `jj new` results in a linear history after step 1 or `jj describe` keeps the shape of the graph after step 2.

## Specifications

- Platform: Debian linux
- Version: jj 0.11.0+20231111-ac53e26183315bd4 (based on the state of the main branch on 11/11).

----------------------

**Update:** From the discussion below up to https://github.com/martinvonz/jj/issues/2600#issuecomment-1818086284, it seems this is actually 2.5 issues:

- [ ] We should fix `jj describe`, `jj edit` messing up the shape and any similar bugs we can find.
- [ ] We should allow `rebase` and `abandon` (and others?) to create children that are also descendants
- [ ] We should test and fix [the issue that will cause with `rebase -r` onto descendants](https://github.com/martinvonz/jj/blob/22ad4d759919278da1b7452a8b48413ac8ac6bc4/cli/src/commands/rebase.rs#L345-L348) and any similar issues.

Lots of fun tests to write!

**Comment by martinvonz** [comment]
> Either `jj new` results in a linear history after step 1 or `jj describe` keeps the shape of the graph after step 2.

I was surprised that `jj describe` drops the merge. I consider that the bug.

@matts1, if you're thinking of working on #229, it's probably a good idea to keep this case in mind as well.

**Comment by ilyagr** [comment]
If so, should `abandon` and similar commands continue to avoid this outcome?

I'm guessing Git supports it, in which case we have to be able to pull such commits from a remote.

**Comment by martinvonz** [comment]
> I'm guessing Git supports it, in which case we have to be able to pull such commits from a remote.

Yes, and GitHub (and probably GitLab and others) create these all the time. Projects that use GitHub's default way of integrating PRs (called "Merge", I think) will have lots of these merges.

> If so, should `abandon` and similar commands continue to avoid this outcome?

I'm not sure. To me, it's surprising if commands like `jj describe` drop an edge because they don't normally change the shape of the DAG. It's less clear what `jj abandon` should do. Let's say we have this history:

```
D
|\
| C
B |
|/
A
```

If the user abandoned C, they would probably want D to become a child of only B, but it also seems reasonable to keep the shape of the history by making making D a child of B and A.

There's also this degenerate case:
```
D
|\
C |
|/
B
|
A
```

Here, I think it's clear that abandoning C should not leave B and B (duplicated) as parents of D. I think it's also clear that abandoning A should not change D's parents. I would also say that abandoning B should result in D having C and A as parents.

**Comment by ilyagr** [comment]
For the degenerate case, I'm guessing Git does not allow duplicated parents?

Here are a few thoughts about implementation difficulties.

Also, let's say that `D` had a child in this case, and we abandon `D`. I'll also draw it a little differently (I find this easier to understand): 

```
E
|
D
|\
| C
|/
B
|
A
```

Abandoning `D` should likely make `C` and `B` the parents of `E`.

From the implementation standpoint, however, the above behavior is not trivial to reconcile with the current behavior of abandoning `C` in your non-degenerate example:

```
D
|\
| C
B |
|/
A
```

leaving `D` with one parent.

If we change the behavior and abandoning `C` make it leave `D` with two parents,

https://github.com/martinvonz/jj/blob/22ad4d759919278da1b7452a8b48413ac8ac6bc4/cli/src/commands/rebase.rs#L345-L348

will probably need reworking. The assumption there is already false, but the fact that `rebase` itself does not create such incestuous commits is probably good enough to make the logic work. I wonder what other fun test cases we'd need to add.

**Comment by martinvonz** [comment]
> From the implementation standpoint, however, the above behavior is not trivial to reconcile with the current behavior of abandoning `C` in your non-degenerate example

Good point. I think that's a good argument for not having too much smarts in the auto-rebasing code. If the user wants to linearize history, they can manually update D to have just one parent with `jj rebase -s D -d B`.

**Comment by ilyagr** [comment]
Instead of `jj describe`, a better demo of the bug is to `jj edit` the commit, `touch qq`, and run any jj command to import the working copy. I updated the bug description to mention that. The problem is somewhere in DescendantRebaser, I'd guess.

**Comment by ilyagr** [comment]
Specifically, I think it's this section that reshapes the graph for `edit` or `describe`:

https://github.com/martinvonz/jj/blob/16620e0e4c47815f751e27870c700fca66037442/lib/src/rewrite.rs#L445-L456

**Comment by ilyagr** [comment]
Here's a fun edge case I found. Let's say we decide we want to simplify ancestry as little as possible.

Here's little puzzle (answer below): why would `jj` have trouble doing `jj rebase -r base -d root` for the following tree?

```
    @  c
    ◉    b
    ├─╮
    │ ◉  a
    ├─╯
    ◉  base
    ◉  root
```

<details><summary>Answer (there are also spoilers below)</summary>

Because `b` would then be a child of both `a` and the root commit. With the Git backend, at least, that is not allowed.

</details>

I can see two options of what to do here:

- Print an error message. This seems like it would be surprising and annoying, since it takes a puzzle to figure out what was wrong in the first place.
- Simplify ancestry like we do now. Then, `b` will be a parent of `a` only.

Either way, the behavior will be surprisingly different from what happens in the following tree, where the same command can work fine.

```
    @  c
    ◉    b
    ├─╮
    │ ◉  a
    ├─╯
    ◉  base
    ◉  another commit
    ◉  root
```

**Comment by martinvonz** [comment]
Good find. I think [the current error from the Git backend](https://github.com/martinvonz/jj/blob/ec7f9e79f67d9a5a12d221c60a91d59b5eb6b925/lib/src/git_backend.rs#L934-L940) seems appropriate in this case. It's only a limitation of the Git backend after all. It's also a rare case even when using the Git backend. I don't think it should affect our decision. I don't mind answering questions from the presumably few users who run into it. What do you think?

**Comment by ilyagr** [comment]
Also, right now, the error looks extra-scary. We'd probably want to make it look friendlier:

> Internal error: Merge failed: Backend error: Error: The Git backend does not support creating merge commits with the root commit as one of the parents.

**Comment by martinvonz** [comment]
I think so, yes. Ilya can reopen if he feels differently.
