### ISSUE TITLE
"Error: Failed to run editor" on Windows

### ISSUE THREAD

**Issue by hickford** [martinvonz/jj#2614]
Hi. I tried to set the editor on Windows but got an error:

```
>jj config set --user ui.editor "C:\Program Files\Microsoft VS Code\Code.exe"

>jj describe
Error: Failed to run editor 'C:\Program Files\Microsoft VS Code\Code.exe'

>jj version
jj 0.11.0-f00f7527ddce21886fe93e11324c5227f15eeaca
```

I'm using Windows

**Comment by yuja** [comment]
You'll probably need to use the array syntax. See the Notepad++ example:
https://martinvonz.github.io/jj/v0.11.0/config/#editor

**Comment by ilyagr** [comment]
Perhaps the error message could have shown that it's trying to call "C:\Program" with some arguments.
