### ISSUE TITLE
`jj rebase -r A -d descendant_of_A` can panic if the graph has weird ancestry.

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2650]
See https://github.com/martinvonz/jj/pull/2644 for the panicking test (`jj_cli_panic`). See also https://github.com/martinvonz/jj/pull/2644#discussion_r1408562382.

This is loosely related to #2600. It happens with or without #2646 .

**Comment by ilyagr** [comment]
Indeed, it seems like removing that code + #2646 fix that bug. However, there are still issues with the root commit, see https://github.com/martinvonz/jj/issues/2600#issuecomment-1835418824. If we keep simplifying the graph for the root commit, I'm not sure if some shade of this bug will remain.

**Comment by ilyagr** [comment]
I'm not actively working on this ATM, it's likely to be affected as we refactor the DescendantRebaser. This could also become a part of that refactor.

**Comment by bnjmnt4n** [comment]
I think this has been fixed by migrating to the new `transform_descendants` API in #3551. In particular, the panicking test case no longer panics.

**Comment by ilyagr** [comment]
Thank you so much for working on this! I haven't been able to look at the details yet, but it sounds very nice.
