### ISSUE TITLE
gix::Repository can't deal with .git being a symlink

### ISSUE THREAD

**Issue by matts1** [martinvonz/jj#2668]
## Description
This [commit](https://github.com/martinvonz/jj/commit/c88e69ad6f5af236ade02221175cb92c267c6db0) switched from git2 to gix. However, it appears to not play nice when .git is a symlink, rather than an actual directory. This, unfortunately, breaks anyone using the [repo](https://gerrit.googlesource.com/git-repo) tool.

## Steps to Reproduce the Problem

Requires prerelease JJ (issue not present in latest released version)
1. `git clone <any repository>`
2. `mv .git ../git_directory`
3. `ln -s ../git_directory .git`
4. `jj init --git-repo .`

## Expected Behavior
Success

## Actual Behavior
`Error: Failed to access the repository: Failed to open git repository: No such file or directory (os error 2)`

Alternatively, if you've already created the repo with jj, and you update to a version that breaks this, you will find that your git and JJ have seperate states.

## Specifications

- Platform:
Linux
- Version:
Prerelease

**Comment by yuja** [comment]
>     1. `git clone <any repository>`
>     2. `mv .git ../git_directory`
>     3. `ln -s ../git_directory .git`
>     4. `jj init --git-repo .`

If the repository is named as `git_directory.git` at step 2, the problem goes away. The `repo` tool I have (v2.39) sets up repositories that way, but I don't know if that depends on the `repo` version or some configuration.

FWIW, it's better for jj to not resolve `.git` symlink. If the git repo is opened by `.git` path, gix won't be confused.

**Comment by matts1** [comment]
Ah, that explains why my repro was wierd. I was originally trying to file a bug for "Alternatively, if you've already created the repo with jj, and you update to a version that breaks this, you will find that your git and JJ have seperate states.", but wasn't even able to do jj init.

Can you repro this instead?

```
# cd to a git repo managed by the repo tool
rm -rf .jj
git checkout main
git branch foo
git checkout foo
touch foo
git commit -am foo
<prerelease jj> init --git-repo .
<prerelease jj> checkout @--
```

According to prerelease jj, main is checked out, but if you run git log, it thinks foo is checked out still.

**Comment by yuja** [comment]
> According to prerelease jj, main is checked out, but if you run git log, it thinks foo is checked out still.

Yes, I can reproduce the problem with that setup. gitoxide appears to be strict about the working directory path. We rely on libgit2's bug that works fine even if `$(readlink .git)/..` were not a valid working copy.
