### ISSUE TITLE
`jj new` can hang

### ISSUE THREAD

**Issue by shavitmichael** [martinvonz/jj#2729]
## Description
I'm on a collocated git project (backed by android's repo tool, with watchman enabled). I recently got into a state where `jj new` or `jj co` operations hung until I sent them SINGINT. I recently upgraded jj which may or may not be related.

## Steps to Reproduce the Problem
1. Unknown?
2. jj edit to some commit. 
3. jj new (with or without --ignore-working-copy)
4. Hang
5. Sigint to kill jj

`jj log` and `jj op log` after killing jj shows that a new commit is correctly created however, and nothing looks abnormal. In fact subsequent `jj co` and `jj edit` commands no longer hang.
Calling `jj op restore` to the operation preceding `jj new` will also hang, but again nothing looks abnormal in `jj log` after killing it and the restore looks successful. The next `jj new/co` operation will again hang.

## Other information

Used `flamegraph` to capture a flamegraph after letting it hang for a minute or two which can hopefully help point to the problem.

![flame_3](https://github.com/martinvonz/jj/assets/4763500/7d0f407a-12f1-4044-b20f-610f3c7794d2)

## Specifications

- Version:  `jj 0.12.0-af6047a655c57ddc3854fc5d89463403a38081d3`

**Comment by yuja** [comment]
Can you test this? https://github.com/martinvonz/jj/pull/2730

FWIW, if you don't need a history of jj, you might want to remove and recreate `.jj` repo to import existing git commits in the new tree-conflict format. It will greatly improve the performance of `jj log` for example.

**Comment by shavitmichael** [comment]
Thank you Yuya! Tested #2730 and it indeed fixed the issue.
