### ISSUE TITLE
`jj rebase --skip-empty` unexpectedly changes the commit graph

### ISSUE THREAD

**Issue by afgomez** [martinvonz/jj#2760]
## Description

When running `jj rebase --skip-empty` the commit graph gets mangled if there are empty commits created as a result of the operation.

## Steps to Reproduce the Problem

1. Create a repo with some commits

```
$ jj init --git test-repo; cd test-repo
$ echo a > a; jj commit -m A
$ echo b > b; jj commit -m B
$ echo c > c; jj commit -m C
$ jj log
@  ovpukpso ...@gmail.com 2023-12-31 09:50:57.000 +01:00 18755ef0
│  (empty) (no description set)
◉  uuxmnpmy ...@gmail.com 2023-12-31 09:50:57.000 +01:00 61676efa
│  C
◉  yvvmnvxw ...@gmail.com 2023-12-31 09:50:49.000 +01:00 4b9ba9d2
│  B
◉  lrkotskn ...@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000
```

2. Create a new commit on top of `lrk`, with the same changes as `yvv`

```
$ jj co lrk
$ echo b > b; jj commit -m 'Another B'
$ jj
@  ypxrttrn ...@gmail.com 2023-12-31 09:53:12.000 +01:00 7321edf3
│  (empty) (no description set)
◉  lxknpytx ...@gmail.com 2023-12-31 09:53:12.000 +01:00 eca4b830
│  Another B
│ ◉  uuxmnpmy ...@gmail.com 2023-12-31 09:50:57.000 +01:00 61676efa
│ │  C
│ ◉  yvvmnvxw ...@gmail.com 2023-12-31 09:50:49.000 +01:00 4b9ba9d2
├─╯  B
◉  lrkotskn antarticonorte@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000
```

3. Switch to the commit with description 'C' and rebase with `--skip-empty` on top of `lxk` (the commit described as 'Another B'). 

```
$ jj co uux
$ jj
@  xsylwmsl ...@gmail.com 2023-12-31 09:54:09.000 +01:00 9b0f9b9f
│  (empty) (no description set)
◉  uuxmnpmy ...@gmail.com 2023-12-31 09:50:57.000 +01:00 61676efa
│  C
◉  yvvmnvxw ...@gmail.com 2023-12-31 09:50:49.000 +01:00 4b9ba9d2
│  B
│ ◉  lxknpytx ...@gmail.com 2023-12-31 09:53:12.000 +01:00 eca4b830
├─╯  Another B
◉  lrkotskn ...@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000

% jj rebase -d lxk --skip-empty
Rebased 3 commits
Working copy now at: uuxmnpmy 79d445d5 C
Parent commit      : lrkotskn 161d8858 A
Added 0 files, modified 0 files, removed 1 files # <<< Note that a file is being removed. 

# vvv Note that the working copy is at 'C', not in a new empty commit.
# My guess is that `--skip-empty` is removing `xsy`.
# Note as well that 'C' is not properly rebased on top of 'Another B'. It's
# on top of 'A'
~/code/test-repo% jj
@  uuxmnpmy ...@gmail.com 2023-12-31 09:55:44.000 +01:00 79d445d5
│  C
│ ◉  lxknpytx ...@gmail.com 2023-12-31 09:53:12.000 +01:00 eca4b830
├─╯  Another B
◉  lrkotskn ...@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000
```

In comparison, this is what happens with a regular rebase:

```
~/code/test-repo% jj
@  xsylwmsl ...@gmail.com 2023-12-31 09:54:09.000 +01:00 9b0f9b9f
│  (empty) (no description set)
◉  uuxmnpmy ...@gmail.com 2023-12-31 09:50:57.000 +01:00 61676efa
│  C
◉  yvvmnvxw ...@gmail.com 2023-12-31 09:50:49.000 +01:00 4b9ba9d2
│  B
│ ◉  lxknpytx ...@gmail.com 2023-12-31 09:53:12.000 +01:00 eca4b830
├─╯  Another B
◉  lrkotskn ...@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000

~/code/test-repo% jj rebase -d lx
Rebased 3 commits
Working copy now at: xsylwmsl e3fc4b16 (empty) (no description set)
Parent commit      : uuxmnpmy 1fb4f069 C

~/code/test-repo% jj
@  xsylwmsl ...@gmail.com 2023-12-31 09:57:26.000 +01:00 e3fc4b16
│  (empty) (no description set)
◉  uuxmnpmy ...@gmail.com 2023-12-31 09:57:26.000 +01:00 1fb4f069
│  C
◉  yvvmnvxw ...@gmail.com 2023-12-31 09:57:26.000 +01:00 ffeb7970
│  (empty) B
◉  lxknpytx ...@gmail.com 2023-12-31 09:53:12.000 +01:00 eca4b830
│  Another B
◉  lrkotskn ...@gmail.com 2023-12-31 09:50:39.000 +01:00 161d8858
│  A
◉  zzzzzzzz root() 00000000
```

## Expected Behavior

- The commits get rebased on top of the specified destination, in a linear fashion like when doing a normal rebase
- `jj` creates a new empty commit at the tip of the branch

## Actual Behavior

- The commits create a branched history.
- `jj` keeps the current commit at the last commit of the branch.

## Specifications

- Platform: macOS
- Version: 0.12.0

**Comment by yuja** [comment]
> My guess is that `--skip-empty` is removing `xsy`.

Yeah, that's probably it (though I don't know why `uuxmnpmy` wasn't rebased. There may be two separate problems.)

The `@` commit is included in the explicit rebase source, and it's empty. In this scenario, (hypothetical) `--skip-emptied` (drop revisions that _become_ empty) option would work better. We can of course add special case to recreate the wc commit if it was previously empty, but I don't know if that's reasonable.

**Comment by martinvonz** [comment]
Hmm, that's a weird bug. @matts1, do you have time to look into it? Also, @ilyagr, since you're working on refactoring this code, do you want us to not touch this until you're done refactoring? I'm not sure exactly which parts of it you're going to touch.

> The `@` commit is included in the explicit rebase source, and it's empty. In this scenario, (hypothetical) `--skip-emptied` (drop revisions that _become_ empty) option would work better. We can of course add special case to recreate the wc commit if it was previously empty, but I don't know if that's reasonable.

I think `jj rebase --skip-empty` should behave as a regular `jj rebase` followed by abandoning of any empty commits in the set of new commits (except that we don't even create the intermediate commits and set predecessor pointers for obslog).

**Comment by ilyagr** [comment]
Interesting bug.

I think the bug could also occur with `--skip-emptied`, though it wouldn't be as common. The working copy can become emptied by a rebase even if it wasn't empty.

I think the fix would be to add another condition to `--skip-empty`'s logic: don't abandon commits if they are merge commit (as it is today) **or** if they are the working copy. This wouldn't interfere with what I'm doing at all, unless I'm missing something and it's actually a much more complicated fix. The test should be based on #2738, which I'll probably merge tomorrow.

**Comment by matts1** [comment]
Was able to repro, thanks for filing the bug.

**Comment by matts1** [comment]
After rereading the comments, I should probably clarify some things.

> My guess is that `--skip-empty` is removing `xsy`.

This was intentional. I'm not a big fan of rebase changing how it works depending on your working commit, but I can definitely see the use for it here. I'm far more concerned about the fact that the history remains branched. There's open questions here (eg. "It's unclear to me what the best behavior is if the working copy has children").

For now, I won't touch this aspect of the bug. Someone else is welcome to make a change if they want though.

I care far more about the rebase creating seperate branches, which is definitely not WAI. I'll be working on fixing that.

**Comment by ilyagr** [comment]
#2738 is merged now, so it shouldn't be an obstacle for writing a test for #2766 anymore.

Thanks, Matt, for working on this!

**Comment by ilyagr** [comment]
Tangentially related, @matts1, do you remember why we never implemented `--skip-emptied` in addition to `--skip-empty`? This is not a call to action, I'm mostly just curious.

**Comment by matts1** [comment]
I felt that there was a few open questions still regarding API.

Here are three options I was considering:
* Have two flags, `--skip-emptied` and `--skip-empty`
* Have an enum flag `--skip-empty=newly|all|never`
* Have a single flag `--skip-empty` which does all empty commits
* Have a single flag `--skip-empty` which does newly empty commits

I implemented the third option, but in retrospect, I'd probably be happy changing it to the fourth option. I personally think option 1 adds too much complexity to the API.

**Comment by ilyagr** [comment]
I like option 1 and option 4. Option 2 is annoying since the user will have to specify something each time; I don't think clap provides a good way to allow both `--skip-empty` by itself and `--skip-empty all`.

**Comment by afgomez** [comment]
> - Have a single flag --skip-empty which does newly empty commits

To me this sounds like what I would want the tool to do. Only skip the commits if they become empty. If for whatever reason I have created empty commits (Like... I don't know... I want to outline how the history might look like before implementing anything) I think they should be preserved.

It's worth considering renaming the flag to `--skip-emptied` then, to make it clear that it would not skip currently empty commits.
