### ISSUE TITLE
`jj status` reports link in Fuchsia repo as removed

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2878]
## Steps to Reproduce the Problem

```
$ jj git clone https://fuchsia.googlesource.com/fuchsia
$ cd fuchsia
$ jj st
Working copy changes:
R third_party/rust_crates/intree/fuchsia-cprng
Working copy : pvlt 915e3db8 (no description set)
Parent commit: tluk 8b9bdc30 main master | [bt] Define the host-watcher crate
```

I haven't had time to figure out why it's happening. It may be relevant that the link points to a directory. We might not have any test coverage for that.

**Comment by ilyagr** [comment]
See also [the Discord discussion](https://discord.com/channels/968932220549103686/1199462154164781259) for weirder-looking problems with snapshotting/materializing the working copy that the problem Martin demoed seems to cause if you try to work with that repo.

**Comment by yuja** [comment]
We have `.metadata()` call in gitigreno-special case. Perhaps, that's the source of the problem. I'll take a look.

https://github.com/martinvonz/jj/blob/57d5abab0ceabd8a441aff4d50d3280d59eca411/lib/src/local_working_copy.rs#L889-L911

**Comment by joyously** [comment]
So in `jj`, the `R` indicates removed? 
I would expect `D` for delete and `R` for rename.

**Comment by martinvonz** [comment]
> So in `jj`, the `R` indicates removed?

Correct.

> I would expect `D` for delete and `R` for rename.

Makes sense. That's what `git status -s` uses.
