### ISSUE TITLE
FR: test if multiiple lists are all empty in template

### ISSUE THREAD

**Issue by amiryal** [martinvonz/jj#2924]
# The problem

I would like to decorate commits in a log template with all possible local `RefName`s listed in parentheses, but omit the parentheses if the commit has no such references to list. However, there is no way currently to cast multiple `List`s into a `Boolean` in the template.

I.e. the following does not currently work:

```sh
jj log -T 'if(branches ++ git_refs, "(" ++ separate(" ", branches, git_refs) ++ ")")'
```

```
Error: Failed to parse template:  --> 1:4
  |
1 | if(branches ++ git_refs, "(" ++ separate(" ", branches, git_refs) ++ ")")
  |    ^------------------^
  |
  = Expected expression of type "Boolean"
```

# Workaround

```sh
jj log -T 'if(branches, "(" ++ separate(" ", branches, git_refs) ++ ")", if(git_refs, "(" ++ git_refs ++ ")"))'
```

This ↑ gets progressively unwieldy as more lists are added, e.g. `branches`, `tags`, `git_refs`, `git_head`.

# Possible solutions

* Return a `List<Template>` when concatenating `List`s, which should enable to cast it as `Boolean` for the condition.
* Add boolean logic operators, like `x | y` (“`x` or `y`”).
* Add a `surround(add_prefix: String, add_suffix: String, content: Template) -> Template` function, which renders empty if `content` is empty.
* Add optional `add_prefix: String, add_suffix: String` parameters to the existing `label`, `concat` and `separate` functions.
* Any other acceptable solution.

## Solutions that were ruled out

* Cast `Template` to `Boolean`: if the template renders non-empty — true; if empty — false. (Ruled out in [#comment](https://github.com/martinvonz/jj/issues/2924#issuecomment-1925272488) because `bool ++ bool` would always evaluate to true.)

**Comment by yuja** [comment]
Perhaps, adding infix logic ops is the way to go. It'll also work for `bool | bool` (whereas `if(bool ++ bool, ..)` would be always true even if `Template` could be converted to bool.)

I also think `surround(..)` is good because it's not uncommon to wrap non-empty content in parens.
