### ISSUE TITLE
`jj init --git-repo=.` does weird things to the git index

### ISSUE THREAD

**Issue by jyn514** [martinvonz/jj#2942]
## Description

`jj init` makes git that all files have been deleted in the index, even though the working tree is unmodified.

## Steps to Reproduce the Problem

```
; git status -sb
## HEAD (no branch)
?? cli/src/commands/help.rs
; rm -rf .jj
; jj init --git-repo=.
Done importing changes from the underlying Git repo.
Initialized repo in "."
```

## Expected Behavior
the git index is unchanged.

## Actual Behavior
the git index shows a bunch of files deleteed:
```
; git status -sb
## HEAD (no branch)
D  .editorconfig
D  .envrc.recommended
D  .gitattributes
...
?? cli/src/commands/help.rs
...
?? .editorconfig
?? .envrc.recommended
?? .gitattributes
...

```

if i run `git reset HEAD`, it goes back to normal:
```
## HEAD (no branch)
?? cli/src/commands/help.rs
```
but it seems quite odd that i have to do that; and i don't think most people would think of running `reset HEAD`.

## Specifications

- Platform: Linux pop-os 6.6.10-76060610-generic #202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
- Version: jj 0.13.0-81b0e3bf3bf6f230740e93532b9a9767e8a4ef6e

**Comment by yuja** [comment]
Appears that this is a bug of 9faa4670d53fa8ecdcb62b82ef988ad587a973c1. I'll take a look.
