### ISSUE TITLE
FR: `jj git push --tracked --deleted` should work

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#2946]
This is a followup to #2935 and a TODO in there.

**Comment by yuja** [comment]
or make `--deleted` imply `--tracked`? Untracked remote branches can't be deleted anyway.

**Comment by yuja** [comment]
> or make `--deleted` imply `--tracked`? Untracked remote branches can't be deleted anyway.

Oh, it's effectively it. Existence of untracked remote isn't an error, but a warning. I think the current behavior is pretty okay.

**Comment by ilyagr** [comment]
Good point. I think we should make deleted imply tracked. No point in trying to push branches that can't be pushed. We only need to check the description of the option slightly.
