### ISSUE TITLE
FR: Pattern match the arguments for `revset-aliases`

### ISSUE THREAD

**Issue by Zambito1** [martinvonz/jj#2966]
**Is your feature request related to a problem? Please describe.**
I want to be able to use revset aliases that can handle different numbers of arguments. I think pattern matching on the arguments is the most natural way to do this.

**Describe the solution you'd like**
```toml
[revset-aliases]
'review(x)' = '(::x | ::@) ~ ::trunk()'
'review(x, y)' = '(::x | ::@) ~ ::y'
```

The first alias defines a function that will show the intersection between the provided branch and your working branch, and only the commits of those that have not landed on the `trunk()` branch. This is useful for reviewing merge requests.

It may be useful to specify a target besides the `trunk()`, if that is not what the target branch is. Specifying an additional, optional argument would be a good way to do this.

**Describe alternatives you've considered**
This could be achieved by naming the second alias something different, but I think pattern matching on the arguments like this is a reasonable behavior to expect.

**Comment by yuja** [comment]
iirc, Sapling added support for overloading by arity. That's probably doable in jj.
