### ISSUE TITLE
FR: Support passing template to `jj show` command

### ISSUE THREAD

**Issue by zummenix** [martinvonz/jj#2969]
**Is your feature request related to a problem? Please describe.**

I'd like to setup my shell prompt to print current state of a change – basic info like change id, empty or not, maybe description and a branch

**Describe the solution you'd like**

I'd like to pass a custom template from my jj config to `jj show`, for example ex: `jj show -T prompt_show_oneline`

**Describe alternatives you've considered**

One alternative is to use `jj log -T prompt_show_oneline | head -n1` but it prints leading symbols of a graph (dots and `@`) that I don't need in this case.

**Additional context**

–

**Comment by martinvonz** [comment]
> but it prints leading symbols of a graph

There's `--no-graph` :) (But that doesn't mean that we shouldn't support templating in `jj show`.)

**Comment by zummenix** [comment]
> There's `--no-graph`

Thank you! I haven't thought about it :)

 I managed it to work using `jj log --no-graph --limit 1 -r ..@ -T prompt_show_oneline`

**Comment by zummenix** [comment]
> For truly lightweight prompt (that will show that repo is stale until you run some jj command), a non-snapshotting status/diff are needed (there's a FR I made for that, hard to look up on mobile while typing this)

@necauqua Most likely this one: https://github.com/martinvonz/jj/issues/2562
