### ISSUE TITLE
FR: Render elided commits in `jj log` as synthetic node

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2971]
**Is your feature request related to a problem? Please describe.**

We currently render elided nodes in the log output as dashed lines, like this:
```
◉  tou yuya@tcha.org 2 days ago 99f0e7f8
╷  cli: remove workaround for ": {source}" embedded in error message
╷ ◉  oxlm ben@brittain.org 2 days ago pager@origin cb232258
╭─╯  cli: Provide better flags for the "less" pager than default
◉  kksnw ben@brittain.org 2 days ago ae3404cd
│
~
```

It's not obvious what the dashed lines mean.

**Describe the solution you'd like**

It would be clearer if we inserted a synthetic node where we elide commits:

```
◉  tou yuya@tcha.org 2 days ago 99f0e7f8
╷  cli: remove workaround for ": {source}" embedded in error message
◌ (elided commits)
╷
╷ ◉  oxlm ben@brittain.org 2 days ago pager@origin cb232258
╭─╯  cli: Provide better flags for the "less" pager than default
◉  kksnw ben@brittain.org 2 days ago ae3404cd
│
~
```

We might not even need to draw the dashed lines if we do (but they're not expensive or anything, so we could).

If we draw a synthetic node for elided commits in the middle of the graph, then it would also make sense to also do that instead of  the tilde we currently draw for elided nodes going to the root.

We may or may not want to also mention the number of elided commits (e.g. "(1234 elided commits)"). Depends on how cheap we can make it.

This would also solve #1252.

**Describe alternatives you've considered**

We could instead use some clearer symbol for dashed line, possibly using more space.

**Comment by epage** [comment]
For git-stack, I was considering a vertical ellipses for the synthetic node for elided commits.

**Comment by ilyagr** [comment]
I actually think `~` is pretty good for elided commits.

**Comment by arxanas** [comment]
Here's an example of what omitted commits look like in git-branchless:

<img width="718" alt="Screenshot 2024-02-11 at 12 30 33" src="https://github.com/martinvonz/jj/assets/454057/a00d1bcf-df26-4b21-b863-f4694761c3ce">

Note that the log is reversed and trunk commits are represented with an ellipsis *without* a commit count. (Also, it doesn't use `◌`, but it should because that's clearly a better choice of icon.)

**Comment by thoughtpolice** [comment]
See also: https://github.com/martinvonz/jj/pull/3124 for an experiment I'm running with a totally different icon which I think looks like a "scissor snip."

**Comment by bnjmnt4n** [comment]
Closing since this was done in https://github.com/martinvonz/jj/pull/3027. https://github.com/martinvonz/jj/issues/3099 tracks the display of number of elided commits in the synthetic node.
