### ISSUE TITLE
FR: abandon changes that have been merged into trunk

### ISSUE THREAD

**Issue by jyn514** [martinvonz/jj#2978]
**Is your feature request related to a problem? Please describe.**
i want `jj log` to show me only my work-in-progress changes. i came up with the following revset filter:
```
jj log -r 'trunk()..mine()'
```
which mostly works, but also shows changes that have been merged into main:
```
; jj l
@  ovnquutq github@jyn.dev 2024-02-06 22:43:03.000 -05:00 3ea39416
│  (empty) (no description set)
~

◉  vtvmzysm github@jyn.dev 2024-02-06 22:10:43.000 -05:00 push-vtvmzysmmmuk 9a005d7d
│  document the jj equivalent of git reset --soft
~

◉  unqytsxw github@jyn.dev 2024-02-04 14:40:32.000 -05:00 binary-diff 42077f4f
│  don't try to diff binary files
~
...
```

now, my first thought was "oh, this is showing branches as well as unmerged changes", but `jj branch delete binary-diff && jj git push --deleted` didn't help. so i think somewhere between `jj git push` and `jj git fetch` it has lost track of the fact that `unqytsxw` and `rqvskzow` are the same change.

**Describe the solution you'd like**
i would like jj to be able to tell when a change fetched from git is the same as a local change made natively with jj. i *think* that would make my `trunk()..mine()` filter work without more changes.

**Describe alternatives you've considered**
- a general purpose feature to combine all changes with identical description and diff. this could be interactive if people are worried about it being too broad.

**Additional context**
git lets you do `git fetch --prune`, which deletes local branches that were already deleted on the remote. that would solve the majority of my use case (in theory; in practice i usually forget to delete the branches on the remote). but jj doesn't filter out changes without a branch by default, and i would feel a little silly creating a branch for each change since that seems to explicitly recommended against in the docs.

**Comment by arxanas** [comment]
This might be somewhere else on the issue tracker as a `sync` command

**Comment by jyn514** [comment]
do you mean https://github.com/martinvonz/jj/issues/1039 ? i don't think that would do the same thing; it would rebase `unqytsxw`, but i don't think jj ever unifies a change with another change when rebasing? am i missing something?

**Comment by jyn514** [comment]
actually trying `jj rebase -d main@origin -r unqytsxw` gave me merge conflicts, which is exactly the opposite of what i want (not to think about merged changes).

**Comment by yuja** [comment]
> `jj branch delete binary-diff && jj git push --deleted` didn't help. so i think somewhere between `jj git push` and `jj git fetch` it has lost track of the fact that `unqytsxw` and `rqvskzow` are the same change.

If the branch is deleted at remotes, the subsequent `jj git fetch` (which is equivalent to `git fetch --prune`) would delete the local named branch, and abandon the commit.
(This behavior can be disabled by `git.abandon-unreachable-commits = false`.)

`jj branch delete` doesn't abandon the commits, so you'll need to do `jj abandon main..binary-diff` to delete both named branch ref and commits locally.

**Comment by jyn514** [comment]
ah, interesting. looks like that only works on the first fetch after, if i reset `unqytsxw` to its old position and run `jj git fetch` nothing happens. but that's ok, i know not to run `jj branch delete` for next time.

thanks!

**Comment by yuja** [comment]
Unreachable commits are determined by branch names, so it won't work if the local (and/or tracking remote) branch has been deleted. I think that's the limitation of the current git iterop where change ids aren't exchanged.

Also, the commits aren't abandoned if they are referenced by another ref or Git `HEAD`.
