### ISSUE TITLE
FR: support for case-insensitive file systems

### ISSUE THREAD

**Issue by mhammond** [martinvonz/jj#3039]
I'm enjoying jj on smaller repos, so thought I'd try it out on a larger one, gecko. This repo unfortunately has some confusion around the case of some files - in particular, one directory exists with 2 variations of case:

https://hg.mozilla.org/mozilla-central/file/tip/testing/web-platform/meta/WebIDL
https://hg.mozilla.org/mozilla-central/file/tip/testing/web-platform/meta/webidl

(please ignore the hg part, I'm accessing this via git via other magic, but this is the canonical repo)

On MacOS and Windows, it's necessary to set `git config core.ignorecase true`, causing git to fold these 2 directories into the same one. However, jj always records a working tree change for whatever entry does not match the current file-system. Eg, if I rename the folder in the working tree to be one of the variants, every other variant is marked as modified.

I can't find any jj config options in the docs which seem to help here.

Happy to provide any more information (and maybe even contribute if there is clear guidance on a direction and strategy)

**Comment by PhilipMetzger** [comment]
I think this is already reported as #1737, with the same reproducer.

**Comment by mhammond** [comment]
Ah, thank you, I failed to find that.
