### ISSUE TITLE
FR: Improve graph drawing (printing)

### ISSUE THREAD

**Issue by zummenix** [martinvonz/jj#3048]
**Is your feature request related to a problem? Please describe.**

I'm not sure if it is a bug or a feature. And even if it's a bug that needs fixing. Anyway, sometimes jj draws graphs similar to this one:
```
◉    Merge pull request #124 from stavares843/change-read-me
├─╮
│ ◉  Merge branch 'master' into change-read-me
╭─┤
◉ │  Created a new release (#122)
◉ │  Add option to create a custom data type (#121)
◉ │  Enable swift PM tests on Linux and macOS (#118)
◉ │  Created a new release (#117)
◉ │  Linux support (#116)
│ ◉  change: improve read me
├─╯
```

Please note the graph around `Merge branch 'master' into change-read-me` node.

**Describe the solution you'd like**

In this particular case I'd like it to look like this (or something similar):

```
◉    Merge pull request #124 from stavares843/change-read-me
├─╮
│ ◉  Merge branch 'master' into change-read-me
├─┤
◉ │  Created a new release (#122)
◉ │  Add option to create a custom data type (#121)
◉ │  Enable swift PM tests on Linux and macOS (#118)
◉ │  Created a new release (#117)
◉ │  Linux support (#116)
│ ◉  change: improve read me
├─╯
```

**Describe alternatives you've considered**

--

**Additional context**

This is the repo https://github.com/WeTransfer/Mocker from where I took the example. I've noticed similar cases at my work but I can't share it.

**Comment by martinvonz** [comment]
I think the reason for that is to make it clearer which direction the line goes. In your version of the graph, one might think that the top commit is a merge of "Created a new release (#122)" and "change: improve read me".

**Comment by zummenix** [comment]
That's a good point! What do you feel about this variant?

```
◉    Merge pull request #124 from stavares843/change-read-me
╰─╮
  ◉  Merge branch 'master' into change-read-me
╭─┤
◉ │  Created a new release (#122)
```

**Comment by joyously** [comment]
I'm glad someone pointed out the difference, because I couldn't see it until then.
At first, I liked the proposed variant since the branches are merged, but it misrepresents the master branch a little, doesn't it?

**Comment by martinvonz** [comment]
> At first, I liked the proposed variant since the branches are merged, but it misrepresents the master branch a little, doesn't it?

Yes, I think it makes it look like "Merge pull request #124 from stavares843/change-read-me" has a single parent.

**Comment by zummenix** [comment]
> At first, I liked the proposed variant since the branches are merged, but it misrepresents the master branch a little, doesn't it?

I suppose, yes.

I managed to find another interesting case at work. Here is the redacted version:
```
◉    Merge branch 'promotions' into 'master'
├─╮
│ ◉  promotions commit 3
│ ◉  promotions commit 2
│ ◉  promotions commit 1
◉ │  Merge branch 'fix-infinite-loader' into 'master'
├─╮
◉ │  fix-infinite-loader commit
├─╯
◉    Merge branch 'fix-magnitude' into 'master'
├─╮
│ ◉  fix-magnitude commit
├─╯
◉    Merge branch 'up-version' into 'master'
```

1.  It is a little confusing around `Merge branch 'fix-infinite-loader' into 'master'`. I'm thinking – where does the `promotions` branch start?
2. Strangeness around `fix-infinite-loader commit` node. It looks like the commit is in the `master` branch but it is actually in the `fix-infinite-loader` branch. But previous `fix-magnitude commit` is shown correctly.

**Comment by martinvonz** [comment]
Git and jj don't have any permanent tracking of which branch a commit is on. In Git's terminology, the "fix-infinite-loader commit" commit is in the `master` branch because all ancestors of the branch pointer (i.e. all commits leading up to it) are considered to be in the branch. A commit can be in multiple branches.

I think we generally draw the first parent of a merge on the left. Maybe what happened with the "fix-infinite-loader commit" is that the edge to its parent was already in the graph because "promotions commit 1" also has that edge. So maybe that's why it didn't get drawn on the right like "fix-magnitude commit".

So I think this is WAI. I'm not sure there's anything we want to change here. I'll close this but feel free to reopen if you think I missed anything.
