### ISSUE TITLE
gitignore panic on directory names that contain curly braces 

### ISSUE THREAD

**Issue by fleimgruber** [martinvonz/jj#3064]
## Description

Initializing a jj repo from an existing git repo fails in gitignore related checks if directory file names contain curly braces.

## Steps to Reproduce the Problem

1. `git clone git@github.com:drivendata/cookiecutter-data-science.git`
2. Create a global `.gitignore` file containing `__pycache__`
3. `jj git init --git-repo=.`

`.jj` gets created, but subsequent jj commands, e.g. `jj log`, also lead to the panic.

## Expected Behavior

No thread panic

## Actual Behavior

This gets printed to terminal:

```
Done importing changes from the underlying Git repo.
thread '<unnamed>' panicked at lib\src\gitignore.rs:139:40:
called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    ^{{ cookiecutter.repo_name }}/(.*/)?__pycache__/.*
      ^
error: repetition quantifier expects a valid decimal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
```

## Specifications

- Platform: Windows 10
- Version: jj 0.14.0

**Comment by daehyeok** [comment]
#3071 will fix this bug.
