### ISSUE TITLE
FR: Support shell command aliases

### ISSUE THREAD

**Issue by yjyao** [martinvonz/jj#3082]
**Is your feature request related to a problem? Please describe.**
the `aliases` in `jj`'s config can only run `jj` subcommands.

**Describe the solution you'd like**
to be able to configure an alias that runs a shell command. both git and mercurial support this. with this, one can chain multiple `jj` commands with one alias, which i don't think is possible with today's `jj` aliases.

**Comment by yuja** [comment]
Related discussion in https://github.com/martinvonz/jj/issues/3001
