### ISSUE TITLE
`jj diff` wraps prematurely when paging with `delta`

### ISSUE THREAD

**Issue by dustypomerleau** [martinvonz/jj#3090]
## Description

Thanks for all your hard work on `jj`!

I'm struggling to get my git pager to display normally in combination with `jj diff`:

## Steps to Reproduce the Problem

1. install [`delta`](https://github.com/dandavison/delta)
1. in `config.toml` set `ui.diff.tool = "delta"`
1. in `gitconfig [core]` set `pager = delta`
1. compare output from `jj diff` to output from `git diff`

## Expected Behavior

Full width of the terminal should be used to display the diff.

## Actual Behavior

`git diff` uses all of the available space, but `jj diff` does not (see screenshot).

## Specifications

- Platform: macOS 14.4
- Version: `jj` 0.14.0, `delta` 0.16.5

<img width="1674" alt="Screenshot 2024-02-17 at 18 43 16" src="https://github.com/martinvonz/jj/assets/6304651/e8d38329-cc2d-4419-815a-ea6ac039e090">

**Comment by yuja** [comment]
> 2. in `config.toml` set `ui.diff.tool = "delta"`

You'll probably need to set `delta` as the pager (not the diff command.) See https://github.com/martinvonz/jj/issues/1194

`ui.diff.tool` is the command to produce text diff of two directories.

**Comment by dustypomerleau** [comment]
Ah, it works! Thanks so much for your time, @yuja.
