### ISSUE TITLE
FR: Override default diff/merge editor without resorting to `--config-toml "ui.{diff,merge}-editor=…"`

### ISSUE THREAD

**Issue by amiryal** [martinvonz/jj#3102]
I like having the full comfort of `meld-3` with the mouse and a GUI, but sometimes I need to pick just a small thing and stay in the terminal with both hands on the keyboard. For all the commands that refer to `ui.diff.tool` in the configuration, we already have the `--tool` option to override it, e.g. with `--tool :builtin` to stay in the terminal.

The feature request is to add similar `--tool` options for overriding `ui.diff-editor` and `ui.merge-editor` (as appropriate) to all of the commands that refer to them.

**Comment by yuja** [comment]
Duplicates of #2575. For now, you could use command `[aliases]`
