### ISSUE TITLE
FR: `jj branch list --tracked`

### ISSUE THREAD

**Issue by PhilipMetzger** [martinvonz/jj#3105]
**Is your feature request related to a problem? Please describe.**
It has come up in Discord that we have no way of listing just the tracked branches, which is useful information if you use `jj` in a primarily branching oriented workflow.  

**Describe the solution you'd like**
Implement `jj branch list --tracked` to display all tracked branches.

**Comment by timcki** [comment]
Hi! This seems like a good first issue I'd love to tackle if no one started working on it yet ((:

**Comment by martinvonz** [comment]
I haven't heard anything from anyone, so feel free. Thanks!

**Comment by prscoelho** [comment]
I had started it, [some discussion here](https://discord.com/channels/968932220549103686/1209571976578990161), but it's totally fine if you want to pick it up.

I had some questions which may be helpful:

- should git remote be shown here? collocated git repos will have a remote tracking `branch@git` for all local branches
- would it be preferred to take in a list of remotes like: `jj branch list --tracked origin` to list all currently tracked `@origin`?
