### ISSUE TITLE
FR: Display rebase instructions in status

### ISSUE THREAD

**Issue by NoahTheDuke** [martinvonz/jj#3108]
**Is your feature request related to a problem? Please describe.**

`jj rebase` requires a number of steps to properly resolve conflicts. When it is first run and a conflict is encountered, it displays the steps needed. However, unless they're copied elsewhere, they can be lost (clearing terminal window, running a command that pushes them out of terminal window history, etc). Unless the user knows those steps by heart, or knows where to find them in the documentation, this can lead to confusion and incorrect state.

Anonymized example from discord:

```
New conflicts appeared in these commits:
  zypwvlpt 19d36876 main* | (conflict) Do one thing.
  krznntxs ee1cb33d (conflict) Do another thing.
  mknzsumx 1ff0f052 branch-1* | (conflict) Do a third thing.
To resolve the conflicts, start by updating to the first one:
  jj new mknzsumxuxto
Then use `jj resolve`, or edit the conflict markers in the file directly.
Once the conflicts are resolved, you may want inspect the result with `jj diff`.
Then run `jj squash` to move the resolution into the conflicted commit.
```

**Describe the solution you'd like**

Display the current state of the rebase in `jj status`, along with the steps to take.

**Describe alternatives you've considered**

- Do nothing. Always the easiest solution. (`jj gud`, as the kids say.)
- Add a command that displays the tips.
- Disallow doing anything else until the rebase/conflict is resolved.

**Additional context**

N/A

**Comment by ilyagr** [comment]
As I mentioned on Discord, I think it'd be nice to store *all* user-facing messages in in the operations log (perhaps with some garbage collection) and be able to replay them. This would also be relevant for transient error messages while snapshotting, importing git refs, etc.

This would only apply to mutating operations (including snapshotting, which is stored in the op log), but I think that's fine.

**Comment by poliorcetics** [comment]
I've made a PR for this, @NoahTheDuke could you take a look to see if it fixes your issue :) ?

**Comment by NoahTheDuke** [comment]
I don't run HEAD right now, but from reading the code, that looks like it would be helpful.

**Comment by NoahTheDuke** [comment]
@poliorcetics thank you for implementing this!
