### ISSUE TITLE
FR: A revset to determine the main branch in a repository.

### ISSUE THREAD

**Issue by PhilipMetzger** [martinvonz/jj#3113]
**Is your feature request related to a problem? Please describe.**
Add a revset to determine the quasi main "branch" in a repository, similar to `immutable_heads()`.

**Describe the solution you'd like**
Add some repo- and user setting to determine a main branch in a repository, as it will be useful for the `jj` native forge.
As it probably won't be as branching oriented as Git is. 

**Additional context**
This was previously a hidden FR in #1431.

**Comment by PhilipMetzger** [comment]
Anothre issue which relates to this is #1415.

**Comment by thoughtpolice** [comment]
Isn't this just `trunk()`?

**Comment by PhilipMetzger** [comment]
No, `trunk()` is a approximation to work with Git :-), this one is independant of backend.

**Comment by yuja** [comment]
> No, `trunk()` is a approximation to work with Git :-), this one is independant of backend.

In what way `trunk()` is Git specific? If there's a `jj` native repo, I expect `trunk()` will be resolved to the main branch in that context. If the branching model is quite different from `::<head-commit-of-the-main-branch>`, `trunk()` wouldn't work, though.

**Comment by martinvonz** [comment]
I also don't understand what this FR is about. FWIW, we have overridden `trunk` at Google to count `main@piper` as our trunk (`piper` is the name of our internal, non-Git remote).

**Comment by PhilipMetzger** [comment]
I made some mistakes yesterday, as mentioned `trunk()` adresses this issue, so I'm closing it.
