### ISSUE TITLE
FR: Add `\x01` and `\x02` to the color formats to support `$PS1`

### ISSUE THREAD

**Issue by yjyao** [martinvonz/jj#3155]
**Is your feature request related to a problem? Please describe.**
i was trying to use `jj --ignore-working-copy log --no-graph -l1 -r @ -T '...'` to build a `$PS1` prompt. however, the coloring confuses the readline length calculation because of lack of `\x01`/`\x02` (or `\[`/`\]`) control characters.

**Describe the solution you'd like**
always wrap color control codes with `\x01`/`\x02` --- unless that would cause any problem?

**Describe alternatives you've considered**
create a dedicated `$PS1`-generator like how Git has `__git_ps1`.

**Comment by martinvonz** [comment]
I'm not familiar with `\x01`/`\x02`. Do you mean that we should just print those two bytes before/after color codes? How is the terminal supposed to treat them? Can you link to the spec? Is it well supported?

**Comment by yuja** [comment]
Appears that `less` visualizes these control chars, so it's not an option to change the default `--color` behavior.
```sh
% printf '\x01' | less -FRX
^A
```

Another way around is to make templater parse `\x<hex>` escapes and let user insert `\x01\x1b[m`, etc. manually.

**Comment by yjyao** [comment]
actually this is a non-issue. i wasn't thinking straight. apparently i can just generate the `'\x01'` and `'\e'` strings in the template and then evaluate them in PS1...

1. use `jj log -l1--color never -T '"\\e[32m" ++ "hey" ++ "\\e[0m"'` to create the string `\e[32mhey\e[0m`.
2. use `printf '%b'` (or `echo -e`) to print it.

and with jj's support on custom functions, creating these templates is very neat:

```shell
echo -e "$(jj --ignore-working-copy --color never log -l1 -r @ --no-graph --config-toml "
[template-aliases]
'colored(color, txt)' = '''
  surround('\x01\e[' ++ color ++ 'm\x02', '\x01\e[0m\x02', txt)
'''
'red(txt)'     = '''colored('31', txt)'''
'green(txt)'   = '''colored('32', txt)'''
'yellow(txt)'  = '''colored('33', txt)'''
'blue(txt)'    = '''colored('34', txt)'''
'magenta(txt)' = '''colored('35', txt)'''
'cyan(txt)'    = '''colored('36', txt)'''
'white(txt)'   = '''colored('37', txt)'''
" -T '
green(change_id.shortest())
'
```

feel free to close this ticket i guess.
