### ISSUE TITLE
FR: Add a function or set of functions to the template language to be able to format or pad strings

### ISSUE THREAD

**Issue by zummenix** [martinvonz/jj#3183]
**Is your feature request related to a problem? Please describe.**

I'm playing with my own log template and trying to configure it to my liking. I've come to the point that I'd like to make the log output to look like a table (sort of). Specifically, I'd like to trim and pad long usernames (See the desired output in "Solution" section below).

**Describe the solution you'd like**

Maybe a set of functions on `String`? (the naming is discussable)

- `lpad(padding: String, len: Int) -> String` – make the length of a string to be greater or equal to `len` by adding `padding` on the left side
- `rpad(padding: String, len: Int) -> String` – make the length of a string to be greater or equal to `len` by adding `padding` on the right side
- `lclamp(prefix: String, len: Int) -> String` – make the string to not exceed `len` on the left side and adding `prefix` if it does
- `rclamp(suffix: String, len: Int) -> String` – make the string to not exceed `len` on the right side and adding `suffix` if it does

Example usage for my use case: `author.username().rclamp("…", 11).rpad(" ", 12)`

With this I'll be able to make the following log output (note `username` "field"):

```
@  2024-03-02 11:55 zummenix     xpzvslnz (empty) (no description set)
◉  2024-03-02 06:31 yuya         xnmuzvwm merge_tools: extract configuration error to separate type main HEAD@git
◉  2024-03-02 06:31 yuya         lkwokwtr merge_tools: load diff/merge editor settings by caller
◉  2024-03-02 06:31 yuya         nnzmkuom merge_tools: introduce Diff/MergeEditor newtypes
◉  2024-03-02 06:31 yuya         ppuxklvu merge_tools: process "ui.diff-instructions" option by caller
◉  2024-03-02 06:31 yuya         yvklwytm merge_tools: take diff editor instruction as Option<&str>
◉  2024-03-02 06:31 yuya         lklulkoy merge_tools: don't enable fsmonitor (and file size limit) in temporary snapshot
◉  2024-03-01 21:29 49699333+d…  ylmllwpm cargo: bump the cargo-dependencies group with 1 update
◉  2024-03-01 20:42 dploch       wqmpowkl commit_templater: support extensions of the template language
◉  2024-03-01 20:42 dploch       xskwpskt commit_templater: make a bunch of types public for extensions
◉  2024-03-01 20:42 dploch       mxownsql template_builder: support extending the core template build fn table
◉  2024-03-01 20:00 emesterhaz…  qrptmkwx Add test cases where HexPrefix::new fails due to invalid inputs
```

**Describe alternatives you've considered**

The closest alternative I've come up with is to use `String.substr` template function but of course it doesn't add padding.

**Additional context**

--

**Comment by yuja** [comment]
> Maybe a set of functions on `String`? (the naming is discussable)

Perhaps, it will be a global function similar to `fill(width, content)`. `author` isn't of `String` type for example, but it makes sense to pad/truncate `author` to a certain width.

I have no idea about naming and granularity. It might be a formatting mini language, something like `format("{:<10} {}", foo, bar)`.
