### ISSUE TITLE
gitignore barfs hard on invalid lines

### ISSUE THREAD

**Issue by lukegb** [martinvonz/jj#3185]
## Description

https://gitlab.com/baserow/baserow's gitignore has this line:

```gitignore
^plugin-boilerplate/{{ cookiecutter.project_slug }}/(.*/)?\.DS_Store(/.*|$)
```

because they have a `plugin-boilerplate/{{ cookiecutter.project_slug }}/` directory.

This makes jj very unhappy:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    ^plugin-boilerplate/{{ cookiecutter.project_slug }}/(.*/)?\.DS_Store(/.*|$)
                         ^
error: repetition quantifier expects a valid decimal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', lib/src/gitignore.rs:139:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Steps to Reproduce the Problem

1. jj git clone https://gitlab.com/baserow/baserow.git
1. cd baserow
1. jj status

## Expected Behavior

jj works, maybe?

## Actual Behavior

jj panicks.

## Specifications

- Platform: Linux
- Version: 0.14.0 (and 0.13.0)

**Comment by yuja** [comment]
Duplicates of #3064. The fix will be included in the next release.
