### ISSUE TITLE
README refers to deprecated `checkout`

### ISSUE THREAD

**Issue by joyously** [martinvonz/jj#3209]
## Description
Although the `checkout` command was deprecated, the README.md file explains using the "checkout" concept in 3 places. 
Also, the screenshot examples use `co` alias.

## Expected Behavior
The README explains in terms of the latest commands.

## Actual Behavior
The README explains in old terms.

## Specifications

- Version: 0.14.0

**Comment by Zambito1** [comment]
The 5th screenshot also refers to `merge`

**Comment by ilyagr** [comment]
Fixing this would involve adjusting the scripts in https://github.com/martinvonz/jj/tree/main/demos and then re-running https://github.com/martinvonz/jj/blob/main/demos/run_scripts.sh. I'll hopefully get to it at some point if nobody beats me to it.

**Comment by ilyagr** [comment]
This is also related to the renewed discussion in https://github.com/martinvonz/jj/pull/2842

**Comment by ilyagr** [comment]
In my mind, this is currently blocked on the decision of whether to turn on https://github.com/martinvonz/jj/pull/3501 by default.
