### ISSUE TITLE
jj should be more paranoid about users with no configured username/email

### ISSUE THREAD

**Issue by durin42** [martinvonz/jj#322]
## Description

If you're starting to use jj on a new machine (or using it for the first time) it's _likely_ you'll start out with no jjconfig.toml anywhere, do some work, then try to close the revision and be told to identify yourself to the tool. Sadly, if you do things in that order, you end up with a valid committer name but no author name, which is still a bad experience (I just had to force-push a PR to a project after doing surgery in git because I tripped on this).

## Steps to Reproduce the Problem

1. `cargo build --release jj && cp target/release/jj $SOMEPLACE_ON_PATH`
1. Do stuff with `jj`
1. `jj close`
2. Be sad, create `~/.jjconfig.toml` with user/email config
3. `jj close && jj git push ...`
4. Notice the new commit has your committer info but not your author info

## Expected Behavior
Honestly I think even working copy snapshots should outright fail if there's no author, but that's also a pretty huge speedbump to initial experimentation. Maybe if we're closing a commit with the magic no-user strings, stamp in the committer name once it's valid?

## Actual Behavior
As above

## Specifications

- Platform: macOS
- Version: 6c83eb6ae3c56f1912a630dca4751c7f723a81a3

**Comment by durin42** [comment]
Also: I couldn't figure out how to rewrite the author name in `jj`, which is something I probably do at least monthly in `git`? I gave up and used `git` today, but it'd be nice to not have to break the glass.

**Comment by martinvonz** [comment]
> Honestly I think even working copy snapshots should outright fail if there's no author, but that's also a pretty huge speedbump to initial experimentation.

Yes, that's how it was initially and it was indeed a huge speedbump (reported by our friend Pulkit, IIRC).

> Maybe if we're closing a commit with the magic no-user strings, stamp in the committer name once it's valid?

Yes, that makes sense. We should also prevent pushing these commits (if they get past the on-close check).
