### ISSUE TITLE
Need a way of setting name/email/timestamp for author/committer

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#328]
## Description

We need a way to override metadata on commits. In Git and Mercurial, the natural place to do that is when amending. Mercurial also has the `metaedit` extension for editing commit information. Perhaps we could copy that name? We could also put it on `describe`, but that's probably not where users would look for this feature?

## Specifications

- Version: 0.4.0

**Comment by yuja** [comment]
I don't know if `metaedit` is discoverable name, but maybe `describe` could be
aliased to that command. I tend to use `describe` to fix up commit message of 
earlier revisions, which is basically what `hg metaedit` would do.

**Comment by martinvonz** [comment]
We should also consider how to copy a description or a change ID from another commit. Maybe all this functionality can be provided by the same command.

**Comment by dbarnett** [comment]
FWIW, I did expect `jj describe` to help me update author, or at least to point me to a related command that did from `jj help describe`.

As a workaround, what's the simplest workflow to do this with existing commands? Best I found was:
```
jj co somecommit-
jj restore --from somecommit
jj describe -m 'Description from somecommit'
```

**Comment by martinvonz** [comment]
I think that's the best we have.

Thinking more about the command, maybe `describe` is the best place to put it. If we had a separate `metaedit` command, then it would be weird for that to not be able for setting the description. And if it could do all that `describe` can (and more), then why would we have `describe`? So maybe `describe` is the best place, maybe adding `metaedit` as an alias? `jj help describe` currently says "Edit the change description". We could just change that to something like "Set the change description or other metadata".

**Comment by joyously** [comment]
Both Git and Bazaar put this on the `commit` command as a flag.

**Comment by dbarnett** [comment]
Where in jj you don't use a `commit` command but `describe` is the nearest equivalent, right?

**Comment by martinvonz** [comment]
Yes, putting the functionality in `describe` is still my best bet.

**Comment by martinvonz** [comment]
There's now `jj describe --reset-author` (added in #1395).

**Comment by dbarnett** [comment]
Can we call this Fixed?

Between `--reset-author` & `--no-edit` and env vars, seems like you've nicely covered "a way of setting name/email/timestamp". You can reset name/email using `--reset-author` (or even set them to arbitrary values using `JJ_USER=foo JJ_EMAIL="me@example.com" jj describe --reset-author --no-edit`), and timestamp can be bumped the same way.

**Comment by martinvonz** [comment]
I left it open because I had not added a `--author-name="Some One"` option, but I think you're right that we can having the user pass those values via environment variables (or config options) is good enough for now. Thanks for pointing that out.

**Comment by gasche** [comment]
I spent ten minutes looking for how to specify/change the author of a jj change -- I find it very surprising in particular that `jj describe` does not let us do this. I finally gave up, assumed that it was not possible, and decided to look for issues discussing this.

It looks like the workaround above can be used:

    JJ_USER=foo JJ_EMAIL="me@example.com" jj describe --reset-author --no-edit

but this is not documented anywhere that I could find except here, which means that the feature is not at all discoverable. (Question: what kind of `jj help ...` command can I use to learn about those JJ_* environment variables?)

I think that a good first step would be to show exactly this example in the documentation of `--reset-author`. But I also believe that adding explicit `describe` options to set the author would be nice.

**Comment by martinvonz** [comment]
> I think that a good first step would be to show exactly this example in the documentation of `--reset-author`. But I also believe that adding explicit `describe` options to set the author would be nice.

That sounds good to me. Do you think you can find time to implement it?

> (Question: what kind of `jj help ...` command can I use to learn about those JJ_* environment variables?)

I don't think it's documented anywhere yet :( Maybe it should be documented in https://martinvonz.github.io/jj/v0.12.0/config/#user-settings. We have documentation of how `$JJ_EDITOR` overrides `ui.editor` there, so it seems consistent to document how `$JJ_USER/$JJ_EMAIL` work there.

**Comment by toddjonker** [comment]
Was the `describe --reset-author` reverted?  I'm seeking this feature, but that option doesn't exist in 0.45.1

**Comment by scott2000** [comment]
I believe it's been replaced by `jj metaedit`, which has a `--update-author` and `--update-author-timestamp` option.
