### ISSUE TITLE
FR: date/timestamp based revset queries

### ISSUE THREAD

**Issue by farnoy** [martinvonz/jj#3287]
**Is your feature request related to a problem? Please describe.**
To quickly browse logs in a given timeframe, it would be helpful to have extra revset queries available.

**Describe the solution you'd like**
`commited_on(5 days ago)` `authored_on(2020-01-01)`, similar time formats as in gitrevisions(7)?

This way, I could do `commited_on(2020-01-01)::committed_on(2020-12-31)` and get a fixed window of time.

**Describe alternatives you've considered**
I initially thought of `before(date)` but I don't think that's necessary when combined with other expressions.

**Additional context**
-

**Comment by yuja** [comment]
> This way, I could do `commited_on(2020-01-01)::committed_on(2020-12-31)` and get a fixed window of time.

If `commited_on(2020-01-01)` means `2020-01-01 00:00:00 to 23:59:59`, the DAG range `::` wouldn't work. There may be no revisions committed within the time range.

I think the syntax proposed by @arxanas is pretty good. It's similar to the string pattern syntax we already have.
https://github.com/arxanas/git-branchless/wiki/Reference:-Revsets#patterns

We'll need a time range internally to represent "N days ago" anyway.

**Comment by arxanas** [comment]
Some relevant discussion here: https://discord.com/channels/968932220549103686/968932220549103689/threads/1206776912542703706

**Comment by ChrisPenner** [comment]
I'd love something like this for filtering down my default log revset; I want to see the full changesets for any branch I've edited within the last 30 days or w/e

**Comment by jennings** [comment]
Added in #3887.

```
jj log -r 'committer_date(after:"3 days ago")'
jj log -r 'committer_date(before:"2024-01-01")'
jj log -r 'author_date(after:"2024-03-25 12:56")'
```
