### ISSUE TITLE
Concerning reindexing warning after upgrade

### ISSUE THREAD

**Issue by prattmic** [martinvonz/jj#3323]
## Description

When upgrading to a new version of jj with a changed index format, jj reindexes after failing to read the old index. The warning printed in this case is rather concerning. Having experienced corrupt git repos, this message definitely gave me a second of horror that things were really screwed up.

## Steps to Reproduce the Problem

1. Create a repo with an older version of jj
1. Upgrade to a newer version of jj with a changed index
1. Run `jj st`

(I'm unsure exactly which before/after versions caused this specific message for me.)

## Expected Behavior

jj prints an unconcerning reindexing message. 

Suggestion: perhaps the jj index could record its version somewhere (if it doesn't already), and then when encountering an error on an old index it softens the message to something like:

```
Outdated index version v0.13, expected v0.14. Reindexing...
```

Or even no message at all if the user doesn't need to know. Though if reindexing can be slow that may be a good reason to keep.

## Actual Behavior

```
Failed to load commit index file 'db4e8c6c3a17cea4b02f29dc06574125bd8fbd6e7811583b36da75a9083a3edac65a97f426d2fefe80a86a0bff46b3128a436f8135d77278417500731289959f' (maybe the format has changed): No such file or directory (os error 2). Reindexing...
```

## Specifications

- Platform: linux-amd64
- Version: Internal unstable version

**Comment by PhilipMetzger** [comment]
The message recently moved from stdout to stderr in https://github.com/martinvonz/jj/commit/1f6d1de62d718869d10da8c2a07eb2ee3b436b75. So this should be fixed in a recent ToT version.

**Comment by martinvonz** [comment]
The message @prattmic is actually the new message. I'll see if I can make the message less scary.
