### ISSUE TITLE
jj 0.15.0 and 0.15.1 do not pass tests on openSUSE

### ISSUE THREAD

**Issue by johanneskastl** [martinvonz/jj#3329]
## Description
I am packaging jj for openSUSE. Since 0.15.0 the checks do not succeed, 0.15.1 does not fix this.

Not sure if this is an issue in jj or in openSUSE. But as this also hits openSUSE Leap 15.5, which is not using versions of rust-related tools as up to date as Tumbleweed, I suspect this might be in jj.

If there is additional information I should provide, please reach out to me.

Kind Regards
Johannes

## Steps to Reproduce the Problem

1. Compile the binary.
1. Run `cargo test --offline --no-fail-fast`, see the [RPM macro](https://github.com/Firstyear/cargo-packaging/blob/main/macros.cargo#L20)
1. Tests are failing.

## Expected Behavior
Tests should succeed like before

## Actual Behavior

```
[...]
[ 1900s]
[ 1900s] failures:
[ 1900s]
[ 1900s] ---- test_ssh_signing::ssh_signing_bad_allowed_signers stdout ----
[ 1900s] thread 'test_ssh_signing::ssh_signing_bad_allowed_signers' panicked at lib/tests/test_ssh_signing.rs:145:10:
[ 1900s] called `Result::unwrap()` on an `Err` value: Backend(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
[ 1900s]
[ 1900s] ---- test_ssh_signing::ssh_signing_missing_allowed_signers stdout ----
[ 1900s] thread 'test_ssh_signing::ssh_signing_missing_allowed_signers' panicked at lib/tests/test_ssh_signing.rs:162:10:
[ 1900s] called `Result::unwrap()` on an `Err` value: Backend(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
[ 1900s]
[ 1900s] ---- test_ssh_signing::ssh_signing_roundtrip stdout ----
[ 1900s] thread 'test_ssh_signing::ssh_signing_roundtrip' panicked at lib/tests/test_ssh_signing.rs:123:10:
[ 1900s] called `Result::unwrap()` on an `Err` value: Backend(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
[ 1900s]
[ 1900s]
[ 1900s] failures:
[ 1900s]     test_ssh_signing::ssh_signing_bad_allowed_signers
[ 1900s]     test_ssh_signing::ssh_signing_missing_allowed_signers
[ 1900s]     test_ssh_signing::ssh_signing_roundtrip
[ 1900s]
[ 1900s] test result: FAILED. 307 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.88s
[ 1900s]
[ 1900s] error: test failed, to rerun pass `-p jj-lib --test runner`
[ 1900s]      Running unittests src/lib.rs (target/debug/deps/jj_lib_proc_macros-3d1cc922ae618c4e)
[ 1900s]
[ 1900s] running 0 tests
[ 1900s]
[ 1900s] test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
[ 1900s]
[ 1900s]      Running unittests src/lib.rs (target/debug/deps/testutils-31d3b4136baf59e0)
[ 1900s]
[ 1900s] running 0 tests
[ 1900s]
[ 1900s] test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
[ 1900s]
[ 1900s]    Doc-tests jj-cli
[ 1902s]
[ 1902s] running 1 test
[ 1902s] test cli/src/generic_templater.rs - generic_templater::GenericTemplateLanguage<'a,C>::add_keyword (line 60) ... ignored
[ 1902s]
[ 1902s] test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
[ 1902s]
[ 1902s]    Doc-tests jj-lib
[ 1903s]
[ 1903s] running 1 test
[ 1903s] test lib/src/signing.rs - signing::SigningBackend::verify (line 96) ... ignored
[ 1903s]
[ 1903s] test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
[ 1903s]
[ 1903s]    Doc-tests jj-lib-proc-macros
[ 1904s]
[ 1904s] running 0 tests
[ 1904s]
[ 1904s] test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

## Specifications

- Platform: openSUSE Tumbleweed 64bit, Leap 15.5, Leap 15.6 beta, ...

**Comment by ilyagr** [comment]
I've seen similar errors when running on systems without gpg installed.

I thought we made those tests not run without gpg, but that might not be in 0.15.1.

**Comment by thoughtpolice** [comment]
It looks like these tests need `ssh-keygen` in `$PATH`, among other things: https://github.com/martinvonz/jj/blob/1ec6a8f92d4f9bf75285c6ceaf9ae628b52baba5/lib/tests/test_ssh_signing.rs#L108

Can you link the rpm spec for the SUSE package? Perhaps you just need to include `gpg` and `ssh` packages as build-time dependencies? (They are also runtime dependencies for signing but I'm not sure if it's necessary to specify that frankly.)

**Comment by johanneskastl** [comment]
Thanks @ilyagr  @thoughtpolice,

I am currently checking whether the tests succeed once gnupg is present, will also check for ssh-keygen.

Thanks for the hints.

**Comment by johanneskastl** [comment]
OK, adding gnupg and openssh-common solved the issue. Thanks for the help!
