### ISSUE TITLE
FR: `jj backout` should be able to revert an entire series of revisions

### ISSUE THREAD

**Issue by thoughtpolice** [martinvonz/jj#3339]
It's useful to occasionally not just backout one commit, but a series that landed and ultimately caused regressions. At the moment, `jj backout` takes exactly one revision, so doing this requires scripting around `jj log` in your shell to get the revisions.

Realistically speaking, this means that `jj backout -r` should take a revset, much like `jj abandon` does.

There are some edge cases to handle I think, because you need to effectively resolve the union of all provided revsets, then for any changes that are determined to have a parent/child relationship, you need to back them out in reverse order. But I don't think this would be too hard, so I'm tagging this with "good first issue" for anyone who wants to try it.

**Comment by arxanas** [comment]
There might also be a cool "anti-absorb" feature where backout reverts a provided set of commits, as well as all of their dependent patches automatically. This is occasionally useful when you need to revert something urgently, but some amount of dependent stuff has already landed (that you're not specifically aware of), and you don't want to roll back *everyone's* commits.

**Comment by khionu** [comment]
There's a conceptual overlap with this and #3428. Might be good at looking at how they could complement each other later, maybe by allowing backout to take a waypoint identifier.

**Comment by necauqua** [comment]
I don't think so?.

> by allowing backout to take a waypoint identifier

What would that mean?

Backout creates a commit that's an inverse of it's argument, and this FR is for it to also work as an inverse of a union of commits matched by a revset.

Oplog waypoint is just a human-readable name for an oplog entry basically, so how would the backout comment interact with an operation argument?.

Operation being "the state of the entire repo at some point in the past" - not a single working tree, that's just a commit, but the entire commit graph itself
