### ISSUE TITLE
FR: rebase should skip rewriting commit if it's a no-op 

### ISSUE THREAD

**Issue by colemickens** [martinvonz/jj#3365]
**Is your feature request related to a problem? Please describe.**

Hi,

I run this regularly to make sure my nixpkgs is updated/rebased:

```
jj git fetch --all-remotes;
jj rebase -b cmpkgs -d nixos-unstable@nixos;
jj git push -b cmpkgs
```

However, this ALWAYS results in a new commit, even if no actual rebase is necessary

**Describe the solution you'd like**
`jj` notices, like `git` does, that no actual changes are needed.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bnjmnt4n** [comment]
I've put up a PR for this at #3367. In that implementation, I only check commits explicitly passed to the `jj rebase` command to skip rewrites. I'm not sure if this check should be performed at the descendant rebaser's level instead?

**Comment by martinvonz** [comment]
Yes, I agree. I think it's best to let the automatic rebasing behavior in `DescendantRebaser` not have much logic and instead have individual commands like `jj rebase` decide when to skip a step.

**Comment by bnjmnt4n** [comment]
I'm not sure what the behavior of rebase for `-r` should be if the revision is already on the destination. If the revision contains children, the current implementation will rebase the revision's children onto the revision's parent. Even if we skip updating of the given revision to avoid changing its commit ID, should its children still be rebased onto its parent?

This isn't an issue for `-s` and `-b`, since all descendants will be shifted along with the original commit.

**Comment by martinvonz** [comment]
> Even if we skip updating of the given revision to avoid changing its commit ID, should its children still be rebased onto its parent?

Good catch. I think children definitely should be rebased. I think we want this PR to just avoid rebasing if it would effectively be a no-op (except that commit ids change), but that's not the case for `-r`.

**Comment by colemickens** [comment]
Hm, maybe I'm missing a fine detail or misunderstood that sentence, but the scenario I'm thinking of in git -- the noop does not rewrite commit ids, which is kind of my motivation here.

**Comment by martinvonz** [comment]
I think we agree. When I said "effectively be a no-op (except that commit ids change)", I was talking about behavior *before* this PR. I was saying that the behavior where, loosely speaking, the commit graph looks the same afterwards - and *only* then - should this PR make it actually a no-op.
