### ISSUE TITLE
FR: Add a revset for heads of other local workspaces

### ISSUE THREAD

**Issue by Zoybean** [martinvonz/jj#3384]
**Is your feature request related to a problem? Please describe.**
I do not use workspaces (yet), but I expect that if I did, I might like for a workspace's working-copy commit to be immutable from other workspaces, as I know that editing the head of one workspace from another will cause that workspace's copy to become [stale](https://martinvonz.github.io/jj/v0.15.1/working-copy/#stale-working-copy), requiring a manual step to re-sync. This seems like something I'd prefer to avoid (though maybe it is not as much an issue as I am expecting).

The only barrier to me making them immutable, is the lack of a revset referring to those commits, as I know I can configure `immutable_heads()` myself.

**Describe the solution you'd like**
Define a revset, e.g. `workspace_working_copy()` that refers to the working-copy commits of any workspaces, or `foreign_working_copy()` for the working-copy commits of other workspaces. (Adding one would allow configuring an alias for the other)

**Describe alternatives you've considered**
None

**Additional context**
I'm very new to `jj`. Maybe this feature is needless, or already exists in some form.

**Comment by yuja** [comment]
Templater has `working_copies`, but apparently revset doesn't. It should be easy to add the one.

**Comment by ckoehler** [comment]
Implemented by [7bde6dd](https://github.com/martinvonz/jj/commit/7bde6ddc2994a470ea315b26ac05f6016c5636a7)
