### ISSUE TITLE
FR: Add a way to get a list of changed files in specified revisions

### ISSUE THREAD

**Issue by marcinjahn** [martinvonz/jj#3385]
**Is your feature request related to a problem? Please describe.**
Some tools (e.g. linters) need a list of files to operate on. When working on some branch, it's useful to only lint files that got changed between the current branch and trunk. 

**Describe the solution you'd like**
Something similar to `git show --pretty="" --name-only <SHA>` would be pretty useful. Additionally, an option to separate file names by spaces, and not new lines would also be helpful to feed the output to another command.

**Describe alternatives you've considered**
Using git directly, but I'd prefer to avoid that.

**Comment by bnjmnt4n** [comment]
There's currently `jj diff --summary -r REV`, which maybe can be used with something like `jj diff --summary -r REV | cut -c3-` to get the list of files without the preceding modified/added/deleted indicator.

**Comment by marcinjahn** [comment]
Yeah, it's a good workaround for now, but I believe `jj` should have this functionality built-in.

**Comment by yuja** [comment]
Perhaps, `jj diff`/`show`/`log` or `jj files` can be extended:
* `jj diff --name-only` or some template like `jj show -T 'changed_files.join("\n")'`
* `jj files fileset_expr_to_select_only_changed_files` #3239

**Comment by marcinjahn** [comment]
IMO, `jj diff --name-only` sounds good. I guess my initial requirement for files being separated by spaces is rather specific, and probably jj does not need to deal with that in this simple command. However, if there was some template that would allow to do that, it'd be nice.

**Comment by yuja** [comment]
> `jj diff --name-only` sounds good.

We already have three summary types: `--summary`/`--stat`/`--types`, so it's debatable whether we should add one more or make them generic.

**Comment by fowles** [comment]
https://github.com/martinvonz/jj/pull/3921 adds --name-only
