### ISSUE TITLE
Support for HTTP Proxy

### ISSUE THREAD

**Issue by zicklag** [martinvonz/jj#34]
## Expected Behavior

`jj git clone` uses HTTP proxy according to the `http_proxy` and `https_proxy` environment variables.

## Actual Behavior

Failure to clone behind proxy.

    Error: Fetch failed: Error { code: -1, klass: 2, message: "failed to connect to github.com: Connection timed out" }

## Steps to Reproduce the Problem

1. `jj git clone https://github.com/martinvonz/jj.git jj-jj`

## Specifications

- Version: fdb861b95724676a2f1d4e0f3275ed0a8ac0fa96
- Platform: Ubuntu 20.04

---

I know most people and yourself probably don't have proxies, so I'll probably be the one to work on this if I get the time. :smile:

**Comment by martinvonz** [comment]
@zicklag, hopefully that commit fixes it. Note that you'll have to add some configuration in git to make it work (see e.g. https://gist.github.com/evantoli/f8c23a37eb3558ab8765), but I suspect you already have that set up.

**Comment by zicklag** [comment]
Just tested. It works!

**Comment by martinvonz** [comment]
Yay! Thanks for testing :)
