### ISSUE TITLE
Writes to repository fail if the configured immutable_heads can't be resolved.

### ISSUE THREAD

**Issue by noahmayr** [martinvonz/jj#3415]
## Steps to Reproduce the Problem

1.`jj git clone git@github.com:martinvonz/jj.git`
2. `cd jj`
3. `jj config set --repo "revset-aliases.immutable_heads()" "main@origin | gh-pages@origin"`
4. `jj git remote rename origin upstream`
5. `jj new`

## Expected Behavior
A new change is created or a clear error telling me how to resolve this issue is shown

## Actual Behavior
An unclear error is shown "Error: Revision "main@origin" doesn't exist"

## Specifications

- Platform: MacOS 14.4
- Version: 0.15.1

**Comment by yuja** [comment]
Perhaps, the error can be translated to `ConfigError` at `check_rewritable()` as we do for "revsets.short-prefixes".

**Comment by noahmayr** [comment]
Some additional context https://discord.com/channels/968932220549103686/1224073749012414575
@yuja I added a more useful error message there and updated the contributing docs to suggest setting the repo config `remote_branches(exact: "main") | remote_branches(exact: "gh-pages")` instead of `main@origin` and `gh-pages@origin`
