### ISSUE TITLE
FR: FAQ ideas 

### ISSUE THREAD

**Issue by paul-hammant** [martinvonz/jj#3475]
A list of the questions without the expanded answers. Maybe the answers are '>'  .. 'V' expansion click/tap.

New FAQ - 
Q: what is the backend for JJ?
A: There's a Git backend and there's an experimental Local backend. Because of ABIs, it is possible to write other backends.

**Comment by ilyagr** [comment]
Technically, this is doable with the `<details>` element, but I think that'd make things inconsistent with other documentation pages. This is what the "Table of Contents" is for (see screenshot below).

Unfortunately, the mkdocs-material theme puts the TOC in very different places depending on the screen size. On Mobile, it's in the hamburger menu. Ideally, we'd fix this somehow, but this seems tricky.

**Comment by paul-hammant** [comment]
Oh, I see - right hand side - I'd missed that.
