### ISSUE TITLE
jj git fetch creates conflicts on remote branches without local changes

### ISSUE THREAD

**Issue by avoinov-k** [martinvonz/jj#3495]
## Description
`jj git fetch` erroneously abandons commits when the deleted branch has descendants (and commits are still reachable via those descendants). It tries to rebase the descendants to its parent and generates conflicts in the remote branches that have no local changes (and not even tracked), which leaves the local repo in the state that doesn't represent the state of the remote.

## Steps to Reproduce the Problem

1. Create a branch structure in the remote git repo like this: `main -> A -> B -> C`
1. Clone the repo with `jj git clone`
1. Delete branch `B` on the remote
1. `jj git fetch`

Here's the script that demonstrates the problem: [repro.sh](https://gist.githubusercontent.com/avoinov-k/56f57254218f5103dbc6983445b1f396/raw/ed142726d5f4581a7e4d8c7d0d29e14a8a1b2fba/repro.sh)

## Expected Behavior
There should be no conflicts between remote branches. The state should reflect the state of the remote repo.
Conflicts with local changes are possible, but this is the case without local changes.

## Actual Behavior
`jj git fetch` tries to rebase one remote branch on another, resulting in conflicts. Some remote branches became hidden.

## Specifications

- Platform:
```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224
```
- Version:
```
$ jj --version
jj 0.16.0
```

**Comment by yuja** [comment]
This is working as intended. From jj's perspective, the branch B has been abandoned.
That said, I understand the current behavior is undesirable especially if these remote branches are NOT meant to be managed locally.

One way to mitigate the problem is to preserve all (or visible?) untracked remote branches. It'll provide better UX if both branch B and C aren't tracked. However, if the branch B is managed locally, the user might want B gets abandoned depending on the context.

**Comment by avoinov-k** [comment]
I agree that for jj branch such behaviour would correct. But here we are in the area of compatibility with git, and those are unfortunately git branches. I'd say it should be 100% compatible here. I didn't show it in the reproduction steps, but with current behaviour in colocated repo git and jj will show different views of the same branches, and that would be very surprising for the most users.

**Comment by yuja** [comment]
Well, the view is correct in a way that remote branches aren't moved along (but got hidden), but I see what you mean.

Anyways, it's probably better to pin untracked remote branches so long as they are still visible.
