### ISSUE TITLE
jj split (and anything with `--interactive`) doesn't support empty files

### ISSUE THREAD

**Issue by matts1** [martinvonz/jj#3511]
## Description

When splitting a commit with empty files, it's impossible to select those empty files.

## Steps to Reproduce the Problem

1. touch foo bar
1. jj split
1. Attempt to select foo but not bar

## Expected Behavior

Foo will be selected

## Actual Behavior

You're unable to select empty files

## Specifications

- Platform: Debian
- Version: 0.15

**Comment by martinvonz** [comment]
I think this is #3016, which was closed just an hour ago :)
