### ISSUE TITLE
FR: `jj log` column alignment

### ISSUE THREAD

**Issue by ebensh** [martinvonz/jj#3523]
**Is your feature request related to a problem? Please describe.**
The `jj log` command is customizable in terms of what appears, but many of the values are variable width, for example a committer's email or a branch name. I believe that, if it were possible, being able to expand or truncate values to a fixed width on each field display would allow for much nicer scanning of the log.

I'm frequently working in a fairly linear A->B->C flow, so it may be more difficult in repositories that have lots of staggering relationships.

**Describe the solution you'd like**
I would like a way to configure the output format of each value string in the log line to a fixed width, such as the committer's email (I'm working in an internal setting with a small team, so a prefix is fine for me to identify the person, but ideally cutting off the @company.domain and then expanding to a fixed width that is about as large as the longest email)

Before:
```
◉  vnsvwosu abc@corp.com 2024-04-16 6b339281
│  fix(CI): by doing someting (#10761)
◌  (elided revisions)
│ ◉  suzuppvu xyz@corp.com 2024-04-16 some-branch@origin f16753c8
├─┘  Update some midstream build
│ ◉  qlupnzlm qvcr@corp.com 2024-04-16 some-branch-2@origin a147b6e6
├─┘  Update some reference
◉  mkpxxotl defsomereallylongname@corp.com 2024-04-16 34a4fb89
```

After:
```
-------------------------v Note fixed width spacing here to expand, dropping the @corp.com
◉  vnsvwosu 6b339281 abc      2024-04-16
│  fix(CI): by doing someting (#10761)
◌  (elided revisions)
│ ◉  suzuppvu f16753c8 xyz      2024-04-16 some-branch@origin 
├─┘  Update some midstream build
│ ◉  qlupnzlm a147b6e6 qvcr     2024-04-16 some-branch-2@origin
├─┘  Update some reference
◉  mkpxxotl 34a4fb89 defsomer 2024-04-16
----------------------------^ truncating to maintain fixed width, but enough to know who
```

It would also be nice to put the breadcrumb trail on the left in `jj log` in its own based-on-max-width "pane" to the left of the revision ID. For example:

Before:
```
◉  vnsvwosu abc@corp.com 2024-04-16 23:42:32 6b339281
│  fix(CI): by doing someting (#10761)
◌  (elided revisions)
│ ◉  suzuppvu xyz@corp.com 2024-04-16 22:07:41 some-branch@origin f16753c8
├─┘  Update some midstream build
│ ◉  qlupnzlm qvcr@corp.com 2024-04-16 20:31:12 some-branch-2@origin a147b6e6
├─┘  Update some reference
◉  mkpxxotl def@corp.com 2024-04-16 18:52:19 34a4fb89
```

After:
```
◉    vnsvwosu abc@corp.com 2024-04-16 23:42:32 6b339281
│    fix(CI): by doing someting (#10761)
◌    (elided revisions)
│ ◉  suzuppvu xyz@corp.com 2024-04-16 22:07:41 some-branch@origin f16753c8
├─┘  Update some midstream build
│ ◉  qlupnzlm qvcr@corp.com 2024-04-16 20:31:12 some-branch-2@origin a147b6e6
├─┘  Update some reference
◉    mkpxxotl def@corp.com 2024-04-16 18:52:19 34a4fb89
```

These solutions could be combined to give a nice alignment on output.

**Describe alternatives you've considered**
- I tried to figure out a way to do this in a PAGER tool but wasn't able to find something that fit the bill. Maybe if I set a custom field separator in JJ and then could split the strings in a pager?
- As a temporary workaround I've formatted the diff to primarily fixed width values on the left and pushing variable values to the right. For example: revision ID, commit ID, YYYY-mm-dd, only then branch name and author

**Additional context**
Sorry if this already exists and I couldn't figure it out. I do think it'll make the log output, which is primary view into my repo, a lot nicer. It'll also help scanning the information in output like `jj status`, if it's available there. Note that `jj status` does this with the extra space before the : after "Working copy" and putting both fixed width IDs at the front:
```
------------v here
Working copy : tsqpwnys 65e982d2 (empty) (no description set)
Parent commit: lmrqzxnn 824f5230 master | XYZ-12345: Ticket Description (#12345)
```

**Comment by yuja** [comment]
Perhaps, column layout can be achieved in combination with #3183 (add padding function) and #3457 (teach graph width).

**Comment by martinvonz** [comment]
> Perhaps, column layout can be achieved in combination with #3183 (add padding function) and #3457 (teach graph width).

Makes sense to me. I'll close this but feel free to reopen if you think more than those features are needed.

**Comment by ebensh** [comment]
I've read your comments, the linked PRs, and the default templates again. I also played with a new/old tool: the `column` command.

I think I can actually achieve my original goal by:
1. Replacing the separator here: https://github.com/martinvonz/jj/blob/main/cli/src/config/templates.toml#L70 with some special character, maybe ASCII 31 (https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text)
2. Adding a delimiter at the start of the line as well, to separate the graph portion of the log output from the descriptions
3. Piping the output to `column` as my pager, and setting `pager` to always on

With some re-ordering of the outputs I think this will achieve something /close/ to what I'm looking for.

With that in mind, instead of needing to *copy* the templates and inevitably diverging, could we create an alias in the default templates like "field separator" (defaults to space) and "record separator" (defaults to new line) and use those in the built-in templates' `separate` and similar usage of new line instead?

If that's asking too much to add to the built-in's then I'll just copy the templates and do that manually, see how it goes :)

**Comment by ebensh** [comment]
@martinvonz I don't see a way to reopen; does this sound reasonable?

**Comment by yuja** [comment]
> With that in mind, instead of needing to _copy_ the templates and inevitably diverging, could we create an alias in the default templates like "field separator" (defaults to space) and "record separator" (defaults to new line) and use those in the built-in templates' `separate` and similar usage of new line instead?

I would just copy the default template for customization, but if column alignment is common, I think these separator templates can be added.

BTW, `record_separator` wouldn't work in graph output. Newline character will be appended if the template output isn't terminated by `\n`.

**Comment by Nemo157** [comment]
I would also really like an option to have the leading column of each line's text aligned next to the graph. Especially with more complex graphs with a lot of indent levels it's hard to scan the list for specific details (and those are the times when it's really useful to be able to see the graph next to it once you id which commit you're interested in, so `--no-graph` isn't as helpful).

**Comment by PhilipMetzger** [comment]
@bryceberger has a downstream change which allows you to configure the column limit.

**Comment by bryceberger** [comment]
https://github.com/bryceberger/jj/tree/log-width (currently: https://github.com/bryceberger/jj/commit/5b2585df59aa5fe3ef0aa3ecbe19f7f0b5151d58). Not quite sure it's relevant here. Just lets you get the current available width, i.e. `$COLUMNS - graph_width`
