### ISSUE TITLE
Initialization boilerplate is lengthy and error-prone

### ISSUE THREAD

**Issue by cbarrete** [martinvonz/jj#3555]
Feel free to close this if the use case is not supported.

I'm in the process of writing a front-end to jj, for which I'm trying to leverage both the `jj_lib` and `jj_cli` crates. They are quite nice to work with once everything is setup, but getting there is quite difficult.
Concretely, I've had to implement the following by hand:
- Loading both built-in and user configuration
- Loading template aliases
- Loading the workspace (it works fine using `StoreFactories::default()` and `default_working_copy_factories()`, but this may not be comprehensive?)
- Initializing "languages" (e.g. `CommitTemplateLanguage`)
- Creating various context types such as `IdPrefixContext`, `RevsetWorkspaceContext`, `RevsetParseContext`, etc.
- A few more minor things

The issues stem mostly from two root causes:
- A lot of the loading is done ad-hoc either in `CliRunner::run`/`CliRunner::run_internal` or `cmd_*()` (for specific commands)
- Many of the helpers are coupled to `Ui`, which is not reusable by client code (which may not want to use `UiOutput`, for example)

The two main concerns that I have regarding this issue are:
- It is challenging to get the same behavior as the canonical CLI, which then results in a confusing user experience
- I expect that it will be challenging to keep up with upstream changes when any of the logic that has to be reimplemented changes

I think that it is reasonable to expect that some of those should be covered in a straightforward way. For example, while it should be possible to control what configuration is loaded, it should also be straightforward to load "whatever the CLI loads" as well.

**Comment by martinvonz** [comment]
#3034 is closely related. In short, I agree with you. There's way too much logic in the CLI crate helpers right now.

**Comment by ilyagr** [comment]
Thanks for working on a `jj` front-end.

Just in case you aren't on our Discord, are you aware of https://github.com/gulbanana/gg? It probably had to deal with similar problems. You could commiserate with the author :).

**Comment by cbarrete** [comment]
My bad, I missed that other issue, I will close this one then.

I am in the Discord, but I rarely remember to log in! I haven't taken a close look at `gg` yet, but I probably will soon for some inspiration :)
