### ISSUE TITLE
Conflict on rebase clears execute flag on script

### ISSUE THREAD

**Issue by mrstanwell** [martinvonz/jj#3579]
## Description
If a script in a repo has perms 755, but a rebase causes a conflict in the script, the conflicted file's perms get set to 644 and remain so after the conflict is resolved.

## Steps to Reproduce the Problem
1.  Run this script to create a repo and introduce a conflict:
    ```bash
    #!/usr/bin/env bash
    
    mkdir /tmp/repro_permfail
    cd /tmp/repro_permfail/
    jj git init
    cat <<EOF > script.sh
    #!/usr/bin/bash
    echo "No conflict here."
    EOF
    chmod 755 script.sh
    jj desc -m "script import"
    jj new -m "set up for conflict"
    cat <<EOF >> script.sh
    echo "Half a conflict."
    EOF
    jj new -r @- -m "create a conflict"
    cat <<EOF >> script.sh
    echo "The other half."
    EOF
    ```
1. Now rebase the "create a conflict" revision onto the "set up for conflict" revision.  This will create a conflict:  `jj rebase -r <REV1> -d <REV2>`  (I don't know how to script that, unfortunately...)
1. `jj new -r REV1` to resolve the conflict.

## Expected Behavior
The permissions on `script.sh` remain 755.

## Actual Behavior
The permissions on `script.sh` are changed to 644 in the conflicted state and remain so after resolution.

## Specifications

- Platform: macOS 14.4.1 (Sonoma)
- Version: `jj 0.16.0`

**Comment by martinvonz** [comment]
> 2\. (I don't know how to script that, unfortunately...)

`jj rebase -d '@-+ ~ @'` (finds siblings) or `jj rebase -d 'description("set up")'`

**Comment by mrstanwell** [comment]
Nice.  I knew there had to be a clever revset to do that.  `jj` is cool.

**Comment by gulbanana** [comment]
I think this is down to conflict materialisation not yet looking through the merge at file bits. I'll have a go at fixing it.
