### ISSUE TITLE
FR: Add prebuilt binaries for linux arm systems

### ISSUE THREAD

**Issue by senekor** [martinvonz/jj#3717]
**Is your feature request related to a problem? Please describe.**

I just installed jj on my raspberry pi server, which took almost half an hour. It would be great if I didn't have to install from source every time there is an update.

**Describe the solution you'd like**

I would like prebuilt binaries to be provided for `aarch64-unknown-linux-musl` such that they are discoverable by `cargo-binstall` just like on x86.

**Describe alternatives you've considered**

None.

**Additional context**

To sanity-check the feasibility of this, I tried to cross-compile on my x86 machine.
(I don't think GitHub provides linux ARM runners, so a native build is not an option.)
It didn't work at first, and I don't understand enough about cross compiling to understand the error messages.
However, I was able to get it to compile with [cross](https://github.com/cross-rs/cross) very easily.
I `scp`ed the result over to my server and it seems to work fine.

If the maintainers are OK with using cross, I'd be happy to update and test the release workflow accordingly.

**Comment by thoughtpolice** [comment]
FWIW, GHA is apparently going to add arm64 runners and did so in private beta in January. https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/ &mdash; I wonder if maybe we could apply for it.

Buck2 also uses cross for its aarch64-builds though and it seems like a good choice, so I wouldn't be opposed to using it. This is more of a PSA.
