### ISSUE TITLE
FR: Branch list templates

### ISSUE THREAD

**Issue by Cretezy** [martinvonz/jj#3760]
**Is your feature request related to a problem? Please describe.**
I would like `jj branch list` to support `-T` for templating, similar to `jj log`.

**Describe the solution you'd like**
`-T` with the potential options:

- `branch_name`: Branch name
- `remote`: Remote name
- `change_id`: Change ID
- `commit_id`: Commit ID
- Most log options should also work (such as `description`), as each branch points to a change 

**Describe alternatives you've considered**

None possible. For my use case (lazyjj), I will parse the output using regex for now.

**Comment by yuja** [comment]
It's implemented by 12b873e1eff64ed3bca9bf4d1a7547c7c0c98bfd, and will be available in the next release.

**Comment by Cretezy** [comment]
Amazing! Didn't notice this landed.
