### ISSUE TITLE
Checksum of the 0.18.0 release have changed.

### ISSUE THREAD

**Issue by kamiccolo** [martinvonz/jj#3872]
## Description

It was noticed by Arch packagers that the checksum of the 0.18.0 release source tarball [1] have changed somewhere around a week ago.
Was it intentional move to re-tag or delete [2] the release and re-release the same version with some additional changes applied?

From the downstream perspective we would kindly ask not to change already released tags. Or pretty please, just give us some heads up on changes which have happened intentionally.

[1] Source tarball: https://github.com/martinvonz/jj/archive/refs/tags/v0.18.0/jj-0.18.0.tar.gz
     Old sha256: 3e07ba61974e05daa604bdd5a31ec0aaad52e16226dabb380916b8e7e7702b9b
     
[2] Possible deletion of the tag: https://github.com/martinvonz/jj/activity?ref=refs/tags/v0.18.0

## Expected Behavior
- After the release tarballs and their checksums not changing

## Actual Behavior
- Release tarball have changed after the release

## Specifications
- Version: v0.18.0

**Comment by martinvonz** [comment]
Sorry, that was my fault. I got confused when I was going to publish the crate and thought I needed to make some changes but it turned out I had checked out the wrong commit, so I just added the tag back to the same commit. I'll try to be more careful in the future. We're also looking into automating the release, which should eliminate this kind of think.

**Comment by kamiccolo** [comment]
> Sorry, that was my fault. I got confused when I was going to publish the crate and thought I needed to make some changes but it turned out I had checked out the wrong commit, so I just added the tag back to the same commit. I'll try to be more careful in the future. We're also looking into automating the release, which should eliminate this kind of think.

Thank You very much for the quick response! I will pass on the news to the downstream packaging initiative...
Nowadays everyone seems to be getting a bit more sensitive about source archives misbehaving... :)
