### ISSUE TITLE
Screen corruption in `--interactive` with tabs

### ISSUE THREAD

**Issue by msuozzo** [martinvonz/jj#3944]
## Description

I haven't isolated the exact problem but the interactive view is ~unusable for many of my diffs and it seems strongly correlated with the screen scrolling in the presence of tab characters. Another clue is that the 'cursor' bar which is highlighted seems to skip the tab characters, leaving a blank space in the highlight at the tab character and the highlight wrapping onto the following line.

## Steps to Reproduce the Problem

1. Create a screen's worth of diffs
1. jj squash --interactive
1. Scroll to the bottom of the screen

## Expected Behavior

Normal scrolling

## Actual Behavior

Corrupted text movement

## Specifications

- Platform: Linux (Debian)
- Version: v0.18.0

**Comment by msuozzo** [comment]
This looks like it's actually https://github.com/arxanas/scm-record/issues/2

**Comment by arxanas** [comment]
We just merged @firestack's https://github.com/arxanas/scm-record/pull/37 to fix this upstream 🙂.
