### ISSUE TITLE
FR: branch pointers should update when I `jj commit`

### ISSUE THREAD

**Issue by ChrisPenner** [martinvonz/jj#3976]
**Is your feature request related to a problem? Please describe.**
After many `jj commit`s, I find myself constantly needing to `jj branch set ...` to get my branch pointers back up to the latest change, I'd love if jj could keep them up to date in common unambiguous situations.

**Describe the solution you'd like**
I think it would solve it for me if:
* on `jj commit`, for each parent who has no other children other than the revision I'm committing, move any branches pointing to that parent to point to the new commit instead.

**Describe alternatives you've considered**
I suppose you could update the branch pointer to the new empty change on `jj new` and `jj commit`, but I think it would cause errors trying to push an empty commit too often, seems more clunky.

**Comment by ilyagr** [comment]
You should take a look at https://github.com/martinvonz/jj/discussions/3549. I'll try to add some docs to that post in a second.
