### ISSUE TITLE
Related work: Breezy (Bazaar)

### ISSUE THREAD

**Issue by peterg-gh** [martinvonz/jj#40]
I think that among `docs/related_work.md` Breezy (previously known as Bazaar) should also be mentioned, as it is also both a distinct VCS with its own native storage backend(s), and a backend to the `.git` storage format, with several interesting features (according to Mark Shuttleworth its unique selling point is accurate history of file renames, for example).

https://www.breezy-vcs.org/
http://bazaar.canonical.com/en/

I think that it is rather more interesting than Mercurial, in particular because its latest native storage layer is much more reasonable, in part because of having a `.git` storage backend, in part because of keeping well a history of renames (it is file+patch oriented rather than content oriented like `git`).

**Comment by martinvonz** [comment]
Makes sense, I'll add it.
