### ISSUE TITLE
FR: let users configure default values for the CLI options

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#4016]
(I brought this up on Discord yesterday, thought I'd log it here for posterity.)

I propose we add support for a `[cli]` section in the config where users could set default values for every single option on every single command of the jj CLI. I'll concede the current state of things is not too problematic but I do think this feature would be nice to have (and would probably reduce some dev work for whenever we want to elevate options as config settings).

For example, `git.colocate` in #2512 would be `cli.git.init.colocate` (and wouldn't need any special casing). Similarly, the already existing `git.fetch` and `git.push` could be `cli.git.fetch.remote` and `cli.git.push.remote` respectively etc.

**Comment by martinvonz** [comment]
Also see #1509. That was closed because Mercurial decided to deprecate their support for default arguments. I'm not sure if this issue is different enough. We should at least address the arguments mentioned there.

**Comment by avamsi** [comment]
ACK, similar to #1509, that seems reason enough to close.
