### ISSUE TITLE
Segfault in jj log with 4000+ revisions

### ISSUE THREAD

**Issue by tim-janik** [martinvonz/jj#4031]
## Description

I'm using `jj log` with an fzf query string. Since jj log cannot grep for a query string in commits as of 0.18.0, I'm using `git log --format=%h -P --grep` for now. For wildcards in large repositories, this can yield 4000+ revisions, triggering a segfault in jj log.

## Steps to Reproduce the Problem

Enter a repository with 4000+ commits.

```
jj log -r $(GIT_DIR=$(jj root)/.jj/repo/store/git git log --all --format=%h --grep . | tr '\n' "|")'none()'
Segmentation fault
jj log -r $(GIT_DIR=$(jj root)/.jj/repo/store/git git log --all --format=%h --max-count 3500 --grep . | tr '\n' "|")'none()'
◉  uznpwzlt benjamin@dev.ofcr.se 2024-07-04 17:23:59 bnjmnt4n/push-uzynoulwtlvz@origin 5445df74
│  cli: add `jj operation show` command
◉  qztwlksp benjamin@dev.ofcr.se 2024-07-04 17:23:59 fe917b22
│  cli: add `jj operation diff` command
◉  qwwqyoxs benjamin@dev.ofcr.se 2024-07-04 17:23:42 541c031c
│  repo: add `RepoLoader::merge_operations`
```

## Expected Behavior

The` --max-count 3500` shouldn't be needed. Looking at the length of the revision string, I suspect there is a 32k limit in revision expression evaluation somewhere: 

```
GIT_DIR=$(jj root)/.jj/repo/store/git git log --all --format=%h --max-count 3585 --grep . | tr '\n' "|" | wc -c
32265
```

Ideally, revision strings of arbitrary length should be supported. And could be loaded from a file ;-)

## Actual Behavior

Unless --max-count  is used, wildcards yielding long revision lead to a segfault in e.g.:

```
fzf -q GREP-PATTERN --disabled --ansi  \
  --bind 'change:reload( jj --no-pager log --color=always -T builtin_log_oneline -r $(GIT_DIR=$(jj root)/.jj/repo/store/git git log --all --format=%h --grep {q} | tr "\n" "|")"none()" )' \
  --preview "[[ {} =~ ^[^abc-xyz()]*([k-xyz]{8,})\  ]] && jj --ignore-working-copy show --color=always  \${BASH_REMATCH[1]}" \
  </dev/null
```

## Specifications

- Platform: amd64, Ubuntu 22.04.4 LTS
- Version: jj 0.18.0-9fb5307b7886e390c02817af7c31b403f0279144

**Comment by yuja** [comment]
`x|y|z|..` is parsed as `((x|y)z)|..`, and the parsed tree is processed recursively without flattened as of now. That's why. Mercurial has a workaround for machine-generated query like that.

To grep commit description, use `-r description(..)`. `jj` doesn't have a revset predicate to search for commit contents (diff) right now #2933.

You can also enlarge stack size by `ulimit -s`.
