### ISSUE TITLE
Commit via $EDITOR only works with terminal editors

### ISSUE THREAD

**Issue by yb66** [martinvonz/jj#404]
## Description

I noticed that commit messages weren't saved when using my favourite editor (BBEdit) so I tried a few things.

These work:

    EDITOR=pico jj commit
    EDITOR=vim jj commit

These don't, they leave `(no description set)` in the log.

    EDITOR=subl jj commit
    EDITOR=bbedit jj commit

(`subl` is Sublime Edit's commandline runner.)

When using BBEdit I get this pop up before saving:

> This file appears to have been modified.
> The file at /path/to/files/.jj/repo/description-2655695675.txt may have been changed on disk by another application.
> If so, saving this document may cause data loss. Are you sure you wish to proceed?

I get no such warning with Pico or Vim.

## Steps to Reproduce the Problem

1. Make the default editor a GUI based one or use the EDITOR var
2. Run `EDITOR=subl jj commit`
3. Add a commit message and save
4. Run `jj log` and see the commit message is missing

## Expected Behavior

The log shows the commit message I saved.

## Actual Behavior

The log shows a commit with `(no description set)`.

## Specifications

- Platform: Mac
- Version: jj 0.4.0

**Comment by yuja** [comment]
Needs `-w` option? The editor process must not exit until the window closed.
https://stackoverflow.com/a/9408117

**Comment by yb66** [comment]
@yuja That is a very good point, and by checking my global gitconfig (which I should've done at the beginning 🤦 ) I see:

    [core]
	editor = bbedit -w

That has indeed fixed it.

I wasn't aware jj had a config, but [it does](https://github.com/martinvonz/jj/blob/051c01491c32dcc6865d8ac84b6bd240148624c2/CHANGELOG.md#L62) though I only found this in the CHANGELOG. If there's not a piece of more solid documentation then I'd be happy to put in a PR.

**Comment by martinvonz** [comment]
> If there's not a piece of more solid documentation then I'd be happy to put in a PR.

Correct, there's not yet a place where we document all configuration options. I PR adding a doc in https://github.com/martinvonz/jj/tree/main/docs would be welcome. Don't feel that you need to make it complete if you send a PR; even just starting a doc will be very useful.
