### ISSUE TITLE
FR:  be less strict about requiring quotes for globs in filesets

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#4053]
I'm using [filesets](https://martinvonz.github.io/jj/prerelease/filesets/) and have `ui.allow-filesets=true`.

I was confused when the following did not work:

```console
$ jj log glob:'Car*'   # These are *shell* quotes, `jj` does not see them
Error: Failed to parse fileset: Syntax error
Caused by:  --> 1:9
  |
1 | glob:Car*
  |         ^---
  |
  = expected <EOI>, `|`, `&`, or `~`
```

After quite a bit of confusion, I found out that `jj` requires extra quotes: `jj log glob:'"Car*"'` so that the argument `jj` ends up seeing is quoted as `glob:"Car*"`

I wonder, would it be possible to relax this restriction?

Failing that, would it be possible to have a better error message?

(The docs also explain that quotes are required if filenames have spaces, but that's a separate restriction that seems harder to relax)

**Comment by yuja** [comment]
It's in TODO, and we just need to decide whether we prefer quote-less syntax over stricter parsing #2101.
https://github.com/martinvonz/jj/blob/a983abb594896e357ca290824dd6d90ed34bf11d/lib/src/fileset.pest#L17-L36

(I personally lean towards quote-less syntax.)
