### ISSUE TITLE
FR: repetition counts for `+` and `-`

### ISSUE THREAD

**Issue by Zoybean** [martinvonz/jj#4055]
**Is your feature request related to a problem? Please describe.**
Most often when I'm undoing something, I'll look at the op log and then figure out the number of operations I want to undo, then count that many `-`'s, e.g.: `jj op restore @---`.
I rarely have a use for more than 2 `+` or `-`, outside of `jj op restore`.

**Describe the solution you'd like**
I'd like to be able to say `jj op restore @-3`.
Naturally, this feature would allow both `+` and `-` operations to accept a nonnegative integer count, on arbitrary revsets.
Unfortunately, if these are handled as postfix operators, I figure this would imply that things like `@-3+2` and pathological combinations like `@--3+2++0-+` would be valid syntax, which I think are not desirable, but may be necessary in order for the feature to work.

**Describe alternatives you've considered**
I could just copy the hash of the state I want to revert to, or continue to count repetitions of `+` and `-`. This avoids over-complicating the syntax for such a small gain.

**Comment by yuja** [comment]
Related: https://github.com/martinvonz/jj/issues/3337

For `op restore` specifically, some interactive UI to pick from the last ~10 operations might be useful. Maybe that can also be achieved by using fzf. https://github.com/martinvonz/jj/wiki/fzf
