### ISSUE TITLE
Typo in the tutorial

### ISSUE THREAD

**Issue by wolfv6** [martinvonz/jj#4138]
## Description

In the tutorial:
https://martinvonz.github.io/jj/latest/tutorial/#conflicts
https://github.com/martinvonz/jj/blob/main/docs/tutorial.md

A confusing typo in the sentence, "Second, because B2 modified the same file (and word) as B1, rebasing it resulted in conflicts, as the output indicates."
The "B2" should read "A".

**Comment by bnjmnt4n** [comment]
This isn't a typo, there is a conflict in the rebase because B2 (which is the commit being rebased onto A) was made after B1, and thus depends on the changes made in B1. Removing B1 from B2's ancestry causes the conflict.
