### ISSUE TITLE
"jj status" output while fixing conflicts is misleading and offers bad advice

### ISSUE THREAD

**Issue by mhammond** [martinvonz/jj#4147]
In my scenario:
* `jj rebase` - get some conflicts.
* `jj new changeid` to start resolving them.
* fix the conflicts, run `jj status` to check I've got everything.

The output from the `jj status` is shown:
![image](https://github.com/user-attachments/assets/a2649453-ef65-4389-a199-a3718d555f70)

However, I think the text is misleading: it's telling me to `jj new change_id` - but that change is already my parent, and my current change has resolved the conflicts. If I follow that advice, I'll effectively lose the fixes to the conflicts and need to start again. Once I re-resolve them, `jj status` will again advise me to drop the fixes and start again. This will continue until I learn to ignore the given advice, and I'll later discover I have a number of almost identical heads, all fixing the same conflicts.

**Comment by martinvonz** [comment]
I agree. I think we even talked about in the PR that introduced the feature. So this was a known shortcut we took there.

**Comment by seh** [comment]
I've been caught by this several times, and have also learned to ignore the advice, but I still don't know what better advice to offer.

**Comment by bnjmnt4n** [comment]
A workaround could be to detect if the current working copy commit is a direct child of the root conflicted commit, and modify the message to something like:

```
The parent commit of the working copy is conflicted.
To resolve the conflicts, you can use `jj resolve`, or edit the conflict markers in the file directly.
Once the conflicts are resolved, you may want to inspect the result with `jj diff`.
Then run `jj squash` to move the resolution into the conflicted commit.
```

However, this might still be inaccurate if the user didn't run `jj new conflicted-commit`, but ran `jj edit child-of-conflicted-commit`.

**Comment by essiene** [comment]
So I was playing around with this, and it seems we spit out this message once there is **any** ancestor with a conflict. Regardless of the state of the working commit itself.

Supposing we instead:
1. On a commit with a conflict: Print out the hint and point at the first unique ancestor(s) that have conflicts.
2. On a commit without conflicts:
  - If the immediate parent has no conflict. Ignore. Conflict has been fixed by some other 
    commit.
  - If the parent has a conflict. Print a different hint like "Conflict has been resolve" or 
    some better english.

**Comment by essiene** [comment]
> So I was playing around with this, and it seems we spit out this message once there is **any** ancestor with a conflict. Regardless of the state of the working commit itself.
> 
> Supposing we instead:
> 
> 1. On a commit with a conflict: Print out the hint and point at the first unique ancestor(s) that have conflicts.

It looks like this is already handled the proper way, no-op here.

> 2. On a commit without conflicts:
> 
> * If the immediate parent has no conflict. Ignore. Conflict has been fixed by some other
>   commit.
> * If the parent has a conflict. Print a different hint like "Conflict has been resolve" or
>   some better english.

This should help with the false positives.

**Comment by essiene** [comment]
After more playing around, how about the following:

* Working commit has conflict?
  * FALSE
    * Parent has conflict?
      * FALSE - do nothing
      * TRUE  - msg: "Working copy resolves conflict in Parent"
  * TRUE
    * Any decendant **without** conflict?
      * TRUE  - "Conflict has been resolved in <decendant_commit>"
      * FALSE - ...continue with current message we print today...
