### ISSUE TITLE
jj log --stat overflows terminal window

### ISSUE THREAD

**Issue by xzfc** [martinvonz/jj#4158]
## Description

The width of the stat section produced by `jj log --stat` depends on the terminal width (it's good). However, it doesn't take into an account that it's shifted to the right by the graph.

## Steps to Reproduce the Problem

Run `jj log --stat` and see this.

```
│ ◉  kuvzrvpw benjamin@dev.ofcr.se 2024-04-30 18:10:15 f465b7d7
│ │  rebase: `move_commits`: use `rebase_commit_with_options` to rebase commits
│ │  cli/src/commands/rebase.rs | 38 ++++++++++++++++++++++++++++++++------
│ │  1 file changed, 32 insertions(+), 6 deletions(-)
│ ◉  wvmsrkmq benjamin@dev.ofcr.se 2024-04-30 17:37:50 d46b7b70
│ │  rebase: `move_commits`: do not remove parents of target commits which are o
utside the target set
│ │  cli/src/commands/rebase.rs       | 59 ++++++++++++++++---------
│ │  cli/tests/test_rebase_command.rs | 95 +++++++++++++++++++++++++++++++++----
---
│ │  2 files changed, 117 insertions(+), 37 deletions(-)
│ ◉  uwzykukz benjamin@dev.ofcr.se 2024-04-30 17:37:50 ed5b26ae
├─╯  rebase: modify tests to avoid printing commit and change IDs
│    cli/tests/test_rebase_command.rs | 670 +++++++++++++++++++-----------------
--
│    1 file changed, 335 insertions(+), 335 deletions(-)
◉  zompxkst benjamin@dev.ofcr.se 2024-04-30 17:35:25 f1f84544
│  rebase: do not print out commit summaries of skipped commits
│  cli/src/commands/rebase.rs       | 85 ++++++++++++++++++---------------------
-
│  cli/tests/test_rebase_command.rs | 46 +++++++---------------
│  2 files changed, 53 insertions(+), 78 deletions(-)
◌  (elided revisions)
:
```

Note the stray hyphens on the left side. They should belong to their previous lines. Making the terminal window wider won't help — these lines are always longer than the terminal width exactly by one or three characters.

## Expected Behavior

Either let the stat summary be narrower by the width of the graph part (different for each commit), or by a constant amount of characters (won't help for branchy trees, but it would be enough for most of the cases).

## Specifications

- Platform: Linux
- Version: 0.19.0

**Comment by ilyagr** [comment]
As I mention in the bugs I'm linking, there's a workaround that made me much less frustrated by this. If `less` is ultimately the pager used, typing `-S` in it to chop long lines helps a lot.
