### ISSUE TITLE
FR: Equivalent to `git commit`'s `--author <id>` option in `jj {desc,commit}`

### ISSUE THREAD

**Issue by ErichDonGubler** [martinvonz/jj#4170]
**Is your feature request related to a problem? Please describe.**

Occasionally, I would like to author commits on behalf of somebody in a way that doesn't fit a typical [`Signed-Off-By: …`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s) (see also <https://github.com/martinvonz/jj/issues/1399>) or [`Co-authored-by: …`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line) footer. 

* The most common case I've run into personally is when I'm pairing with somebody(ies) on a single machine (i.e., via [Visual Studio Live Share](https://visualstudio.microsoft.com/services/live-share/)) and we need to determine which individuals occupy the author slot and/or a `Co-authored-by` footer. When the person determined to occupy the author slot doesn't match the current user or repo configuration, one must specify a different author.
* Other times, I have created commits for a coworker that is not currently at their desk, but are instructing me on what changes to make. This can happen when they're responding to an issue that has come up in production, but the coworker is away from their typical development environment.

To satisfy the above, one can…

1. …make temporary edits to a `config.toml` layer, then author a commit in `jj`.
2. …use `--config-toml 'user.name = "…"' --config-toml 'user.email = "…"'` in the command when authoring a commit.
3. …use [`git commit --author=…`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt) and `jj git import`, if the `jj` repo is in a co-located repository.

It could be _much_ easier to do one-off revision authoring if `jj` offered an interface designed to do so. Unfortunately, one cannot make one's own via `jj` aliases, because they don't allow for the specification of arguments (see also <https://github.com/martinvonz/jj/issues/3673>).

**Describe the solution you'd like**

Git's current interface appears to satisfy all use cases I'm aware of (contradictory or supplementary examples welcome as comments!), so something close to (a subset of) it seems reasonable to propose.

More formally, I propose we add an `--author <spec>` option to `jj desc` and `jj commit`, where `<spec>` must be of the format `$name <$email>`. This is equivalent to specifying `--config-toml 'user.name = "…"' --config-toml 'user.email = "…"'`.

If more than a single `--author` option is specified, the operation should fail, instructing the user to specify, at most, one. This forwards-compatible design is deliberately restrictive, for forwards compatibility with some design possibilities I see.[^1][^2][^3]

[^1]: This proposal makes no attempt to imitate Git's partial matching functionality, i.e., specifying `--author Erich` in a repository I've committed to might conveniently match `Erich Gubler <…>`. This seems important for usability, but also likely warrants some design thinking WRT search heuristics for partial matches. I'm happy to file a follow-up issue on this, if this issue accepted.
[^2]: In the example of aliases that specify an `--author` flag, it seems obvious that the intent of the user calling the alias would be to override what was previously specified. However, I'm uncertain if our currently CLI makes it easy to implement a "last specified author between two separate options wins" approach, which is what Git CLI does, and that might conflict with the `--author-from` option I'm toying with in footnote 3.
[^3]: I also wanted to propose `--author-from <revset>`, where `<revset>` is a revset query that must resolve to a single revision, like [`jj squash --to …`](https://martinvonz.github.io/jj/v0.19.0/cli-reference/#jj-squash). This would re-use the author information specified in the revision. However, since this doesn't exist in Git, I'm not sure if it's useful.

**Describe alternatives you've considered**

1. Expose this functionality using a different CLI. I can't imagine a useful one that is meaningfully different, but it's worth inviting others to think critically about this, I suppose!
5. Do nothing. As noted above, there are workarounds for not having this functionality, so let users do that.

    This feels dissatisfying, since there is general familiarity with Git's `--author` option and there don't seem to be any significant risks with it.

**Additional context**

\-

**Comment by jonathantanmy** [comment]
Note that `jj describe` already has a `--reset-author` flag, with instructions (`jj describe --help`) on how to use the JJ_USER and JJ_EMAIL envvars to set a different author if you want. This is similar, I guess, to your solution of specifying `--config-toml` on the CLI, except that it is shorter.

I don't contribute a lot to the jj project so don't take my opinions on this too seriously, but for what it's worth, I'm OK either way. Adding `--author` would make adopters from Git more comfortable, but keeping the status quo means that users don't need to read two ways to do one thing when they read the docs.

**Comment by mati865** [comment]
There is at least one big difference between using `--reset-author` and Git's `--author`. ``--reset-author`` will reset the timestamp to the current time.
This becomes important when you want to fix just an email address but keep other things. My use case is fixing commits for repositories that require a specific email.
