### ISSUE TITLE
FR: Error exit code from editor on `jj commit` should abort the commit

### ISSUE THREAD

**Issue by ChrisPenner** [martinvonz/jj#4178]
**Is your feature request related to a problem? Please describe.**
When I type `jj commit`, jj opens Vim for me to write a message.
I really like that jj shows which file-changes are being committed in the text log before committing;
However, sometimes I see that there are changes I _don't_ want to commit, or that I wanted to `jj split` before committing.
I'd love a way to _cancel_ the commit once I see that I don't want to proceed.

**Describe the solution you'd like**
In git, I can abort a commit by `:exit 1`'ing the editor, git notices the process failed non-zero, and aborts the commit, this seems like an elegant solution.

**Describe alternatives you've considered**
I know that I can `jj undo`, but honestly it doesn't cross my mind very often. Maybe I just need to get into the habit of it, but the differing behaviour from git seemed confusing to me so I figured I'd point it out :) 

Thanks everyone!

**Comment by ilyagr** [comment]
It's meant to work this way in `jj`, so I'd call it a bug if it doesn't. OTOH, I couldn't reproduce it.

I think the issue is that, in Vim, `:exit 1` exits with a 0 error code. (I think it might interpret 1 as a file name?). Use `:cq` or `:cq!` to exit with a non-zero error code.

**Comment by ChrisPenner** [comment]
Oh, you're definitely right! I must've been hallucinating that it worked in git, or maybe it's that an empty buffer fails in git, but not in jj?

Either way, this one's user error, thanks!
