### ISSUE TITLE
`ui.merge-editor = "vscode"` doesn't work by default on Windows

### ISSUE THREAD

**Issue by Jcparkyn** [martinvonz/jj#4207]
## Description

The default settings for using vscode as a merge editor don't work on Windows. I got around this by setting:

```
jj config set --user merge-tools.vscode.program "code.cmd"
```

## Steps to Reproduce the Problem

1. `jj config set --user ui.merge-editor "vscode"`
1. Create a conflict
1. `jj resolve --debug`

## Expected Behavior
Opens the vscode merge editor.

## Actual Behavior

```sh
$ jj resolve --debug   
2024-08-04T01:30:56.098182Z  INFO jj_cli::cli_util: debug logging enabled
Resolving conflicts in: hello2.md
2024-08-04T01:30:56.121812Z  INFO run_command:cmd_resolve: jj_cli::merge_tools::external: Invoking the external merge tool: cmd="code" "--wait" "--merge" "C:\\Users\\James\\AppData\\Local\\Temp\\jj-resolve-jL95Mj\\left_hello2.md" "C:\\Users\\James\\AppData\\Local\\Temp\\jj-resolve-jL95Mj\\right_hello2.md" "C:\\Users\\James\\AppData\\Local\\Temp\\jj-resolve-jL95Mj\\base_hello2.md" "C:\\Users\\James\\AppData\\Local\\Temp\\jj-resolve-jL95Mj\\output_hello2.md"
Error: Failed to resolve conflicts
Caused by:
1: Error executing 'code' (run with --debug to see the exact invocation)
2: program not found

```

## Specifications

- Platform: Windows 10 (not WSL)
- Version: `jj 0.19.0`

**Comment by DD5HT** [comment]
https://martinvonz.github.io/jj/latest/config/#editor

It is documented there: `ui.editor = "code.cmd -w"   # VS Code on Windows`

jj could detect it's on windows and then replace vscode with the actual command but I'm not sure if that's something which should be done.

**Comment by Jcparkyn** [comment]
That documentation only works for the regular editor, not the diff editor 😃. I don't mind this requiring manual setup, but the current documentation doesn't mention that this extra option is required. https://martinvonz.github.io/jj/latest/config/#3-way-merge-tools-for-conflict-resolution

**Comment by martinvonz** [comment]
Seems like we should add that config to https://github.com/martinvonz/jj/blob/main/cli/src/config/windows.toml then. Want to send a PR, @Jcparkyn?
