### ISSUE TITLE
FR: Switch from RUST_LOG to JJ_LOG 

### ISSUE THREAD

**Issue by theduke** [martinvonz/jj#4219]
**Is your feature request related to a problem? Please describe.**

I work on a lot of Rust projects, and I often set the RUST_LOG env var, either manually or automatically with direnv.

This means that I end up seeing `jj` logs , even if I absolutely don't care about them.

Rust itself switched from `RUST_LOG` over to `RUSTC_LOG` quite a while ago, with a similar motivation.

**Describe the solution you'd like**

Since `jj` will be used in (Rust) development environments, it makes sense to :

* Stop respecting the `RUST_LOG` env var
* use `JJ_LOG` for logging configuration instead

Happy to open a PR for this if agreed upon.

**Comment by arxanas** [comment]
I'm in favor. We already have `JJ_TRACE` as well.

**Comment by ilyagr** [comment]
As a slight aside, it would be nice to document the relationship between the `--debug` option, `JJ_TRACE`, and the new `JJ_LOG`.
