### ISSUE TITLE
Broken pipe when running `jj rebase 2>&1 | head` causes stale working copy

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#4239]
I tried the following command in the situation where the rebase would cause the conflict.

(The goal was to use the command in a demo but shorten the output)

The result was, surprisingly, a stale working copy for the following operation. This is not a concurrency bug, it is completely repeatable for me.

```console
$ jj rebase -s third -d first 2>&1 |  head -n 3 # Shorten the long message
Rebased 2 commits
New conflicts appeared in these commits:
  lnyvokkk 34755ec1 third | (conflict) third
$ jj rebase -s second -d third
Error: The working copy is stale (not updated since operation 6c9667ecda1f).
Hint: Run `jj workspace update-stale` to update it.
See https://github.com/martinvonz/jj/blob/main/docs/working-copy.md#stale-working-copy for more information.
```

I'm guessing that the first `jj rebase` aborted in the middle of an operation because of a broken pipe, and this caused a corrupted working copy. I'm not 100% sure this is a bug, but it's certainly was surprising to me.

**Comment by yuja** [comment]
I think this is expected after failed working-copy updates.

That said, this particular scenario can be mitigated by reordering `update_working_copy()` and `report_repo_changes()`.

https://github.com/martinvonz/jj/blob/b3ede64472f9cd9290cb6a3f8776caac69dca793/cli/src/cli_util.rs#L1424-L1430

**Comment by ilyagr** [comment]
I'm not sure what's best here, but here are two unbaked thoughts.

I wonder if, in the ideal world, we could make it so that as many errors as possible are either handled before the mutation starts or after it is over. That sounds like a lot of busywork, though.

I suppose we could treat BrokenPipe-s specially. It's a bit annoying that we can't judge the error by their larger type; some IOErrors are critical (writing to the store failed), and some are just BrokenPipe-s.

**Comment by yuja** [comment]
I think many of the interrupted mutation problems are addressed by transaction in jj. Working-copy updates and git exports are two major sources of inconsistency, and I think we can avoid broken pipes in that region relatively easily.

**Comment by essiene** [comment]
So I put together a draft in #4517, that just moves the call to `self.report_repo_changes(...)` after the `may_update_working_copy(...)` block.

It changes the ordering of messages on the CLI. I'm not sure if I think the ordering is better or worse, but it's very different. Is this fine? Should we look for another way to solve this?

thoughts?

**Comment by yuja** [comment]
> changes the ordering of messages on the CLI. I'm not sure if I think the ordering is better or worse,

I think it's okay, and I personally like the new order since conflicts would be the thing the user will have to address next.

**Comment by essiene** [comment]
> > changes the ordering of messages on the CLI. I'm not sure if I think the ordering is better or worse,
> 
> I think it's okay, and I personally like the new order since conflicts would be the thing the user will have to address next.

Okie dokie. I'll mark the PR as ready then. Thanks.
