### ISSUE TITLE
FR: unsquash with multiple parents/children

### ISSUE THREAD

**Issue by Zoybean** [martinvonz/jj#4258]
**Is your feature request related to a problem? Please describe.**
Often I will have a tree something like this:
```
> jj log
○    M
├─╮  
│ ○  A
│ │  
○ │  B
├─╯  
○    
```
I might go back and make some changes to A
```
> jj new --after $A
> jj log
○    M
├─╮  
│ @  C
│ │  (empty)
│ ○  A
│ │  
○ │  B
├─╯  
○    
```
Making changes at C will usually create conflicts in M, so I will `backout` C, and `rebase` the backout to between C and its children, which resolves the conflicts.
so:
```
> jj backout -r $C
> jj log
○    M (conflict)
├─╮  
│ │ ○  D
│ ├─╯  backout C
│ @  C
│ │  fixup A
│ ○  A
│ │  
○ │  B
├─╯  
○    
> jj rebase -r $D --after $C
# this resolves conflict in M
> jj log
○    M
├─╮  
│ ○  D
│ │  backout C
│ @  C
│ │  fixup A
│ ○  A
│ │  
○ │  B
├─╯  
○    
```
at this point, I want to `squash` C into A, and `unsquash` D into M, but the latter is not allowed - you can't `unsquash` a merge commit.

**Describe the solution you'd like**
I'd like to be able to `unsquash` a commit into its (merge) parent, or possibly between any pair of commits like I can with `squash`, e.g.
```
> jj log
○    M
├─╮  
│ ○  D
│ │  backout C
│ @  C
│ │  fixup A
│ ○  A
│ │  
○ │  B
├─╯  
○    
> jj unsquash --from $D --to $M
```

I suspect that in general, this `jj unsquash --from $A --to $B` operation would be roughly equivalent to
```
jj squash --from $B --to $A --keep-empty
jj squash --from $A --to $B
```

**Describe alternatives you've considered**
I suspect that in many cases, I can just use `squash --from $D --to $M`, but if M already contains some conflict resolution, I don't want to `squash` the other commit "onto" that resolution, but "under" it instead.

**Comment by joyously** [comment]
> I'd like to be able to `unsquash` a commit into its (merge) parent

The merge commit is not a parent.

> I might go back and make some changes to A

By doing `new`, you are not changing A. Would you get a different result if you use `edit`?

**Comment by Zoybean** [comment]
Yeah my terminology is off, and I've done a bad job of expressing the intent of the operations. I'll try and clarify.

> The merge commit is not a parent.

Oops, that should probably have been, "I'd like to be able to unsquash a merge commit from a specific parent commit".

> you are not changing A

Sorry, the intention of the operation was not apparent in how I described it. I'll try again. I'd like to make changes to A without propagating those changes to M. The task I was working on at the time was not expressible as a `jj split -r $A`, though for the sake of example that would be a far better choice. I'll edit the original post, as that would make the whole thing clearer I think.

**Comment by Zoybean** [comment]
I've been trying to find an example to demonstrate where the direction of a squash is significant, but I think I've just convinced myself that there's actually no difference, and that `unsquash` doesn't do anything you can't do with a single `squash`.
