### ISSUE TITLE
`jj git push -c @` results in `Error: Remote rejected the update of some refs (do you have permission to push to ["refs/heads/push-ntrnrmqmtyxm"]?)`

### ISSUE THREAD

**Issue by mrcjkb** [martinvonz/jj#4280]
## Description

Hey :wave: 

I've been starting to use `jj` and forked a repo. I was able to `jj git push -c @` before, and open a PR.
But now, it always complains (in all repositories) with the following output:

```
❯ : jj git push -c @
Creating branch push-ntrnrmqmtyxm for revision ntrnrmqmtyxm
Branch changes to push to origin:
  Add branch push-ntrnrmqmtyxm to a338fe15f7c6
remote: Resolving deltas: 100% (1/1), done.
Error: Remote rejected the update of some refs (do you have permission to push to ["refs/heads/push-ntrnrmqmtyxm"]?)
```

## Steps to Reproduce the Problem

I don't think this can be reproduced easily, as it happens to me whenever I `jj git push`.

## Specifications

- Platform: NixOS (nixpkgs-unstable)
- Version: 0.20.0

```
❯ : jj op log
@  e381e2e06d65 mrcjk@nixos-tux 18 minutes ago, lasted 1 millisecond
│  snapshot working copy
│  args: jj log --no-pager --limit 4
○  bddb60a90710 mrcjk@nixos-tux 18 minutes ago, lasted 38 milliseconds
│  describe commit cc42727e58f1f46e83b1f80b56acd09b87af811a
│  args: jj describe -m 'ci: add luarocks-tag-release workflow'
○  ffd9ec7dc70d mrcjk@nixos-tux 18 minutes ago, lasted 39 milliseconds
│  new empty commit
│  args: jj new
```

**Comment by bnjmnt4n** [comment]
Can you provide any details about the remote you are trying to push to? If you're pushing to a forked repository, could it be on a different remote (try using `--remote`)? Without any other information, it's hard to debug this.

**Comment by mrcjkb** [comment]
Thanks for the quick response.

It's definitely a credentials issue. If I use git to checkout and push a branch, it works after going through `git-credential-oath` (which I have set as my `credential.helper` in my git config).
I suppose libgit2 doesn't work with that.

I usually use SSH, but switched to HTTPS for jj, because it doesn't yet respect `~/.ssh/config`. I had forgotten I was using `git-credential-oath`.

**Comment by mrcjkb** [comment]
Well that's weird. Now it's working again.
Perhaps it was an issue with my local caches?
