### ISSUE TITLE
`jj git fetch` succeeds in pulling a non-existent branch name

### ISSUE THREAD

**Issue by rdamazio** [martinvonz/jj#4293]
## Description

If I specify a non-existent branch name to `jj git fetch`, it doesn't fail.

## Steps to Reproduce the Problem

1. `jj git clone https://github.com/rdamazio/efis-editor.git`
1. `cd efis-editor`
1. `jj git remote add zyv https://github.com/zyv/efis-editor.git`
2. `jj git fetch -b features/foreflight-support --remote zyv` (misspelled branch name)

## Expected Behavior

It'd tell me that the branch I asked to fetch does not exist.

## Actual Behavior

`Nothing changed`

## Specifications

- Platform: macOS 14.6.1 (23G93)
- Version: `jj 0.17.1-a17292317c63df7aad14c3203046f683b847fa69`

**Comment by yuja** [comment]
Perhaps, warning can be displayed if a branch glob doesn't match any of the changed or known remote branches.
