### ISSUE TITLE
FR: Equivalent to `git ls-files`?

### ISSUE THREAD

**Issue by mrcjkb** [martinvonz/jj#4323]
**Is your feature request related to a problem? Please describe.**

I often used `git ls-files` (which includes staged files) to navigate a project's files (e.g. via the telescope.nvim plugin or piped into [rip]grep).
When working with jj, that command doesn't include new files in jj's working copy changes.

**Describe the solution you'd like**

It would be nice to have a jj equivalent, which includes jj's working copy changes.

**Describe alternatives you've considered**

- Move a git branch or `jj git push`. 
- Pipe all files, including those not under scm into [rip]grep or telescope.

**Comment by bnjmnt4n** [comment]
`jj file list` lists all files in the specified revision (defaulting to the working copy). I think that should be what you're looking for?

**Comment by martinvonz** [comment]
#4324 adds it to https://martinvonz.github.io/jj/latest/git-comparison/#command-equivalence-table

**Comment by mrcjkb** [comment]
Thanks, that's what I was looking for.
