### ISSUE TITLE
Could use a full example of how to pass templates to cli args

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#4357]
Could there be a full example of how to pass `--template` to `show` or some basic command like that?

I went looking for how to use them and even though there are docs like https://martinvonz.github.io/jj/latest/templates/ I found it surprisingly hard to guess exactly what strings I could pass to the argument that wouldn't give me cryptic errors like `  = expected <EOI> or <expression>`.

**Comment by dbarnett** [comment]
Also is there a command to take a revision and spit out _just_ a templatized string of the revision's data, not as part of other output? Something like `git describe`?

**Comment by yuja** [comment]
Maybe we should add some command-line examples to the templates doc or `jj log --help`.

> a command to take a revision and spit out just a templatized string of the revision's data

`jj log --no-graph` ?

**Comment by dbarnett** [comment]
> > a command to take a revision and spit out just a templatized string of the revision's data
> 
> `jj log --no-graph` ?

Yep, works great. Thanks!

One misfeature on that, for reference: if it's printing multiple revisions it should probably print each output on its own line, like

```shell
$ jj log -r 'latest(@)' -r 'latest(@-)' -T change_id --no-graph
wpttulzmmyqmwrzyzmpkzkymomuyonvx
nppwrmyyloxvqmrtnnrwlkmytlyvtmxs
```
instead of printing everything on one line like it currently does: `wpttulzmmyqmwrzyzmpkzkymomuyonvxnppwrmyyloxvqmrtnnrwlkmytlyvtmxs`
