### ISSUE TITLE
`jj log --no-graph` shouldn't print multiple revs on same output line

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#4359]
## Description

I noticed that `jj log --no-graph` can print all revisions smushed on the same output line if you give it a `--template` that doesn't contain newlines. That should probably be changed to output at most one rev per line.

## Steps to Reproduce the Problem

1. Execute `jj log --no-graph -T 'change_id'`

## Expected Behavior

Should see each rev's template output on its own line:
```
wpttulzmmyqmwrzyzmpkzkymomuyonvx
nppwrmyyloxvqmrtnnrwlkmytlyvtmxs
xnqptntytzzmqlprxpzrzwszyrtqoxwy
numulsylomkvnsuuyyqwnqpqmkprrvll
kpnnxqwsrtvzyzqrvutxxtzxloomovpl
```

## Actual Behavior

Outputs single long line of output for all revs in the revset:
`wpttulzmmyqmwrzyzmpkzkymomuyonvxnppwrmyyloxvqmrtnnrwlkmytlyvtmxsxnqptntytzzmqlprxpzrzwszyrtqoxwynumulsylomkvnsuuyyqwnqpqmkprrvllkpnnxqwsrtvzyzqrvutxxtzxloomovpl`

## Specifications

- Platform: Ubuntu Linux 24.04
- Version: jj 0.20.0

**Comment by martinvonz** [comment]
That's working as intended. You can use `jj log --no-graph -T 'change_id ++ "\n"'` if you want the newlines.

**Comment by yuja** [comment]
As Martin said, it's by design. User might want to separate fields by `"\0"` for example. Maybe we can include some template examples in the help message.

**Comment by dbarnett** [comment]
Got it, thanks! And I was pleasantly surprised that that nicely trims the output so there's always exactly one newline at the end.
