### ISSUE TITLE
Test failure in the last release (0.21.0)

### ISSUE THREAD

**Issue by orhun** [martinvonz/jj#4394]
## Description

Hello! I'm one of the maintainers of the [`jujutsu`](https://archlinux.org/packages/extra/x86_64/jujutsu/) package for Arch Linux and just hit the following test failure while building `0.21.0` in a clean chroot:

```
ailures:

---- test_show_command::test_show_basic stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: show_basic-10
Source: cli/tests/test_show_command.rs:218
────────────────────────────────────────────────────────────────────────────────
Expression: stdout
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    3     3 │ Committer: Test User <test.user@example.com> (2001-02-03 08:05:09)
    4     4 │
    5     5 │     (no description set)
    6     6 │
    7       │-file2            | 3 ++-
    8       │-{file1 => file3} | 0
          7 │+... | 3 ++-
          8 │+... | 0
    9     9 │ 2 files changed, 2 insertions(+), 1 deletion(-)
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'test_show_command::test_show_basic' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'show_basic-10' failed in line 218
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_show_command::test_show_basic

test result: FAILED. 571 passed; 1 failed; 0 ignored; 0 measured; 21 filtered out; finished in 14.40s

error: test failed, to rerun pass `-p jj-cli --test runner`
```

## Steps to Reproduce the Problem

1. Fetch the PKGBUILD from [GitLab](https://gitlab.archlinux.org/archlinux/packaging/packages/jujutsu).
2. Update `pkgver` variable and `sha256sums` for `0.21.0`.
3. Build in a clean chroot (`extra-x86_64-build`) 

## Expected Behavior

Successful build.

## Actual Behavior

See above.

## Specifications

- Platform: Arch Linux
- Version: `0.21.0`

**Comment by emilazy** [comment]
Interesting. We also run the tests in a namespaced sandbox in Nixpkgs, but didn't have any issues with the update.

**Comment by alerque** [comment]
I believe this has to do with TTY detection in the test suite. We have other tests that are failing for the same reason already. I think the output of the `git` porcelain commands are trying to tweak the output based on detected `$COLUMNS` or other things that are not set in Arch's nspawn build environment. In this test they are truncating file names because it thinks it doesn't have the width to display them. Or something like that.

**Comment by cormacrelf** [comment]
I think this explains it:

<img width="255" alt="Screenshot 2024-09-05 at 11 33 14 pm" src="https://github.com/user-attachments/assets/932d673c-9ba0-45cc-955f-758abfada953">

**Comment by martinvonz** [comment]
#4397 should fix it. Let us know if we should just merge that (once reviewed and approved) or if we should apply it directly on top of 0.21.0 and cut a 0.21.1 based on that (I prefer not to if we can avoid it).

**Comment by orhun** [comment]
Applied the patch in #4397 and I confirm that it fixes the issue 🥳

**Comment by martinvonz** [comment]
So should I just merge that or do you need a 0.21.1 release?

**Comment by thoughtpolice** [comment]
FWIW I think skipping another release is totally fine. Other downstreams can easily pick this patch and we can refer it to them if needed.

**Comment by orhun** [comment]
Yup, whatever you prefer. We currently skip that test anyways - will remove that line of code when there is a new release.

**Comment by martinvonz** [comment]
> Other downstreams can easily pick this patch and we can refer it to them if needed.

Ah, good. I didn't know if that would be easy for them. I'll merge the PR closed this ticket then.

**Comment by emilazy** [comment]
If there’s one thing Linux distributions are good at doing, it’s applying patches to other people’s software 😅

**Comment by alerque** [comment]
I already released on Arch with the test disabled. This fix might actually allow us to re-enable several other tests that were failing too, but I suppose it's not urgent to have a release for the tests that *can* be skipped.

**Comment by joyously** [comment]
Doesn't the failure indicate that the code isn't getting a default value when the environment variable isn't set? Setting the variable for the test seems like a hack.

**Comment by martinvonz** [comment]
> Doesn't the failure indicate that the code isn't getting a default value when the environment variable isn't set?

We try to detect the terminal width ([here](https://github.com/martinvonz/jj/blob/e8d790952647283f9201fe4df200d84188db2de0/cli/src/ui.rs#L719)) when the environment variable is not set. If that fails, we [default to 80](https://github.com/martinvonz/jj/blob/e8d790952647283f9201fe4df200d84188db2de0/cli/src/ui.rs#L653). The problem happens (happened) when we successfully detected the terminal width during tests.

**Comment by alerque** [comment]
> Setting the variable for the test seems like a hack.

I don't think so. The test is not related to terminal detection and hence should be setup to be as independent as possible from the TTY in use. In this case it should be hard coded for everybody since that is the only way to consistently test the thing that is actually supposed to be tested there.

If you *were* testing the output at different terminal widths you would want to hard code a couple tests at different fixed widths. Otherwise having expectations for the output of the test is meaningless.
