### ISSUE TITLE
FR: jj undo should print what operation is being undone

### ISSUE THREAD

**Issue by rdamazio** [martinvonz/jj#4431]
**Is your feature request related to a problem? Please describe.**
When you run `jj undo`, it prints the new commit and parent, but doesn't tell me what was undone.
This requires going back and forth between `undo` and `op log` which is inconvenient.

**Describe the solution you'd like**
It should print what operation is being undone (e.g. "workspace snapshot triggered by jj st", "jj rebase", "workspace snapshot + jj rebase", etc.)

**Describe alternatives you've considered**
Running `jj op log` and keeping the result open to understand what's happening, re-running it periodically if there's many operations to undo.

**Comment by PhilipMetzger** [comment]
this also belongs to #3700
