### ISSUE TITLE
Managed to checkout hidden change, escalated into panic

### ISSUE THREAD

**Issue by Veykril** [martinvonz/jj#4446]
## Description

I managed to somehow have a hidden change checked out, but I do not know how I managed to do so (and forgot to snapshot my op log at the tim). Then for fun I tried `jj edit @` which caused the following panic:
```text
workspace\rust\rust-analyzer (08c7bbc) 
❯ jj edit nxv
thread 'main' panicked at C:\Users\lukas\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jj-lib-0.19.0\src\id_prefix.rs:176:89:
Change ids present in narrower search set should be present globally.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Steps to Reproduce the Problem

Unfortunately I don't know what exactly I did aside from trying to resolve conflicts between two remote branches.

## Expected Behavior

Afaik one shouldnt be able to check out hidden changes

## Actual Behavior

Managed to check out a hidden change

## Specifications

- Platform: Windows
- Version: 0.19.0

**Comment by martinvonz** [comment]
#4427 might have fixed this bug, but maybe more likely it would just make it harder to trigger

**Comment by yuja** [comment]
Perhaps, we'll need to remove the assertion anyway. User can configure short-prefixes to include e.g. `remote_branches()`.
