### ISSUE TITLE
`jj squash --keep-emptied` does not copy the description of the source commit

### ISSUE THREAD

**Issue by samueltardieu** [martinvonz/jj#4473]
## Description

`jj squash` help page says that the description of the source commit, if any, will be copied or merged into the target commit description. This is not the case when using `--keep-emptied`.

## Steps to Reproduce the Problem

```
$ jj new
$ jj new -m "Some description"
$ echo foo > bar
$ jj squash --keep-emptied
$ jj log -r @-::
@  rtnywryn sam@rfc1149.net 2024-09-15 14:36:12 84bf696b
│  (empty) Some description
○  nsknwpvm sam@rfc1149.net 2024-09-15 14:36:12 5c65418c
│  (no description set)
```

## Expected Behavior

The description should have been moved to the target commit.

## Actual Behavior

No description copying or merging takes place.

## Specifications

- Platform: Linux
- Version: main

**Comment by matts1** [comment]
Correct. Keep-empty should not squash the descriptions by design.  I think most use cases where you'd want keep-empy you'd also want to preserve the description. Do you have a use case where you want keep-emptied but want to preserve it?

**Comment by samueltardieu** [comment]
> Correct. Keep-empty should not squash the descriptions by design. I think most use cases where you'd want keep-empy you'd also want to preserve the description. Do you have a use case where you want keep-emptied but want to preserve it?

Assuming a *not* is missing in the last part of the sentence, no, I don't have such a use-case. I was just surprised by the discrepancy between the documentation and the reality. I've opened #4485 to make the documentation match the current behavior.
