### ISSUE TITLE
--no-pager doesn't work with `help` subcommand.

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [martinvonz/jj#4501]
## Steps to Reproduce the Problem

1. run `jj help --no-pager` (or any `help` subcommand with `--no-pager`).

this also happens with subcommands that print help when you run them, like `jj git --no-pager`.
 
## Expected Behavior

it prints the same help text that `jj help` would, but without the pager.

## Actual Behavior

it prints:
```
error: unrecognized subcommand '--no-pager'

Usage: jj [OPTIONS] <COMMAND>

For more information, try '--help'.
```

## Specifications

- Platform: nixos
- Version: 0.21.0

---

running `jj --help --no-pager` doesn't return the error, but still uses the pager.

this bug probably isn't that important, but it is an inconsistency. you can still use `PAGER=cat jj help` to get it to print without a pager if you don't want to disable it globally.

**Comment by Grillo-0** [comment]
`jj --no-pager help` works. I think it still doesn't solve the issue, but it works if you just want the help command with no pager
