### ISSUE TITLE
FR: Examples of using `jj log --template` for ad-hoc and scripting

### ISSUE THREAD

**Issue by msiebuhr** [martinvonz/jj#4503]
**Is your feature request related to a problem? Please describe.**

I have some tooling that needs git-sha's for our release-flow to work; I've figured that `jj log --limit 1 --revisions '~empty()' --template 'commit_id'` gets me some of the way, but https://martinvonz.github.io/jj/latest/templates/ isn't entirely clear on what I can put in there and how to do so.

**Describe the solution you'd like**

A small example when running `jj help log` for the `--template` flag and/or some examples of command-line usage in https://martinvonz.github.io/jj/latest/templates/s, like https://martinvonz.github.io/jj/latest/revsets/#examples does would be nice.

**Describe alternatives you've considered**

**Additional context**
Writing git-interop so scripts run locally resolve the same commit-sha's as our "legacy" git-based workflows does.

**Comment by msiebuhr** [comment]
Oh, and `--no-graph` makes the output more machine-readable - less `akw` and `cut`'ing after running commands :)

**Comment by yuja** [comment]
Merged with #4357
