### ISSUE TITLE
Rework revset operators

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#46]
Mercurial has a `::` operator, which returns the ancestors when used as a prefix (`::foo`), descendants when used as a suffix (`foo::`), and the intersection of the two when used as infix (`foo::bar`). I like that and I tried to extend it by using the same operator for parents and children. That's how I ended up with `:foo` meaning "parents of foo" and `foo:` meaning "children" of `foo`. However, it hasn't worked very well in practice.

One problem with it is that we don't have a simple way of saying "N generations back/forward". Git and Mercurial have `foo~10` for saying "ten generations back from foo". However, because we use `:` as either prefix or suffix, `11:22` becomes ambiguous (is it 22 generations after a commit with hex prefix 11 or 11 generations before a commit with hex prefix 22?).

Another problem, which is just small annoyance, is that by using `:` as prefix for the very common case of specifying parents, we make it harder to go one more step back, because the user needs to move the input cursor to before the symbol. For example, if you've entered `jj diff -r :@` and realized that you wanted to go one more step back, you need to move the cursor left before you can insert an extra `:`.

So, we should probably switch to `foo~` for "parents of foo" and maybe `foo+` for "children of foo". Then we free up `:` to be used in other operators. We could probably use `:` for Mercurial's `::` operator (we don't want its `:` operator). Maybe we should also support Git's `..` operator (not sure about `...` -- I almost never want it myself).

I think it would be nice to also have a syntax for a range of generations. Perhaps `foo[-5:2]` could mean "from 5 generations back to 2 generations forward from foo".

I wonder if we should use an operator for commit ID and/or change ID. Maybe `=abc` could be the commit ID with prefix `abc` and `%abc` could be the change ID with prefix `abc`. I'm not sure it's worth spending two characters on that. We should definitely have revset *functions* for it.

**Comment by arxanas** [comment]
`~` is pretty awful to type in my experience. If you're open to changing it, maybe `-` instead? It would be easier to type and it's symmetric with `+`.

Have you considered operator syntax for the predecessors/successors of a given commit? Sometimes I want to write out `git move -s 'foo' -d 'bar' && git checkout foo2`, where `foo2` is the (to-be-created) successor of the preceding operation. I guess `pred`/`succ` are probably short enough for that use case.

**Comment by martinvonz** [comment]
> `~` is pretty awful to type in my experience. If you're open to changing it, maybe `-` instead? It would be easier to type and it's symmetric with `+`.

Good point. As odd as it seems, I'm not sure I considered using `-` for that.

I think the main reason for not choosing `-` is that I'd like to have syntax for "3 generations before `foo`" but `foo-3` would then be ambiguous with "revision `foo` minus revision `3`". That expression may seem unlikely to be useful in practice, but it can happen if e.g. `foo` is actually a change ID or even something like `:@` (ancestors of the working copy commit) and `3` is actually a decimal-looking hex prefix of a commit/change ID. But that's still a poor reason because I can simply switch the two operators (using `~` for set difference).

Another reason is of course that `~` is more familiar for users coming from Git or Mercurial, but that's also a weak reason, IMO (as someone who insist on metric units after >10 years in the US).

I'll make the change. Thanks for the suggestion!

By the way, a problem I already have with the `-` operator is that it's somewhat common for branches and tags to have a hyphen in them, such as in `v2.9.0-rc0` (in the git.git repo). Those currently have to be quoted in order to not be interpreted as a set difference. Combined with shell quoting, that means you have to do things like `jj diff -r '"v2.9.0-rc0"'`.

Mercurial has the same problem. They have a hack where they [try to parse the combined expression as a symbol](https://www.mercurial-scm.org/repo/hg/file/9cf5ac8c7109/mercurial/revsetlang.py#l195) and treat it as a single symbol if it exists. That's a hack because it means that you can't parse an expression without knowing which symbols exist.

Now that I think about it, maybe `-` should be allowed in symbols, so `v2.9.0-rc0` would be parsed as valid symbol and the user could do `v2.9.0 - rc0` if they wanted the other parse (i.e. set difference before I make the change you suggested). That's not so bad because it requires only only level of quoting on the command line (the shell quoting). I think I'll try to make that change too.

> Have you considered operator syntax for the predecessors/successors of a given commit? Sometimes I want to write out `git move -s 'foo' -d 'bar' && git checkout foo2`, where `foo2` is the (to-be-created) successor of the preceding operation. I guess `pred`/`succ` are probably short enough for that use case.

Yep, I intended to have an operator for predecessors/successors before I started removing support for evolution :) I can usually get away without them by using change IDs. In your particular example, I'd do `jj rebase -s abc -d def && jj co abc` where `abc` is a change ID. I may eventually add some operator for predecessors/successors based on the operation log.

**Comment by martinvonz** [comment]
> Now that I think about it, maybe `-` should be allowed in symbols, so `v2.9.0-rc0` would be parsed as valid symbol and the user could do `v2.9.0 - rc0` if they wanted the other parse (i.e. set difference before I make the change you suggested). That's not so bad because it requires only only level of quoting on the command line (the shell quoting). I think I'll try to make that change too.

Hmm, except that that would make pretty common expressions like `@-3` annoying to type. I'm still not sure what to do about this. I guess I'll live with the awkward quoting solution for now.

**Comment by martinvonz** [comment]
There's now some [documentation of the revset syntax](https://github.com/martinvonz/jj/blob/main/docs/revsets.md), linked from the [README](https://github.com/martinvonz/jj/blob/main/README.md).

**Comment by arxanas** [comment]
> Hmm, except that that would make pretty common expressions like @-3 annoying to type. I'm still not sure what to do about this. I guess I'll live with the awkward quoting solution for now.

Oof, that would make branch `foo-2` which is like the original branch `foo` hard to address. I could imagine accidentally using the second ancestor of `foo` in those cases.

One option would be to require a sigil instead of a pair of quotes to address a branch. After all, why do commits and branches and everything live in the same namespace to begin with? (Isn't the logic for `git checkout` overcomplicated?) But that might be too different for users to get used to.

I guess you could produce a warning whenever they use the non-existent function `foo` like `did you mean *foo to address branch foo?` (where `*` is the branch sigil) or similarly when they try to address non-existent function `abc` with message `did you mean %abc to address commit with change ID abc?`. Adding a sigil after the fact is annoying, but less annoying than dealing with nested quotes.

**Comment by martinvonz** [comment]
Good points about both names like `foo-2` and using a sigil. One problem with using a sigil (besides getting users used to it) is that it needs a different sigil for each kind of symbol (branch, tag, git ref, change ID, ...), including for any new kinds of symbols added in the future. Of course, only commonly used kinds would need their own sigil (others can use functions like `my_thing(foo)`). I'm also not sure if we'd want different sigils for e.g. branches and tags.

Another option is of course to avoid having revset operators that use any characters that are commonly used in ref names. That would make at least `-` unviable, and maybe `+` as well (and `_`, but we already don't use that).

Maybe users will eventually get used to used to using `_` instead of `-` in branch names, but there are of course very many of existing Git repos that already have branches and tags with `-` in them.

**Comment by martinvonz** [comment]
@quark-zju had another suggestion: First assume the revset is actually just a single symbol (don't even parse it as a revset?) and try to look it up. If that fails, interpret it as a revset.

That would mean that e.g. `foo-2` would be interpreted as just `"foo-2"` but `parents(foo-2)` would be interpreted as `parents(parents("foo", 2))`. In most cases it would just work as you'd expect, especially if you're an average user.

**Comment by tp-woven** [comment]
> Now that I think about it, maybe `-` should be allowed in symbols, so `v2.9.0-rc0` would be parsed as valid symbol and the user could do `v2.9.0 - rc0` if they wanted the other parse (i.e. set difference before I make the change you suggested). That's not so bad because it requires only only level of quoting on the command line (the shell quoting). I think I'll try to make that change too.

Having just getting bitten by this, +1 from me on allowing dashes in symbols and requiring spaces around them for the operator, for a couple of reasons:

- It doesn't require double-quoting, which is very unnatural.
- It requires quoting for the more complex expression, which I think is more in line with people's expectations - people already know they have to quote spaces.

**Comment by martinvonz** [comment]
Yet another option would be to not use the `-` operator both as a postfix (for "immediate parents") and infix operator (for "N generations back") like hg and git do (e.g. `HEAD~` and `HEAD~5`). Perhaps `-#` and `+#` are decent operators for the "N generations back/forward" case? I think that's my favorite solution so far.

**Comment by martinvonz** [comment]
However, another aspect to weigh in is that the `5` in the hypothetical `foo-#5` (or whatever syntax we use) stands out by being not being a revset. So maybe we should just make the user use a revset function instead of starting to make some atoms be integers and some be revset symbols.

Either way, it sounds like we should start by allowing `-` in symbols, except as the last character.

**Comment by martinvonz** [comment]
With the latest change to allow internal `-` and `+` characters in symbols, I'm mostly happy with what we have. Using `~` instead of `-` for difference is perhaps the most unfortunate aspect, but it feels like the lesser evil.
