### ISSUE TITLE
`jj git push -b` is parsed as `jj git push --branch`

### ISSUE THREAD

**Issue by fnuttens** [martinvonz/jj#4601]
## Description

Ever since the deprecation of `branches` in favor of `bookmarks`, jj has trouble recognizing the `-b` argument in `git push` command.

## Steps to Reproduce the Problem

1. update to jj 0.22.0
1. run `jj git push -b foo`

## Expected Behavior

~~Branch~~ Bookmark `foo` is pushed to remote.

## Actual Behavior

```
error: unexpected argument '--branch' found

Usage: jj git push [OPTIONS]

For more information, try '--help'
```

## Specifications

- Platform: Linux
- Version: 0.22.0

**Comment by martinvonz** [comment]
> error: unexpected argument '--branch' found

Where did `jj` even get that `--branch` from? Does your shell expand it transparently somehow, perhaps using a previous `jj` version's completion scripts? If `jj git push -b foo` is exactly what you ran, then I don't see where `jj` would get the `--branch` from.

**Comment by fnuttens** [comment]
@martinvonz argh my bad yeah nushell completions are to blame here 😅 
Thanks for replying!
