### ISSUE TITLE
FR: Shorten help output

### ISSUE THREAD

**Issue by nop** [martinvonz/jj#4611]
### Is your feature request related to a problem? Please describe.

I don't paginate jj output because I often use the information in later commands and like to see the output at the same time. When I try to get help on a certain jj command, the help info is way too long, and I lose my terminal history off the top of the screen.

I know I pipe help output to a pager, but I would still like to see the help output as a part of my terminal history and not an alternate screen (cleared on pager exit), so I can use that information to craft my next command without having to memorize the output.

### Describe the solution you'd like

I think the best way to fix this would be to only show global options with the "top-level" jj help information. That is, only when the user executes `jj help` or `jj --help`, but not in combination with a sub-command: `jj help next`, `jj next --help`.

If a user requests help with a specific sub-command, they're likely only seeking the information specific to that command, and not global options. If the user, in the process of learning jj, has read multiple help outputs, they likely don't need to re-read the same information for global options.

If global options are necessary in every scenario, perhaps a different, shorter version of the global options output would suffice. Or maybe a note that says "see `jj help` for global options".

**Comment by nop** [comment]
This may be more confusing to the user, but you could also have more general, verbose information accessible via `jj help` and more topical, concise information via `jj <command> --help`.

**Comment by samueltardieu** [comment]
If your pager is `less`, you can give it the `-X` argument to not clear the screen upon exiting. For example, in my `~/.jjconfig.toml`, I have:

```toml
[ui]
pager = "less -FRX"
```

- `-F` quits automatically if there is only one screen, so that I don't have to press "ESC" or "q".
- `-R` lets raw characters through, which means that I get colors even when paging.
- `-X` prevents the screen from being cleared upon exit.

Other pagers might offer similar capabilities.

**Comment by yuja** [comment]
`jj next -h` (not `--help`) will show the shorter version. Does that work for you?

**Comment by nop** [comment]
> `jj config set --user ui.pager 'less -FRX'`

I was ignorant of the `ui.pager` option (my own fault, not the docs') and forgot about `-FRX`. Thanks!

**Comment by nop** [comment]
> `jj next -h` (not `--help`) will show the shorter version. Does that work for you?

This works for me and is what I wanted. I'm not sure if different behavior between short (`-h`) and long (`--help`) flags is standard or expected convention. I could be wrong but I wasn't expecting different behavior from `-h`, so I didn't think to try it. I think the current behavior (different output between `-h` and `--help`) is hard to find but more useful than my proposed solution. It's documented in the help output, which I think is "discoverable" enough:

> -h, --help
>         Print help (see a summary with '-h')

> -h, --help     Print help (see more with '--help')
