### ISSUE TITLE
jj handles renames of the remote trunk poorly

### ISSUE THREAD

**Issue by tonyfinn** [martinvonz/jj#4616]
## Steps to Reproduce the Problem

1. Create a git repo with a `master` branch
2. Push the git repo to a remote
3. Run `jj git init --colocate` in this copy
4. Run `jj branch track master@origin` in this copy
5. From a different checkout of the git repo (or a different device/user), rename the branch `master` to `main`, push the new `main` branch to the remote, delete `master` on the remote
6. Run `jj git fetch` on the first checkout
7. Attempt to switch to the new `main` branch with `jj new main`

## Expected Behavior

Ideally: You're able to continue developing the on local repo with the new name for the trunk branch. 

At a minimum: Warn the target that the `trunk()` alias refers to has been deleted and you need to update the `trunk()` alias.

## Actual Behavior

Output from `jj git fetch` in step 6:

```
> jj git fetch
bookmark: main@origin   [updated] tracked
bookmark: master@origin [deleted] untracked
```

Most `jj` commands fail after this `jj git fetch`.

```
> jj new main
Config error: Invalid `revset-aliases.immutable_heads()`
Caused by: Revision "master@origin" doesn't exist
```

```
> jj log
Error: Revision "master@origin" doesn't exist
```

```
> jj log -r main@origin
Error: Failed to parse template: In alias "builtin_log_node"
Caused by:
1:  --> 1:1
  |
1 | builtin_log_node
  | ^--------------^
  |
  = In alias "builtin_log_node"
2:  --> 6:10
  |
6 |       if(immutable, "immutable"),
  |          ^-------^
  |
  = Failed to evaluate revset
3: Revision "master@origin" doesn't exist
Hint: Did you mean "main@origin"
```

```
> jj bookmark untrack master@origin
Error: No such remote bookmark: master@origin
```

It's not clear how to recover from this situation other than `rm -R .jj && jj git init --colocate`

## Specifications

- Platform: NixOS
- Version: 0.22.0

**Comment by yuja** [comment]
You'll ened to update `trunk()` saved in .jj/repo/config.toml, which was probably generated by `jj git init --colocate`.

I agree the error message isn't actionable.
