### ISSUE TITLE
FR: `jj restore --interactive`

### ISSUE THREAD

**Issue by cbarrete** [martinvonz/jj#4651]
In the Git world, I'm used to self-reviewing changes and staging them piecewise with https://github.com/tpope/vim-fugitive, which I can emulate in jj with `jj commit -i`. However, `vim-fugitive` also lets me restore/discard hunks interactively, which I believe jj doesn't support right now.

Ideally, I'd like to be able to single-handedly commit and restore hunks (or squash and restore them). As this would likely require more design, adding an interactive version to `jj restore` seems like an improvement over the status quo, while remaining consistent with other commands.

I've tried messing with the diff editor when calling other interactive subcommands, but I could not get the behavior I wanted (and it was hacky).

**Comment by bnjmnt4n** [comment]
I think this is a duplicate of https://github.com/martinvonz/jj/issues/3012.

**Comment by cbarrete** [comment]
Indeed, thanks for letting me know, I should have found it before opening this...
