### ISSUE TITLE
FR: jj commit --reset-author should also reset the author timestamp

### ISSUE THREAD

**Issue by farnoy** [martinvonz/jj#4689]
**Is your feature request related to a problem? Please describe.**
In the index-less/working-copy/auto-commit model, I often have a long-standing empty commit that later gets re-purposed to deliver some change. This puts distance between when this commit is first created (as empty) and when the change is really done.

**Describe the solution you'd like**
I think `--reset-author` could be repurposed for this, semantically, but we could also have another option. Something at `describe`/`commit` time feels like the right place.

**Describe alternatives you've considered**
The best one I know is `jj duplicate` followed by a rebase, which re-creates the commit with the same parent, but you need to move the downstream commits over.

**Comment by scott2000** [comment]
I think `--reset-author` already does reset the author timestamp in addition to the name/email, just like in Git. Also, if a commit has no changes and an empty description, the author timestamp is automatically reset whenever the commit becomes non-empty or is given a description.

**Comment by farnoy** [comment]
Huh, I don't know what happened when I tried but you're right, it does work. Even on immutable commits 👍

**Comment by farnoy** [comment]
Closing, it is documented and working as expected https://martinvonz.github.io/jj/latest/cli-reference/#jj-commit
