### ISSUE TITLE
[git] `git log` may hide `refs/jj/keep/*` in the future by default

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#473]
## Description

This isn't a problem yet (and might not be), but I'll document it anyway just in case

By default, `git log` shows "decorations" for each ref that points to a commit, which includes refs that are only used internally by Git and not actually useful to the user. This behavior is somewhat useful for jj because `git log` shows `refs/jj/keep/*`.

This is likely to change; on the Git mailing list, there is an [in-flight series](https://lore.kernel.org/git/pull.1301.v3.git.1659722323.gitgitgadget@gmail.com/) that shrinks the default set of decorations to a set of "sensible" refs. This will be confusing for anyone relying on the default behavior, but users should be able to unbreak themselves as that series will almost certainly include a config option to get the old behavior of showing all decorations.

**Comment by martinvonz** [comment]
Thanks for the heads up. I actually think that will be an improvement :) I would at least prefer that myself.

**Comment by chooglen** [comment]
There's probably nothing for us to fix. If anything, users will probably be happy that `refs/jj/keep/*` is omitted.
