### ISSUE TITLE
Bookmark auto-tracking is broken (as documented)

### ISSUE THREAD

**Issue by kfkonrad** [martinvonz/jj#4732]
## Description

[The docs](https://martinvonz.github.io/jj/latest/config/#automatic-local-bookmark-creation) mention the `git.auto-local-bookmark` setting and is called that throughout the docs. The codebase uses both that name as well as `git.auto-local-bookmark` somewhat inconsistently. The line where that matters most is the following: https://github.com/martinvonz/jj/blob/e464c0e607fd9b7308c8c0666f5d5b2c5c9596c9/lib/src/settings.rs#L54

This results in the unfortunate effect that any setting `git.auto-local-bookmark = true` will be ignored leading to unexpecting behavior when following the documented approach

## Steps to Reproduce the Problem

1. Remove any config for `git.auto-local-branch = true` - branches are now called bookmarks after all
1. Add `git.auto-local-bookmark = true` to your config
1. Fetch changes containing a new bookmark

## Expected Behavior

`git.auto-local-branch` should be defunct (or emit a deprecation warning perhaps?) and `git.auto-local-bookmark` should take over that functionality.

Alternatively: If `git.auto-local-branch` is the intended name for that setting going forward, the field in the Settings struct should be renamed to match the name and the documentation should be updated to reflect it as well.

## Actual Behavior

Following the steps above newly fetched bookmarks aren't tracked

## Specifications

- Platform: macOS Sequoia 15.0.1
- Version: 0.22.0 (also present on the current main, see permalink above for exact revision)

**Comment by martinvonz** [comment]
I've updated your report to say `git.auto-local-bookmark` instead of `git.track-local-bookmarks`.

**Comment by martinvonz** [comment]
Thanks for letting us know! #4733 should fix it. I didn't add a deprecation warning because we don't have a simple way of propagating the error. We can continue to support the old config for a long time without much maintenance cost. We can add a deprecation warning later if we want to actually phase it out.
