### ISSUE TITLE
`jj -h --color=never` and `jj -h --no-pager` do not work with options in this order

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#4746]
`jj --color=never -h` and `jj  --no-pager -h` work as expected. `jj -h --color=never` and `jj -h --no-pager` ignore the extra option.

## Specifications

- Platform: ARM Mac OS
- Version: Today's nightly, jj 0.22.0-f2acb98ef2a0b33e665d28d58b59bd3d713b0fbd

**Comment by yuja** [comment]
Just for reference, see this thread for how `-h`/`--help` is interpreted by clap: https://github.com/martinvonz/jj/pull/4518#discussion_r1786655967

**Comment by ilyagr** [comment]
From a certain perspective, this could seem quite minor, but I think it is worth addressing (if we can) because:

- this will happen to beginners and people looking for help
- this messes up the principle that the order of `jj` arguments is usually irrelevant
- these two points combined mean that it may take new people a long time to realize this is an exception from a rule. They will instead wonder every time whether reordering arguments will trip them up, and might abandon `jj` thinking the UI is confusing.

Of course, this does not mean that any amount of tortured code is acceptable to solve this problem.
