### ISSUE TITLE
FR: Fuzzy search for some commands eg. jj restore

### ISSUE THREAD

**Issue by DD5HT** [martinvonz/jj#4769]
**Is your feature request related to a problem? Please describe.**
I added a lot of files, via search and replace and wanted to revert changes in one file.
I can run `jj restore <filename> ` but typing and finding the right filename can be bothersome in a really large repository with a lot of changes. I would be nice to make it easier.

**Describe the solution you'd like**
I want to run something like
`jj restore --fzf ` and then be able to select the file I want to restore interactively. 

**Describe alternatives you've considered**
Alternatively I could write a script...

```nu
# nushell
jj st | lines | input list --fuzzy | each {|x| split column " "} | select column2 |  ...
```

**Comment by yuja** [comment]
We have some ideas to improve completion. https://github.com/martinvonz/jj/issues/4763
It'll be nice if `fzf` can be somehow integrated.

**Comment by senekor** [comment]
Completing the subset of files where restore makes sense is definitely planned. I don't think fzf can be integrated into the completions directly though, we just communicate completion candidates to the shell. The UX for selecting the candidates is up to the shell.

Side note: the dynamic completions don't support nushell yet, this is an upstream limitation of clap / clap_complete_nushell. So, if you are using nushell interactively, you won't benefit from these dynamic completions once we implement them. :slightly_frowning_face:

**Comment by senekor** [comment]
There is now a PR for the file completion: #4887

If that's sufficient to you, maybe you can link the issue to be closed by the PR.

I personally don't think we should integrate fzf. It's a big step outside the scope of a CLI and into the territory of TUI. There are other projects working on more interactive, graphical jj clients, including two TUIs: [lazyjj](https://github.com/Cretezy/lazyjj) and [jj_tui](https://github.com/faldor20/jj_tui).

**Comment by martinvonz** [comment]
> There are other projects working on more interactive, graphical jj clients, including two TUIs: [lazyjj](https://github.com/Cretezy/lazyjj) and [jj_tui](https://github.com/faldor20/jj_tui).

And [jj-fzf](https://github.com/tim-janik/jj-fzf)
