### ISSUE TITLE
Checking out commit with submodule update fails

### ISSUE THREAD

**Issue by mlcui-corp** [martinvonz/jj#4825]
## Description

Switching between two commits in a colocated `chromium/src` repository with a submodule update causes a check out error and fails to update the working directory.

## Steps to Reproduce the Problem

1. Clone `chromium/src`: `git clone --single-branch https://chromium.googlesource.com/chromium/src` (warning: huge repo!) and colocate it: `jj git init --colocate`
1. `jj new a82b0322c54c-` to check out the parent of https://crrev.com/a82b0322c54c
1. `jj new a82b0322c54c` to check out https://crrev.com/a82b0322c54c

## Expected Behavior

The `jj new` succeeds, ignoring the submodule.

## Actual Behavior

```
Internal error: Failed to check out commit [empty commit on top of the command being checked out]
Caused by:
1: Failed to remove file [chromium/src]/clank
2: Is a directory (os error 21)
```

Afterwards, the working copy is stale, and running `jj workspace update-stale` gives:

```
ignoring git submodule at "clank"
Reset the working copy parent to the new Git HEAD.
Concurrent modification detected, resolving automatically.
Nothing to do (the working copy is not stale).
```

## Specifications

- Platform: gLinux
- Version: 6739dccc6de8

Note that I have

```toml
[core]
fsmonitor = "watchman"
watchman.register_snapshot_trigger = true
```

in my `.jjconfig.toml`.

This seems to have previously worked. Will bisect once I have time.

**Comment by yuja** [comment]
It's pretty much broken by 8540536e. Maybe we should skip entries conflicting with existing directory.
