### ISSUE TITLE
FR: Make auto-local-bookmark more powerful

### ISSUE THREAD

**Issue by senekor** [martinvonz/jj#4835]
**Problem**

I want to auto-track my bookmarks, because I have lots of bookmarks and several workstations. Tracking them all manually is tedious. The configuration [`git.auto-local-bookmark`](https://martinvonz.github.io/jj/latest/bookmarks/#automatic-tracking-of-bookmarks-gitauto-local-bookmark-option) exists, but it will track _all_ bookmarks, even the ones from collaborators, which I usually don't want to be tracked.

**Suggested solution**

I would like the configuration key `git.auto-local-bookmark` to be more powerful than just a boolean. I think a string pattern should be sufficient, it could be set to one's `git.push-bookmark-prefix`.

**Alternatives**

If a string pattern is not expressive enough, it could also be a revset. But I can't think of a situation where I'd need that.

**Additional context**

This was [Yuya's idea](https://github.com/martinvonz/jj/pull/4823#issuecomment-2467693794) responding to [my problem description here](https://github.com/martinvonz/jj/pull/4823#issuecomment-2467621889).

**Comment by yuja** [comment]
I think the pattern has to be configured by `(name, remote)` pair. I don't know if it should be `<name>@<remote>` syntax, or per-remote list of patterns.

**Comment by senekor** [comment]
I'm just now realizing that `jj bookmark track` takes a pattern already. From the help output:

```
Examples: bookmark@remote, glob:main@*, glob:jjfan-*@upstream
#                                       ^^^^^^^^^^^^^^^^^^^^^
#                                       exactly my use case
```

So, the status quo is not that bad, it's just a single command every once in a while. I used to do one command per bookmark, which is tedious.

> I think the pattern has to be configured by `(name, remote)` pair. I don't know if it should be `<name>@<remote>` syntax, or per-remote list of patterns.

From the above example, the CLI uses `<name>@<remote>` syntax for bookmark tracking, so that should work in the config too, right?

> With the above, I can directly use Git's refspecs to specify what to fetch and how (whether to materialize local remote-tracking branches or not). Does this approach work for your use-case?

I'm not quite following yet, how does the jj-git-interop behave here? I know that I can use some glob syntax in the git config for fetching... (though I've had to look it up every time I used it.) Is this respected by `jj git fetch`? Or do you fetch with git and then `jj git import`?

**Comment by xxxserxxx** [comment]
Will `git.auto-local-bookmark` make my bookmarks work like Mercurial bookmarks?

I may be unnecessarily carrying Mercurial mental models across, but I've long since ditched both branches and tags in Mercurial. My workflow (in hg) is:

1. Create a bookmark X for something I'm working on
2. commit, commit, commit
3. `hg book -i`
4. `hg push -B X`
5. Repeat at 1

All of my CI processes are based on bookmarks; artifacts and releases are triggered (or not) by bookmark pushes; versions come from bookmarks... and all of this hinges on the fact that the active Mercurial bookmark floats with tip. In jj, they don't; they're basically tags.

I don't so much care about tracking remote bookmarks, but I _am_ interested in having a floating bookmark that follows commits on a series of commits. Can I do that with `git.auto-local-bookmark`?

**Comment by senekor** [comment]
No, `git.auto-local-bookmark` doesn't solve your problem. Automatically tracking new remote bookmarks and automatically moving bookmarks when creating new commits are different things.

**Comment by martinvonz** [comment]
> I don't so much care about tracking remote bookmarks, but I _am_ interested in having a floating bookmark that follows commits on a series of commits. Can I do that with `git.auto-local-bookmark`?

No, but `experimental-advance-branches` sounds like what you're looking for. We don't seem to have better documentation about it than https://github.com/jj-vcs/jj/blob/7402362c80a6af1a609e9fb05009e624fb566252/cli/src/config-schema.json#L506

You may also want to try creating the bookmark only when you're ready to push, so you avoid moving it forward at least once. I use `jj git push -c` to automatically create a bookmark and push it. If rewrite commits, the bookmarks will automatically move to the rewritten commits (just like in Mercurial), so if your workflow involves force-pushing to the remote (as we do with the jj project itself), you should quite rarely have to manually move bookmarks.

**Comment by xxxserxxx** [comment]
That's good advice, thanks. In my case, I'm frequently jumping between branches. For example, I have a larger, several-day feature I'm working on, and in the middle find a bug or some other smaller feature I want to get out so I switch to a different branch. `jj git push -c` seems very much specific to pushing use cases and wouldn't help me keep track of multiple active local heads.

I use bookmarks for tagging (`bookmark -i` as a fixator), and for tracking branches. Mercrial came up with yet another branching workflow thing which I saw no value for -- bookmarks achieved everything I wanted and were reasonably well-supported by tooling (Go and Sourcehut both recognize bookmarks as tag-ish things). I _really_ like the floating nature of bookmarks as they allow me to put a stake in the metaphorical ground for a release and yet keep working on that until I'm ready to _actually_ release it, at which time I inactivate and push the bookmark. `jj push -c` might be useful for me here, although another valuable aspect of bookmarks is that they were a one -- and _only_ one -- mechanism I had to understand. I really appreciated how bookmarks collapsed the functionality of branches, named branches, and tags all in one really simple mechanism.

advance-branches sounds like it might be a better fit; I'll dig in and see how it works for me.
