### ISSUE TITLE
FR: Optionally emit more details when refusing to push private commits

### ISSUE THREAD

**Issue by shanesveller** [martinvonz/jj#5002]
**Is your feature request related to a problem? Please describe.**

When I have commits that match my `private` settings, and I attempt to bulk push using commands like `jj git push [--all | --tracked]` or similar, the default error sort of immediately forces me to `jj show` a regular commit ID in order to recall what the change was, or what its description was. Or I could use `jj log` to also see it in the context of its lineage.

Sample from the test suite code:
```
Error: Won't push commit aa3058ff8663 since it is private
```

Given how `jj` has adjusted my workflows, I'm less likely than ever to recognize a given raw commit SHA at a glance, and if my push syntax didn't reference a specific bookmark or change I don't have that to contextualize it with either.

**Describe the solution you'd like**
An early improvement would be to emit the description and/or change ID as part of the existing command output:

```
# same sample as above
Error: Won't push commit aa3058ff8663 since it is private
commit aa3058ff8663, description: 'private 1'
```

This could be opt-in as a flag if preserving the terse output as default is desired.

I'd love even richer output that collated multiple errors if I had a bulk push attempt that included more than one private commit as I believe it will currently fail-fast.

**Describe alternatives you've considered**

A suffix output with something spiritually like:
```
Reminder: jj log -r 'private() & {the-original-push-revset}' for context
```
Would help steer me as well, although `private()` is not currently a revset/alias or defined directly as one, it's a separate `git.private-commits` settings so on 0.23.0 I'd actually have to write:
```bash
jj log -r "$(jj config get git.private-commits) ..."
```

**Additional context**
I'm open to any solutions that improve the UX here, but I'll also open a PR shortly with an attempt at the "include the description via opt-in flag" tactic above, in case it passes muster.

**Comment by yuja** [comment]
I think this is implemented by https://github.com/martinvonz/jj/commit/5553baf540e203aed072cbbfaec8815938283f3d, closing.

**Comment by shanesveller** [comment]
Fine with me! The only passage that I considered unfulfilled was:

> I'd love even richer output that collated multiple errors if I had a bulk push attempt that included more than one [private or otherwise failed] commit as I believe it will currently fail-fast.
