### ISSUE TITLE
jjdescription line ignore match is "JJ: " with a required space character

### ISSUE THREAD

**Issue by nekopsykose** [martinvonz/jj#5004]
## Description

(not really a bug, but more of a question)

as far as i can tell, this has been the behaviour all the way since it was introduced in f96130d21c362d162ad83903be8a57c22234fdb8

is there a reason why the space is required? i feel like just `JJ:` would make more sense as a match, and then a line with just `JJ:`(no space) on it would also get ignored, whereas currently the lack of space puts a literal `JJ:` into the description. it would also somewhat match git, where a mere `#` ignores the rest of the line (unless the core.commentChar/commentString is changed, of course)

as an aside, the comment prefix in https://github.com/kareigu/tree-sitter-jjdescription/blob/23dd3dd18ee29bdd761642511aa314215801afd8/grammar.js#L4 gets this wrong; but rather than just go fix it there straight away (by adding a space, i guess), i was wondering if there was a reason why the space is required at all, hence this question first :)

## Steps to Reproduce the Problem

1. put `JJ:` without a space into the editor in `jj edit`

## Expected Behavior

it ignores the line

## Actual Behavior

it expects a trailing space, so it doesn't, and a literal `JJ:` is left in the description

## Specifications

- Platform: linux
- Version: 0.23.0

**Comment by martinvonz** [comment]
I don't think I had a good reason for it. I suspect I required the space because all lines we insert into the commit message start with the `JJ: ` prefix (including the space). So I think it's that way on purpose, but I'm happy to change it.
