### ISSUE TITLE
The progress bar causes massive traffic and high CPU usage to the terminal running `jj`

### ISSUE THREAD

**Issue by azuwis** [martinvonz/jj#5057]
## Description

```
$ jj git clone https://github.com/torvalds/linux.git
Fetching into new repo in "/tmp/linux"
  9% 578.6 MiB at   2.4 MiB/s [███████████                                                               ]
```

The progress bar showed above causes massive traffic and high CPU usage to the terminal running `jj`, if `jj` is run in the remote server, it also causes massive traffic between local machine and remote server.

## Steps to Reproduce the Problem

Ssh login to a remote server, and run `jj git clone https://github.com/torvalds/linux.git /tmp/linux` on the remote server.

Run `sudo nethogs -a` on the remote server to measure the network traffic.

### The progress bar causes massive traffic between local machine and remote server

`jj git clone https://github.com/torvalds/linux.git /tmp/linux`:

<img width="813" alt="Screenshot 2024-12-09 at 10 46 01" src="https://github.com/user-attachments/assets/d9586532-c911-422b-940a-3a470aa5e921">

### Git does not have this behavior

`git clone https://github.com/torvalds/linux.git /tmp/linux`:

<img width="810" alt="Screenshot 2024-12-09 at 10 47 08" src="https://github.com/user-attachments/assets/2216eede-00fd-4133-8e1c-6eedaadba90f">

### When the progress bar is redirect to `/dev/null`, the massive traffic is gone

`jj git clone https://github.com/torvalds/linux.git /tmp/linux 2>/dev/null`:

<img width="810" alt="Screenshot 2024-12-09 at 10 50 13" src="https://github.com/user-attachments/assets/b7b9bb30-9eb6-4597-9f51-4b96e512f1cf">

### The progress bar also causes `tmux` high CPU usage when running `jj` in `tmux`:

<img width="817" alt="Screenshot 2024-12-09 at 11 50 26" src="https://github.com/user-attachments/assets/59d5998d-a29d-4ff6-956d-ddc10929bdc8">

When running `git clone ..` in `tmux`, you can't even see `tmux` in `top`:

<img width="812" alt="Screenshot 2024-12-09 at 11 46 20" src="https://github.com/user-attachments/assets/89180e1a-750c-4bfa-bd7d-080c67a4c58e">

## Expected Behavior

The progress bar do not cause massive traffic and high CPU usage to the terminal.

## Actual Behavior

The progress bar causes massive traffic and high CPU usage to the terminal.

## Specifications

- Platform: Linux and macOS
- Version: 0.23.0

**Comment by martinvonz** [comment]
Thanks for the detailed report. Looks like a simple fix.
