### ISSUE TITLE
gitignore incompatibility with *~

### ISSUE THREAD

**Issue by hanwen-flow** [martinvonz/jj#5059]
## Description

I have trouble convincing jj to leave emacs backup files alone in new repos.

```
hanwen@hanwen-flow:/tmp$ mkdir jj-repro
hanwen@hanwen-flow:/tmp$ cd jj-repro/
hanwen@hanwen-flow:/tmp/jj-repro$ jj git init --colocate
Initialized repo in "."
hanwen@hanwen-flow:/tmp/jj-repro$ echo hoi > foo~
hanwen@hanwen-flow:/tmp/jj-repro$ ls
foo~
hanwen@hanwen-flow:/tmp/jj-repro$ jj diff --name-only|cat
foo~
hanwen@hanwen-flow:/tmp/jj-repro$ echo '*~' > .gitignore
hanwen@hanwen-flow:/tmp/jj-repro$ jj diff --name-only|cat
.gitignore
foo~
hanwen@hanwen-flow:/tmp/jj-repro$ jj commit -m 'ignore' .gitignore 
Working copy now at: ykkstpsq 1477f6a8 (no description set)
Parent commit      : vvvlpwkx a04d0c9c ignore
hanwen@hanwen-flow:/tmp/jj-repro$ jj diff --name-only|cat
foo~
hanwen@hanwen-flow:/tmp/jj-repro$ git status
HEAD detached at a04d0c9
nothing to commit, working tree clean
```

I am a bit stumped, because I have another repo on another machine where I got this to work, but I can't recall what I tweaked there.

## Specifications

- Platform: linux x64
- Version: jj 0.21.0-d002a5ad35e624a731e96e85f490f28febc7797e

**Comment by yuja** [comment]
`.gitignore` only applies to new (untracked) files. You'll need to do `jj file untrack 'glob:"*~"'` to remove a tracked file from the commit. (see #4509 for why `~` needs quotes)

I think there's a feature request about newly-tracked ignored files, something like making `jj status` to show hint how to untrack these files.

**Comment by hanwen-flow** [comment]
so if I understand correctly, any jj command takes a snapshot, making a `*~` file be tracked before I add the pattern to `.gitignore` 

that matches what I see, 
```
hanwen@hanwen-flow:/tmp/zq$ jj git init --colocate
Initialized repo in "."
hanwen@hanwen-flow:/tmp/zq$ echo '*~' > .gitignore
hanwen@hanwen-flow:/tmp/zq$ touch foo~
hanwen@hanwen-flow:/tmp/zq$ jj diff --name-only|cat
.gitignore
hanwen@hanwen-flow:/tmp/zq$ 
```

the behavior is logical in retrospect, but maybe could be mentioned more explicitly in the docs.

**Comment by yuja** [comment]
> any jj command takes a snapshot, making a `*~` file be tracked before I add the pattern to `.gitignore`

Correct. A working-copy change is a commit in jj.

> the behavior is logical in retrospect, but maybe could be mentioned more explicitly in the docs.

Do you have any suggestion? It's documented in tutorial, but the Git comparison table might be a better place.

https://martinvonz.github.io/jj/latest/tutorial/#creating-our-first-change
https://martinvonz.github.io/jj/latest/git-comparison/#command-equivalence-table

**Comment by hanwen-flow** [comment]
"jj gitignore" on google doesn't bring up the tutorial in the first 10 results. instead, the first page is https://martinvonz.github.io/jj/latest/git-compatibility/, which just says " Ignores in .gitignore files are supported. So are ignores in .git/info/exclude or configured via Git's core.excludesfile config. The .gitignore support uses a native implementation, so please report a bug if you notice any difference compared to git."

maybe something like 

"Patterns for untracked files in .gitignore files are supported. So are ignores in .git/info/exclude or configured via Git's core.excludesfile config. For tracked files, see 'jj untrack'. The .gitignore support uses a native implementation, ... "

**Comment by joyously** [comment]
It could also mention that if you know you need a pattern ignored, make the ignore file before the `init` command.

**Comment by hanwen-flow** [comment]
thanks, Yuya!
