### ISSUE TITLE
FR: Greater than (`>`, `>=`) and less than (`<`, `<=`) comparison operators

### ISSUE THREAD

**Issue by zx8** [martinvonz/jj#5062]
**Is your feature request related to a problem? Please describe.**

I started using `jj` a few days ago and am in the weeds of the templating language, attempting to reproduce the same format I use for my `git log` output.

To achieve that, I'm trying to write a template for `jj log -T ...` that formats things different based on the length of the description, but the templating language seems to lack these operators to perform a comparison like:

```
$ jj log -T 'if(description.first_line().len() > 100, "foo", "bar")'
Error: Failed to parse template: Syntax error
Caused by:  --> 1:35
  |
1 | if(description.first_line().len() > 100, "foo", "bar")
  |                                   ^---
  |
  = expected `++`, `||`, `&&`, `==`, or `!=`
```

**Describe the solution you'd like**

It would be nice to be able to use `>` / `>=` / `<` / `<=` to make decisions based on the length of the output, to ensure everything is aligned neatly, like my `git log` output.

**Describe alternatives you've considered**

I'm not sure there are any alternatives for what I'm trying to achieve here.

**Comment by stefanboca** [comment]
I also ran into this a while ago, and realized this could also be done with eg `description.first_line().substr(0, 100).starts_with(description.first_line())` as the condition, although this is quite unwieldy and unintuitive. Equality comparisons were recently added to the templating language so this seems like a logical next step.

**Comment by martinvonz** [comment]
If you want to add support for it, you could look at #4781 for inspiration
