### ISSUE TITLE
Bogus completion for `jj rebase`

### ISSUE THREAD

**Issue by WhyNotHugo** [martinvonz/jj#5105]
## Description

The completion for `jj rebase -d` shows files in the current directory, but `-d` takes a commit or bookmark.

## Steps to Reproduce the Problem

1. Type `jj rebase -d`
1. Press <kbd>Tab</kbd>

## Expected Behavior

Completion should show valid options; commits or bookmarks in this case.

## Actual Behavior

Completion shows files in `$PWD`, which would be invalid input for this flag.

## Specifications

- Platform: Alpine Linux
- Version: 0.24.0

**Comment by WhyNotHugo** [comment]
I'm using zsh

**Comment by WhyNotHugo** [comment]
Right, `COMPLETE=zsh jj` does generate the right results.

**Comment by WhyNotHugo** [comment]
BTW: the docs specify this command:

    source <(COMPLETE=zsh jj)

This will only enable completions for the current shell, not actually install them. To install them and have them work on all shells, you'd use:

    COMPLETE=zsh jj | doas tee /usr/share/zsh/site-functions/_jj

Do you think distributions should install the "regular" completions, or the dynamic ones?

**Comment by martinvonz** [comment]
> Do you think distributions should install the "regular" completions, or the dynamic ones?

For the time being, I think they should only install the regular/static completions. We need to test the dynamic ones a bit more first. I don't remember the details but I've heard several times about issues with dynamic completions in zsh and bash.
