### ISSUE TITLE
`sign-all = true` does not sign commits created by `jj split` (but yes those created by `jj new`)

### ISSUE THREAD

**Issue by jalil-salame** [martinvonz/jj#5106]
## Description

I started using a [Nitrokey 3A Mini](https://shop.nitrokey.com/shop/nk3am-nitrokey-3a-mini-149) device (required by work) to sign my commits. `jj split` does not sign the commits created.

## Steps to Reproduce the Problem

1. Setup a signing key.
1. Do some changes.
1. Run `jj split` and create two commits
2. Observe the commits with `git log --show-signature`
3. See that the commits created by `jj split` do not contain a signature.

## Expected Behavior

Commits created by `jj split` should contain a signature

## Actual Behavior

Commits created by `jj split` don't contain a signature

## Specifications

- Platform: linux
- Version: `jj 0.24.0`

**Comment by jalil-salame** [comment]
This might be related to #4561 as I noticed the commits were not using my work email, but my personal email.

**Comment by martinvonz** [comment]
Yes, it's probably that. Feel free to reopen if it happens with commits authored by you.
