### ISSUE TITLE
FR: Add aliases to autocompletion

### ISSUE THREAD

**Issue by magikid** [martinvonz/jj#5126]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I hit tab and my aliases aren't suggested by my shell.

**Describe the solution you'd like**
I'd love it it the completion included my aliases.

**Describe alternatives you've considered**
I've considered adding them manually by `cat`ing them onto the end of the autocomplete but it's pretty hacky.

I'm currently running `jj 0.23.0`

**Comment by magikid** [comment]
This is what it looks like currently in my fish config:

```
begin
    jj util completion fish
    complete -c jj -n "__fish_jj_needs_command" -f -a "l"
    complete -c jj -n "__fish_jj_needs_command" -f -a "lb"
    complete -c jj -n "__fish_jj_needs_command" -f -a "colo"
    complete -c jj -n "__fish_jj_needs_command" -f -a "master-rebase"
    complete -c jj -n "__fish_jj_needs_command" -f -a "master-track"
    complete -c jj -n "__fish_jj_needs_command" -f -a "main-rebase"
    complete -c jj -n "__fish_jj_needs_command" -f -a "main-track"
    complete -c jj -n "__fish_jj_needs_command" -f -a "bookmark-last"
    complete -c jj -n "__fish_jj_needs_command" -f -a "bc"
end | source
```

**Comment by martinvonz** [comment]
Added in 0.24 :) Use `COMPLETE=fish jj | source` to set it up. See https://martinvonz.github.io/jj/latest/install-and-setup/#command-line-completion.

**Comment by midischwarz12** [comment]
@martinvonz This does not provide completion for aliases. This provides completion for *only* `jj` subcommands. Tested jj 0.29.0 using:
```zsh
autoload -U compinit
compinit
source <(jj util completion zsh)
```

Please reopen.

**Comment by magikid** [comment]
This works for me in zsh.  It seems like there is a mismatch between `jj util completion zsh` and `COMPLETE=zsh jj`
```
autoload -U compinit
compinit
source <(COMPLETE=zsh jj)
```

**Comment by martinvonz** [comment]
@midischwarz12: Also note that we deliberately don't auto-complete aliases of length 1 or 2. I don't know if that's what you ran into.

**Comment by midischwarz12** [comment]
@magikid I see. Can confirm this works. Should we provide this in the docs if this is the case? I currently do not see this anywhere.

**Comment by martinvonz** [comment]
It's [here](https://jj-vcs.github.io/jj/latest/install-and-setup/#zsh) but you have to click "Dynamic" to see it.

**Comment by midischwarz12** [comment]
Ah, how could I have not seen that. Thanks!
