### ISSUE TITLE
Splitting working copy seems broken (in a --git-repo=. repo)

### ISSUE THREAD

**Issue by unrelentingtech** [martinvonz/jj#54]
Interested to see a VCS tool compatible with Git, I decided to play with it, starting with this bit from the docs:

> With Jujutsu, you'd instead use jj split to split the working copy commit into two commits

I did `jj init --git-repo=.` in a checkout of this very repo and edited two files:

```
% jj st
Parent commit: 03e6b8c0e6a4 working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
Working copy : d6382403c415
Working copy changes:
M README.md
M rustfmt.toml
```

Now I run `jj split`. Say I want to commit `rustfmt.toml` first, so I copy `README.md` left-to-right in Meld and enter the obvious descriptions and it seems to work:

```
% jj split
First part: 62cb2d07bc52 first part
Second part: 949b4659aee9 second part
Working copy now at: 949b4659aee9 second part
```

## Expected Behavior

Working copy actually being at `949b4659aee9` like the message said?

## Actual Behavior

The log and status command act like the split did not happen:

```
% jj status
Parent commit: 03e6b8c0e6a4 working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
Working copy : 16178fc092a1 first part
Working copy changes:
M README.md
M rustfmt.toml
% jj log
@ 16178fc092a1 e612ec30d5df greg@unrelenting.technology 2022-02-18 01:06:53.000 +03:00
| first part
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
| working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

The split commits do *exist*:

```
% jj show 62cb2d07bc52
Commit ID: 62cb2d07bc52b1345cced9acf003c73e84435086
Change ID: e612ec30d5df4d2b848c81d9f7078a7b
Author: Greg V <greg@unrelenting.technology> (2022-02-18 01:06:53.000 +03:00)
Committer: Greg V <greg@unrelenting.technology> (2022-02-18 01:12:57.000 +03:00)

first part

Modified regular file rustfmt.toml:
   1    1: max_width = 10069
   2    2: wrap_comments = true
   3    3: format_strings = true
   4    4: error_on_line_overflow = true
    ...
```

but are seemingly just lost from the `jj log` perspective.
`jj diff` and equivalently `jj show 16178fc092a1` (the hash at the top of the log) show both changes together, i.e. what was there before the split, but with the same "first part" description as the actual first part (`62cb2d07bc52`). But the hash is new.

Looking at the git repo, actually the real first part is committed.

```
% g log --oneline | head
62cb2d0 first part
03e6b8c working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

And after fiddling with the git CLI (no write commands, only viewing the log) the `jj log` is messed up? o_0

```
@ 16178fc092a1 e612ec30d5df greg@unrelenting.technology 2022-02-18 01:06:53.000 +03:00    divergent
| first part
| o 62cb2d07bc52 e612ec30d5df greg@unrelenting.technology 2022-02-18 01:06:53.000 +03:00    HEAD@git divergent
|/  first part
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
| working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

Maybe I misunderstood something but it sounds like a bug?

## Steps to Reproduce the Problem

(above — I don't think steps should be below the story)

## Specifications

- Version: 03e6b8c0e6a44d12494a7467f626108ebba2fbec
- Platform: FreeBSD -CURRENT

**Comment by unrelentingtech** [comment]
Trying with version be7b0e6839e9 (before all the working copy series of changes) and with 03e6b8c0e6a (current), all the following behavior seems identical:

```
~/src/github.com/martinvonz/jj % jj split
First part: 27e0c89064d1 firstpart
Second part: 6cc0991be296 2ndpart
Working copy now at: 6cc0991be296 2ndpart
~/src/github.com/martinvonz/jj % jj st
Parent commit: 03e6b8c0e6a4 working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
Working copy : b7d019839761 firstpart
Working copy changes:
M README.md
M rustfmt.toml
~/src/github.com/martinvonz/jj % jj co 6cc0991be296
Working copy now at: 6cc0991be296 2ndpart
~/src/github.com/martinvonz/jj % jj co 6cc0991be296
Already on that commit
~/src/github.com/martinvonz/jj % jj st
Parent commit: 27e0c89064d1 firstpart
Working copy : 6cc0991be296 2ndpart
Working copy changes:
M README.md
~/src/github.com/martinvonz/jj % jj log
o b7d019839761 9c9772c9b6e0 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00    divergent
| firstpart
| o 27e0c89064d1 9c9772c9b6e0 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00    HEAD@git divergent
|/  firstpart
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
| working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
~/src/github.com/martinvonz/jj % jj close
~/src/github.com/martinvonz/jj % jj st
Parent commit: 27e0c89064d1 firstpart
Working copy : 6cc0991be296 2ndpart
Working copy changes:
M README.md
~/src/github.com/martinvonz/jj % jj log
o 6ae061cab33a 1da60c50af93 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00
| 2ndpart
| o b7d019839761 9c9772c9b6e0 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00    divergent
| | firstpart
o | 27e0c89064d1 9c9772c9b6e0 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00    HEAD@git divergent
|/  firstpart
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
| working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
~/src/github.com/martinvonz/jj %  jj abandon b7d019839761
~/src/github.com/martinvonz/jj % jj log
o 6ae061cab33a 1da60c50af93 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00
| 2ndpart
o 27e0c89064d1 9c9772c9b6e0 greg@unrelenting.technology 2022-02-18 02:09:22.000 +03:00    HEAD@git
| firstpart
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
| working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

This unwanted combo commit is still created and left there, I have to manually checkout the right one and manually abandon the combo one.

And the second commit isn't really being properly committed to the branch, after all these operations I'm in a really weird state where committing creates a new divergent commit:

```
~/src/github.com/martinvonz/jj % jj close
Working copy now at: 9a8a8d502a1a second
~/src/github.com/martinvonz/jj % jj close
Nothing changed.
~/src/github.com/martinvonz/jj % jj close
Working copy now at: 9a8a8d502a1a second
~/src/github.com/martinvonz/jj % jj close
Working copy now at: 9a8a8d502a1a second
~/src/github.com/martinvonz/jj % jj close
Nothing changed.
~/src/github.com/martinvonz/jj % jj log | head
o 695fd9ac65d0 35ca5a0652f9 greg@unrelenting.technology 2022-02-18 02:17:19.000 +03:00    divergent
| second
| o f80ca597f482 35ca5a0652f9 greg@unrelenting.technology 2022-02-18 02:17:19.000 +03:00    divergent
|/  second
| o 09cebfecf2ab 35ca5a0652f9 greg@unrelenting.technology 2022-02-18 02:17:19.000 +03:00    divergent
|/  second
| o 91eba24b7e00 35ca5a0652f9 greg@unrelenting.technology 2022-02-18 02:17:19.000 +03:00    divergent
|/  second
| o 962af9496ea9 35ca5a0652f9 greg@unrelenting.technology 2022-02-18 02:17:19.000 +03:00    divergent
|/  second
```

**Comment by martinvonz** [comment]
Thanks for the report! And thanks to @arxanas for the analysis, and for the mention on HN! I was wondering why I suddenly got ~10 extra stars :)

This seems to be a problem when using jj and git with the same working copy. I don't use that setup myself, and it's a pretty recent feature, so I'm not too surprised there are bugs there. I'll try to get around to looking into the bug tonight (Pacific time).

If you want to just test it out without running into that bug, you can run `jj git clone https://github.com/martinvonz/jj` instead.

**Comment by martinvonz** [comment]
> Might be nice to have an "import" mode too that would, instead of creating a "work together" setup, essentially mv .git .jj/repo/store/git and make it all work.

That seems like a good idea. It should be easy to implement. Maybe something like `jj init --consume-git-repo` (happy to hear better names).

> and lobste.rs :)

Ah, thanks for that too, @arxanas

**Comment by martinvonz** [comment]
I just started looking into this and don't yet know what the bug is, but I'll take this opportunity to demonstrate how the operation log can be useful for troubleshooting. Here's what it looks like in the repo I reproduced the bug in earlier today:

```
$ jj op log
@ d98e315cbf30 martinvonz@vonz.svl.corp.google.com 2022-02-17 15:17:54.236 -08:00 - 2022-02-17 15:17:54.238 -08:00
| import git refs
| args: jj log
o 4d88d5b1a7a1 martinvonz@vonz.svl.corp.google.com 2022-02-17 15:17:48.693 -08:00 - 2022-02-17 15:17:48.694 -08:00
| commit working copy
o 157950ed075f martinvonz@vonz.svl.corp.google.com 2022-02-17 15:17:48.686 -08:00 - 2022-02-17 15:17:48.689 -08:00
| import git refs
| args: jj log -r '((heads(remote_branches())..@)-):'
o 0bdcabf7d791 martinvonz@vonz.svl.corp.google.com 2022-02-17 15:17:35.857 -08:00 - 2022-02-17 15:17:45.617 -08:00
| split commit 7c7d82eada48d47afaf34adb007d62ece4efc5a5
| args: jj split
o e3a1061829cc martinvonz@vonz.svl.corp.google.com 2022-02-17 15:16:32.316 -08:00 - 2022-02-17 15:16:32.317 -08:00
| commit working copy
o 38d14fc75ce8 martinvonz@vonz.svl.corp.google.com 2022-02-17 15:15:18.929 -08:00 - 2022-02-17 15:15:18.954 -08:00
| import git refs
| args: jj init '--git-repo=.'
o 2f032253db55 martinvonz@vonz.svl.corp.google.com 2022-02-17 15:15:18.927 -08:00 - 2022-02-17 15:15:18.928 -08:00
| add workspace 'default'
o d83abfadf08b martinvonz@vonz.svl.corp.google.com 2022-02-17 15:15:18.925 -08:00 - 2022-02-17 15:15:18.925 -08:00
initialize repo
```

Operation `0bdcabf7d791` is the result of running `jj split`. The next operation (`157950ed075f`, "import git refs") was an automatic import from git when I ran a log command. Automatic imports and exports happen when the working copy is collocated with a git repo (i.e. when `.jj/` and `.git/` are sibling directories).

If we look at the log output right after the `jj split`, it looks *mostly* good:
```
$ jj log -r main: --at-op 0bdcabf7d791
@ 8aa4dfcfc81b 4576ea2b7c30 martinvonz@google.com 2022-02-17 15:15:18.000 -08:00
| second part
o 87a0d4a4c5a7 18a33db5f3d7 martinvonz@google.com 2022-02-17 15:15:18.000 -08:00
| first part
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main   HEAD@git
~ working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

The part that doesn't look good here is that the git HEAD has not been updated, or at least jj doesn't know that it has. Let's see what it looks like at the next operation, after that automatic import of git refs:
```
$ jj log -r main: --at-op 157950ed075f
@ 87a0d4a4c5a7 18a33db5f3d7 martinvonz@google.com 2022-02-17 15:15:18.000 -08:00    HEAD@git
| first part
o 03e6b8c0e6a4 37df45dd7108 martinvonz@google.com 2022-02-12 23:46:38.000 -08:00 main
~ working_copy: take `Tree`, not `CommitId`, as argument to `check_out()`
```

So it looks like git's HEAD commit has been updated to the "first part" commit, as it should have. However, the "second part" commit is now gone. That commit was supposed to be the remaining changes in the working copy.

I think that problem is that jj didn't record the updated HEAD when it updated it in git land. As a consequence, the subsequent import from git made it look like *the user* (via git) had moved HEAD from the commit pointed to by `main` (`03e6b8c0e6a4`) to the "first part" commit (`87a0d4a4c5a7`). When that happens, jj assumes that the user has taken care of committing the working copy using git, or perhaps that they just discarded it. Either way, jj discards its working copy, which was the "second part" commit in this case.
