### ISSUE TITLE
Working copy snapshot is discarded even if it contained mtime changes

### ISSUE THREAD

**Issue by yuja** [martinvonz/jj#554]
## Description

After `jj init --git-repo .`, `tree_state` contains file states of all `mtime` set to 0.
The subsequent `jj` invocation will stat all files to build new tree id and state, but the
result is discarded because `new_tree_id == *checkout_commit.tree_id()`. This continues
until you made some changes to the working copy.

## Steps to Reproduce the Problem

1. `git clone somewhat-large-repo`
2. `jj init --git-repo .`
3. `jj st` more than once

## Expected Behavior

The second `jj st` should be faster.

## Actual Behavior

Slow.

## Specifications

- Platform: Linux
- Version: f173f599328c

---

One way to propagate the dirty state is to make `snapshot()` return `Option<TreeId>`.

```
        if let Some(new_tree_id) = locked_wc.snapshot(base_ignores)? {
            if new_tree_id != *checkout_commit.tree_id() {
                ...
            }
            locked_wc.finish(self.repo.op_id().clone());
```

But it might be better to make `LockedWorkingCopy` manage dirty state, so the caller
can always call `locked_wc.finish(operation_id)`.

**Comment by martinvonz** [comment]
> But it might be better to make `LockedWorkingCopy` manage dirty state, so the caller
> can always call `locked_wc.finish(operation_id)`.

I agree that that seems cleaner.
