### ISSUE TITLE
MacOS 12.1 installation fail

### ISSUE THREAD

**Issue by olegafx** [martinvonz/jj#62]
## Expected Behavior
You follow installation instructions and it should be installed without any errors.

## Actual Behavior
I was following installation instructions, but I had several errors.

These fixed the problem:

```
brew install pkg-config
brew install openssl
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```

I guess openssl was not needed, but setting PKG_CONFIG_PATH is required

## Steps to Reproduce the Problem

1. Install `rustup`
1. `rustup install nightly`
1. `cargo +nightly install --git https://github.com/martinvonz/jj.git`

## Specifications

- Version: 0.2
- Platform: MacOS 12.1 on Apple Silicon

**Comment by martinvonz** [comment]
Thanks for the report. I have a Mac with not much installed. I seemed to need `brew install openssl` and `xcode-select --install`, but not the `pkg-config` stuff. Maybe I'll just mention all of them as possibly being needed.

**Comment by olegafx** [comment]
It's weird because I already had xcode tools installed:
```
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by martinvonz** [comment]
Yeah, I didn't mean that `xcode-select --install` would have installed `pkg-config`, I just meant that that's an additional step I should mention for Mac. I don't know why you needed to set `PKG_CONFIG_PATH` and I didn't.
