### ISSUE TITLE
jj status does not honor .git/info/exclude

### ISSUE THREAD

**Issue by mdaniel** [martinvonz/jj#65]
## Expected Behavior

`jj` would honor the existing `.git/info/exclude` in addition to `.gitignore`, to allow easier coexistence with `git`

## Actual Behavior

`jj status` adds local files even if they are excluded by `.git/info/exclude`

## Steps to Reproduce the Problem

1. `git clone https://github.com/martinvonz/jj.git`
1. `cd jj && jj init --git-repo .`
1. `jj st`
1. observe it says everything is ok
1. `echo secret-password >> .git/info/exclude`
1. `touch secret-password`
1. `jj status`
1. observe jj has started to track `secret-password`

I also tried it with `jj git clone` and then editing `.jj/repo/store/git/info/exclude` with the same outcome

The problem this is trying to solve is when one does not wish to make formal edits to the upstream repo's `.gitignore` but also needs `jj` to stop adding local log files, editor metadata, etc, on any random jj operation

## Specifications

- Version: 2916cb2d9f654313727b539b6991bc09d5af560b
- Platform: darwin/amd64

**Comment by martinvonz** [comment]
I can see how that's broken. I'll try to fix it when I get back to a computer in about a week. As a workaround, you can add the patterns to `~/.gitignore`.

**Comment by martinvonz** [comment]
If anyone else wants to look into it, [this TODO](https://github.com/martinvonz/jj/blob/2916cb2d9f654313727b539b6991bc09d5af560b/lib/src/working_copy.rs#L316) explains how to do it.
