### ISSUE TITLE
Remove nixpkgs-mozilla overlay once nightly features aren't used anymore

### ISSUE THREAD

**Issue by pingiun** [martinvonz/jj#68]
Currently the project doesn't build on Rust stable, this means the Nix derivation requires a Rust overlay which supplies the nightly version.

The code which requires the nightly features could be changed, or the nightly features could be stabilized, in which case the nixpkgs overlay should probably be removed such that the Rust compiler from nixpkgs is used instead.

At the time of writing, these nightly features are used:
- [assert_matches](https://github.com/martinvonz/jj/blob/2916cb2d9f654313727b539b6991bc09d5af560b/lib/src/lib.rs#L15) - rust-lang tracking issue: https://github.com/rust-lang/rust/issues/82775
- [map_first_last](https://github.com/martinvonz/jj/blob/2916cb2d9f654313727b539b6991bc09d5af560b/lib/src/lib.rs#L16) - rust-lang tracking issue: https://github.com/rust-lang/rust/issues/62924

See also: https://github.com/martinvonz/jj/pull/66#discussion_r810686682

**Comment by bobvanderlinden** [comment]
Good to see the work on flake.nix :+1:

I was looking into packaging jj for nixos, but I'm not sure whether we want a nightly rustc in there. Stopped working on it for now.

@arxanas 's comment gave me some hope.
> Is this to support a version of Rust which isn't available in Nix? @martinvonz might be open to lowering the minimum-supported Rust version instead.

**Comment by martinvonz** [comment]
> Good to see the work on flake.nix :+1:
> 
> I was looking into packaging jj for nixos, but I'm not sure whether we want a nightly rustc in there. Stopped working on it for now.
> 
> @arxanas 's comment gave me some hope.
> > Is this to support a version of Rust which isn't available in Nix? @martinvonz might be open to lowering the minimum-supported Rust version instead.

I'm fine with lowering the required Rust version. I just won't be able to work on it myself because I'm traveling this week. I will have occasional access so I can at least approve PRs from anyone who feels like removing those uses of unstable features.

Thanks for your help, everyone!
