### ISSUE TITLE
Musl binary for Linux

### ISSUE THREAD

**Issue by elkarouh** [martinvonz/jj#73]
## Expected Behavior
My machine at work doesn't allow any own install.
Can you provide a musl binary>
Many thanks

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by arxanas** [comment]
@martinvonz you might be able to produce binaries using GitHub actions, without having to set up Linux (or other platforms) yourself. @epage does it for `git-stack` here: https://github.com/epage/git-stack/blob/main/.github/workflows/post-release.yml

**Comment by martinvonz** [comment]
Thanks for the pointer, @arxanas! I have no experience creating musl binaries so having a place to copy from will be very valuable.

**Comment by martinvonz** [comment]
@elkarouh, I'm on vacation for a week, so don't expect this to be fixed sooner than that. I'll have occasional access to approve PRs if you or someone else wants to take care of it, though.

**Comment by martinvonz** [comment]
I also found https://github.com/rust-build/rust-build.action. That seems easy to use, so I guess I'll try that first.

**Comment by martinvonz** [comment]
I think I finally got the build on GitHub to work! Check out https://github.com/martinvonz/jj/releases for the latest release ([direct link to musl binary for 0.3.3](https://github.com/martinvonz/jj/releases/download/v0.3.3/jj-v0.3.3-x86_64-unknown-linux-musl.tar.gz)). The binary seemed to work when I tested it, but please let me know how it goes for you.

**Comment by elkarouh** [comment]
It works!
Thanks.
