### ISSUE TITLE
Installation instructions for Ubuntu

### ISSUE THREAD

**Issue by chtenb** [martinvonz/jj#75]
I had to install the `libssl-dev` package as well as the `openssl` package before ff would compile. Perhaps good to include this in the installation instructions. Settings the `PKG_CONFIG_PATH` was not necessary.

**Comment by arxanas** [comment]
If jj isn't yet using SSL features of `git2`, I recommend that it disable default features so that it doesn't carry an SSL dependency with it (that's what git-branchless does).

**Comment by martinvonz** [comment]
I suppose `libssl-dev` and `openssl` are needed on Linux in general, right? Unless someone who knows better tells me otherwise, I'll update the installations instructions to say that. I guess I'll assume the packages have the same names and are not installed by default on most distributions.
