### ISSUE TITLE
`jj update` takes me to a *commit id* when I meant a *change id* with no warning

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#799]
Repo state:  [jj_up_f798.tar.gz](https://github.com/martinvonz/jj/files/10097368/jj_up_f798.tar.gz)

My last command was `jj up f798` as I meant to get to the "Refactor errors" commit a.k.a. 508216 in the `jj log` output below (it's near the middle). However, I ended up at a very old commit without warning. In other cases, I saw `jj` warn me in this case, I think.

Separately, this is an example of an unexpected (to me) divergence from a recent build of `jj` similar to https://github.com/martinvonz/jj/issues/666. Unfortunately, I missed the exact moment it happened, and I'm not 100% sure that's a bug.

```
$ jj log
@ 6eb5df3ff40c ilyagr@users.noreply.github.com 2022-11-26 18:12:38.000 -08:00 80a0e8cc7a19
| (no description set)
| o c2a3c7d6c506 ilyagr@users.noreply.github.com 2022-11-24 18:31:47.000 -08:00 815745052ec0
| | NOTES: jj describe -r change, jj log -r change_confl_with_commit
| o f55d4d08eb8c ilyagr@users.noreply.github.com 2022-11-10 20:01:04.000 -08:00 mergetool-pr* f7e7de121e5d
| | Rename `jj resolve` to `jj conflict resolve`
| | o 2406d3e3d9e6 ilyagr@users.noreply.github.com 2022-11-24 19:45:46.000 -08:00 764188a78414
| | | write_all -> std::file::write
| o | c62dbc06da8b ilyagr@users.noreply.github.com 2022-10-30 01:23:45.000 -07:00 ilya* divergent 86ae33dc6966
| |/  Documentation for `jj resolve` and merge tool config
| o c47b7a983914 ilyagr@users.noreply.github.com 2022-10-30 19:41:19.000 -07:00 mergetool2* a3deb889060f
| | Mergetool config
| o f7987e8fdbad ilyagr@users.noreply.github.com 2022-10-30 19:41:19.000 -07:00 divergent 508216f4996b
| | Refactor errors
| o 10b33904c5db ilyagr@users.noreply.github.com 2022-10-27 20:30:44.000 -07:00 divergent 6ee36ff26b77
| : New `jj resolve` command uses an external merge tool to resolve conflicts
| : o db25140d31a8 martinvonz@google.com 2022-09-22 15:34:25.000 -07:00 918da280837d
| : | readme: remove now-unnecessary `--bin jj` argument to `cargo install`
| : o 90013bb15181 martinvonz@google.com 2022-09-22 11:32:16.000 -07:00 e48334d96e91
| :/  testing: don't have cargo install test tools
| o c4b869aa460d yuya@tcha.org 2022-09-22 18:29:06.000 +09:00 51cb4d901c32
|/  cli: abbreviate operation id embedded in warning/error messages
o cf23ae0cf4c1 martinvonz@google.com 2021-03-11 21:45:04.000 -08:00 HEAD@git f79874d612e5
~ view: let repo get current operation from OpHeadsStore and pass in
```

**Comment by yuja** [comment]
`jj` looks up a commit id first, then falls back to a change id. Maybe that's why.

@martinvonz Maybe better to try both and error out if found both (and not root)?

**Comment by ilyagr** [comment]
Maybe I was confused, but I thought I saw an error in a similar case.

In any case, now that `jj log` highlights the change id by putting it first, I think `jj` must either prefer the commit id to a commit id or error out when both exist (probably the latter), if it's not already the case.

**Comment by martinvonz** [comment]
I agree that it would be better to error out if they both match. I think that would mean doing a scan of all entries in the commit index. I don't know how slow that would be on large repos (might add 100ms, so probably fine?). We should keep this in mind when we redesign the commit index to use segmented changelog.

**Comment by yuja** [comment]
> I think that would mean doing a scan of all entries in the commit index.

Maybe you mean a scan of all visible entries? That's probably slow, but we pay that cost every time we do look up commit by change id afaik.

**Comment by martinvonz** [comment]
> > I think that would mean doing a scan of all entries in the commit index.
> 
> Maybe you mean a scan of all visible entries? That's probably slow, but we pay that cost every time we do look up commit by change id afaik.

I actually meant all entries, but you're right that since we recommend looking up by change ID already, users are most likely already paying that cost. I checked in the Linux repo and it's ~300ms there, but we need to fix other performance issues before that's the biggest problem anyway. Notably, our working-copy format (protobuf) is slow, and we need to index which commits/trees have conflicts (instead of walking the whole tree object recursively), since we present that in the log output.

**Comment by martinvonz** [comment]
Sorry, that was a bit unclear. I meant to say that I *meant* all entries, but you're right that it's a scan of all visible entries we do to resolve a change ID, and you're right that users already pay that cost.

**Comment by ilyagr** [comment]
Along these lines, it would also be nice to highlight the shortest unique prefix for each hash.

**Comment by ilyagr** [comment]
Separately, here is a more far-fetched idea to address both this and addressing divergent commits.

We could say that if a user adds `~` (say) to a hash prefix, they are referring to a change id and not a commit id. Adding the `~` could be optional. If there is both a commit and a change starting with `ab5d`, using `ab5d` could refer to the commit (as it does now) but print a warning. The user can `jj undo` (if necessary) and then replace `ab5d` with `ab5d~`.

If there are several commits in the change `bcd`, they could be numbered and be referred to as `bcd~1`, `bcd~2`, etc. The change id would be shown this way in the log. As today, `bcd` or `bcd~` could refer to all of them.

**Comment by yuja** [comment]
> We could say that if a user adds `~` (say) to a hash prefix, they are referring to a change id and not a commit id.

If we need a concise notation to disambiguate change/commit ids, I would rather add a prefix to the change id space, like `I0123abcd` of gerrit. The prefix is mandatory, so there should be no ambiguity. I think there were some discussion in discord, but I don't remember if there was a conclusion.

> 4. If the change `abc` contains several commits, `abc~x` refers to the commit starting with `x` inside change `abc`.

Aside from the syntax, yeah, it might be useful to add some config or expression to narrow the space of short hash resolution. Mercurial provides a config knob to disambiguate short hash within the given revset, so you can use a reasonably short hash.
