### ISSUE TITLE
Crash when referring to un-imported Git commit

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#814]
## Description

As reported on Discord by @pranaysashank, `jj checkout` crashes if you try to access a Git commit that's never been seen in the jj repo.

## Steps to Reproduce the Problem

1. Create a Git repo with two commits, then make one of them unreferenced (via e.g. `git reset --hard HEAD~`)
1. Create a jj repo backed by the git repo
1. Refer to the unreferenced Git commit (e.g. `jj show <hash>`)

## Expected Behavior

The command either works (preferably) or it says that the commit doesn't exist.

## Actual Behavior

Crash:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lib/src/revset.rs:1737:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Specifications

- Platform: All
- Version: 0.5.1

**Comment by samueltardieu** [comment]
This has been fixed by #1026 by issuing a proper error.
