### ISSUE TITLE
Add a note about `jj edit` in the tutorial?

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#840]
## Description

Might want to mention `jj edit` when introducing `jj new` and `jj squash` in the tutorial.

In my case, towards the end in the ["Moving content changes between commits" section](https://github.com/martinvonz/jj/blob/main/docs/tutorial.md#moving-content-changes-between-commits), I did some operations to fix a typo on one of the parent commits and ended up with a working copy commit on top of the "ABCD" commit, and couldn't figure out how to move the working copy back so that the later commands on `@` and `@-` would work properly. `jj edit` was exactly the answer I was looking for.

**Comment by PhilipMetzger** [comment]
While we're writing documention about `jj edit` we should also mention how we can return to a specific revision. As in my experience I did some work in `@` then went back to edit a previous revision. It wasn't clear how I could return to head.

e.g do work in `@`, `jj edit $rev` amend changes and then return to the previous working copy with `jj co/new 'heads(@:)`.

**Comment by martinvonz** [comment]
@dbarnett and @PhilipMetzger, do you want to review #876?
