### ISSUE TITLE
Implement jj next/prev

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#878]
There should be a pair of commands `jj next` and `jj prev` for quickly checking out the next/previous commit from `@`, similar to the [next/prev commands from git-branchless](https://github.com/arxanas/git-branchless/wiki/Command:-git-next,-git-prev).

**Comment by dbarnett** [comment]
For now, you can add these aliases to your jj config to get something close:
```toml
[alias]
prev = ["co", "@--"]
next = ["co", "@-+ ~ @"]
```
but with a pretty big misfeature that in branch/merge cases instead of getting a picker to say which prev/next rev you want, it just blows up with an error about "more than one revision".

**Comment by martinvonz** [comment]
I agree. FYI, @rslabbert talked (on Discord) about possibly implementing an interactive command for selecting a commit to check out or edit. Having `prev` and `next` that are non-interactive in the linear case still seems useful, though.

**Comment by dbarnett** [comment]
Oh, another small usability improvement for "more than one revision": It wouldn't hurt anything to have the error list those actual multiple revisions it found, would it? Like:
```
$ jj next
Error: Revset "@-+ ~ @" resolved to more than one revision:
67318df2df48 tutorial: mention `jj edit` and when it's useful
a83a0415aed8 Do not use "..." between diff chunks when it only replaces 1 line of the diff
```

**Comment by martinvonz** [comment]
> Oh, another small usability improvement for "more than one revision": It wouldn't hurt anything to have the error list those actual multiple revisions it found, would it? Like:
> 
> ```
> $ jj next
> Error: Revset "@-+ ~ @" resolved to more than one revision:
> 67318df2df48 tutorial: mention `jj edit` and when it's useful
> a83a0415aed8 Do not use "..." between diff chunks when it only replaces 1 line of the diff
> ```

It would probably not hurt anything to include up to, say, 5 commits there.

If we wanted to format and color those commits as we usually, I'm not sure how to do it cleanly. So far, the errors we return have a single, plain-text error message, and an optional plain-text hint. We render the text in red and the hint in blue (by default). That happens here: https://github.com/martinvonz/jj/blob/4a889b986ce88cb47f94097bc1c89dc80258f4db/src/cli_util.rs#L1481-L1487. We could of course print out the unwanted revisions *before* returning the error, which would end up looking more like this:

```
$ jj next
Hint: Revset "@-+ ~ @" resolved to more than one revision: 
67318df2df48 tutorial: mention `jj edit` and when it's useful
a83a0415aed8 Do not use "..." between diff chunks when it only replaces 1 line of the diff
Error: Revset "@-+ ~ @" resolved to more than one revision.
```

It might be better to just render it as plain-text error plus hint then, pretty much as you suggested above:

```
$ jj next
Error: Revset "@-+ ~ @" resolved to more than one revision.
Hint: The revset resolved to these revisions:
67318df2df48 tutorial: mention `jj edit` and when it's useful
a83a0415aed8 Do not use "..." between diff chunks when it only replaces 1 line of the diff
```

**Comment by ilyagr** [comment]
Following the idea of https://github.com/martinvonz/jj/issues/878#issuecomment-1345286087, I like

```toml
[revset-aliases]
next = "@-+ ~ @" 
prev = "@--"  # Though I usually just type @--
```

Then, you can do `jj up next`, `jj log -r next` (especially if it resolves to multiple revisions), `jj rebase -d next`, etc. You can do this instead of or in addition to the `[alias]`-es.
