### ISSUE TITLE
`jj split .` should create an empty commit, and `jj split nonexistent_file` should be easier

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#881]
1. Currently, `jj split . -r @-` results in a message saying `Nothing changed.`. It should instead create an empty commit after the commit being split. This is very similar to https://github.com/martinvonz/jj/issues/787.

    Attempting to do this with interactive  `jj split` by changing nothing and exiting also currently results in the `Nothing changed` message. This behavior should probably be kept, but perhaps in this case there could be a UI hint to use `jj split .` in case that's what the user actually wanted to do.

    Note that this is different from `jj new` behavior if the commit has any children. Currently, the best workaround I know is to use `jj new` followed by `jj rebase` in this case.

4.  `jj split nonexistent_file -r @-` does create an empty commit before the commit being split, as @martinvonz once taught me, which is useful (especially for merge commits). I think there should be an easier way, e.g. `jj split --none -r @-`.

    For the record, currently, another way to achieve this is to use interactive `jj split` and undo all the changes there.

**Comment by martinvonz** [comment]
Sounds good. Allowing `jj split .` seems consistent with allowing `jj squash` on an empty commit, as you noted.

I wonder if there's a more intuitive way of achieving what the user intended. `jj new --insert`? What do you typically do after inserting the empty commit? Do you edit it and let the every command rebase the descendants or do you check it out and squash in changes once you're done?

**Comment by ilyagr** [comment]
For inserting above a commit (`jj split .` case), I usually want it when I have a structure like

    a b
     \|
    commit to split

I think `jj new --insert` would work well here.

Conversely,  `jj split nonexistent`  is useful for merge commits. I'm not sure if adding this as `jj new --insert-below` makes sense. Perhaps we can think of something better, or maybe `jj split --none` is good enough.

**Comment by ilyagr** [comment]
> What do you typically do after inserting the empty commit? Do you edit it and let the every command rebase the descendants or do you check it out and squash in changes once you're done?

To actually answer your question: I check it out and squash when I want a rebase to happen. When I `jj edit` directly, I'm worried about races between VS Code and jj being more common, for instance because the rebases get slower.

**Comment by martinvonz** [comment]
> > What do you typically do after inserting the empty commit? Do you edit it and let the every command rebase the descendants or do you check it out and squash in changes once you're done?
> 
> To actually answer your question: I check it out and squash when I want a rebase to happen. When I `jj edit` directly, I'm worried about races between VS Code and jj being more common, for instance because the rebases get slower.

In that case, `jj new --insert` wouldn't really be what you want because that would presumably edit the new commit. The `new` followed by `rebase` you mentioned actually sounds pretty good then. Is your issue with it that it doesn't match your mental model as well?

**Comment by ilyagr** [comment]
Yes, I wouldn't want to immediately edit that commit, though it wouldn't be much of a burden to do another `jj new`.

The reason I want this is that `commit to split` might have many children, and I'd have to rebase each one.
