### ISSUE TITLE
Add support for pager

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#9]

**Comment by dbarnett** [comment]
Looks like there is a pager triggered for commands like `jj log`, but I'm seeing ANSI escape codes:
`@ ESC[1;35mbb39c26a29feESC[0m ESC[1;33m(no email configured)ESC[0m ESC[1;36m2022-12-03...`

Would it make sense to default to non-colorized output when using a pager or include pointers for configuring a colorized pager?

**Comment by martinvonz** [comment]
Good catch. I'm not at a computer right now, but I think we just default to `less` without the `-R` option. We should improve the default by adding `-FRX`. We can probably also be helpful and give some hints if the user has confirmed `less` without `-R` and it's also not in `$LESS`.

**Comment by martinvonz** [comment]
I think we should consider this bug done by #672 (thanks, @chooglen!). I sent #836 to default to `less -FRX` instead of `less` without arguments. That should fix the biggest you ran into, @dbarnett. I'll leave the nice-to-have for later (warning when the user is using `less` without `-R`).
